export const chapterContent = {
  "storySlug": "the-great-gatsby",
  "level": 4,
  "chapter": 1,
  "pages": {
    "1": {
      "lines": [
        {
          "en": "In my younger and more vulnerable years, my father gave me advice that I've often thought about since.",
          "es": "En mis años más jóvenes y vulnerables, mi padre me dio un consejo que he pensado muchas veces desde entonces."
        },
        {
          "en": "“Whenever you feel like criticizing anyone,” he told me, “just remember that not everyone in this world has had the advantages that you’ve had.”",
          "es": "Siempre que sientas la tentación de criticar a alguien,\" me dijo, \"recuerda que no todos en este mundo han tenido las ventajas que tú has tenido."
        },
        {
          "en": "He didn’t say anything more, but we’ve always communicated in a reserved way, and I understood he meant much more than that. Consequently, I tend to hold back on judgments, a habit that has allowed many curious natures to open up to me and also made me the victim of not a few boring people. The unusual mind quickly notices and attaches itself to this quality in a normal person, and so it happened that in college I was unfairly accused of being a politician, because I was aware of the secret sorrows of wild, unknown men. Most of these confidences were unsolicited—often I pretended to be asleep or busy or even unfriendly when I sensed that an intimate revelation was about to be shared; for the intimate revelations of young men, or at least the way they express them, are usually unoriginal and flawed by obvious omissions. Holding back judgments is a matter of infinite hope. I still fear missing something if I forget that, as my father snobbishly suggested, and I repeat, a sense of the fundamental decencies is unequally distributed at birth.",
          "es": "No dijo nada más, pero siempre nos hemos comunicado de manera reservada, y entendí que quería decir mucho más que eso. Por consiguiente, tiendo a retenerme a la hora de juzgar, un hábito que ha permitido que muchas personas curiosas se abran conmigo y también me ha convertido en víctima de no pocas personas aburridas. La mente inusual rápidamente nota y se apega a esta cualidad en una persona normal, y así sucedió que en la universidad fui injustamente acusado de ser un político, porque era consciente de las penas secretas de hombres salvajes y desconocidos. La mayoría de estas confidencias fueron no solicitadas—frecuentemente fingía estar dormido u ocupado o incluso poco amigable cuando presentía que iba a compartirse una revelación íntima; porque las revelaciones íntimas de hombres jóvenes, o al menos la manera en que las expresan, suelen ser poco originales y están viciadas por omisiones obvias. Retener juicios es cuestión de esperanza infinita. Todavía tengo miedo de perderme algo si olvido eso, como mi padre sugerencia esnobemente, y repito, que un sentido de las decencias fundamentales se distribuye desigualmente al nacer."
        },
        {
          "en": "And, after boasting about my tolerance, I must admit that it has a limit. Behavior might be based on solid ground or shaky foundations, but after a certain point, I don’t care what it’s based on. When I returned from the East last autumn, I felt like I wanted the world to be in uniform and at a kind of moral attention forever; I wanted no more wild adventures with privileged glimpses into the human heart. Only Gatsby, the man who gives his name to this book, was exempt from my reaction—Gatsby, who represented everything I have an unaffected scorn for. If personality is an unbroken series of successful gestures, then there was something beautiful about him, some heightened sensitivity to the promises of life, as if he were related to one of those intricate machines that register earthquakes ten thousand miles away. This responsiveness had nothing to do with that weak impressionability which is dignified under the name of the “creative temperament”—it was an extraordinary gift for hope, a romantic readiness such as I have never found in any other person and which it is not likely I shall ever find again. No—Gatsby turned out all right at the end; it is what preyed on Gatsby, what foul dust floated in the wake of his dreams that temporarily closed out my interest in the failed sorrows and brief elations of men.",
          "es": "Y, después de alardear sobre mi tolerancia, debo admitir que tiene un límite. El comportamiento puede basarse en terreno sólido o cimientos inestables, pero después de cierto punto, no me importa en qué se basa. Cuando regresé del Este el otoño pasado, sentí que quería que el mundo estuviera en uniforme y en una especie de atención moral perpetua; no quería más aventuras salvajes con vistazos privilegiados al corazón humano. Solo Gatsby, el hombre que da su nombre a este libro, fue exento de mi reacción—Gatsby, quien representaba todo lo que siento un desprecio desafectado. Si la personalidad es una serie ininterrumpida de gestos exitosos, entonces había algo hermoso en él, una sensibilidad elevada a las promesas de la vida, como si estuviera relacionado con una de esas máquinas intrincadas que registran terremotos a diez mil millas de distancia. Esta receptividad no tenía nada que ver con esa impresionabilidad débil que se dignifica bajo el nombre del \"temperamento creativo\"—era un don extraordinario para la esperanza, una disposición romántica como no la he encontrado en ninguna otra persona y que probablemente nunca volveré a encontrar. No—Gatsby resultó bien al final; lo que atormentó a Gatsby, qué polvo inmundo flotaba en la estela de sus sueños fue lo que temporalmente cerró mi interés en las penas fallidas y breves alegrías de los hombres."
        }
      ]
    }
  }
};
