// /src/content/ui/en.ts
const en = {
auth: {
  login: "Log In",
  signup: "Sign Up",
  logout: "Log Out",
  email: "Email",
  password: "Password",
  confirmPassword: "Confirm Password",
  name: "Name",
  welcomeBack: "Welcome back!",
  error: "Incorrect credentials. Please try again.",
  or: "or",
  googleLogin: "Log in with Google",
  languagePrompt: "Native language / Idioma nativo:",
  createAccountCard: "Create an account",
  signupError: "Something went wrong. Please try again.",
  signupSuccess: "Account created! Redirecting...",
  signupGoogle: "Sign up with Google",
  alreadyHaveAccount: "Already have an account?",
  newHere: "New Here?",
  loggingIn: "Logging in...",
  creatingAccount: "Creating account...",
  sendOneTimeCode: "Get a one-time login code instead",
  usePassword: "Use password instead",
  forgotPassword: "Forgot password?",
  resetPassword: "Reset Password",
  resetPasswordTitle: "Reset your password",
  resetPasswordSubtitle: "Enter your email and we'll send you a code to reset your password.",
  newPassword: "New Password",
  confirmNewPassword: "Confirm New Password",
  passwordUpdated: "Password updated successfully!",
  passwordMismatch: "Passwords do not match",
  setNewPassword: "Set New Password",
  updating: "Updating...",
},

language: {
  en: "English",
  es: "Español"
},

stories: {
  goPremium: "Plans",
  premiumDescription: "Unlock smarter tools for faster learning.",
  dashboard: "Dashboard",
  settings: "Settings",
  stories: "Stories",
  loading: "Loading...",
  continue: "Continue",
  back: "Back",
  newBadge: "New",
  rightsPublicDomain: "The original text is in the public domain. This educational adaptation © Cuentana.",
  rightsLicensed: "This work is used under license. This educational adaptation © Cuentana.",
  rightsOriginal: "Original content © Cuentana.",
  readStory: "Read Me",
  readMore: "Read more",
  readLess: "Read less",
  availableLevels: "Available in levels:",
  level: "Level",
  storiesAll: "Stories",
  aiTutor: "AI Tutor",
  takeQuiz: "Take the Quiz",
  myAccount: "My Account",
  createAccount: "Create an Account",
},

story: {
  page: "Page",
  chapter: "Chapter",
  navigate: "Navigate ▾",
  home: "Home",
  levelSelect: "Level Select",
  prev: "Prev",
  next: "Next",
  markComplete: "Mark this story as complete",
  markedComplete: "✅ Story marked as complete!",
  levelUnavailable: "This story is not available at your current level.",
  availableLevelsAre: "Available levels:",
  selectLevel: "Select a level to continue reading:",
  // Poetry anthology navigation labels
  collection: "Collection",
  poem: "Poem",
  // Epic/narrative poetry navigation labels
  canto: "Canto",
  section: "Section",
  // Script navigation labels
  act: "Act",
  scene: "Scene",
},

levels: {
  // Legacy keys for backwards compatibility
  l1: "A1 - Foundations",
  l2: "A2 - Developing",
  l3: "B1 - Independent",
  l4: "B2 - Upper-Intermediate",
  l5: "C1 - Advanced",
  l6: "C2 - Near-Native",
  // CEFR codes
  A1: "A1 - Foundations",
  A2: "A2 - Developing",
  B1: "B1 - Independent",
  B2: "B2 - Upper-Intermediate",
  C1: "C1 - Advanced",
  C2: "C2 - Near-Native",
  // CEFR labels (for dropdown displays)
  cefrLabels: {
    l1: "A1",
    l2: "A2",
    l3: "B1",
    l4: "B2",
    l5: "C1",
    l6: "C2",
  },
  // CEFR descriptions (for onboarding/quiz)
  cefrDescriptions: {
    l1: "Can understand and use basic expressions for concrete needs. Can introduce yourself and ask simple personal questions.",
    l2: "Can understand frequently used expressions on familiar topics like shopping, family, and work. Can handle simple, routine exchanges.",
    l3: "Can handle most situations while traveling. Can describe experiences, events, and briefly explain opinions and plans.",
    l4: "Can understand complex texts and interact fluently with native speakers. Can produce clear, detailed text on a wide range of subjects.",
    l5: "Can understand demanding texts and recognize implicit meaning. Can express ideas fluently with precision and flexibility.",
    l6: "Can understand virtually everything heard or read. Can summarize information from different sources, reconstructing arguments coherently.",
  },
},

home: {
  subtitle: "Learn faster. Learn with stories.",
  quizTitle: "Take the Quiz",
  recommended: "(recommended)",
  letUsPick: "Answer a few questions and we'll personalize your experience.",
  startQuiz: "Start Quiz",
  noThanksTitle: "No Thanks",
  pickLater: "You can customize your level later in app",
  startLearning: "Start Learning",
  haveAccount: "Already have an account?",
  whyTitle: "Why",
  placeholderInfo: "Put your additional information here 🚀",
  aboutLink: "Get to know Cuentana",
  aboutPrefix: "Get to know"
},

onboarding: {
  stepLanguage: "Language",
  stepLevel: "Level",
  stepStart: "Start",
  welcomeTitle: "Welcome to Cuentana",
  welcomeSubtitle: "Let's personalize your learning experience",
  languageTitle: "What's your native language?",
  languageSubtitle: "This helps us customize your experience",
  findYourLevel: "Find Your Level",
  findYourLevelDesc: "Take a quick quiz to find the perfect starting point.",
  quizDuration: "5 questions",
  knowYourLevel: "Already know your level?",
  selectBelow: "Select your proficiency below",
  continueToStories: "Continue to Stories",
  quizProgress: "Question {current} of {total}",
  yourResult: "Your Level",
  startReading: "Start Reading",
  selectLevel: "Select",
  allSetTitle: "You're All Set",
  levelSetTo: "Your level is set to",
  createAccountTitle: "Create a Free Account",
  createAccountBenefit1: "Save your progress across devices",
  createAccountBenefit2: "Upload your own stories",
  createAccountBenefit3: "Build your personal vocabulary list",
  createAccountCta: "Create Account",
  skipForNow: "Continue without an account",
},

about: {
  tagline: "Learn Spanish through stories",
  whatIs: "What is Cuentana?",
  description: "Cuentana is a language learning app that helps you improve your Spanish through engaging stories. Whether you're a beginner or advanced learner, our curated collection of stories adapts to your level, making learning natural and enjoyable.",
  aboutFeature1Title: "Leveled Reading",
  aboutFeature1Desc: "Stories adapted to 5 proficiency levels from beginner to advanced",
  aboutFeature2Title: "Learn by Reading",
  aboutFeature2Desc: "Improve vocabulary and comprehension through context",
  aboutFeature3Title: "Track Progress",
  aboutFeature3Desc: "See your improvement as you read more stories",
  getStarted: "Get Started",
  backToHome: "Back to Home",
},

settings: {
  notLoggedIn: "You are not logged in.",
  greeting: "Hi {name}! 🎉",
  premium: "PRO",
  free: "Free",
  memberStatus: "Member Status",
  nativeLanguage: "My native language:",
  takeQuiz: "▶️ Take the Quiz",
  logOut: "🚪 Log Out",
  loadingLevel: "Loading level...",
  backToStories: "Back to Stories",
  currentLevel: "Current Level",
  levelUndefined: "Current Level: Undefined. Take the Quiz",
  changeLevel: "Take the quiz to change your level",
  earlyAdopterTitle: "You're one of our first 100 users!",
  earlyAdopterMessage: "Thanks for being here from the start. You have free access as an early adopter.",
  earlyAdopterPremium: "You have free premium access as one of our first 100 users. No subscription needed.",
  },

stats: {
  loading: "Loading your stats...",
  lessThanOneMinute: "< 1 min",
  minutes: "min",
  title: "Your Stats",
  memberSince: "Member since",
  timeOnApp: "Time on app",
  timeReading: "Time reading",
  storiesCompleted: "Stories completed"
},
feedback: {
    title1: "Feedback",
    title2: "We'd love to hear your feedback",
    subtitle: "Help us improve Cuentana for everyone",
    typeLabel: "What type of feedback is this?",
    typePlaceholder: "Select feedback type...",
    messageLabel: "Your message",
    placeholder: "What's on your mind?",
    optionalEmail: "Email (for follow-up)",
    cancel: "Cancel",
    send: "Send",
    bug: "🐛 Bug",
    suggestion: "💡 Suggestion",
    other: "✏️ Other",
    optionalFields: "Optional Fields",
    experienceQuestion: "How has your experience been so far?",
    frustrated: "Frustrated",
    neutral: "Neutral",
    happy: "Happy",
    thanks: "Thanks for the feedback!",
    successMessage: "The form was submitted successfully.",
    close: "Close",
  },

premium: {
    benefit1: {
    title: "Instant GPT Translations",
    desc: "Translate any word or phrase with full context."
  },
  benefit2: {
    title: "PRO Stories",
    desc: "Early access to new stories and advanced levels."
  },
  benefit3: {
    title: "Full-Sentence Translation Mode",
    desc: "One-click whole sentence translation with example usage."
  },
  title: "Upgrade Your Plan",
  description: "Unlock smarter tools for faster learning:",
  currentPlan: "Current Plan",
  planPremium: "PRO",
  planFree: "Free",
  returnToStories: "Return to Stories",
  subscribeButton: "Upgrade"
},

translator: {
  translation: "Translation",
  otherCommonUses: "can also mean",
  translating: "Translating",
  signInRequired: "To use AI translations,",
  signIn: "sign in",
  or: "or",
  createAccount: "create a free account",
  saveSignInRequired: "To save words,",
  audioSignInRequired: "To use audio features,",
  rootWord: "Root word",
  lockedFeature: "Upgrade to unlock smart translations",
},

storyTutor: {
  title: "Story Tutor",
  loadingConversation: "Loading conversation...",
  askAnything: "Ask me anything about this story!",
  helpWith: "I can help with vocabulary, grammar, or story comprehension.",
  placeholder: "Ask a question...",
  send: "Send",
  autoMessageWord: "What does \"{word}\" mean?",
  autoMessageVerb: "What does \"{word}\" mean? If it's a verb, can you show me the conjugation?",
  autoMessageSentence: "Can you help me understand this sentence?",
  errorMessage: "Sorry, I encountered an error. Please try again.",
  youSelected: "You selected \"{text}\"",
  seeMore: "See more",
  seeLess: "See less",
  signInToUse: "To use the AI Story Tutor,",
  signIn: "sign in",
  or: "or",
  createAccount: "create a free account",
},

aiTutor: {
  loading: "Loading...",
  startConversation: "Start a conversation with your AI tutor",
  practiceSkills: "Practice your language skills through conversation",
  placeholder: "Type your message...",
  send: "Send",
  errorMessage: "Sorry, I encountered an error. Please try again.",
  signInToUse: "To use the AI Tutor,",
  signIn: "sign in",
  or: "or",
  createAccount: "create a free account",
},

sidebar: {
  guest: "Guest",
  notSignedIn: "Not signed in",
  settings: "Settings",
  goPremium: "Plans",
},

myStories: {
  title: "My Stories",
  upload: "Upload",
  uploadStory: "Upload a Story",
  uploadDescription: "Paste your story text and we'll create learning content at all difficulty levels.",
  noStories: "No stories yet",
  noStoriesDescription: "Upload your first story to start learning with your own content!",
  uploadFirst: "Upload Your First Story",
  addStory: "Add Story",
  wantMore: "Want more stories?",
  upgradeForUnlimited: "Upgrade your plan for unlimited story uploads and longer texts.",
  storyTitle: "Story Title",
  storyTitlePlaceholder: "Enter your story title...",
  sourceLanguage: "Source Language",
  spanish: "Spanish",
  english: "English",
  storyContentPlaceholder: "Paste or type your story here...",
  description: "Description",
  characterCount: "characters",
  uploadButton: "Upload Story",
  uploading: "Uploading...",
  whatHappensNext: "What happens next?",
  step1: "Processing: We'll detect the difficulty level, parse chapters, etc.",
  step2: "Transcription: AI will rewrite the story to match your CEFR level.",
  step3: "Translation: Each level will be translated to both languages.",
  step4: "Your story will be ready to read in 2-20 minutes, depending on length.",
  premiumDailyLimit: "PRO users get 10 uploads per day.",
  dailyUploads: "Daily uploads",
  processing: "Processing...",
  ready: "Ready",
  failed: "Failed",
  partial: "Partial",
  estimatedTime: "Estimated time: 2-3 minutes",
  storyReadyMessage: "Your story is ready to read!",
  processingFailed: "Processing failed. Please try again.",
  readYourStory: "Read Your Story",
  dangerZone: "Danger Zone",
  deleteStory: "Delete Story",
  deleteConfirm: "Are you sure you want to delete \"{title}\"? This action cannot be undone.",
  yesDelete: "Yes, Delete",
  deleting: "Deleting...",
  cancel: "Cancel",
  backToMyStories: "Back to My Stories",
  storyNotFound: "Story not found",
  source: "Source",
  detected: "Detected",
  created: "Created",
  submitForReview: "Submit for Public Review",
  submitting: "Submitting...",
  submittedForReview: "Submitted for review!",
  underReview: "Under review",
  public: "Public",
  notApproved: "Not approved for public",
  premiumRequired: "Upgrade required to share publicly",
  levelBeginner: "A1 - Foundations",
  levelElementary: "A2 - Developing",
  levelIntermediate: "B1 - Independent",
  levelUpperIntermediate: "B2 - Upper-Intermediate",
  levelAdvanced: "C1 - Advanced",
  waiting: "Waiting",
  storyTooShort: "Story is too short. Please provide at least 20 words.",
  storyTooLong: "Story exceeds maximum length.",
  // Cancelled/Partial status
  cancelled: "Cancelled",
  cancelledMessage: "This story upload was cancelled before any chapters were completed.",
  partialMessage: "This story was cancelled mid-upload. Some chapters are available to read.",
  // Content type selection
  contentType: "Content Type",
  contentTypeDescription: "This helps us format your story correctly when displayed.",
  contentTypeAuto: "Auto-detect",
  contentTypeProse: "Novel / Story",
  contentTypePoetry: "Poetry / Lyrics",
  contentTypeEpic: "Epic Poetry",
  contentTypeScript: "Script",
  contentTypeHintAuto: "Select this if you're unsure. Our algorithms analyze your content to determine the best formatting.",
  contentTypeHintProse: "Select this for novels, short stories, articles, or any narrative prose content.",
  contentTypeHintPoetry: "Select this for poetry, song lyrics, or any content with stanza formatting to preserve.",
  contentTypeHintEpic: "Select this for epic or narrative poetry like Beowulf or The Odyssey with canto/book structure.",
  contentTypeHintScript: "Select this for screenplays, stage plays, or dialogue-heavy content with speaker labels.",
  // Processing mode selection
  processingMode: "Reading Versions",
  processingModeDescription: "Choose which versions of the text to generate.",
  processingModeOriginal: "Original only",
  processingModeRewritten: "My level only",
  processingModeBoth: "Both",
  processingModeHintOriginal: "Translate the text as-is at its detected difficulty level.",
  processingModeHintRewritten: "Rewrite to your reading level and translate. Skips the original if it's a different level.",
  processingModeHintBoth: "Translate the original and also create a version adapted to your level.",
  // Upload modal UI strings
  uploadSubtitle: "Upload a file or paste your story and we'll turn it into learning content",
  storyContent: "Story content",
  characters: "characters",
  words: "words",
  removeFile: "Remove file",
  fileExceedsLimit: "File exceeds word limit. Please use a shorter file.",
  dropFileHere: "Drop a file here or click to browse",
  supportedFormats: "Supports: .txt, .html, .rtf",
  orPasteText: "or paste your text",
  advancedOptions: "Advanced options",
  titleOptional: "optional - will be auto-detected",
  titlePlaceholder: "Leave empty to auto-detect",
  descriptionLabel: "Description",
  descriptionOptional: "optional - will be auto-generated",
  descriptionPlaceholder: "A brief description of your story...",
  storiesCount: "Stories:",
  todayCount: "Today:",
  storyLimitReached: "Story limit reached",
  dailyLimitReached: "Daily limit reached",
  storyLimitMessage: "You've reached the maximum of {max} stories.",
  dailyLimitMessage: "You've used your daily upload limit. Try again tomorrow!",
  upgradeToPremium: "Upgrade",
  upgradeForMore: "Upgrade for more",
  firstStoryBonus: "First story this month: up to {max} words free.",
  freeTierLimit: "Free tier: {max} words.",
  errorReadingFile: "Error reading file",
  unsupportedFileType: "Unsupported file type. Accepted: {types}",
  pleaseEnterStory: "Please paste or type your story",
  storyExceedsLimit: "Story exceeds the {max} word limit.",
  freeTier: "Free tier",
  storiesCountUnlimited: "Stories: {count}",
  storiesCountLimit: "{count} / {max} stories",
  // Tag translations
  tagFamily: "Family",
  tagFriendship: "Friendship",
  tagAdventure: "Adventure",
  tagMystery: "Mystery",
  tagRomance: "Romance",
  tagComingOfAge: "Coming of Age",
  tagNature: "Nature",
  tagTechnology: "Technology",
  tagTravel: "Travel",
  tagFood: "Food",
  tagHumorous: "Humorous",
  tagHeartwarming: "Heartwarming",
  tagSuspenseful: "Suspenseful",
  tagReflective: "Reflective",
  tagInspiring: "Inspiring",
  tagUrban: "Urban",
  tagRural: "Rural",
  tagHistorical: "Historical",
  tagFantasy: "Fantasy",
  tagContemporary: "Contemporary",
  tagLatinAmerica: "Latin America",
  tagSpain: "Spain",
  tagUsa: "USA",
  tagMulticultural: "Multicultural",
  tagEpic: "Epic",
  tagMythology: "Mythology",
  tagHeroic: "Heroic",
  tagTragedy: "Tragedy",
  tagComedy: "Comedy",
  tagMonsters: "Monsters",
  tagHerosJourney: "Hero's Journey",
  tagWar: "War",
  tagLove: "Love",
  tagDeath: "Death",
  tagRevenge: "Revenge",
  // Story type translations
  typeShortStory: "Short Story",
  typePoem: "Poem",
  typeFable: "Fable",
  typeFolktale: "Folktale",
  typeNovel: "Novel",
  typeArticle: "Article",
  typeDialogue: "Dialogue",
  typeSongLyrics: "Song Lyrics",
  typeEpic: "Epic",
  typeMyth: "Myth",
  typeLegend: "Legend",
  typeMovieScript: "Movie Script",
  typeTvScript: "TV Script",
  // Target audience translations
  audienceAll: "All",
  audienceChildren: "Children",
  audienceTeen: "Teen",
  audienceAdult: "Adult",
},

upload: {
  // Phase titles
  detecting: "Detecting...",
  adapting: "Adapting...",
  translating: "Translating...",
  finalizing: "Wrapping things up...",
  // Stage steps
  detect: "Detect",
  adapt: "Adapt",
  translate: "Translate",
  done: "Done",
  // Error
  uploadFailed: "Upload failed",
  dismiss: "Dismiss",
  // Review
  reviewYourStory: "Review Your Story",
  // Messages
  uploadingStory: "Uploading your story...",
  detectingLanguage: "Detecting language...",
  analyzingLevel: "Analyzing difficulty level...",
  creatingDescription: "Creating title & description...",
  adaptingLevel: "Adapting {from}→{to}",
  adaptingGeneric: "Adapting",
  translatingRewritten: "Translating rewritten {level} text...",
  translatingOriginal: "Translating {level} text...",
  finalizingStory: "Finalizing your story...",
  readyForReview: "Ready for review!",
  uploadSuccess: "Story uploaded successfully!",
  somethingWentWrong: "Something went wrong",
  processingStory: "Processing Story",
  chapterProgress: "Chapter {current}/{total}",
  // Step labels (displayed as carousel subtitle during upload)
  stepCreatingRecord: "Creating story record",
  stepPreparingLevels: "Preparing reading levels",
  stepDetectingLanguage: "Detecting language",
  stepAnalyzingMetadata: "Analyzing story metadata",
  stepGeneratingTitle: "Generating title",
  stepGeneratingDescription: "Generating description",
  stepGeneratingHook: "Generating hook",
  stepDetectingStoryType: "Detecting story type",
  stepDetectingAudience: "Detecting target audience",
  stepExtractingTags: "Extracting tags",
  stepDetectingLevel: "Detecting CEFR level",
  stepCleaningText: "Cleaning text",
  stepParsingChapters: "Parsing chapters",
  stepAdaptingLevels: "Adapting to reading levels",
  stepRewritingChapter: "Rewriting chapter",
  stepTranslatingLevels: "Translating all levels",
  stepTranslatingChapter: "Translating chapter",
  stepBuildingLevels: "Building all levels",
  stepBuildingStructure: "Building content structure",
  stepSavingContent: "Saving level content",
  stepComplete: "Complete",
  stepChapterOf: "{current} of {total}",
  // ComparisonModal (progress viewer)
  rewrite: "Rewrite",
  rewriteFromTo: "Rewrite {from} → {to}",
  translateLevel: "Translate {level}",
  translateOriginal: "Translate {level} (Original)",
  translateRewritten: "Translate {level} (Rewritten)",
  original: "Original",
  rewritten: "Rewritten",
  source: "source",
  translated: "translated",
  englishSource: "English (Source)",
  spanishSource: "Spanish (Source)",
  englishTranslation: "English (Translation)",
  spanishTranslation: "Spanish (Translation)",
  chaptersCount: "{completed} of {total} chapters",
  rewritingChapter: "Rewriting chapter {current}...",
  translatingChapterLive: "Translating chapter {current}...",
  chapters: "Chapters:",
  chapterLabel: "Chapter {num}: {left} {leftLabel} → {right} {rightLabel}",
  lineCountMismatch: "Line count mismatch",
  progress: "Progress:",
  lines: "lines",
  loadingPreview: "Loading preview data...",
  failedToLoadPreview: "Failed to load preview",
  waitingForFirstChapter: "Waiting for first chapter to complete...",
  rewritingChapterOf: "Rewriting chapter {current} of {total}",
  translatingChapterOf: "Translating chapter {current} of {total}",
  stanzaBreak: "⸺ stanza break ⸺",
  paragraphBreak: "⸺ paragraph break ⸺",
  // StreamSelector
  previewCompletedStory: "Preview completed story",
  viewProgress: "View Progress",
  chaptersCompleted: "{completed} / {total} chapters completed",
  waitingToStart: "Waiting to start...",
  processingFirstChapter: "Processing first chapter...",
  // Cancel dialog
  cancelUploadTitle: "Cancel Upload?",
  cancelUploadMessage: "This will stop the upload and discard all progress. Are you sure you want to cancel?",
  keepUploading: "Keep Uploading",
  yesCancelUpload: "Yes, Cancel",
  cancelling: "Cancelling...",
},

storiesMetadata: {
  aventura: {
    title: "Aventura",
    description: "Mysteries and hidden creatures in an enchanted forest.",
  },
  "the-last-word": {
    title: "The Last Word",
    hook: "A girl who can barely speak in class is asked to read a poem on stage in front of the entire school.",
    description: "Maya freezes during a history presentation and wishes she could disappear. Then her Spanish teacher announces a poetry project — performed live, on stage, in front of everyone. There's no way out. But late one night, a blank page pulls something unexpected out of her: a poem about birds, about her dog, about Saturday mornings with her dad — and about the silence he left behind.",
  },
  "diego-unplugged": {
    title: "Diego Unplugged",
    hook: "A teenager drops his phone out a window and is forced to survive a month without it.",
    description: "Diego never goes anywhere without his phone. Not to the kitchen, not to bed, not even across the street. Then one summer evening, it slips from his hands and shatters on the sidewalk two stories below. His parents won't pay for the repair. It will take a month of work to save up. At first, the silence is unbearable. Food tastes like nothing, music falls flat, and his hands keep reaching for something that isn't there. But slowly, the world starts to get louder — in ways he never expected.",
  },
  "el-viaje-magico": {
    title: "The Magic Journey",
    description: "A train, an ancient map, and a door to another world.",
  },
  "secretos-del-desierto": {
    title: "Secrets of the Desert",
    description: "The past comes alive among the desert dunes.",
  },
  "my-day-3": {
    title: "My Day",
    hook: "A simple poem about the rhythm of an ordinary day — from dawn to dusk.",
    description: "",
  },
  "poems-by-emily-dickinson-complete": {
    title: "Poems by Emily Dickinson, Three Series, Complete",
    hook: "Discover the introspective and unconventional poetry of Emily Dickinson, reflecting her unique perspective on life and success.",
    description: "This collection brings together the early published poems of Emily Dickinson, edited after her death by Mabel Loomis Todd and T. W. Higginson. Written largely without thought of publication, her verses reflect a fiercely independent spirit and an unconventional style that defied the literary norms of her time. A lifelong recluse from Amherst, Massachusetts, Dickinson produced poems of striking originality—flashes of profound insight into nature, life, faith, and death—marked by vivid imagery, daring thought, and a voice unlike any other in American poetry.",
  },"the-great-gatsby-a-8": {
    title: "The Great Gatsby",
    hook: "In the roaring twenties, a mysterious millionaire captivates with his lavish lifestyle and secrets.",
    description: "In the shimmering summer of 1922, a young man from the Midwest arrives on the shores of Long Island and enters a world of unimaginable wealth, reckless indulgence, and broken dreams. His enigmatic neighbor, Jay Gatsby, throws lavish parties at his Gothic mansion—yet no one seems to know who he truly is or what he desires.\n\nAs Nick Carraway is drawn into Gatsby's orbit, he discovers the truth behind the spectacle: a consuming, hopeless love for Daisy Buchanan—a woman of old money, charm, and carelessness. Gatsby has reinvented himself entirely, building a fortune on the dark fringes of the American Dream, all for the chance to reclaim a past that may never have truly existed.\n\nBut beneath the glitter of Jazz Age New York lies a world of betrayal, violence, and moral decay. When secrets unravel and loyalties are tested, the consequences prove devastating—and inescapable.\n\nWidely regarded as one of the greatest novels ever written, The Great Gatsby is F. Scott Fitzgerald's luminous portrait of the American Dream—its promise, its seduction, and its ruin.",
  },
  "the-adventures-of-tom-sawyer": {
    title: "The Adventures of Tom Sawyer",
    displayTitle: "Tom Sawyer",
    hook: "Join Tom Sawyer in a world of mischief, friendship, and unforgettable adventures along the Mississippi River.",
    description: "This classic story follows Tom Sawyer, a clever and adventurous boy growing up in a small town in 19th-century America. Alongside his friend Huck Finn, he gets caught up in exciting escapades—from treasure hunts and cave explorations to witnessing a shocking crime.\n\nMany of the adventures in this story were inspired by real experiences from Mark Twain’s childhood and the lives of those around him. Tom Sawyer himself is a blend of several boys Twain knew, making him a vivid and authentic character.\n\nAlthough written with young readers in mind, the story also invites adults to rediscover the imagination, curiosity, and bold spirit of childhood.",
  },
  "the-wonderful-wizard-of-oz": {
    title: "The Wonderful Wizard of Oz",
    displayTitle: "The Wizard of Oz",
    hook: "Dorothy lives a dull life on the Kansas prairie until a whirlwind takes her on an unexpected journey.",
    description: "This classic story follows Dorothy, a young girl swept away from her home in Kansas to the magical Land of Oz. As she journeys to find her way back, she meets unforgettable companions—a Scarecrow in search of a brain, a Tin Woodman longing for a heart, and a Cowardly Lion seeking courage.\n\nTogether, they embark on an adventure filled with challenges, strange creatures, and powerful magic, all while discovering that the qualities they seek may have been within them all along.\n\nWritten by L. Frank Baum, this timeless tale has captivated readers for generations with its imaginative world, memorable characters, and enduring message about friendship, courage, and believing in oneself.\n\nAlthough written with young readers in mind, the story continues to resonate with audiences of all ages through its warmth, wonder, and universal themes.",
  },




},

audioPlayer: {
  listen: "Listen",
  listening: "Listening",
  turningPage: "Turning page...",
  storyComplete: "Story complete!",
  targetOnly: "Learning language only",
  bilingual: "Both languages",
  resumeListening: "Resume listening",
  errorRetry: "Retry",
  errorSkip: "Skip",
  english: "English",
  spanish: "Spanish",
  playbackSpeed: "Playback Speed",
  settings: "Settings",
  speed: "Speed",
  voice: "Voice",
  close: "Close",
  languageToggle: "ES + EN",
  readBothLanguages: "Read both languages",
  on: "ON",
  off: "OFF",
  preparing: "Preparing",
  checkingCache: "Checking cache...",
  cancel: "Cancel",
  startListening: "Start Listening",
  collection: "Collection",
  chapter: "Chapter",
  line: "line",
  paragraph: "paragraph",
  firstGenLine1: "Congratulations! You're the first to request this {section}'s audio.",
  firstGenLine2: "After it loads, you (and all other users) will have instant playback.",
  firstGenLine3: "Thanks for paving the way for everyone!",
  errorTitle: "We're sorry, something went wrong",
  errorMessage: "We couldn't load the audio. Please refresh the page and try again.",
  errorClose: "Close",
  audioSettings: "Audio Settings",
  normalSpeed: "Normal",
  slowSpeed: "Slow",
  cached: "Ready",
  requiresGeneration: "Requires generation",
  start: "Start",
  startGenerating: "Start Generating",
  variantStandard: "Standard",
  variantSlow: "Slow",
  variantStandardBilingual: "Standard ES + EN",
  variantSlowBilingual: "Slow ES + EN",
  variantStandardDesc: "Normal speed, Spanish only",
  variantSlowDesc: "0.7x speed, Spanish only",
  variantStandardBilingualDesc: "Normal speed, Spanish + English",
  variantSlowBilingualDesc: "0.7x speed, Spanish + English",
},
};

export default en;
