// /src/content/ui/en.ts
const en = {
auth: {
  login: "Log In",
  signup: "Sign Up",
  logout: "Log Out",
  email: "Email",
  password: "Password",
  confirmPassword: "Confirm Password",
  name: "Name",
  welcomeBack: "Welcome back!",
  error: "Incorrect credentials. Please try again.",
  or: "or",
  googleLogin: "Log in with Google",
  languagePrompt: "Native language / Idioma nativo:",
  createAccountCard: "Create an account",
  signupError: "Something went wrong. Please try again.",
  signupSuccess: "Account created! Redirecting...",
  signupGoogle: "Sign up with Google",
  alreadyHaveAccount: "Already have an account?",
  newHere: "New Here?",
},

language: {
  en: "English",
  es: "Español"
},

stories: {
  goPremium: "Go Premium 💎",
  premiumDescription: "Cuentana Premium unlocks smarter tools for faster learning.",
  dashboard: "Dashboard",
  settings: "Settings",
  stories: "Stories",
  loading: "Loading...",
  continue: "Continue",
  back: "Back",
  readStory: "Read Me",
  availableLevels: "Available in levels:",
  level: "Level",
  storiesAll: "Stories",
  aiTutor: "AI Tutor",
  takeQuiz: "Take the Quiz",
  myAccount: "My Account",
  createAccount: "Create an Account",
},

story: {
  page: "Page",
  chapter: "Chapter",
  navigate: "Navigate ▾",
  home: "Home",
  levelSelect: "Level Select",
  prev: "Prev",
  next: "Next",
  markComplete: "Mark this story as complete",
  markedComplete: "✅ Story marked as complete!",
  levelUnavailable: "This story is not available at your current level.",
  availableLevelsAre: "Available levels:",
  selectLevel: "Select a level to continue reading:",
},

levels: {
  l1: "Brand New",
  l2: "Beginner",
  l3: "Intermediate",
  l4: "Advanced",
  l5: "Fluent"
},

home: {
  subtitle: "Learn faster. Learn with stories.",
  quizTitle: "Take the Quiz",
  recommended: "(recommended)",
  letUsPick: "Let us customize your learning experience based on the results.",
  startQuiz: "Start Quiz",
  noThanksTitle: "No Thanks",
  pickLater: "You can customize your level later in app",
  startLearning: "Start Learning",
  haveAccount: "Already have an account?",
  whyTitle: "Why",
  placeholderInfo: "Put your additional information here 🚀",
  aboutLink: "Get to know Cuentana",
  aboutPrefix: "Get to know"
},

settings: {
  notLoggedIn: "You are not logged in.",
  greeting: "Hi {name}! 🎉",
  premium: "Premium 💎",
  free: "Free",
  memberStatus: "Member Status",
  nativeLanguage: "My native language:",
  takeQuiz: "▶️ Take the Quiz",
  logOut: "🚪 Log Out",
  loadingLevel: "Loading level...",
  backToStories: "Back to Stories",
  currentLevel: "Current Level",
  levelUndefined: "Current Level: Undefined. Take the Quiz",
  changeLevel: "Take the quiz to change your level",
  },

stats: {
  loading: "Loading your stats...",
  lessThanOneMinute: "< 1 min",
  minutes: "min",
  title: "Your Stats",
  memberSince: "Member since",
  timeOnApp: "Time on app",
  timeReading: "Time reading",
  storiesCompleted: "Stories completed"
},
feedback: {
    title1: "Feedback",
    title2: "We'd love to hear your feedback",
    subtitle: "Help us improve Cuentana for everyone",
    typeLabel: "What type of feedback is this?",
    typePlaceholder: "Select feedback type...",
    messageLabel: "Your message",
    placeholder: "What's on your mind?",
    optionalEmail: "Email (for follow-up)",
    cancel: "Cancel",
    send: "Send Feedback",
    bug: "🐛 Bug",
    suggestion: "💡 Suggestion",
    other: "✏️ Other",
    optionalFields: "Optional Fields",
    experienceQuestion: "How has your experience been so far?",
    frustrated: "Frustrated",
    neutral: "Neutral",
    happy: "Happy",
    thanks: "Thanks for the feedback!",
    successMessage: "The form was submitted successfully.",
    close: "Close",
  },

premium: {
    benefit1: {
    title: "Instant GPT Translations",
    desc: "Translate any word or phrase with full context."
  },
  benefit2: {
    title: "Premium-Only Stories",
    desc: "Early access to new stories and advanced levels."
  },
  benefit3: {
    title: "Full-Sentence Translation Mode",
    desc: "One-click whole sentence translation with example usage."
  },
  title: "Go Premium 💎",
  description: "Cuentana Premium unlocks smarter tools for faster learning:",
  currentPlan: "Current Plan",
  planPremium: "Premium 💎",
  planFree: "Free",
  returnToStories: "Return to Stories",
  subscribeButton: "Subscribe to Premium"
},

translator: {
  translation: "Translation",
  otherCommonUses: "can also mean",
  translating: "Translating"
},

storyTutor: {
  title: "Story Tutor",
  loadingConversation: "Loading conversation...",
  askAnything: "Ask me anything about this story!",
  helpWith: "I can help with vocabulary, grammar, or story comprehension.",
  placeholder: "Ask a question...",
  send: "Send",
  autoMessageWord: "What does \"{word}\" mean?",
  autoMessageVerb: "What does \"{word}\" mean? If it's a verb, can you show me the conjugation?",
  autoMessageSentence: "Can you help me understand this sentence?",
  errorMessage: "Sorry, I encountered an error. Please try again.",
  youSelected: "You selected \"{text}\""
},

aiTutor: {
  loading: "Loading...",
  startConversation: "Start a conversation with your AI tutor",
  practiceSkills: "Practice your language skills through conversation",
  placeholder: "Type your message...",
  send: "Send",
  errorMessage: "Sorry, I encountered an error. Please try again."
},

myStories: {
  title: "My Stories",
  upload: "Upload",
  uploadStory: "Upload a Story",
  uploadDescription: "Paste your story text and we'll create learning content at all difficulty levels.",
  noStories: "No stories yet",
  noStoriesDescription: "Upload your first story to start learning with your own content!",
  uploadFirst: "Upload Your First Story",
  addStory: "Add Story",
  wantMore: "Want more stories?",
  upgradeForUnlimited: "Upgrade to Premium for unlimited story uploads and longer texts.",
  storyTitle: "Story Title",
  storyTitlePlaceholder: "Enter your story title...",
  sourceLanguage: "Source Language",
  spanish: "Spanish",
  english: "English",
  storyContent: "Story Content",
  storyContentPlaceholder: "Paste or type your story here...",
  description: "Description",
  descriptionOptional: "optional",
  descriptionPlaceholder: "A brief description of your story...",
  characterCount: "characters",
  freeTierLimit: "Free tier",
  upgradeForMore: "Upgrade for more",
  uploadButton: "Upload Story",
  uploading: "Uploading...",
  whatHappensNext: "What happens next?",
  step1: "Processing: We'll detect the difficulty level, parse chapters, etc.",
  step2: "Transcription: AI will rewrite the story to match your CEFR level.",
  step3: "Translation: Each level will be translated to both languages.",
  step4: "Your story will be ready to read in 2-20 minutes, depending on length.",
  storyLimitReached: "Story Limit Reached",
  storyLimitMessage: "You've reached the maximum of {max} stories.",
  dailyLimitReached: "Daily Limit Reached",
  dailyLimitMessage: "You've used your daily upload limit. Try again tomorrow!",
  premiumDailyLimit: "Premium users get 10 uploads per day.",
  dailyUploads: "Daily uploads",
  processing: "Processing...",
  ready: "Ready",
  failed: "Failed",
  partial: "Partial",
  estimatedTime: "Estimated time: 2-3 minutes",
  storyReadyMessage: "Your story is ready to read!",
  processingFailed: "Processing failed. Please try again.",
  readYourStory: "Read Your Story",
  dangerZone: "Danger Zone",
  deleteStory: "Delete Story",
  deleteConfirm: "Are you sure you want to delete \"{title}\"? This action cannot be undone.",
  yesDelete: "Yes, Delete",
  deleting: "Deleting...",
  cancel: "Cancel",
  backToMyStories: "Back to My Stories",
  storyNotFound: "Story not found",
  source: "Source",
  detected: "Detected",
  created: "Created",
  submitForReview: "Submit for Public Review",
  submitting: "Submitting...",
  submittedForReview: "Submitted for review!",
  underReview: "Under review",
  public: "Public",
  notApproved: "Not approved for public",
  premiumRequired: "Premium required to share publicly",
  levelBeginner: "Level 1 (A1 - Beginner)",
  levelElementary: "Level 2 (A2 - Elementary)",
  levelIntermediate: "Level 3 (B1 - Intermediate)",
  levelUpperIntermediate: "Level 4 (B2 - Upper Intermediate)",
  levelAdvanced: "Level 5 (C1 - Advanced)",
  waiting: "Waiting",
  storyTooShort: "Story is too short. Please provide at least 100 characters.",
  storyTooLong: "Story exceeds maximum length.",
},

storiesMetadata: {
  aventura: {
    title: "Aventura",
    description: "Mysteries and hidden creatures in an enchanted forest.",
  },
  "the-last-word": {
    title: "The Last Word",
    description: "Mysteries and hidden creatures in an enchanted forest.",
  },
  "diego-unplugged": {
    title: "Diego Unplugged",
    description: "A young man's journey of self-discovery when he disconnects from the digital world.",
  },
  "my-day": {
    title: "My Day",
    description: "A simple poem about the joys of everyday life.",
  },"el-viaje-magico": {
    title: "The Magic Journey",
    description: "A train, an ancient map, and a door to another world.",
  },
  "secretos-del-desierto": {
    title: "Secrets of the Desert",
    description: "The past comes alive among the desert dunes.",
  },
}

};

export default en;
