// /src/content/ui/en.ts
const en = {
auth: {
  login: "Log In",
  signup: "Sign Up",
  logout: "Log Out",
  email: "Email",
  password: "Password",
  confirmPassword: "Confirm Password",
  name: "Name",
  welcomeBack: "Welcome back!",
  error: "Incorrect credentials. Please try again.",
  or: "or",
  googleLogin: "Log in with Google",
  languagePrompt: "Native language / Idioma nativo:",
  createAccountCard: "Create an account",
  signupError: "Something went wrong. Please try again.",
  signupSuccess: "Account created! Redirecting...",
  signupGoogle: "Sign up with Google",
  alreadyHaveAccount: "Already have an account?",
  newHere: "New Here?",
  loggingIn: "Logging in...",
  creatingAccount: "Creating account...",
  sendOneTimeCode: "Get a one-time login code instead",
  usePassword: "Use password instead",
  forgotPassword: "Forgot password?",
  resetPassword: "Reset Password",
  resetPasswordTitle: "Reset your password",
  resetPasswordSubtitle: "Enter your email and we'll send you a code to reset your password.",
  newPassword: "New Password",
  confirmNewPassword: "Confirm New Password",
  passwordUpdated: "Password updated successfully!",
  passwordMismatch: "Passwords do not match",
  setNewPassword: "Set New Password",
  updating: "Updating...",
},

language: {
  en: "English",
  es: "Español"
},

stories: {
  goPremium: "Go Premium 💎",
  premiumDescription: "Cuentana Premium unlocks smarter tools for faster learning.",
  dashboard: "Dashboard",
  settings: "Settings",
  stories: "Stories",
  loading: "Loading...",
  continue: "Continue",
  back: "Back",
  readStory: "Read Me",
  availableLevels: "Available in levels:",
  level: "Level",
  storiesAll: "Stories",
  aiTutor: "AI Tutor",
  takeQuiz: "Take the Quiz",
  myAccount: "My Account",
  createAccount: "Create an Account",
},

story: {
  page: "Page",
  chapter: "Chapter",
  navigate: "Navigate ▾",
  home: "Home",
  levelSelect: "Level Select",
  prev: "Prev",
  next: "Next",
  markComplete: "Mark this story as complete",
  markedComplete: "✅ Story marked as complete!",
  levelUnavailable: "This story is not available at your current level.",
  availableLevelsAre: "Available levels:",
  selectLevel: "Select a level to continue reading:",
  // Poetry anthology navigation labels
  collection: "Collection",
  poem: "Poem",
  // Epic/narrative poetry navigation labels
  canto: "Canto",
  section: "Section",
  // Script navigation labels
  act: "Act",
  scene: "Scene",
},

levels: {
  // Legacy keys for backwards compatibility
  l1: "A1 - Foundations",
  l2: "A2 - Developing",
  l3: "B1 - Independent",
  l4: "B2 - Upper-Intermediate",
  l5: "C1 - Advanced",
  l6: "C2 - Near-Native",
  // CEFR codes
  A1: "A1 - Foundations",
  A2: "A2 - Developing",
  B1: "B1 - Independent",
  B2: "B2 - Upper-Intermediate",
  C1: "C1 - Advanced",
  C2: "C2 - Near-Native",
  // CEFR labels (for dropdown displays)
  cefrLabels: {
    l1: "A1",
    l2: "A2",
    l3: "B1",
    l4: "B2",
    l5: "C1",
    l6: "C2",
  },
  // CEFR descriptions (for onboarding/quiz)
  cefrDescriptions: {
    l1: "Can understand and use basic expressions for concrete needs. Can introduce yourself and ask simple personal questions.",
    l2: "Can understand frequently used expressions on familiar topics like shopping, family, and work. Can handle simple, routine exchanges.",
    l3: "Can handle most situations while traveling. Can describe experiences, events, and briefly explain opinions and plans.",
    l4: "Can understand complex texts and interact fluently with native speakers. Can produce clear, detailed text on a wide range of subjects.",
    l5: "Can understand demanding texts and recognize implicit meaning. Can express ideas fluently with precision and flexibility.",
    l6: "Can understand virtually everything heard or read. Can summarize information from different sources, reconstructing arguments coherently.",
  },
},

home: {
  subtitle: "Learn faster. Learn with stories.",
  quizTitle: "Take the Quiz",
  recommended: "(recommended)",
  letUsPick: "Answer a few questions and we'll personalize your experience.",
  startQuiz: "Start Quiz",
  noThanksTitle: "No Thanks",
  pickLater: "You can customize your level later in app",
  startLearning: "Start Learning",
  haveAccount: "Already have an account?",
  whyTitle: "Why",
  placeholderInfo: "Put your additional information here 🚀",
  aboutLink: "Get to know Cuentana",
  aboutPrefix: "Get to know"
},

onboarding: {
  stepLanguage: "Language",
  stepLevel: "Level",
  stepStart: "Start",
  welcomeTitle: "Welcome to Cuentana",
  welcomeSubtitle: "Let's personalize your learning experience",
  languageTitle: "What's your native language?",
  languageSubtitle: "This helps us customize your experience",
  findYourLevel: "Find Your Level",
  findYourLevelDesc: "Take a quick quiz to find the perfect starting point.",
  quizDuration: "5 questions",
  knowYourLevel: "Already know your level?",
  selectBelow: "Select your proficiency below",
  continueToStories: "Continue to Stories",
  quizProgress: "Question {current} of {total}",
  yourResult: "Your Level",
  startReading: "Start Reading",
  selectLevel: "Select",
  allSetTitle: "You're All Set",
  levelSetTo: "Your level is set to",
  createAccountTitle: "Create a Free Account",
  createAccountBenefit1: "Save your progress across devices",
  createAccountBenefit2: "Upload your own stories",
  createAccountBenefit3: "Build your personal vocabulary list",
  createAccountCta: "Create Account",
  skipForNow: "Skip for now",
},

about: {
  tagline: "Learn Spanish through stories",
  whatIs: "What is Cuentana?",
  description: "Cuentana is a language learning app that helps you improve your Spanish through engaging stories. Whether you're a beginner or advanced learner, our curated collection of stories adapts to your level, making learning natural and enjoyable.",
  aboutFeature1Title: "Leveled Reading",
  aboutFeature1Desc: "Stories adapted to 5 proficiency levels from beginner to advanced",
  aboutFeature2Title: "Learn by Reading",
  aboutFeature2Desc: "Improve vocabulary and comprehension through context",
  aboutFeature3Title: "Track Progress",
  aboutFeature3Desc: "See your improvement as you read more stories",
  getStarted: "Get Started",
  backToHome: "Back to Home",
},

settings: {
  notLoggedIn: "You are not logged in.",
  greeting: "Hi {name}! 🎉",
  premium: "Premium 💎",
  free: "Free",
  memberStatus: "Member Status",
  nativeLanguage: "My native language:",
  takeQuiz: "▶️ Take the Quiz",
  logOut: "🚪 Log Out",
  loadingLevel: "Loading level...",
  backToStories: "Back to Stories",
  currentLevel: "Current Level",
  levelUndefined: "Current Level: Undefined. Take the Quiz",
  changeLevel: "Take the quiz to change your level",
  },

stats: {
  loading: "Loading your stats...",
  lessThanOneMinute: "< 1 min",
  minutes: "min",
  title: "Your Stats",
  memberSince: "Member since",
  timeOnApp: "Time on app",
  timeReading: "Time reading",
  storiesCompleted: "Stories completed"
},
feedback: {
    title1: "Feedback",
    title2: "We'd love to hear your feedback",
    subtitle: "Help us improve Cuentana for everyone",
    typeLabel: "What type of feedback is this?",
    typePlaceholder: "Select feedback type...",
    messageLabel: "Your message",
    placeholder: "What's on your mind?",
    optionalEmail: "Email (for follow-up)",
    cancel: "Cancel",
    send: "Send Feedback",
    bug: "🐛 Bug",
    suggestion: "💡 Suggestion",
    other: "✏️ Other",
    optionalFields: "Optional Fields",
    experienceQuestion: "How has your experience been so far?",
    frustrated: "Frustrated",
    neutral: "Neutral",
    happy: "Happy",
    thanks: "Thanks for the feedback!",
    successMessage: "The form was submitted successfully.",
    close: "Close",
  },

premium: {
    benefit1: {
    title: "Instant GPT Translations",
    desc: "Translate any word or phrase with full context."
  },
  benefit2: {
    title: "Premium-Only Stories",
    desc: "Early access to new stories and advanced levels."
  },
  benefit3: {
    title: "Full-Sentence Translation Mode",
    desc: "One-click whole sentence translation with example usage."
  },
  title: "Go Premium 💎",
  description: "Cuentana Premium unlocks smarter tools for faster learning:",
  currentPlan: "Current Plan",
  planPremium: "Premium 💎",
  planFree: "Free",
  returnToStories: "Return to Stories",
  subscribeButton: "Subscribe to Premium"
},

translator: {
  translation: "Translation",
  otherCommonUses: "can also mean",
  translating: "Translating"
},

storyTutor: {
  title: "Story Tutor",
  loadingConversation: "Loading conversation...",
  askAnything: "Ask me anything about this story!",
  helpWith: "I can help with vocabulary, grammar, or story comprehension.",
  placeholder: "Ask a question...",
  send: "Send",
  autoMessageWord: "What does \"{word}\" mean?",
  autoMessageVerb: "What does \"{word}\" mean? If it's a verb, can you show me the conjugation?",
  autoMessageSentence: "Can you help me understand this sentence?",
  errorMessage: "Sorry, I encountered an error. Please try again.",
  youSelected: "You selected \"{text}\""
},

aiTutor: {
  loading: "Loading...",
  startConversation: "Start a conversation with your AI tutor",
  practiceSkills: "Practice your language skills through conversation",
  placeholder: "Type your message...",
  send: "Send",
  errorMessage: "Sorry, I encountered an error. Please try again."
},

myStories: {
  title: "My Stories",
  upload: "Upload",
  uploadStory: "Upload a Story",
  uploadDescription: "Paste your story text and we'll create learning content at all difficulty levels.",
  noStories: "No stories yet",
  noStoriesDescription: "Upload your first story to start learning with your own content!",
  uploadFirst: "Upload Your First Story",
  addStory: "Add Story",
  wantMore: "Want more stories?",
  upgradeForUnlimited: "Upgrade to Premium for unlimited story uploads and longer texts.",
  storyTitle: "Story Title",
  storyTitlePlaceholder: "Enter your story title...",
  sourceLanguage: "Source Language",
  spanish: "Spanish",
  english: "English",
  storyContentPlaceholder: "Paste or type your story here...",
  description: "Description",
  characterCount: "characters",
  uploadButton: "Upload Story",
  uploading: "Uploading...",
  whatHappensNext: "What happens next?",
  step1: "Processing: We'll detect the difficulty level, parse chapters, etc.",
  step2: "Transcription: AI will rewrite the story to match your CEFR level.",
  step3: "Translation: Each level will be translated to both languages.",
  step4: "Your story will be ready to read in 2-20 minutes, depending on length.",
  premiumDailyLimit: "Premium users get 10 uploads per day.",
  dailyUploads: "Daily uploads",
  processing: "Processing...",
  ready: "Ready",
  failed: "Failed",
  partial: "Partial",
  estimatedTime: "Estimated time: 2-3 minutes",
  storyReadyMessage: "Your story is ready to read!",
  processingFailed: "Processing failed. Please try again.",
  readYourStory: "Read Your Story",
  dangerZone: "Danger Zone",
  deleteStory: "Delete Story",
  deleteConfirm: "Are you sure you want to delete \"{title}\"? This action cannot be undone.",
  yesDelete: "Yes, Delete",
  deleting: "Deleting...",
  cancel: "Cancel",
  backToMyStories: "Back to My Stories",
  storyNotFound: "Story not found",
  source: "Source",
  detected: "Detected",
  created: "Created",
  submitForReview: "Submit for Public Review",
  submitting: "Submitting...",
  submittedForReview: "Submitted for review!",
  underReview: "Under review",
  public: "Public",
  notApproved: "Not approved for public",
  premiumRequired: "Premium required to share publicly",
  levelBeginner: "A1 - Foundations",
  levelElementary: "A2 - Developing",
  levelIntermediate: "B1 - Independent",
  levelUpperIntermediate: "B2 - Upper-Intermediate",
  levelAdvanced: "C1 - Advanced",
  waiting: "Waiting",
  storyTooShort: "Story is too short. Please provide at least 100 characters.",
  storyTooLong: "Story exceeds maximum length.",
  // Cancelled/Partial status
  cancelled: "Cancelled",
  cancelledMessage: "This story upload was cancelled before any chapters were completed.",
  partialMessage: "This story was cancelled mid-upload. Some chapters are available to read.",
  // Content type selection
  contentType: "Content Type",
  contentTypeDescription: "This helps us format your story correctly when displayed.",
  contentTypeAuto: "Auto-detect",
  contentTypeProse: "Novel / Story",
  contentTypePoetry: "Poetry / Lyrics",
  contentTypeEpic: "Epic Poetry",
  contentTypeScript: "Script",
  contentTypeHintAuto: "Select this if you're unsure. Our algorithms analyze your content to determine the best formatting.",
  contentTypeHintProse: "Select this for novels, short stories, articles, or any narrative prose content.",
  contentTypeHintPoetry: "Select this for poetry, song lyrics, or any content with stanza formatting to preserve.",
  contentTypeHintEpic: "Select this for epic or narrative poetry like Beowulf or The Odyssey with canto/book structure.",
  contentTypeHintScript: "Select this for screenplays, stage plays, or dialogue-heavy content with speaker labels.",
  // Processing mode selection
  processingMode: "Reading Versions",
  processingModeDescription: "Choose which versions of the text to generate.",
  processingModeOriginal: "Original only",
  processingModeRewritten: "My level only",
  processingModeBoth: "Both",
  processingModeHintOriginal: "Translate the text as-is at its detected difficulty level.",
  processingModeHintRewritten: "Rewrite to your reading level and translate. Skips the original if it's a different level.",
  processingModeHintBoth: "Translate the original and also create a version adapted to your level.",
  // Upload modal UI strings
  uploadSubtitle: "Paste your story and we'll turn it into learning content",
  storyContent: "Story content",
  characters: "characters",
  removeFile: "Remove file",
  fileExceedsLimit: "File exceeds character limit. Please use a shorter file.",
  dropFileHere: "Drop a file here or click to browse",
  supportedFormats: "Supports: .txt, .html, .rtf",
  orPasteText: "or paste your text",
  advancedOptions: "Advanced options",
  titleOptional: "optional - will be auto-detected",
  titlePlaceholder: "Leave empty to auto-detect",
  descriptionLabel: "Description",
  descriptionOptional: "optional - will be auto-generated",
  descriptionPlaceholder: "A brief description of your story...",
  storiesCount: "Stories:",
  todayCount: "Today:",
  storyLimitReached: "Story limit reached",
  dailyLimitReached: "Daily limit reached",
  storyLimitMessage: "You've reached the maximum of {max} stories.",
  dailyLimitMessage: "You've used your daily upload limit. Try again tomorrow!",
  upgradeToPremium: "Upgrade to Premium",
  upgradeForMore: "Upgrade for more",
  firstStoryBonus: "First story this month: up to {max} characters free.",
  freeTierLimit: "Free tier: {max} characters.",
  errorReadingFile: "Error reading file",
  unsupportedFileType: "Unsupported file type. Accepted: {types}",
  pleaseEnterStory: "Please paste or type your story",
  storyExceedsLimit: "Story exceeds the {max} character limit.",
},

storiesMetadata: {
  aventura: {
    title: "Aventura",
    description: "Mysteries and hidden creatures in an enchanted forest.",
  },
  "the-last-word": {
    title: "The Last Word",
    description: "Mysteries and hidden creatures in an enchanted forest.",
  },
  "diego-unplugged": {
    title: "Diego Unplugged",
    description: "A young man's journey of self-discovery when he disconnects from the digital world.",
  },
  "my-day": {
    title: "My Day",
    description: "A simple poem about the joys of everyday life.",
  },
  "el-viaje-magico": {
    title: "The Magic Journey",
    description: "A train, an ancient map, and a door to another world.",
  },
  "secretos-del-desierto": {
    title: "Secrets of the Desert",
    description: "The past comes alive among the desert dunes.",
  },
  "poems-by-emily-dickinson": {
    title: "Poems by Emily Dickinson, Three Series, Complete",
    description: "The verses of Emily Dickinson belong emphatically to what Emerson long since called 'the Poetry of the Portfolio,'—something produced absolutely without the thought of publication, and solely by way of expression of the writer's own mind. Such verse must inevitably forfeit whatever advantage lies in the discipline of public criticism and the enforced conformity to accepted ways. On the other hand, it may often gain something through the habit of freedom and the unconventional utterance of daring thoughts. In the case of the present author, there was absolutely no choice in the matter; she must write thus, or not at all. A recluse by temperament and habit, literally spending years without setting her foot beyond the doorstep, and many more years during which her walks were strictly limited to her father's grounds, she habitually concealed her mind, like her person, from all but a very few friends; and it was with great difficulty that she was persuaded to print, during her lifetime, three or four poems. Yet she wrote verses in great abundance; and though brought curiously indifferent to all conventional rules, had yet a rigorous literary standard of her own, and often altered a word many times to suit an ear which had its own tenacious fastidiousness.",
  },
  },
};

export default en;
