// /src/content/ui/es.ts
const es = {
  auth: {
  login: "Iniciar sesión",
  signup: "Crear cuenta",
  logout: "Cerrar sesión",
  email: "Correo electrónico",
  password: "Contraseña",
  confirmPassword: "Confirmar contraseña",
  name: "Nombre",
  welcomeBack: "¡Bienvenido de nuevo!",
  error: "Credenciales incorrectas. Inténtalo de nuevo.",
  or: "o",
  googleLogin: "Inicia sesión con Google",
  languagePrompt: "Idioma nativo / Native language:",
  createAccountCard: "Crear una cuenta",
  signupError: "Algo salió mal. Inténtalo de nuevo.",
  signupSuccess: "¡Cuenta creada! Redirigiendo...",
  signupGoogle: "Registrarse con Google",
  alreadyHaveAccount: "¿Ya tienes una cuenta?",
  newHere: "¿Eres nuevo?",
},

language: {
  en: "English",
  es: "Español"
},

  stories: {
  goPremium: "Hazte Premium 💎",
  premiumDescription: "Cuentana Premium desbloquea herramientas más inteligentes para aprender más rápido.",
  dashboard: "Panel",
  settings: "Configuración",
  stories: "Historias",
  loading: "Cargando...",
  continue: "Continuar",
  back: "Atrás",
  readStory: "Léeme",
  availableLevels: "Disponible en niveles:",
  level: "Nivel",
  storiesAll: "Historias",
  aiTutor: "Tutor IA",
  takeQuiz: "Haz el Quiz",
  myAccount: "Mi Cuenta",
  createAccount: "Crea una Cuenta",
},

story: {
  page: "Página",
  chapter: "Capítulo",
  navigate: "Navegar ▾",
  home: "Inicio",
  levelSelect: "Seleccionar Nivel",
  prev: "Anterior",
  next: "Siguiente",
  markComplete: "Marcar esta historia como completada",
  markedComplete: "✅ ¡Historia marcada como completada!",
  levelUnavailable: "Esta historia no está disponible en tu nivel actual.",
  availableLevelsAre: "Niveles disponibles:",
  selectLevel: "Selecciona un nivel para continuar leyendo:",
},

levels: {
  l1: "Recién empezado",
  l2: "Principiante",
  l3: "Intermedio",
  l4: "Avanzado",
  l5: "Fluido"
},

  home: {
  subtitle: "Aprende más rápido. Aprende con historias.",
  quizTitle: "Haz el Quiz",
  recommended: "(recomendado)",
  letUsPick: "Vamos a personalizar tu experiencia de aprendizaje según los resultados.",
  startQuiz: "Empezar Quiz",
  noThanksTitle: "No Gracias",
  pickLater: "Puedes personalizar tu nivel más tarde en la aplicación.",
  startLearning: "Comenzar Aprendizaje",
  haveAccount: "¿Ya tienes una cuenta?",
  whyTitle: "¿Por qué",
  placeholderInfo: "Put your additional information here 🚀",
  aboutLink: "Conoce Cuentana",
  aboutPrefix: "Conoce"
},

settings: {
  notLoggedIn: "No has iniciado sesión.",
  greeting: "¡Hola {name}! 🎉",
  premium: "Premium 💎",
  free: "Gratis",
  memberStatus: "Estado de miembro",
  nativeLanguage: "Mi idioma nativo:",
  takeQuiz: "▶️ Haz el Quiz",
  logOut: "🚪 Cerrar sesión",
  loadingLevel: "Cargando nivel...",
  backToStories: "Volver a historias",
  currentLevel: "Nivel actual",
  levelUndefined: "Nivel actual: indefinido. Haz el quiz",
  changeLevel: "Haz el quiz para cambiar tu nivel",
},

stats: {
  loading: "Cargando tus estadísticas...",
  lessThanOneMinute: "< 1 min",
  minutes: "min",
  title: "Tus estadísticas",
  memberSince: "Miembro desde",
  timeOnApp: "Tiempo en la app",
  timeReading: "Tiempo leyendo",
  storiesCompleted: "Historias completadas"
},

feedback: {
    title1: "Comentarios",
    title2: "Nos encantaría conocer tus comentarios.",
    subtitle: "Ayúdanos a mejorar Cuentana para todos",
    typeLabel: "¿Qué tipo de comentario es?",
    typePlaceholder: "Selecciona un tipo...",
    messageLabel: "Tu mensaje",
    placeholder: "¿En qué estás pensando?",
    optionalEmail: "Correo (para seguimiento)",
    cancel: "Cancelar",
    send: "Enviar Comentario",
    bug: "🐛 Error",
    suggestion: "💡 Sugerencia",
    other: "✏️ Otro",
    optionalFields: "Campos opcionales",
    experienceQuestion: "¿Cómo ha sido tu experiencia hasta ahora?",
    frustrated: "Frustrado/a",
    neutral: "Neutral",
    happy: "Feliz",
    thanks: "¡Gracias por tus comentarios!",
    successMessage: "El formulario se envió con éxito.",
    close: "Cerrar",
  },

premium: {
  title: "Hazte Premium 💎",
  description: "Cuentana Premium desbloquea herramientas más inteligentes para aprender más rápido:",
  benefit1: {
    title: "Traducciones GPT Instantáneas",
    desc: "Traduce cualquier palabra o frase con contexto completo."
  },
  benefit2: {
    title: "Historias Exclusivas",
    desc: "Acceso anticipado a nuevas historias y niveles avanzados."
  },
  benefit3: {
    title: "Modo de Traducción de Oraciones",
    desc: "Traduce oraciones completas con un solo clic y ejemplos de uso."
  },
  currentPlan: "Plan Actual",
  planPremium: "Premium 💎",
  planFree: "Gratis",
  returnToStories: "Volver a las Historias",
  subscribeButton: "Suscribirme a Premium"
},

translator: {
  translation: "Traducción",
  otherCommonUses: "también puede significar",
  translating: "Traduciendo"
},

storyTutor: {
  title: "Tutor de Historia",
  loadingConversation: "Cargando conversación...",
  askAnything: "¡Pregúntame lo que quieras sobre esta historia!",
  helpWith: "Puedo ayudarte con vocabulario, gramática o comprensión de la historia.",
  placeholder: "Haz una pregunta...",
  send: "Enviar",
  autoMessageWord: "¿Qué significa \"{word}\"?",
  autoMessageVerb: "¿Qué significa \"{word}\"? Si es un verbo, ¿puedes mostrarme la conjugación?",
  autoMessageSentence: "¿Puedes ayudarme a entender esta oración?",
  errorMessage: "Lo siento, encontré un error. Por favor intenta de nuevo.",
  youSelected: "Seleccionaste \"{text}\""
},

aiTutor: {
  loading: "Cargando...",
  startConversation: "Inicia una conversación con tu tutor IA",
  practiceSkills: "Practica tus habilidades lingüísticas conversando",
  placeholder: "Escribe tu mensaje...",
  send: "Enviar",
  errorMessage: "Lo siento, encontré un error. Por favor intenta de nuevo."
},

myStories: {
  title: "Mis Historias",
  upload: "Subir",
  uploadStory: "Subir una Historia",
  uploadDescription: "Pega el texto de tu historia y crearemos contenido de aprendizaje en todos los niveles de dificultad.",
  noStories: "Aún no hay historias",
  noStoriesDescription: "¡Sube tu primera historia para empezar a aprender con tu propio contenido!",
  uploadFirst: "Sube Tu Primera Historia",
  addStory: "Añadir Historia",
  wantMore: "¿Quieres más historias?",
  upgradeForUnlimited: "Actualiza a Premium para subir historias ilimitadas y textos más largos.",
  storyTitle: "Título de la Historia",
  storyTitlePlaceholder: "Escribe el título de tu historia...",
  sourceLanguage: "Idioma Original",
  spanish: "Español",
  english: "Inglés",
  storyContent: "Contenido de la Historia",
  storyContentPlaceholder: "Pega o escribe tu historia aquí...",
  description: "Descripción",
  descriptionOptional: "opcional",
  descriptionPlaceholder: "Una breve descripción de tu historia...",
  characterCount: "caracteres",
  freeTierLimit: "Nivel gratuito",
  upgradeForMore: "Actualiza para más",
  uploadButton: "Subir Historia",
  uploading: "Subiendo...",
  whatHappensNext: "¿Qué pasa después?",
  step1: "Procesamiento: Detectaremos el nivel de dificultad, analizaremos capítulos, etc.",
  step2: "Transcripción: La IA reescribirá la historia para tu nivel CEFR.",
  step3: "Traducción: Cada nivel será traducido a ambos idiomas.",
  step4: "Tu historia estará lista en 2-20 minutos, dependiendo de la longitud.",
  storyLimitReached: "Límite de Historias Alcanzado",
  storyLimitMessage: "Has alcanzado el máximo de {max} historias.",
  dailyLimitReached: "Límite Diario Alcanzado",
  dailyLimitMessage: "Has usado tu límite diario de subidas. ¡Inténtalo mañana!",
  premiumDailyLimit: "Los usuarios Premium tienen 10 subidas por día.",
  dailyUploads: "Subidas diarias",
  processing: "Procesando...",
  ready: "Lista",
  failed: "Fallida",
  partial: "Parcial",
  estimatedTime: "Tiempo estimado: 2-3 minutos",
  storyReadyMessage: "¡Tu historia está lista para leer!",
  processingFailed: "El procesamiento falló. Por favor intenta de nuevo.",
  readYourStory: "Lee Tu Historia",
  dangerZone: "Zona de Peligro",
  deleteStory: "Eliminar Historia",
  deleteConfirm: "¿Estás seguro de que quieres eliminar \"{title}\"? Esta acción no se puede deshacer.",
  yesDelete: "Sí, Eliminar",
  deleting: "Eliminando...",
  cancel: "Cancelar",
  backToMyStories: "Volver a Mis Historias",
  storyNotFound: "Historia no encontrada",
  source: "Origen",
  detected: "Detectado",
  created: "Creada",
  submitForReview: "Enviar para Revisión Pública",
  submitting: "Enviando...",
  submittedForReview: "¡Enviada para revisión!",
  underReview: "En revisión",
  public: "Pública",
  notApproved: "No aprobada para público",
  premiumRequired: "Premium requerido para compartir públicamente",
  levelBeginner: "Nivel 1 (A1 - Principiante)",
  levelElementary: "Nivel 2 (A2 - Elemental)",
  levelIntermediate: "Nivel 3 (B1 - Intermedio)",
  levelUpperIntermediate: "Nivel 4 (B2 - Intermedio Alto)",
  levelAdvanced: "Nivel 5 (C1 - Avanzado)",
  waiting: "Esperando",
  storyTooShort: "La historia es muy corta. Por favor proporciona al menos 100 caracteres.",
  storyTooLong: "La historia excede la longitud máxima.",
},

storiesMetadata: {
  aventura: {
    title: "Aventura",
    description: "Misterios y criaturas ocultas en un bosque encantado.",
  },
  "the-last-word": {
    title: "La Última Palabra",
    description: "Misterios y criaturas ocultas en un bosque encantado.",
  },
  "diego-unplugged": {
    title: "Diego Desconectado",
    description: "El viaje de autodescubrimiento de un joven cuando se desconecta del mundo digital.",
  },
  "my-day": {
    title: "Mi Día",
    description: "Un poema simple sobre las alegrías de la vida cotidiana.",
  },"el-viaje-magico": {
    title: "El Viaje Mágico",
    description: "Un tren, un mapa antiguo, y una puerta a otro mundo.",
  },
  "secretos-del-desierto": {
    title: "Secretos del Desierto",
    description: "El pasado cobra vida entre las dunas del desierto.",
  },
}

};

export default es;
