// /src/content/ui/es.ts
const es = {
  auth: {
  login: "Iniciar sesión",
  signup: "Crear cuenta",
  logout: "Cerrar sesión",
  email: "Correo electrónico",
  password: "Contraseña",
  confirmPassword: "Confirmar contraseña",
  name: "Nombre",
  welcomeBack: "¡Bienvenido de nuevo!",
  error: "Credenciales incorrectas. Inténtalo de nuevo.",
  or: "o",
  googleLogin: "Inicia sesión con Google",
  languagePrompt: "Idioma nativo / Native language:",
  createAccountCard: "Crear una cuenta",
  signupError: "Algo salió mal. Inténtalo de nuevo.",
  signupSuccess: "¡Cuenta creada! Redirigiendo...",
  signupGoogle: "Registrarse con Google",
  alreadyHaveAccount: "¿Ya tienes una cuenta?",
  newHere: "¿Eres nuevo?",
  loggingIn: "Iniciando sesión...",
  creatingAccount: "Creando cuenta...",
  sendOneTimeCode: "Obtener un código de inicio de sesión",
  usePassword: "Usar contraseña",
  forgotPassword: "¿Olvidaste tu contraseña?",
  resetPassword: "Restablecer contraseña",
  resetPasswordTitle: "Restablece tu contraseña",
  resetPasswordSubtitle: "Ingresa tu correo y te enviaremos un código para restablecer tu contraseña.",
  newPassword: "Nueva contraseña",
  confirmNewPassword: "Confirmar nueva contraseña",
  passwordUpdated: "¡Contraseña actualizada!",
  passwordMismatch: "Las contraseñas no coinciden",
  setNewPassword: "Establecer nueva contraseña",
  updating: "Actualizando...",
},

language: {
  en: "English",
  es: "Español"
},

  stories: {
  goPremium: "Planes",
  premiumDescription: "Desbloquea herramientas más inteligentes para aprender más rápido.",
  dashboard: "Panel",
  settings: "Configuración",
  stories: "Historias",
  loading: "Cargando...",
  continue: "Continuar",
  back: "Atrás",
  readStory: "Léeme",
  readMore: "Leer más",
  readLess: "Leer menos",
  availableLevels: "Disponible en niveles:",
  level: "Nivel",
  storiesAll: "Historias",
  aiTutor: "Tutor IA",
  takeQuiz: "Haz el Quiz",
  myAccount: "Mi Cuenta",
  createAccount: "Crea una Cuenta",
},

story: {
  page: "Página",
  chapter: "Capítulo",
  navigate: "Navegar ▾",
  home: "Inicio",
  levelSelect: "Seleccionar Nivel",
  prev: "Anterior",
  next: "Siguiente",
  markComplete: "Marcar esta historia como completada",
  markedComplete: "✅ ¡Historia marcada como completada!",
  levelUnavailable: "Esta historia no está disponible en tu nivel actual.",
  availableLevelsAre: "Niveles disponibles:",
  selectLevel: "Selecciona un nivel para continuar leyendo:",
  // Poetry anthology navigation labels
  collection: "Colección",
  poem: "Poema",
  // Epic/narrative poetry navigation labels
  canto: "Canto",
  section: "Sección",
  // Script navigation labels
  act: "Acto",
  scene: "Escena",
},

levels: {
  // Legacy keys for backwards compatibility
  l1: "A1 - Fundamentos",
  l2: "A2 - En Desarrollo",
  l3: "B1 - Independiente",
  l4: "B2 - Intermedio Alto",
  l5: "C1 - Avanzado",
  l6: "C2 - Casi Nativo",
  // CEFR codes
  A1: "A1 - Fundamentos",
  A2: "A2 - En Desarrollo",
  B1: "B1 - Independiente",
  B2: "B2 - Intermedio Alto",
  C1: "C1 - Avanzado",
  C2: "C2 - Casi Nativo",
  // CEFR labels (for dropdown displays)
  cefrLabels: {
    l1: "A1",
    l2: "A2",
    l3: "B1",
    l4: "B2",
    l5: "C1",
    l6: "C2",
  },
  // CEFR descriptions (for onboarding/quiz)
  cefrDescriptions: {
    l1: "Puede comprender y usar expresiones básicas para necesidades concretas. Puede presentarse y hacer preguntas personales sencillas.",
    l2: "Puede comprender expresiones frecuentes sobre temas familiares como compras, familia y trabajo. Puede manejar intercambios simples y rutinarios.",
    l3: "Puede manejar la mayoría de situaciones al viajar. Puede describir experiencias, eventos y explicar brevemente opiniones y planes.",
    l4: "Puede comprender textos complejos e interactuar con fluidez con hablantes nativos. Puede producir textos claros y detallados sobre una amplia gama de temas.",
    l5: "Puede comprender textos exigentes y reconocer significados implícitos. Puede expresar ideas con fluidez, precisión y flexibilidad.",
    l6: "Puede comprender prácticamente todo lo que oye o lee. Puede resumir información de diferentes fuentes, reconstruyendo argumentos de manera coherente.",
  },
},

  home: {
  subtitle: "Aprende más rápido. Aprende con historias.",
  quizTitle: "Haz el Quiz",
  recommended: "(recomendado)",
  letUsPick: "Responde unas preguntas y personalizaremos tu experiencia.",
  startQuiz: "Empezar Quiz",
  noThanksTitle: "No Gracias",
  pickLater: "Puedes personalizar tu nivel más tarde en la aplicación.",
  startLearning: "Comenzar Aprendizaje",
  haveAccount: "¿Ya tienes una cuenta?",
  whyTitle: "¿Por qué",
  placeholderInfo: "Put your additional information here 🚀",
  aboutLink: "Conoce Cuentana",
  aboutPrefix: "Conoce"
},

onboarding: {
  stepLanguage: "Idioma",
  stepLevel: "Nivel",
  stepStart: "Empezar",
  welcomeTitle: "Bienvenido a Cuentana",
  welcomeSubtitle: "Personalicemos tu experiencia de aprendizaje",
  languageTitle: "¿Cuál es tu idioma nativo?",
  languageSubtitle: "Esto nos ayuda a personalizar tu experiencia",
  findYourLevel: "Encuentra tu Nivel",
  findYourLevelDesc: "Responde unas preguntas para encontrar tu punto de partida.",
  quizDuration: "5 preguntas",
  knowYourLevel: "¿Ya sabes tu nivel?",
  selectBelow: "Selecciona tu nivel abajo",
  continueToStories: "Ir a las Historias",
  quizProgress: "Pregunta {current} de {total}",
  yourResult: "Tu Nivel",
  startReading: "Empezar a Leer",
  selectLevel: "Seleccionar",
  allSetTitle: "Todo Listo",
  levelSetTo: "Tu nivel está configurado en",
  createAccountTitle: "Crea una Cuenta Gratis",
  createAccountBenefit1: "Guarda tu progreso en todos tus dispositivos",
  createAccountBenefit2: "Sube tus propias historias",
  createAccountBenefit3: "Crea tu lista de vocabulario personal",
  createAccountCta: "Crear Cuenta",
  skipForNow: "Continuar sin cuenta",
},

about: {
  tagline: "Aprende español a través de historias",
  whatIs: "¿Qué es Cuentana?",
  description: "Cuentana es una aplicación de aprendizaje de idiomas que te ayuda a mejorar tu español a través de historias interesantes. Ya seas principiante o avanzado, nuestra colección de historias se adapta a tu nivel, haciendo que el aprendizaje sea natural y agradable.",
  aboutFeature1Title: "Lectura por Niveles",
  aboutFeature1Desc: "Historias adaptadas a 5 niveles de competencia, desde principiante hasta avanzado",
  aboutFeature2Title: "Aprende Leyendo",
  aboutFeature2Desc: "Mejora tu vocabulario y comprensión a través del contexto",
  aboutFeature3Title: "Sigue tu Progreso",
  aboutFeature3Desc: "Observa tu mejora mientras lees más historias",
  getStarted: "Comenzar",
  backToHome: "Volver al Inicio",
},

settings: {
  notLoggedIn: "No has iniciado sesión.",
  greeting: "¡Hola {name}! 🎉",
  premium: "PRO",
  free: "Gratis",
  memberStatus: "Estado de miembro",
  nativeLanguage: "Mi idioma nativo:",
  takeQuiz: "▶️ Haz el Quiz",
  logOut: "🚪 Cerrar sesión",
  loadingLevel: "Cargando nivel...",
  backToStories: "Volver a historias",
  currentLevel: "Nivel actual",
  levelUndefined: "Nivel actual: indefinido. Haz el quiz",
  changeLevel: "Haz el quiz para cambiar tu nivel",
},

stats: {
  loading: "Cargando tus estadísticas...",
  lessThanOneMinute: "< 1 min",
  minutes: "min",
  title: "Tus estadísticas",
  memberSince: "Miembro desde",
  timeOnApp: "Tiempo en la app",
  timeReading: "Tiempo leyendo",
  storiesCompleted: "Historias completadas"
},

feedback: {
    title1: "Comentarios",
    title2: "Nos encantaría conocer tus comentarios.",
    subtitle: "Ayúdanos a mejorar Cuentana para todos",
    typeLabel: "¿Qué tipo de comentario es?",
    typePlaceholder: "Selecciona un tipo...",
    messageLabel: "Tu mensaje",
    placeholder: "¿En qué estás pensando?",
    optionalEmail: "Correo (para seguimiento)",
    cancel: "Cancelar",
    send: "Enviar Comentario",
    bug: "🐛 Error",
    suggestion: "💡 Sugerencia",
    other: "✏️ Otro",
    optionalFields: "Campos opcionales",
    experienceQuestion: "¿Cómo ha sido tu experiencia hasta ahora?",
    frustrated: "Frustrado/a",
    neutral: "Neutral",
    happy: "Feliz",
    thanks: "¡Gracias por tus comentarios!",
    successMessage: "El formulario se envió con éxito.",
    close: "Cerrar",
  },

premium: {
  title: "Mejora Tu Plan",
  description: "Desbloquea herramientas más inteligentes para aprender más rápido:",
  benefit1: {
    title: "Traducciones GPT Instantáneas",
    desc: "Traduce cualquier palabra o frase con contexto completo."
  },
  benefit2: {
    title: "Historias Exclusivas",
    desc: "Acceso anticipado a nuevas historias y niveles avanzados."
  },
  benefit3: {
    title: "Modo de Traducción de Oraciones",
    desc: "Traduce oraciones completas con un solo clic y ejemplos de uso."
  },
  currentPlan: "Plan Actual",
  planPremium: "PRO",
  planFree: "Gratis",
  returnToStories: "Volver a las Historias",
  subscribeButton: "Mejorar"
},

translator: {
  translation: "Traducción",
  otherCommonUses: "también puede significar",
  translating: "Traduciendo",
  signInRequired: "Para usar traducciones con IA,",
  signIn: "inicia sesión",
  or: "o",
  createAccount: "crea una cuenta gratis",
  audioSignInRequired: "Para usar funciones de audio,",
  rootWord: "Raíz",
  lockedFeature: "Mejora tu plan para desbloquear traducciones inteligentes",
},

storyTutor: {
  title: "Tutor de Historia",
  loadingConversation: "Cargando conversación...",
  askAnything: "¡Pregúntame lo que quieras sobre esta historia!",
  helpWith: "Puedo ayudarte con vocabulario, gramática o comprensión de la historia.",
  placeholder: "Haz una pregunta...",
  send: "Enviar",
  autoMessageWord: "¿Qué significa \"{word}\"?",
  autoMessageVerb: "¿Qué significa \"{word}\"? Si es un verbo, ¿puedes mostrarme la conjugación?",
  autoMessageSentence: "¿Puedes ayudarme a entender esta oración?",
  errorMessage: "Lo siento, encontré un error. Por favor intenta de nuevo.",
  youSelected: "Seleccionaste \"{text}\"",
  signInToUse: "Para usar el Tutor de Historia con IA,",
  signIn: "inicia sesión",
  or: "o",
  createAccount: "crea una cuenta gratis",
},

aiTutor: {
  loading: "Cargando...",
  startConversation: "Inicia una conversación con tu tutor IA",
  practiceSkills: "Practica tus habilidades lingüísticas conversando",
  placeholder: "Escribe tu mensaje...",
  send: "Enviar",
  errorMessage: "Lo siento, encontré un error. Por favor intenta de nuevo.",
  signInToUse: "Para usar el Tutor IA,",
  signIn: "inicia sesión",
  or: "o",
  createAccount: "crea una cuenta gratis",
},

sidebar: {
  guest: "Invitado",
  notSignedIn: "No has iniciado sesión",
  settings: "Ajustes",
  goPremium: "Planes",
},

myStories: {
  title: "Mis Historias",
  upload: "Subir",
  uploadStory: "Subir una Historia",
  uploadDescription: "Pega el texto de tu historia y crearemos contenido de aprendizaje en todos los niveles de dificultad.",
  noStories: "Aún no hay historias",
  noStoriesDescription: "¡Sube tu primera historia para empezar a aprender con tu propio contenido!",
  uploadFirst: "Sube Tu Primera Historia",
  addStory: "Añadir Historia",
  wantMore: "¿Quieres más historias?",
  upgradeForUnlimited: "Mejora tu plan para subir historias ilimitadas y textos más largos.",
  storyTitle: "Título de la Historia",
  storyTitlePlaceholder: "Escribe el título de tu historia...",
  sourceLanguage: "Idioma Original",
  spanish: "Español",
  english: "Inglés",
  storyContentPlaceholder: "Pega o escribe tu historia aquí...",
  description: "Descripción",
  characterCount: "caracteres",
  uploadButton: "Subir Historia",
  uploading: "Subiendo...",
  whatHappensNext: "¿Qué pasa después?",
  step1: "Procesamiento: Detectaremos el nivel de dificultad, analizaremos capítulos, etc.",
  step2: "Transcripción: La IA reescribirá la historia para tu nivel CEFR.",
  step3: "Traducción: Cada nivel será traducido a ambos idiomas.",
  step4: "Tu historia estará lista en 2-20 minutos, dependiendo de la longitud.",
  premiumDailyLimit: "Los usuarios PRO tienen 10 subidas por día.",
  dailyUploads: "Subidas diarias",
  processing: "Procesando...",
  ready: "Lista",
  failed: "Fallida",
  partial: "Parcial",
  estimatedTime: "Tiempo estimado: 2-3 minutos",
  storyReadyMessage: "¡Tu historia está lista para leer!",
  processingFailed: "El procesamiento falló. Por favor intenta de nuevo.",
  readYourStory: "Lee Tu Historia",
  dangerZone: "Zona de Peligro",
  deleteStory: "Eliminar Historia",
  deleteConfirm: "¿Estás seguro de que quieres eliminar \"{title}\"? Esta acción no se puede deshacer.",
  yesDelete: "Sí, Eliminar",
  deleting: "Eliminando...",
  cancel: "Cancelar",
  backToMyStories: "Volver a Mis Historias",
  storyNotFound: "Historia no encontrada",
  source: "Origen",
  detected: "Detectado",
  created: "Creada",
  submitForReview: "Enviar para Revisión Pública",
  submitting: "Enviando...",
  submittedForReview: "¡Enviada para revisión!",
  underReview: "En revisión",
  public: "Pública",
  notApproved: "No aprobada para público",
  premiumRequired: "Se requiere mejorar para compartir públicamente",
  levelBeginner: "A1 - Fundamentos",
  levelElementary: "A2 - En Desarrollo",
  levelIntermediate: "B1 - Independiente",
  levelUpperIntermediate: "B2 - Intermedio Alto",
  levelAdvanced: "C1 - Avanzado",
  waiting: "Esperando",
  storyTooShort: "La historia es muy corta. Por favor proporciona al menos 100 caracteres.",
  storyTooLong: "La historia excede la longitud máxima.",
  // Cancelled/Partial status
  cancelled: "Cancelada",
  cancelledMessage: "La carga de esta historia fue cancelada antes de que se completaran los capítulos.",
  partialMessage: "Esta historia fue cancelada durante la carga. Algunos capítulos están disponibles para leer.",
  // Content type selection
  contentType: "Tipo de contenido",
  contentTypeDescription: "Esto nos ayuda a formatear tu historia correctamente.",
  contentTypeAuto: "Auto-detectar",
  contentTypeProse: "Novela / Cuento",
  contentTypePoetry: "Poesía / Letras",
  contentTypeEpic: "Poesía Épica",
  contentTypeScript: "Guión",
  contentTypeHintAuto: "Selecciona esto si no estás seguro. Nuestros algoritmos analizan tu contenido para determinar el mejor formato.",
  contentTypeHintProse: "Selecciona esto para novelas, cuentos, artículos o cualquier contenido narrativo en prosa.",
  contentTypeHintPoetry: "Selecciona esto para poesía, letras de canciones o cualquier contenido con formato de estrofas.",
  contentTypeHintEpic: "Selecciona esto para poesía épica o narrativa como Beowulf o La Odisea con estructura de cantos.",
  contentTypeHintScript: "Selecciona esto para guiones de cine, teatro o contenido con diálogos y nombres de personajes.",
  // Processing mode selection
  processingMode: "Versiones de lectura",
  processingModeDescription: "Elige qué versiones del texto generar.",
  processingModeOriginal: "Solo original",
  processingModeRewritten: "Solo mi nivel",
  processingModeBoth: "Ambos",
  processingModeHintOriginal: "Traduce el texto tal cual a su nivel de dificultad detectado.",
  processingModeHintRewritten: "Reescribe a tu nivel de lectura y traduce. Omite el original si es un nivel diferente.",
  processingModeHintBoth: "Traduce el original y también crea una versión adaptada a tu nivel.",
  // Upload modal UI strings
  uploadSubtitle: "Sube un archivo o pega tu historia y la convertiremos en contenido de aprendizaje",
  storyContent: "Contenido de la historia",
  characters: "caracteres",
  removeFile: "Eliminar archivo",
  fileExceedsLimit: "El archivo excede el límite de caracteres. Por favor usa un archivo más corto.",
  dropFileHere: "Arrastra un archivo aquí o haz clic",
  supportedFormats: "Soporta: .txt, .html, .rtf",
  orPasteText: "o pega tu texto",
  advancedOptions: "Opciones avanzadas",
  titleOptional: "opcional - se auto-detectará",
  titlePlaceholder: "Dejar vacío para auto-detectar",
  descriptionLabel: "Descripción",
  descriptionOptional: "opcional - se generará automáticamente",
  descriptionPlaceholder: "Una breve descripción de tu historia...",
  storiesCount: "Historias:",
  todayCount: "Hoy:",
  storyLimitReached: "Límite de historias alcanzado",
  dailyLimitReached: "Límite diario alcanzado",
  storyLimitMessage: "Has alcanzado el máximo de {max} historias.",
  dailyLimitMessage: "Has usado tu límite diario de subidas. ¡Intenta de nuevo mañana!",
  upgradeToPremium: "Mejorar",
  upgradeForMore: "Mejora para más",
  firstStoryBonus: "Primera historia del mes: hasta {max} caracteres gratis.",
  freeTierLimit: "Límite gratuito: {max} caracteres.",
  errorReadingFile: "Error al leer el archivo",
  unsupportedFileType: "Tipo de archivo no soportado. Aceptados: {types}",
  pleaseEnterStory: "Por favor pega o escribe tu historia",
  storyExceedsLimit: "La historia excede el límite de {max} caracteres.",
  freeTier: "Gratis",
  storiesCountUnlimited: "Historias: {count}",
  storiesCountLimit: "{count} / {max} historias",
  // Tag translations
  tagFamily: "Familia",
  tagFriendship: "Amistad",
  tagAdventure: "Aventura",
  tagMystery: "Misterio",
  tagRomance: "Romance",
  tagComingOfAge: "Crecimiento",
  tagNature: "Naturaleza",
  tagTechnology: "Tecnología",
  tagTravel: "Viaje",
  tagFood: "Comida",
  tagHumorous: "Humorístico",
  tagHeartwarming: "Conmovedor",
  tagSuspenseful: "Suspenso",
  tagReflective: "Reflexivo",
  tagInspiring: "Inspirador",
  tagUrban: "Urbano",
  tagRural: "Rural",
  tagHistorical: "Histórico",
  tagFantasy: "Fantasía",
  tagContemporary: "Contemporáneo",
  tagLatinAmerica: "Latinoamérica",
  tagSpain: "España",
  tagUsa: "EE.UU.",
  tagMulticultural: "Multicultural",
  tagEpic: "Épico",
  tagMythology: "Mitología",
  tagHeroic: "Heroico",
  tagTragedy: "Tragedia",
  tagComedy: "Comedia",
  tagMonsters: "Monstruos",
  tagHerosJourney: "Viaje del Héroe",
  tagWar: "Guerra",
  tagLove: "Amor",
  tagDeath: "Muerte",
  tagRevenge: "Venganza",
  // Story type translations
  typeShortStory: "Cuento",
  typePoem: "Poema",
  typeFable: "Fábula",
  typeFolktale: "Cuento Popular",
  typeNovel: "Novela",
  typeArticle: "Artículo",
  typeDialogue: "Diálogo",
  typeSongLyrics: "Letra de Canción",
  typeEpic: "Épica",
  typeMyth: "Mito",
  typeLegend: "Leyenda",
  typeMovieScript: "Guión de Cine",
  typeTvScript: "Guión de TV",
  // Target audience translations
  audienceAll: "Todos",
  audienceChildren: "Niños",
  audienceTeen: "Adolescentes",
  audienceAdult: "Adultos",
},

upload: {
  // Phase titles
  detecting: "Detectando...",
  adapting: "Adaptando...",
  translating: "Traduciendo...",
  finalizing: "Finalizando...",
  // Stage steps
  detect: "Detectar",
  adapt: "Adaptar",
  translate: "Traducir",
  done: "Listo",
  // Error
  uploadFailed: "Error en la carga",
  dismiss: "Descartar",
  // Review
  reviewYourStory: "Revisa Tu Historia",
  // Messages
  uploadingStory: "Subiendo tu historia...",
  detectingLanguage: "Detectando idioma...",
  analyzingLevel: "Analizando nivel de dificultad...",
  creatingDescription: "Creando título y descripción...",
  adaptingLevel: "Adaptando {from}→{to}",
  adaptingGeneric: "Adaptando",
  translatingRewritten: "Traduciendo texto reescrito {level}...",
  translatingOriginal: "Traduciendo texto {level}...",
  finalizingStory: "Finalizando tu historia...",
  readyForReview: "¡Lista para revisión!",
  uploadSuccess: "¡Historia subida exitosamente!",
  somethingWentWrong: "Algo salió mal",
  processingStory: "Procesando historia",
  chapterProgress: "Capítulo {current}/{total}",
  // Step labels (displayed as carousel subtitle during upload)
  stepCreatingRecord: "Creando registro de historia",
  stepPreparingLevels: "Preparando niveles de lectura",
  stepDetectingLanguage: "Detectando idioma",
  stepAnalyzingMetadata: "Analizando metadatos de la historia",
  stepGeneratingTitle: "Generando título",
  stepGeneratingDescription: "Generando descripción",
  stepGeneratingHook: "Generando gancho",
  stepDetectingStoryType: "Detectando tipo de historia",
  stepDetectingAudience: "Detectando audiencia objetivo",
  stepExtractingTags: "Extrayendo etiquetas",
  stepDetectingLevel: "Detectando nivel CEFR",
  stepCleaningText: "Limpiando texto",
  stepParsingChapters: "Analizando capítulos",
  stepAdaptingLevels: "Adaptando a niveles de lectura",
  stepRewritingChapter: "Reescribiendo capítulo",
  stepTranslatingLevels: "Traduciendo todos los niveles",
  stepTranslatingChapter: "Traduciendo capítulo",
  stepBuildingLevels: "Construyendo todos los niveles",
  stepBuildingStructure: "Construyendo estructura de contenido",
  stepSavingContent: "Guardando contenido del nivel",
  stepComplete: "Completo",
  stepChapterOf: "{current} de {total}",
  // ProgressViewerModal
  rewrite: "Reescritura",
  rewriteFromTo: "Reescritura {from} → {to}",
  translateLevel: "Traducción {level}",
  translateOriginal: "Traducción {level} (Original)",
  translateRewritten: "Traducción {level} (Reescrito)",
  original: "Original",
  rewritten: "Reescrito",
  source: "Origen",
  translated: "Traducido",
  englishSource: "Inglés (Origen)",
  spanishSource: "Español (Origen)",
  englishTranslation: "Inglés (Traducción)",
  spanishTranslation: "Español (Traducción)",
  chaptersCount: "{completed} de {total} capítulos",
  rewritingChapter: "Reescribiendo capítulo {current}...",
  translatingChapterLive: "Traduciendo capítulo {current}...",
  chapters: "Capítulos:",
  chapterLabel: "Capítulo {num}: {left} {leftLabel} → {right} {rightLabel}",
  lineCountMismatch: "Diferencia en cantidad de líneas",
  progress: "Progreso:",
  lines: "líneas",
  loadingPreview: "Cargando vista previa...",
  failedToLoadPreview: "Error al cargar vista previa",
  waitingForFirstChapter: "Esperando a que se complete el primer capítulo...",
  rewritingChapterOf: "Reescribiendo capítulo {current} de {total}",
  translatingChapterOf: "Traduciendo capítulo {current} de {total}",
  stanzaBreak: "⸺ salto de estrofa ⸺",
  // StreamSelector
  previewCompletedStory: "Vista previa de historia completada",
  viewProgress: "Ver progreso",
  chaptersCompleted: "{completed} / {total} capítulos completados",
  waitingToStart: "Esperando para iniciar...",
  processingFirstChapter: "Procesando primer capítulo...",
  // Cancel dialog
  cancelUploadTitle: "¿Cancelar carga?",
  cancelUploadMessage: "Esto detendrá la carga y descartará todo el progreso. ¿Estás seguro de que quieres cancelar?",
  keepUploading: "Seguir cargando",
  yesCancelUpload: "Sí, cancelar",
  cancelling: "Cancelando...",
},

storiesMetadata: {
  aventura: {
    title: "Aventura",
    description: "Misterios y criaturas ocultas en un bosque encantado.",
  },
  "the-last-word": {
    title: "La Última Palabra",
    description: "Acompaña a Maya mientras enfrenta sus miedos de hablar en público y descubre su fuerza interior.",
  },
  "diego-unplugged": {
    title: "Diego Desconectado",
    description: "El viaje de autodescubrimiento de un joven cuando se desconecta del mundo digital.",
  },
  "el-viaje-magico": {
    title: "El Viaje Mágico",
    description: "Un tren, un mapa antiguo, y una puerta a otro mundo.",
  },
  "secretos-del-desierto": {
    title: "Secretos del Desierto",
    description: "El pasado cobra vida entre las dunas del desierto.",
  },
  "my-day-3": {
    title: "Mi Día",
    hook: "Sigue un día típico de la mañana a la noche.",
    description: "",
  },
  "poems-by-emily-dickinson-complete": {
    title: "Poemas de Emily Dickinson, Tres Series, Completo",
    hook: "Descubre la poesía introspectiva y poco convencional de Emily Dickinson, que refleja su perspectiva única sobre la vida y el éxito.",
    description: "Esta colección reúne los primeros poemas publicados de Emily Dickinson, editados después de su muerte por Mabel Loomis Todd y T. W. Higginson. Escritos en gran parte sin pensar en su publicación, sus versos reflejan un espíritu ferozmente independiente y un estilo poco convencional que desafiaba las normas literarias de su tiempo. Una ermitaña de por vida de Amherst, Massachusetts, Dickinson produjo poemas de originalidad sorprendente—destellos de profunda percepción sobre la naturaleza, la vida, la fe y la muerte—marcados por imágenes vívidas, pensamientos audaces y una voz como ninguna otra en la poesía estadounidense.",
  },
  "the-great-gatsby": {
    title: "El Gran Gatsby",
    hook: "En los rugientes años veinte, un millonario misterioso cautiva con su lujoso estilo de vida y secretos.",
    description: "En el resplandeciente verano de 1922, un joven del Medio Oeste llega a las costas de Long Island y se adentra en un mundo de riqueza inimaginable, desenfreno imprudente y sueños rotos. Su enigmático vecino, Jay Gatsby, ofrece fastuosas fiestas en su mansión gótica, pero nadie parece saber quién es realmente ni qué es lo que desea.\n\nA medida que Nick Carraway se ve atraído por la órbita de Gatsby, descubre la verdad detrás del espectáculo: un amor consumidor y desesperado por Daisy Buchanan, una mujer de vieja fortuna, encanto y negligencia. Gatsby se ha reinventado por completo, construyendo una fortuna en los oscuros márgenes del Sueño Americano, todo por la oportunidad de recuperar un pasado que quizás nunca existió realmente.\n\nPero bajo el brillo de la Nueva York de la Era del Jazz se oculta un mundo de traición, violencia y decadencia moral. Cuando los secretos se desmoronan y las lealtades se ponen a prueba, las consecuencias resultan devastadoras e ineludibles.\n\nAmpliamente considerada como una de las mejores novelas jamás escritas, El gran Gatsby es el luminoso retrato de F. Scott Fitzgerald sobre el Sueño Americano: su promesa, su seducción y su ruina.\n",
  },
},

audioPlayer: {
  listen: "Escuchar",
  listening: "Escuchando...",
  turningPage: "Pasando página...",
  storyComplete: "¡Historia completada!",
  targetOnly: "Solo idioma de aprendizaje",
  bilingual: "Ambos idiomas",
  resumeListening: "Reanudar escucha",
  errorRetry: "Reintentar",
  errorSkip: "Saltar",
},
};

export default es;
