export const chapterContent = {
  "storySlug": "the-great-gatsby",
  "level": 5,
  "chapter": 1,
  "pages": {
    "1": {
      "lines": [
        {
          "en": "In my younger and more vulnerable years my father gave me some advice that I’ve been turning over in my mind ever since.",
          "es": "En mis años más jóvenes y vulnerables, mi padre me dio algunos consejos que he estado rumiando en mi mente desde entonces."
        },
        {
          "en": "“Whenever you feel like criticizing anyone,” he told me, “just remember that all the people in this world haven’t had the advantages that you’ve had.”",
          "es": "Siempre que sientas la tentación de criticar a alguien,\" me dijo, \"recuerda simplemente que todas las personas en este mundo no han tenido las ventajas que tú has tenido."
        },
        {
          "en": "He didn’t say any more, but we’ve always been unusually communicative in a reserved way, and I understood that he meant a great deal more than that. In consequence, I’m inclined to reserve all judgements, a habit that has opened up many curious natures to me and also made me the victim of not a few veteran bores. The abnormal mind is quick to detect and attach itself to this quality when it appears in a normal person, and so it came about that in college I was unjustly accused of being a politician, because I was privy to the secret griefs of wild, unknown men. Most of the confidences were unsought—frequently I have feigned sleep, preoccupation, or a hostile levity when I realized by some unmistakable sign that an intimate revelation was quivering on the horizon; for the intimate revelations of young men, or at least the terms in which they express them, are usually plagiaristic and marred by obvious suppressions. Reserving judgements is a matter of infinite hope. I am still a little afraid of missing something if I forget that, as my father snobbishly suggested, and I snobbishly repeat, a sense of the fundamental decencies is parcelled out unequally at birth.",
          "es": "No dijo nada más, pero siempre hemos sido inusualmente comunicativos de una manera reservada, y entendí que quería decir mucho más que eso. En consecuencia, soy propenso a reservarme todos los juicios, un hábito que me ha abierto muchas naturalezas curiosas y también me ha convertido en víctima de no pocos aburridos veteranos. La mente anormal es rápida para detectar y adherirse a esta cualidad cuando aparece en una persona normal, y así sucedió que en la universidad fui injustamente acusado de ser un político, porque era conocedor de las penas secretas de hombres salvajes y desconocidos. La mayoría de las confidencias fueron espontáneas—frecuentemente he fingido dormir, preocupación, o una jovialidad hostil cuando me daba cuenta por algún signo inequívoco de que una revelación íntima estaba a punto de suceder; pues las revelaciones íntimas de los jóvenes, o al menos los términos en que las expresan, suelen ser plagiarias y están viciadas por supresiones obvias. Reservarse los juicios es una cuestión de esperanza infinita. Todavía me da un poco de miedo perderme algo si olvido eso, como mi padre de manera esnob sugirió, y yo esnobísticamente repito, que un sentido de las decencias fundamentales se distribuye desigualmente al nacer."
        },
        {
          "en": "And, after boasting this way of my tolerance, I come to the admission that it has a limit. Conduct may be founded on the hard rock or the wet marshes, but after a certain point I don’t care what it’s founded on. When I came back from the East last autumn I felt that I wanted the world to be in uniform and at a sort of moral attention forever; I wanted no more riotous excursions with privileged glimpses into the human heart. Only Gatsby, the man who gives his name to this book, was exempt from my reaction—Gatsby, who represented everything for which I have an unaffected scorn. If personality is an unbroken series of successful gestures, then there was something gorgeous about him, some heightened sensitivity to the promises of life, as if he were related to one of those intricate machines that register earthquakes ten thousand miles away. This responsiveness had nothing to do with that flabby impressionability which is dignified under the name of the “creative temperament”—it was an extraordinary gift for hope, a romantic readiness such as I have never found in any other person and which it is not likely I shall ever find again. No—Gatsby turned out all right at the end; it is what preyed on Gatsby, what foul dust floated in the wake of his dreams that temporarily closed out my interest in the abortive sorrows and short-winded elations of men.",
          "es": "Y, después de alardear de esta manera de mi tolerancia, llego a la admisión de que tiene un límite. La conducta puede fundarse en la roca sólida o en los pantanos mojados, pero después de cierto punto no me importa en qué se funde. Cuando regresé del Este el pasado otoño, sentí que quería que el mundo estuviera uniforme y en una especie de atención moral para siempre; no quería más excursiones tumultuosas con visiones privilegiadas del corazón humano. Solo Gatsby, el hombre que da su nombre a este libro, estuvo exento de mi reacción—Gatsby, quien representaba todo aquello por lo que siento un desprecio desapasionado. Si la personalidad es una serie ininterrumpida de gestos exitosos, entonces había algo magnífico en él, una sensibilidad exaltada a las promesas de la vida, como si estuviera relacionado con una de esas máquinas intrincadas que registran terremotos a diez mil millas de distancia. Esta capacidad de respuesta no tenía nada que ver con esa impresionabilidad fofa que se dignifica bajo el nombre del \"temperamento creativo\"—era un don extraordinario para la esperanza, una disposición romántica como nunca he encontrado en ninguna otra persona y que probablemente nunca volveré a encontrar. No—Gatsby resultó estar bien al final; fue lo que acosó a Gatsby, qué polvo fétido flotaba en la estela de sus sueños lo que temporalmente cerró mi interés en las angustias abortivas y las alegrías cortas de aliento de los hombres."
        }
      ]
    }
  }
};
