export const chapterContent = {
  "storySlug": "the-adventures-of-tom-sawyer",
  "level": 4,
  "chapter": 5,
  "pages": {
    "1": {
      "lines": [
        {
          "en": "Around half-past ten, the cracked bell of the small church began to ring, signaling the start of the morning sermon. People began to gather, and the Sunday-school children spread out among the pews with their parents to stay under watch. Aunt Polly arrived with Tom, Sid, and Mary, sitting next to her. Tom sat by the aisle to keep him away from the open window and the tempting summer scenes outside. The crowd filed in: the old and needy postmaster, who had seen better days; the mayor and his wife—though a mayor was a bit unnecessary there; the justice of the peace; the widow Douglas, charming and generous, living in the town’s only mansion, known for its hospitality and grand parties; the elderly Major and Mrs. Ward; lawyer Riverson, a new notable from afar; the village belle, followed by young admirers in their best clothes; then the young clerks, who had been waiting in the vestibule, admiring the girls as they passed; and finally, the Model Boy, Willie Mufferson, carefully escorting his mother as if she were fragile. He always brought her to church and was the pride of the matrons. The boys disliked him for being so good and because he was often praised to them. His white handkerchief hung out of his pocket, as usual on Sundays, by accident. Tom had no handkerchief and thought boys who did were snobs.",
          "es": "Alrededor de las diez y media, la campana agrietada de la pequeña iglesia comenzó a sonar, señalando el inicio del sermón matutino. La gente empezó a reunirse, y los niños de la escuela dominical se dispersaron entre los bancos con sus padres para mantenerse bajo vigilancia. La tía Polly llegó con Tom, Sid y Mary, sentándose junto a ella. Tom se sentó al lado del pasillo para alejarlo de la ventana abierta y de las tentadoras escenas del verano afuera. La multitud entró: el viejo y necesitado cartero, quien había conocido días mejores; el alcalde y su esposa—aunque un alcalde era un poco innecesario allí; el juez de paz; la viuda Douglas, encantadora y generosa, viviendo en la única mansión del pueblo, conocida por su hospitalidad y sus grandes fiestas; el anciano Mayor y la Sra. Ward; el abogado Riverson, un nuevo personaje notable de lejos; la bella del pueblo, seguida por jóvenes admiradores en sus mejores ropas; luego los jóvenes empleados de la iglesia, que habían estado esperando en el vestíbulo, admirando a las chicas mientras pasaban; y finalmente, el Niño Modelo, Willie Mufferson, escoltando cuidadosamente a su madre como si fuera frágil. Siempre la traía a la iglesia y era el orgullo de las matronas. A los niños no les caía bien por ser tan bueno y porque frecuentemente lo elogiaban a ellos. Su pañuelo blanco sobresalía de su bolsillo, como de costumbre los domingos, aparentemente por accidente. Tom no tenía pañuelo y pensaba que los niños que los llevaban eran presumidos."
        },
        {
          "en": "With the congregation now fully assembled, the bell rang again to warn latecomers. A solemn hush fell over the church, broken only by the choir's giggles and whispers in the gallery. The choir always whispered during the service. There was once a church choir that behaved well, but I can't remember where it was, perhaps in some foreign country long ago.",
          "es": "Con la congregación completamente reunida, la campana sonó de nuevo para advertir a los atrasados. Un silencio solemne cayó sobre la iglesia, roto únicamente por las risitas y susurros del coro en la galería. El coro siempre susurraba durante el servicio. Una vez hubo un coro de iglesia que se comportaba bien, pero no puedo recordar dónde fue, quizás en algún país extranjero hace mucho tiempo."
        },
        {
          "en": "The minister announced the hymn and read it with great enthusiasm, in a style much admired locally. His voice started at a medium pitch, rising steadily until it reached a peak, emphasizing the top word before dropping dramatically:",
          "es": "El ministro anunció el himno y lo leyó con gran entusiasmo, en un estilo muy admirado localmente. Su voz comenzó en un tono medio, subiendo gradualmente hasta alcanzar un pico, enfatizando la palabra superior antes de caer dramáticamente:"
        },
        {
          "en": "Shall I be car-ri-ed to the skies, on flow’ry beds of ease,",
          "es": "¿Seré lle-va-do a los cielos, en lechos floridos de descanso,"
        },
        {
          "en": "Whilst others fight to win the prize, and sail thro’ blood-y seas?",
          "es": "Mientras otros luchan por ganar el premio, y navegan por mares san-grien-tos?"
        },
        {
          "en": "He was considered an excellent reader. At church events, he was often asked to read poetry, and when he finished, the ladies would raise their hands and let them fall into their laps, rolling their eyes and shaking their heads, as if to say, “Words cannot express it; it is too beautiful, TOO beautiful for this mortal earth.”",
          "es": "Era considerado un excelente lector. En eventos de la iglesia, frecuentemente le pedían que leyera poesía, y cuando terminaba, las damas levantaban sus manos y las dejaban caer en sus regazos, rodando los ojos y moviendo sus cabezas, como si dijeran: \"Las palabras no pueden expresarlo; es demasiado hermoso, DEMASIADO hermoso para esta tierra mortal\".”"
        },
        {
          "en": "After the hymn, Rev. Mr. Sprague turned into a bulletin board, reading notices of meetings and societies until it seemed the list would never end—a strange custom still kept in America, even in cities, despite the abundance of newspapers. Often, the less reason there is for a tradition, the harder it is to abandon.",
          "es": "Después del himno, el Rev. Sr. Sprague se convirtió en un tablero de anuncios, leyendo avisos de reuniones y sociedades hasta que parecía que la lista nunca terminaría—una extraña costumbre que todavía se mantiene en América, incluso en ciudades, a pesar de la abundancia de periódicos. A menudo, cuanto menos razón hay para una tradición, más difícil es abandonarla."
        },
        {
          "en": "Then the minister prayed. It was a generous prayer, covering many details: pleading for the church and its children; for the other village churches; for the village itself; for the county; for the State; for the State officers; for the United States; for its churches; for Congress; for the President; for government officers; for poor sailors in stormy seas; for oppressed millions under European monarchies and Oriental despotisms; for those with the light and good news who still cannot see or hear; for the heathen in distant islands; and finally, he prayed that his words might find grace and favor, and be like seeds sown in fertile ground, yielding a grateful harvest of good. Amen.",
          "es": "Entonces el ministro oró. Fue una oración generosa, cubriendo muchos detalles: suplicando por la iglesia y sus hijos; por las otras iglesias del pueblo; por el pueblo mismo; por el condado; por el Estado; por los funcionarios del Estado; por los Estados Unidos; por sus iglesias; por el Congreso; por el Presidente; por los funcionarios del gobierno; por los pobres marineros en mares tormentosos; por los millones oprimidos bajo monarquías europeas y despotismos orientales; por aquellos con la luz y las buenas nuevas que todavía no pueden ver u oír; por los paganos en islas distantes; y finalmente, oró para que sus palabras encontraran gracia y favor, y fueran como semillas sembradas en tierra fértil, produciendo una cosecha agradecida de lo bueno. Amén."
        }
      ]
    },
    "2": {
      "lines": [
        {
          "en": "There was a rustling of dresses as the standing congregation sat down. The boy, whose story this book tells, did not enjoy the prayer; he only endured it, if that. He was restless throughout, unconsciously keeping track of the prayer’s details—he knew the minister’s routine well. When new content appeared, his ear caught it, and he resented it, finding additions unfair. During the prayer, a fly landed on the pew in front of him, irritating him by calmly grooming itself. It seemed safe, and indeed it was, for Tom dared not catch it during the prayer, fearing his soul would be destroyed. But as soon as “Amen” was spoken, his hand darted forward, capturing the fly. His aunt saw and made him release it.",
          "es": "Hubo un susurro de vestidos mientras la congregación de pie se sentaba. El niño, cuya historia cuenta este libro, no disfrutó de la oración; simplemente la toleró, si es que eso. Estuvo inquieto durante todo el tiempo, registrando inconscientemente los detalles de la oración—conocía bien la rutina del ministro. Cuando aparecía contenido nuevo, su oído lo capturaba, y le molestaba, encontrando los añadidos injustos. Durante la oración, una mosca aterrizó en el banco frente a él, irritándolo al acicalarse tranquilamente. Parecía segura, e infatti lo era, porque Tom no se atrevía a atraparla durante la oración, temiendo que su alma fuera destruida. Pero tan pronto como se pronunció \"Amén\", su mano se lanzó hacia adelante, capturando la mosca. Su tía vio y lo obligó a soltarla."
        },
        {
          "en": "The minister announced his text and droned on monotonously through a sermon so dull that many heads began to nod. Yet, it was about fire and brimstone, reducing the saved to a tiny group. Tom counted the sermon pages; after church, he always knew the number of pages but little else. This time, he was briefly interested when the minister described a grand scene of the world’s hosts gathering at the millennium, where the lion and the lamb would lie down together and a child would lead them. The spectacle's emotion and lesson were lost on Tom; he only thought of the importance of the main character and wished he could be that child if the lion was tame.",
          "es": "El ministro anunció su texto y continuó monótonamente con un sermón tan aburrido que muchas cabezas comenzaron a asentir. Sin embargo, era sobre fuego e infierno, reduciendo a los salvados a un pequeño grupo. Tom contó las páginas del sermón; después de la iglesia, siempre sabía el número de páginas pero poco más. Esta vez, estuvo brevemente interesado cuando el ministro describió una escena grandiosa de las huestes del mundo reuniéndose en el milenio, donde el león y el cordero se acostarían juntos y un niño los guiaría. El espectáculo emocional y la lección se perdieron en Tom; solo pensó en la importancia del personaje principal y deseó poder ser ese niño si el león era manso."
        },
        {
          "en": "He slipped back into his discomfort as the boring argument started again. Soon, he remembered a treasure he had and took it out. It was a big black beetle with strong jaws, which he called a \"pinchbug.\" It was in a small box. The first thing the beetle did was bite his finger. Instinctively, he flicked it away, sending it tumbling into the aisle where it landed on its back. Tom put his hurt finger in his mouth. The beetle lay there, legs waving helplessly, unable to turn over. Tom looked at it, wanting it back, but it was out of reach. Others, also bored by the sermon, noticed the beetle and watched it too. Soon, a wandering poodle came along, looking sad and tired from the summer heat, longing for something different. It spotted the beetle, wagged its tail, and examined the prize. It circled it, sniffed from a distance, then got braver and took a cautious snap at it, just missing. It tried again and again, enjoying the game, then settled down with the beetle between its paws, experimenting with it. Eventually, it got bored and lost interest. Its head drooped, and its chin touched the beetle, which bit it. The dog yelped and shook its head, sending the beetle flying a few yards away, landing on its back again. The nearby spectators quietly laughed, hiding their smiles behind fans and handkerchiefs, and Tom felt completely happy. The dog looked silly and probably felt that way too, but it was also angry and wanted revenge. It approached the beetle cautiously, jumping at it from all angles, landing close to it, snapping with its teeth, and shaking its head until its ears flapped. But it got tired again, tried to chase a fly but found no fun, followed an ant with its nose to the floor, and soon got bored. It yawned, sighed, forgot about the beetle, and sat on it. Suddenly, there was a loud yelp of pain, and the poodle ran up the aisle, still yelping. It dashed across the front of the church, sped down the other aisle, ran past the doors, and raced up the main aisle. Its pain seemed to increase as it went, turning it into a furry comet moving with incredible speed. Finally, the desperate dog veered off and jumped into its owner's lap, who promptly tossed it out the window, where its cries faded away into the distance.",
          "es": "Volvió a hundirse en su malestar cuando el argumento aburrido comenzó de nuevo. Pronto, recordó un tesoro que tenía y lo sacó. Era un gran escarabajo negro con mandíbulas fuertes, al que llamaba un \"escarabajo pinzudo\". Estaba en una pequeña caja. Lo primero que hizo el escarabajo fue morderle el dedo. Instintivamente, lo sacudió, enviándolo rodando por el pasillo donde aterrizó de espaldas. Tom se puso el dedo herido en la boca. El escarabajo yacía allí, con las patas moviéndose indefensamente, incapaz de darse la vuelta. Tom lo miraba, queriéndolo de vuelta, pero estaba fuera de su alcance. Otros, también aburridos por el sermón, notaron el escarabajo y también lo observaron. Pronto, un caniche vagabundo apareció, viéndose triste y cansado por el calor del verano, anhelando algo diferente. Vio el escarabajo, meneó la cola, y examinó el premio. Lo rodeó, olfateó desde la distancia, luego se volvió más valiente e intentó un mordisco cauteloso, casi fallando. Lo intentó una y otra vez, disfrutando del juego, luego se acostó con el escarabajo entre sus patas, experimentando con él. Eventualmente, se aburrió y perdió interés. Su cabeza se inclinó, y su barbilla tocó el escarabajo, que lo mordió. El perro aulló y movió su cabeza, enviando el escarabajo volando varios metros de distancia, aterrizando de espaldas nuevamente. Los espectadores cercanos se rieron silenciosamente, escondiendo sus sonrisas detrás de abanicos y pañuelos, y Tom se sintió completamente feliz. El perro se veía ridículo y probablemente se sentía así también, pero también estaba enfadado y quería venganza. Se acercó al escarabajo cautelosamente, saltando desde todos los ángulos, aterrizando cerca de él, mordiendo con sus dientes, y moviendo su cabeza hasta que sus orejas se agitaban. Pero se cansó de nuevo, intentó perseguir una mosca pero no encontró diversión, siguió una hormiga con su nariz en el piso, y pronto se aburrió. Bostezó, suspiró, olvidó al escarabajo, y se sentó sobre él. De repente, hubo un fuerte aullido de dolor, y el caniche corrió por el pasillo, aullando todavía. Atravesó la parte frontal de la iglesia, corrió por el otro pasillo, pasó por las puertas, y subió por el pasillo principal. Su dolor parecía aumentar conforme iba, convirtiéndolo en un cometa peludo moviéndose con una velocidad increíble. Finalmente, el perro desesperado se desvió y saltó al regazo de su dueña, quien inmediatamente lo lanzó por la ventana, donde sus gritos se desvanecieron a la distancia."
        },
        {
          "en": "By now, the entire church was red-faced, struggling to hold back laughter, and the sermon had come to a complete stop. Soon, the preacher continued, but his words were stumbling and awkward, with no chance of being serious anymore. Even the most solemn statements were met with muffled laughter from some hidden corner, as if the preacher had made a surprisingly funny joke. Everyone felt relieved when the service finally ended, and the blessing was given.",
          "es": "Para entonces, toda la iglesia estaba roja de cara, luchando por contener la risa, y el sermón se había detenido por completo. Pronto, el predicador continuó, pero sus palabras eran tambaleantes e incómodas, sin oportunidad de ser serias nuevamente. Incluso las declaraciones más solemnes fueron recibidas con risas sofocadas de alguna esquina oculta, como si el predicador hubiera hecho una broma sorprendentemente graciosa. Todos sintieron alivio cuando el servicio finalmente terminó, y se dio la bendición."
        },
        {
          "en": "Tom Sawyer walked home feeling quite cheerful, thinking that church services were more enjoyable when something different happened. He had only one regret; he was fine with the dog playing with his pinchbug, but he didn't think it was right for the dog to take it away.",
          "es": "Tom Sawyer caminó a casa sintiéndose bastante alegre, pensando que los servicios religiosos eran más agradables cuando sucedía algo diferente. Tenía solo un arrepentimiento; estaba bien que el perro jugara con su escarabajo pinzudo, pero no le parecía correcto que el perro se lo llevara."
        }
      ]
    }
  }
};
