export const chapterContent = {
  "storySlug": "the-adventures-of-tom-sawyer",
  "level": 3,
  "chapter": 5,
  "pages": {
    "1": {
      "lines": [
        {
          "en": "Around half-past ten, the small church's cracked bell began to ring. People started to gather for the morning sermon. The Sunday-school children sat with their parents to be watched. Aunt Polly arrived, and Tom, Sid, and Mary sat with her. Tom was placed next to the aisle to keep him away from the open window and the tempting summer scenes outside. The crowd walked up the aisles: the old and needy postmaster, who had seen better days; the mayor and his wife—because they had a mayor there, among other unnecessary things; the justice of the peace; the widow Douglas, fair, smart, and forty, a generous soul with a hill mansion, the only palace in town, known for its hospitality and grand parties; the bent and venerable Major and Mrs. Ward; lawyer Riverson, the new notable from afar; the village belle, followed by a group of young heart-breakers in lawn dresses and ribbons; all the young clerks in town stood in the vestibule, admiring the girls until the last one passed; and finally, the Model Boy, Willie Mufferson, who took great care of his mother, as if she were fragile. He always brought his mother to church and was the pride of all the matrons. All the boys disliked him because he was too good and often compared to them. His white handkerchief hung out of his pocket on Sundays—by accident. Tom had no handkerchief and thought boys who did were snobs.",
          "es": "Alrededor de las diez y media, la campana rota de la pequeña iglesia empezó a sonar. La gente comenzó a reunirse para el sermón de la mañana. Los niños de la escuela dominical se sentaron con sus padres para ser vigilados. La tía Polly llegó, y Tom, Sid y Mary se sentaron con ella. Tom fue colocado al lado del pasillo para mantenerlo alejado de la ventana abierta y las tentadoras escenas del verano afuera. La multitud caminó por los pasillos: el viejo y pobre cartero, quien había tenido días mejores; el alcalde y su esposa—porque tenían un alcalde allí, entre otras cosas innecesarias; el juez de paz; la viuda Douglas, hermosa, inteligente y de cuarenta años, un alma generosa con una mansión en la colina, el único palacio del pueblo, conocido por su hospitalidad y sus grandes fiestas; el Mayor venerable y encorvado Ward y su esposa; el abogado Riverson, el nuevo personaje importante de lejos; la bella del pueblo, seguida por un grupo de jóvenes que rompían corazones en vestidos de lino y cintas; todos los jóvenes oficinistas del pueblo estaban en el vestíbulo, admirando a las chicas hasta que pasó la última; y finalmente, el Niño Modelo, Willie Mufferson, quien cuidaba mucho a su madre, como si fuera frágil. Siempre llevaba a su madre a la iglesia y era el orgullo de todas las matronas. A todos los niños les desagradaba porque era demasiado bueno y a menudo lo comparaban con ellos. Su pañuelo blanco colgaba de su bolsillo los domingos—por accidente. Tom no tenía pañuelo y pensaba que los niños que lo tenían eran presumidos."
        },
        {
          "en": "Once the congregation was fully assembled, the bell rang again to warn latecomers. A solemn hush fell upon the church, broken only by the choir's giggles and whispers in the gallery. The choir always giggled and whispered during the service. I remember a church choir that wasn't rude, but I can't recall where it was. It was many years ago, possibly in a foreign country.",
          "es": "Una vez que la congregación estaba completamente reunida, la campana sonó de nuevo para advertir a los atrasados. Un silencio solemne cayó sobre la iglesia, interrumpido solo por las risitas y los susurros del coro en la galería. El coro siempre reía y susurraba durante el servicio. Recuerdo un coro de iglesia que no era mal educado, pero no puedo recordar dónde era. Fue hace muchos años, posiblemente en un país extranjero."
        },
        {
          "en": "The minister announced the hymn and read it with great enjoyment, in a style admired in that area. His voice started at a medium pitch and climbed until it reached a high point, emphasizing the topmost word before dropping down like from a springboard:",
          "es": "El ministro anunció el himno y lo leyó con gran entusiasmo, en un estilo admirado en esa región. Su voz comenzó en un tono medio y subió hasta alcanzar un punto alto, enfatizando la palabra más importante antes de caer como desde un trampolín:"
        },
        {
          "en": "Shall I be car-ri-ed to the skies, on flow’ry beds of ease,",
          "es": "¿Será que seré lle-va-do a los cielos, en camas floridas de paz,"
        },
        {
          "en": "Whilst others fight to win the prize, and sail thro’ blood-y seas?",
          "es": "Mientras otros luchan para ganar el premio, y navegan por mares de san-gre?"
        },
        {
          "en": "He was seen as a wonderful reader. At church gatherings, he was always asked to read poetry. When he finished, the ladies would raise their hands and let them fall into their laps, rolling their eyes and shaking their heads, as if to say, \"Words cannot express it; it is too beautiful, TOO beautiful for this mortal earth.\"",
          "es": "Era visto como un lector maravilloso. En las reuniones de la iglesia, siempre le pedían que leyera poesía. Cuando terminaba, las damas levantaban las manos y las dejaban caer en sus regazos, rodaban los ojos y movían la cabeza, como queriendo decir: \"Las palabras no pueden expresarlo; es demasiado hermoso, DEMASIADO hermoso para esta tierra mortal\".\""
        },
        {
          "en": "After the hymn, Rev. Mr. Sprague turned into a bulletin-board, reading announcements of meetings and societies, which seemed endless. This strange custom still exists in America, even in cities, despite the abundance of newspapers. Often, the less reason there is for a tradition, the harder it is to stop it.",
          "es": "Después del himno, el Reverendo Sprague se convirtió en un tablón de anuncios, leyendo anuncios de reuniones y sociedades, que parecían interminables. Esta extraña costumbre todavía existe en América, incluso en ciudades, a pesar de la abundancia de periódicos. A menudo, cuanto menos razón hay para una tradición, más difícil es dejarla."
        },
        {
          "en": "Then the minister prayed. It was a generous prayer, full of details: it asked for blessings on the church, the children, other churches in the village, the village itself, the county, the State, the State officers, the United States, the churches of the United States, Congress, the President, government officers, sailors in stormy seas, oppressed people under European and Oriental rulers, those who have the light but cannot see or hear, and the heathen in far islands. It ended with a request that his words might find grace and favor, like seeds sown in fertile ground, yielding a good harvest. Amen.",
          "es": "Luego el ministro rezó. Fue una oración generosa, llena de detalles: pedía bendiciones para la iglesia, los niños, otras iglesias del pueblo, el pueblo mismo, el condado, el Estado, los oficiales del Estado, los Estados Unidos, las iglesias de los Estados Unidos, el Congreso, el Presidente, los oficiales del gobierno, los marineros en mares tormentosos, la gente oprimida bajo gobernantes europeos y orientales, aquellos que tienen la luz pero no pueden ver ni oír, y los paganos en islas lejanas. Terminó con una petición de que sus palabras encontraran gracia y favor, como semillas sembradas en tierra fértil, produciendo una buena cosecha. Amén."
        }
      ]
    },
    "2": {
      "lines": [
        {
          "en": "There was a rustling of dresses, and the congregation sat down. The boy whose story this book tells did not enjoy the prayer; he just endured it—if that. He was restless throughout, keeping track of the prayer's details unconsciously. He was not listening, but he knew the usual route the clergyman took, and when something new was added, he noticed it and felt it was unfair. During the prayer, a fly landed on the pew in front of him, torturing his spirit by calmly grooming itself. Tom's hands itched to catch it, but he didn't dare, believing his soul would be instantly destroyed if he did so during the prayer. With the closing sentence, his hand slowly moved forward, and as soon as \"Amen\" was said, the fly was caught. His aunt saw this and made him release it.",
          "es": "Hubo un susurro de vestidos, y la congregación se sentó. El niño cuya historia este libro cuenta no disfrutaba de la oración; simplemente la soportaba—si es que eso. Estuvo inquieto durante todo el tiempo, registrando inconscientemente los detalles de la oración. No estaba escuchando, pero conocía la ruta usual que el clérigo tomaba, y cuando algo nuevo se añadía, lo notaba y sentía que era injusto. Durante la oración, una mosca se posó en el banco frente a él, torturando su espíritu al acicalarse tranquilamente. Las manos de Tom picaban por atraparla, pero no se atrevía, creyendo que su alma sería destruida instantáneamente si lo hacía durante la oración. Con la última oración, su mano se movió lentamente hacia adelante, y tan pronto como se dijo \"Amén\", la mosca fue atrapada. Su tía vio esto e hizo que la soltara."
        },
        {
          "en": "The minister announced his text and droned on monotonously through a dull argument. Many heads began to nod, even though the sermon spoke of fire and brimstone, reducing the elect to a very small group. Tom counted the sermon pages; he always knew how many pages there were after church, but rarely remembered anything else. This time, he was interested for a short while. The minister painted a grand picture of the world's gathering at the millennium when the lion and the lamb would lie down together, and a child would lead them. But the lesson and moral were lost on Tom; he only thought about being the main character in front of the nations. His face lit up with the thought, and he wished he could be that child, if it was a tame lion.",
          "es": "El ministro anunció su texto y habló monótonamente a través de un argumento aburrido. Muchas cabezas comenzaron a inclinarse, aunque el sermón hablaba de fuego e infierno, reduciendo los elegidos a un grupo muy pequeño. Tom contó las páginas del sermón; siempre sabía cuántas páginas había después de la iglesia, pero rara vez recordaba cualquier otra cosa. Esta vez, estuvo interesado por un corto tiempo. El ministro pintó un cuadro grandioso de la reunión del mundo en el milenio cuando el león y el cordero se acostarían juntos, y un niño los guiaría. Pero la lección y la moraleja se perdieron en Tom; solo pensaba en ser el personaje principal frente a las naciones. Su cara se iluminó con el pensamiento, y deseaba poder ser ese niño, si era un león domesticado."
        },
        {
          "en": "Tom was bored again as the dull sermon went on. Then he remembered a treasure he had and took it out. It was a big black beetle with strong jaws, which he called a \"pinchbug.\" It was in a small box. The beetle bit his finger first thing. Tom flicked it away, and it landed on its back in the aisle. His finger went into his mouth, and the beetle struggled to turn over. Tom watched it, wanting it back, but it was too far. Other people who weren't interested in the sermon noticed the beetle too. Soon, a stray poodle wandered in, looking sad and tired. It saw the beetle, wagged its tail, and examined it. The dog sniffed it carefully, then tried to bite it but missed. It kept trying until it lay down with the beetle between its paws. After a while, the dog got bored and its chin touched the beetle, which bit it. The dog yelped and shook its head, sending the beetle flying. People around laughed quietly, and Tom was very happy. The dog looked silly but wanted revenge. It attacked the beetle again, jumping around it and trying to bite it. Eventually, the dog got tired, played with a fly, followed an ant, and then forgot the beetle. It sat on it, yelped in pain, and ran up the aisle. The dog kept yelping, ran across the front, down the other aisle, and back. It was like a furry comet flying around. Finally, it jumped into its owner's lap, who threw it out the window. The dog's cries faded away.",
          "es": "Tom se aburrió de nuevo mientras el tedioso sermón continuaba. Luego recordó un tesoro que tenía y lo sacó. Era un gran escarabajo negro con mandíbulas fuertes, al que llamaba un \"pellizco\". Estaba en una pequeña caja. El escarabajo lo mordió el dedo primero. Tom lo sacudió, y aterrizó sobre su espalda en el pasillo. Su dedo se fue a su boca, y el escarabajo luchó por darse la vuelta. Tom lo miraba, queriendo recuperarlo, pero estaba demasiado lejos. Otras personas que no estaban interesadas en el sermón también notaron el escarabajo. Pronto, un pequeño perro caniche vagabundo entró, viéndose triste y cansado. Vio el escarabajo, movió la cola y lo examinó. El perro lo olfateó cuidadosamente, luego intentó morderlo pero falló. Siguió intentando hasta que se acostó con el escarabajo entre sus patas. Después de un rato, el perro se aburrió y su barbilla tocó el escarabajo, que lo mordió. El perro aulló y movió la cabeza, enviando el escarabajo volando. La gente alrededor rió silenciosamente, y Tom fue muy feliz. El perro se veía tonto pero quería venganza. Atacó el escarabajo de nuevo, saltando alrededor de él e intentando morderlo. Finalmente, el perro se cansó, jugó con una mosca, siguió una hormiga, y luego olvidó el escarabajo. Se sentó sobre él, aulló de dolor, y corrió por el pasillo. El perro siguió aullando, corrió a través del frente, por el otro pasillo, y de vuelta. Era como un cometa peludo volando alrededor. Finalmente, saltó al regazo de su dueña, quien lo lanzó por la ventana. Los gritos del perro se desvanecieron."
        },
        {
          "en": "By then, everyone in the church was red-faced, trying not to laugh. The sermon stopped completely. When it started again, it was awkward and lost its seriousness. Even the serious parts were met with hidden laughter, as if the preacher had told a joke. The congregation was relieved when the service ended and the blessing was given.",
          "es": "Para entonces, todos en la iglesia estaban rojos, intentando no reír. El sermón se detuvo completamente. Cuando comenzó de nuevo, fue incómodo y perdió su seriedad. Incluso las partes serias fueron recibidas con risa oculta, como si el predicador hubiera contado un chiste. La congregación se sintió aliviada cuando el servicio terminó y se dio la bendición."
        },
        {
          "en": "Tom Sawyer went home feeling happy, thinking church was more fun with some excitement. He had only one regret: he didn't mind the dog playing with his pinchbug, but he didn't like that it took it away.",
          "es": "Tom Sawyer llegó a casa sintiéndose feliz, pensando que la iglesia era más divertida con algo de emoción. Tenía un solo arrepentimiento: no le importaba que el perro jugara con su pellizco, pero no le gustaba que se lo llevara."
        }
      ]
    }
  }
};
