export const chapterContent = {
  "storySlug": "dracula",
  "level": 4,
  "chapter": 1,
  "pages": {
    "1": {
      "lines": [
        {
          "en": "JONATHAN HARKER’S JOURNAL",
          "es": "DIARIO DE JONATHAN HARKER"
        },
        {
          "en": "(Kept in shorthand.)",
          "es": "(Escrito en taquigrafía.)"
        },
        {
          "en": "3 May. Bistritz.—Left Munich at 8: P. M., on 1st May, arriving at Vienna early next morning; should have arrived at 6:, but train was an hour late. Buda-Pesth seems a wonderful place, from the glimpse which I got of it from the train and the little I could walk through the streets. I feared to go very far from the station, as we had arrived late and would start as near the correct time as possible. The impression I had was that we were leaving the West and entering the East; the most western of splendid bridges over the Danube, which is here of noble width and depth, took us among the traditions of Turkish rule.",
          "es": "3 de mayo. Bistritz.—Salí de Múnich a las 8 de la tarde del 1 de mayo, llegando a Viena a la mañana siguiente; debería haber llegado a las 6, pero el tren llegó con una hora de retraso. Buda-Pesth parece un lugar maravilloso, por lo poco que vi desde el tren y lo que pude caminar por las calles. Temía alejarme mucho de la estación, porque habíamos llegado tarde y teníamos que partir lo más cerca posible de la hora prevista. La impresión que tuve fue que estábamos dejando Occidente y entrando en Oriente; el más occidental de los magníficos puentes sobre el Danubio, que aquí tiene una anchura y profundidad nobles, nos llevó entre las tradiciones del dominio turco."
        },
        {
          "en": "We left in pretty good time, and came after nightfall to Klausenburgh. Here I stopped for the night at the Hotel Royale. I had for dinner, or rather supper, a chicken done up some way with red pepper, which was very good but thirsty. (Mem., get recipe for Mina.) I asked the waiter, and he said it was called “paprika hendl,” and that, as it was a national dish, I should be able to get it anywhere along the Carpathians. I found my smattering of German very useful here; indeed, I don’t know how I should be able to get on without it.",
          "es": "Salimos con bastante puntualidad y llegamos después del anochecer a Klausenburgh. Aquí me detuve por la noche en el Hotel Royale. Para cenar, o más bien para la cena, comí un pollo preparado de alguna manera con pimiento rojo, que estaba muy bueno pero daba sed. (Mem., conseguir la receta para Mina.) Le pregunté al camarero y me dijo que se llamaba \"paprika hendl\" y que, siendo un plato nacional, debería poder conseguirlo en cualquier lugar a lo largo de los Cárpatos. Encontré que mis conocimientos básicos de alemán fueron muy útiles aquí; de hecho, no sé cómo habría podido arreglármelas sin él."
        },
        {
          "en": "Having had some time at my disposal when in London, I had visited the British Museum, and made search among the books and maps in the library regarding Transylvania; it had struck me that some foreknowledge of the country could hardly fail to have some importance in dealing with a nobleman of that country. I find that the district he named is in the extreme east of the country, just on the borders of three states, Transylvania, Moldavia and Bukovina, in the midst of the Carpathian mountains; one of the wildest and least known portions of Europe. I was not able to light on any map or work giving the exact locality of the Castle Dracula, as there are no maps of this country as yet to compare with our own Ordnance Survey maps; but I found that Bistritz, the post town named by Count Dracula, is a fairly well-known place. I shall enter here some of my notes, as they may refresh my memory when I talk over my travels with Mina.",
          "es": "Habiendo tenido algo de tiempo disponible cuando estaba en Londres, visité el Museo Británico e hice búsquedas entre los libros y mapas de la biblioteca sobre Transilvania; me pareció que tener algún conocimiento previo del país no podría dejar de ser importante al tratar con un noble de ese país. Descubrí que el distrito que nombró está en el extremo este del país, justo en los límites de tres estados, Transilvania, Moldavia y Bukovina, en medio de las montañas de los Cárpatos; una de las partes más salvajes y menos conocidas de Europa. No pude encontrar ningún mapa ni obra que diera la ubicación exacta del Castillo Drácula, pues todavía no hay mapas de este país que se puedan comparar con nuestros mapas del Servicio Topográfico; pero descubrí que Bistritz, el pueblo de correos nombrado por el Conde Drácula, es un lugar bastante conocido. Anotaré aquí algunos de mis apuntes, pues pueden refrescar mi memoria cuando hable de mis viajes con Mina."
        }
      ]
    },
    "2": {
      "lines": [
        {
          "en": "In the population of Transylvania there are four distinct nationalities: Saxons in the South, and mixed with them the Wallachs, who are the descendants of the Dacians; Magyars in the West, and Szekelys in the East and North. I am going among the latter, who claim to be descended from Attila and the Huns. This may be so, for when the Magyars conquered the country in the eleventh century they found the Huns settled in it. I read that every known superstition in the world is gathered into the horseshoe of the Carpathians, as if it were the centre of some sort of imaginative whirlpool; if so my stay may be very interesting. (Mem., I must ask the Count all about them.)",
          "es": "En la población de Transilvania hay cuatro nacionalidades distintas: sajones en el Sur, y mezclados con ellos los valaquos, que son descendientes de los dacios; magiares en el Oeste y székely en el Este y Norte. Voy entre los últimos, que afirman descender de Atila y los hunos. Esto puede ser cierto, pues cuando los magiares conquistaron el país en el siglo once encontraron a los hunos establecidos allí. He leído que toda superstición conocida en el mundo se ha reunido en la herradura de los Cárpatos, como si fuera el centro de un remolino imaginativo; si es así, mi estancia puede ser muy interesante. (Mem., debo preguntarle al Conde todo sobre ellas.)"
        },
        {
          "en": "I did not sleep well, though my bed was comfortable enough, for I had all sorts of queer dreams. There was a dog howling all night under my window, which may have had something to do with it; or it may have been the paprika, for I had to drink up all the water in my carafe, and was still thirsty. Towards morning I slept and was wakened by the continuous knocking at my door, so I guess I must have been sleeping soundly then. I had for breakfast more paprika, and a sort of porridge of maize flour which they said was “mamaliga,” and egg-plant stuffed with forcemeat, a very excellent dish, which they call “impletata.” (Mem., get recipe for this also.) I had to hurry breakfast, for the train started a little before eight, or rather it ought to have done so, for after rushing to the station at 7: I had to sit in the carriage for more than an hour before we began to move. It seems to me that the further east you go the more unpunctual are the trains. What ought they to be in China?",
          "es": "No dormí bien, aunque mi cama era lo suficientemente cómoda, pues tuve toda clase de sueños extraños. Había un perro aullando toda la noche bajo mi ventana, lo que puede haber tenido algo que ver; o puede haber sido el pimentón, pues tuve que beber toda el agua de mi jarra y seguía teniendo sed. Hacia la mañana dormí y me desperté por los golpes continuos en mi puerta, así que supongo que debe haber estado durmiendo profundamente entonces. Para desayunar tuve más pimentón y una especie de gachas de harina de maíz que dijeron que era \"mamaliga\", y berenjena rellena de carne picada, un plato muy excelente, que llaman \"impletata\". (Mem., conseguir también la receta de esto.) Tuve que apurarme con el desayuno, pues el tren salía un poco antes de las ocho, o mejor dicho, debería haber salido, pero después de correr a la estación a las 7 tuve que estar sentado en el coche más de una hora antes de que empezáramos a movernos. Me parece que cuanto más hacia el este vas, más impuntuales son los trenes. ¿Cómo deberían ser en China?"
        },
        {
          "en": "All day long we seemed to dawdle through a country which was full of beauty of every kind. Sometimes we saw little towns or castles on the top of steep hills such as we see in old missals; sometimes we ran by rivers and streams which seemed from the wide stony margin on each side of them to be subject to great floods. It takes a lot of water, and running strong, to sweep the outside edge of a river clear. At every station there were groups of people, sometimes crowds, and in all sorts of attire. Some of them were just like the peasants at home or those I saw coming through France and Germany, with short jackets and round hats and home-made trousers; but others were very picturesque. The women looked pretty, except when you got near them, but they were very clumsy about the waist. They had all full white sleeves of some kind or other, and most of them had big belts with a lot of strips of something fluttering from them like the dresses in a ballet, but of course there were petticoats under them. The strangest figures we saw were the Slovaks, who were more barbarian than the rest, with their big cow-boy hats, great baggy dirty-white trousers, white linen shirts, and enormous heavy leather belts, nearly a foot wide, all studded over with brass nails. They wore high boots, with their trousers tucked into them, and had long black hair and heavy black moustaches. They are very picturesque, but do not look prepossessing. On the stage they would be set down at once as some old Oriental band of brigands. They are, however, I am told, very harmless and rather wanting in natural self-assertion.",
          "es": "Durante todo el día parecimos ir lentamente por un país lleno de belleza de todo tipo. A veces veíamos pequeños pueblos o castillos en la cima de colinas empinadas como los que vemos en antiguos manuscritos; a veces pasábamos por ríos y arroyos que parecían, por el amplio margen pedregoso a cada lado, estar sujetos a grandes inundaciones. Se necesita mucha agua, y corriendo fuerte, para barrer el borde exterior de un río. En cada estación había grupos de personas, a veces multitudes, y de toda clase de atuendos. Algunos eran como los campesinos de mi país o los que vi atravesando Francia y Alemania, con chaquetas cortas y sombreros redondos y pantalones caseros; pero otros eran muy pintorescos. Las mujeres se veían bonitas, excepto cuando te acercabas a ellas, pero eran muy torpes de cintura. Todas tenían mangas blancas completas de algún tipo, y la mayoría tenía cinturones grandes con muchas tiras de algo que ondeaban como los vestidos en un ballet, pero por supuesto había enaguas debajo. Las figuras más extrañas que vimos fueron los eslovacos, que eran más bárbaros que los demás, con sus grandes sombreros de vaquero, pantalones enormes holgados de un blanco sucio, camisas de lino blanco y cinturones de cuero pesados enormes, de casi un pie de ancho, todos cubiertos de clavos de latón. Llevaban botas altas, con los pantalones metidos dentro, y tenían el pelo largo y negro y grandes bigotes negros. Son muy pintorescos, pero no tienen aspecto agradable. En el escenario los señalarían de inmediato como una antigua banda oriental de bandidos. Sin embargo, me han dicho que son muy inofensivos y bastante faltos de seguridad natural."
        },
        {
          "en": "It was on the dark side of twilight when we got to Bistritz, which is a very interesting old place. Being practically on the frontier—for the Borgo Pass leads from it into Bukovina—it has had a very stormy existence, and it certainly shows marks of it. Fifty years ago a series of great fires took place, which made terrible havoc on five separate occasions. At the very beginning of the seventeenth century it underwent a siege of three weeks and lost 13, people, the casualties of war proper being assisted by famine and disease.",
          "es": "Era en el lado oscuro del crepúsculo cuando llegamos a Bistritz, que es un lugar antiguo muy interesante. Estando prácticamente en la frontera—pues el Paso de Borgo lleva desde aquí a Bukovina—ha tenido una existencia muy tormentosa, y ciertamente muestra señales de ello. Hace cincuenta años ocurrió una serie de grandes incendios, que causaron terribles daños en cinco ocasiones distintas. A principios del siglo diecisiete sufrió un sitio de tres semanas y perdió 13,000 personas, las bajas de la guerra propiamente dicha siendo agravadas por el hambre y la enfermedad."
        },
        {
          "en": "Count Dracula had directed me to go to the Golden Krone Hotel, which I found, to my great delight, to be thoroughly old-fashioned, for of course I wanted to see all I could of the ways of the country. I was evidently expected, for when I got near the door I faced a cheery-looking elderly woman in the usual peasant dress—white undergarment with long double apron, front, and back, of coloured stuff fitting almost too tight for modesty. When I came close she bowed and said, “The Herr Englishman?” “Yes,” I said, “Jonathan Harker.” She smiled, and gave some message to an elderly man in white shirt-sleeves, who had followed her to the door. He went, but immediately returned with a letter:—",
          "es": "El Conde Drácula me había dirigido a ir al Hotel Krone Dorado, que encontré, para mi gran alegría, que era completamente anticuado, pues por supuesto quería ver todo lo que pudiera de las costumbres del país. Evidentemente me esperaban, pues cuando me acerqué a la puerta me encontré con una mujer anciana de aspecto alegre con el atuendo campesino habitual—una prenda blanca interior con un delantal doble largo, delante y atrás, de tela de color que se ajustaba casi demasiado apretadamente para el pudor. Cuando me acerqué se inclinó y dijo: \"¿El Herr inglés?\" \"Sí\", respondí, \"Jonathan Harker.\" Sonrió y dio algún mensaje a un hombre anciano en mangas de camisa blanca, que la había seguido a la puerta. Se fue, pero volvió inmediatamente con una carta:—"
        },
        {
          "en": "“My Friend.—Welcome to the Carpathians. I am anxiously expecting you. Sleep well to-night. At three to-morrow the diligence will start for Bukovina; a place on it is kept for you. At the Borgo Pass my carriage will await you and will bring you to me. I trust that your journey from London has been a happy one, and that you will enjoy your stay in my beautiful land.",
          "es": "\"Mi amigo.—Bienvenido a los Cárpatos. Te estoy esperando con ansias. Duerme bien esta noche. A las tres mañana la diligencia partirá hacia Bukovina; un asiento está reservado para ti. En el Paso de Borgo mi carruaje te estará esperando y te llevará a mí. Confío en que tu viaje desde Londres ha sido feliz y que disfrutarás tu estancia en mi hermosa tierra."
        }
      ]
    },
    "3": {
      "lines": [
        {
          "en": "“Your friend,",
          "es": "\"Tu amigo,"
        },
        {
          "en": "“Dracula.”",
          "es": "Drácula."
        },
        {
          "en": "4 May.—I found that my landlord had got a letter from the Count, directing him to secure the best place on the coach for me; but on making inquiries as to details he seemed somewhat reticent, and pretended that he could not understand my German. This could not be true, because up to then he had understood it perfectly; at least, he answered my questions exactly as if he did. He and his wife, the old lady who had received me, looked at each other in a frightened sort of way. He mumbled out that the money had been sent in a letter, and that was all he knew. When I asked him if he knew Count Dracula, and could tell me anything of his castle, both he and his wife crossed themselves, and, saying that they knew nothing at all, simply refused to speak further. It was so near the time of starting that I had no time to ask any one else, for it was all very mysterious and not by any means comforting.",
          "es": "4 de mayo.—Descubrí que mi casero había recibido una carta del Conde, ordenándole que asegurara el mejor lugar en la diligencia para mí; pero al hacer preguntas sobre los detalles pareció algo reticente y fingió que no podía entender mi alemán. Esto no podía ser verdad, porque hasta entonces lo había entendido perfectamente; al menos, respondía mis preguntas exactamente como si lo entendiera. Él y su esposa, la anciana que me había recibido, se miraron de una manera asustada. Murmuró que el dinero había sido enviado en una carta y eso era todo lo que sabía. Cuando le pregunté si conocía al Conde Drácula y si podía decirme algo sobre su castillo, tanto él como su esposa se santiguaron y, diciendo que no sabían nada en absoluto, simplemente se negaron a hablar más. Era tan cerca la hora de salida que no tuve tiempo de preguntar a nadie más, pues todo era muy misterioso y de ninguna manera reconfortante."
        },
        {
          "en": "Just before I was leaving, the old lady came up to my room and said in a very hysterical way:",
          "es": "Justo antes de irme, la anciana subió a mi habitación y dijo de una manera muy histérica:"
        },
        {
          "en": "“Must you go? Oh! young Herr, must you go?” She was in such an excited state that she seemed to have lost her grip of what German she knew, and mixed it all up with some other language which I did not know at all. I was just able to follow her by asking many questions. When I told her that I must go at once, and that I was engaged on important business, she asked again:",
          "es": "\"¿Debes ir? ¡Oh! joven Herr, ¿debes ir?\" Estaba en un estado tan alterado que parecía haber perdido el dominio del alemán que sabía y lo mezcló todo con algún otro idioma que no conocía en absoluto. Apenas pude seguirla haciendo muchas preguntas. Cuando le dije que debía irme inmediatamente y que estaba ocupado en asuntos importantes, me preguntó de nuevo:"
        },
        {
          "en": "“Do you know what day it is?” I answered that it was the fourth of May. She shook her head as she said again:",
          "es": "\"¿Sabes qué día es?\" Respondí que era el cuatro de mayo. Movió la cabeza mientras decía de nuevo:"
        },
        {
          "en": "“Oh, yes! I know that! I know that, but do you know what day it is?” On my saying that I did not understand, she went on:",
          "es": "\"¡Oh, sí! ¡Sé eso! ¡Sé eso, pero sabes qué día es?\" Al decir que no entendía, continuó:"
        }
      ]
    },
    "4": {
      "lines": [
        {
          "en": "“It is the eve of St. George’s Day. Do you not know that to-night, when the clock strikes midnight, all the evil things in the world will have full sway? Do you know where you are going, and what you are going to?” She was in such evident distress that I tried to comfort her, but without effect. Finally she went down on her knees and implored me not to go; at least to wait a day or two before starting. It was all very ridiculous but I did not feel comfortable. However, there was business to be done, and I could allow nothing to interfere with it. I therefore tried to raise her up, and said, as gravely as I could, that I thanked her, but my duty was imperative, and that I must go. She then rose and dried her eyes, and taking a crucifix from her neck offered it to me. I did not know what to do, for, as an English Churchman, I have been taught to regard such things as in some measure idolatrous, and yet it seemed so ungracious to refuse an old lady meaning so well and in such a state of mind. She saw, I suppose, the doubt in my face, for she put the rosary round my neck, and said, “For your mother’s sake,” and went out of the room. I am writing up this part of the diary whilst I am waiting for the coach, which is, of course, late; and the crucifix is still round my neck. Whether it is the old lady’s fear, or the many ghostly traditions of this place, or the crucifix itself, I do not know, but I am not feeling nearly as easy in my mind as usual. If this book should ever reach Mina before I do, let it bring my good-bye. Here comes the coach!",
          "es": "\"Es la víspera del Día de San Jorge. ¿No sabes que esta noche, cuando el reloj dé las doce, todas las cosas malas del mundo tendrán pleno poder? ¿Sabes a dónde vas y qué vas a hacer?\" Estaba en tal angustia evidente que traté de consolarla, pero sin efecto. Finalmente se arrodilló y me imploró que no fuera; al menos que esperara un día o dos antes de partir. Era todo muy ridículo pero no me sentía cómodo. Sin embargo, había negocios que hacer y no podía permitir que nada interfiriera con ello. Por lo tanto traté de ayudarla a levantarse y dije, tan seriamente como pude, que le agradecía, pero mi deber era imperativo y que debía irme. Entonces se levantó, se secó los ojos y, sacando un crucifijo de su cuello me lo ofreció. No sabía qué hacer, pues, siendo un anglicano inglés, me han enseñado a considerar tales cosas como en cierta medida idólatras, y sin embargo parecía tan desagradable rechazar a una anciana con tan buenas intenciones y en tal estado de ánimo. Ella vio, supongo, la duda en mi cara, pues puso el rosario alrededor de mi cuello y dijo: \"Por el bien de tu madre\", y salió de la habitación. Estoy escribiendo esta parte del diario mientras espero la diligencia, que por supuesto llega tarde; y el crucifijo sigue alrededor de mi cuello. Ya sea el miedo de la anciana, las muchas tradiciones espectrales de este lugar, o el crucifijo mismo, no sé, pero no me siento casi tan tranquilo de mente como es usual. Si este libro alguna vez llegara a Mina antes que yo, que traiga mi despedida. ¡Ahí viene la diligencia!"
        },
        {
          "en": "5 May. The Castle.—The grey of the morning has passed, and the sun is high over the distant horizon, which seems jagged, whether with trees or hills I know not, for it is so far off that big things and little are mixed. I am not sleepy, and, as I am not to be called till I awake, naturally I write till sleep comes. There are many odd things to put down, and, lest who reads them may fancy that I dined too well before I left Bistritz, let me put down my dinner exactly. I dined on what they called “robber steak”—bits of bacon, onion, and beef, seasoned with red pepper, and strung on sticks and roasted over the fire, in the simple style of the London cat’s meat! The wine was Golden Mediasch, which produces a queer sting on the tongue, which is, however, not disagreeable. I had only a couple of glasses of this, and nothing else.",
          "es": "5 de mayo. El Castillo.—La grisura de la mañana ha pasado y el sol está alto sobre el horizonte distante, que parece dentado, no sé si de árboles o colinas, pues está tan lejos que las cosas grandes y pequeñas se mezclan. No tengo sueño y, como no debo ser llamado hasta que despierte, naturalmente escribo hasta que me viene el sueño. Hay muchas cosas extrañas que anotar y, para que quien las lea no piense que cené demasiado bien antes de dejar Bistritz, voy a anotar mi cena exactamente. Cené lo que llamaban \"filete de bandido\"—trozos de tocino, cebolla y carne de res, sazonados con pimiento rojo, y ensartados en palos y asados al fuego, al estilo sencillo de la carne de gato de Londres. El vino era Mediasch Dorado, que produce un sabor extraño en la lengua, que sin embargo no es desagradable. Solo bebí un par de copas de esto y nada más."
        },
        {
          "en": "When I got on the coach the driver had not taken his seat, and I saw him talking with the landlady. They were evidently talking of me, for every now and then they looked at me, and some of the people who were sitting on the bench outside the door—which they call by a name meaning “word-bearer”—came and listened, and then looked at me, most of them pityingly. I could hear a lot of words often repeated, queer words, for there were many nationalities in the crowd; so I quietly got my polyglot dictionary from my bag and looked them out. I must say they were not cheering to me, for amongst them were “Ordog”—Satan, “pokol”—hell, “stregoica”—witch, “vrolok” and “vlkoslak”—both of which mean the same thing, one being Slovak and the other Servian for something that is either were-wolf or vampire. (Mem., I must ask the Count about these superstitions)",
          "es": "Cuando subí a la diligencia el conductor no había tomado su asiento y lo vi hablando con la posadera. Evidentemente estaban hablando de mí, pues de vez en cuando me miraban, y algunas de las personas que estaban sentadas en el banco fuera de la puerta—que llaman por un nombre que significa \"portador de palabras\"—vinieron y escucharon, y luego me miraron, la mayoría de ellos con lástima. Pude oír muchas palabras que se repetían a menudo, palabras extrañas, pues había muchas nacionalidades en la multitud; así que tranquilamente saqué mi diccionario políglota de mi bolsa y las busqué. Debo decir que no fueron alentadoras para mí, pues entre ellas estaban \"Ordog\"—Satán, \"pokol\"—infierno, \"stregoica\"—bruja, \"vrolok\" y \"vlkoslak\"—ambas significan lo mismo, una siendo eslovaca y la otra serbia por algo que es un hombre lobo o vampiro. (Mem., debo preguntarle al Conde sobre estas supersticiones)"
        },
        {
          "en": "When we started, the crowd round the inn door, which had by this time swelled to a considerable size, all made the sign of the cross and pointed two fingers towards me. With some difficulty I got a fellow-passenger to tell me what they meant; he would not answer at first, but on learning that I was English, he explained that it was a charm or guard against the evil eye. This was not very pleasant for me, just starting for an unknown place to meet an unknown man; but every one seemed so kind-hearted, and so sorrowful, and so sympathetic that I could not but be touched. I shall never forget the last glimpse which I had of the inn-yard and its crowd of picturesque figures, all crossing themselves, as they stood round the wide archway, with its background of rich foliage of oleander and orange trees in green tubs clustered in the centre of the yard. Then our driver, whose wide linen drawers covered the whole front of the box-seat—“gotza” they call them—cracked his big whip over his four small horses, which ran abreast, and we set off on our journey.",
          "es": "Cuando partimos, la multitud alrededor de la puerta de la posada, que para entonces se había hinchado considerablemente, todos hicieron la señal de la cruz y señalaron dos dedos hacia mí. Con alguna dificultad logré que un compañero de viaje me dijera qué significaba; al principio no quiso responder, pero al saber que era inglés, explicó que era un hechizo o protección contra el mal de ojo. Esto no fue muy agradable para mí, justo comenzando para un lugar desconocido para encontrarme con un hombre desconocido; pero todos parecían tener tan buen corazón, tan afligidos y tan solidarios que no pude dejar de estar tocado. Nunca olvidaré el último vistazo que tuve del patio de la posada y su multitud de figuras pintorescas, todos santiguándose, mientras estaban alrededor del amplio arco, con su fondo de rico follaje de adelfas y naranjos en macetas verdes agrupados en el centro del patio. Luego nuestro conductor, cuyos amplios pantalones de lino cubrían toda la parte delantera del pescante—los llaman \"gotza\"—chasqueó su gran látigo sobre sus cuatro caballos pequeños, que trotaban emparejados, y nos pusimos en marcha en nuestro viaje."
        },
        {
          "en": "I soon lost sight and recollection of ghostly fears in the beauty of the scene as we drove along, although had I known the language, or rather languages, which my fellow-passengers were speaking, I might not have been able to throw them off so easily. Before us lay a green sloping land full of forests and woods, with here and there steep hills, crowned with clumps of trees or with farmhouses, the blank gable end to the road. There was everywhere a bewildering mass of fruit blossom—apple, plum, pear, cherry; and as we drove by I could see the green grass under the trees spangled with the fallen petals. In and out amongst these green hills of what they call here the “Mittel Land” ran the road, losing itself as it swept round the grassy curve, or was shut out by the straggling ends of pine woods, which here and there ran down the hillsides like tongues of flame. The road was rugged, but still we seemed to fly over it with a feverish haste. I could not understand then what the haste meant, but the driver was evidently bent on losing no time in reaching Borgo Prund. I was told that this road is in summertime excellent, but that it had not yet been put in order after the winter snows. In this respect it is different from the general run of roads in the Carpathians, for it is an old tradition that they are not to be kept in too good order. Of old the Hospadars would not repair them, lest the Turk should think that they were preparing to bring in foreign troops, and so hasten the war which was always really at loading point.",
          "es": "Pronto perdí de vista y recuerdo de los miedos espectrales en la belleza de la escena mientras avanzábamos, aunque si hubiera conocido el idioma, o más bien los idiomas, que hablaban mis compañeros de viaje, quizás no habría podido desembarazarme de ellos tan fácilmente. Ante nosotros se extendía una tierra verde inclinada llena de bosques y arboledas, con aquí y allá colinas empinadas, coronadas con grupos de árboles o con granjas, con el extremo del tejado a dos aguas hacia la carretera. Había en todas partes una masa desconcertante de flores de frutal—manzano, ciruela, pera, cerezo; y mientras conducíamos podía ver el pasto verde bajo los árboles salpicado de pétalos caídos. Dentro y fuera de estas colinas verdes de lo que aquí llaman la \"Tierra Media\" corría la carretera, perdiéndose mientras daba la vuelta a la curva cubierta de hierba, u oculta por los extremos dispersos de bosques de pino, que aquí y allá bajaban por las laderas como lenguas de fuego. La carretera era áspera, pero aún parecía que volábamos sobre ella con una prisa febril. No podía entender entonces qué significaba esa prisa, pero el conductor estaba evidentemente decidido a no perder tiempo en llegar a Borgo Prund. Me dijeron que esta carretera es excelente en verano, pero que aún no había sido arreglada después de las nieves invernales. En este aspecto es diferente del curso general de carreteras en los Cárpatos, pues es una tradición antigua que no deben mantenerse en muy buen estado. Antiguamente los Hospodaros no las reparaban, por miedo a que el Turco pensara que se preparaban para traer tropas extranjeras y así apresuraran la guerra que siempre estaba realmente en el punto de estallar."
        }
      ]
    },
    "5": {
      "lines": [
        {
          "en": "Beyond the green swelling hills of the Mittel Land rose mighty slopes of forest up to the lofty steeps of the Carpathians themselves. Right and left of us they towered, with the afternoon sun falling full upon them and bringing out all the glorious colours of this beautiful range, deep blue and purple in the shadows of the peaks, green and brown where grass and rock mingled, and an endless perspective of jagged rock and pointed crags, till these were themselves lost in the distance, where the snowy peaks rose grandly. Here and there seemed mighty rifts in the mountains, through which, as the sun began to sink, we saw now and again the white gleam of falling water. One of my companions touched my arm as we swept round the base of a hill and opened up the lofty, snow-covered peak of a mountain, which seemed, as we wound on our serpentine way, to be right before us:—",
          "es": "Más allá de las colinas verdes e hinchadas de la Tierra Media se elevaban poderosas laderas de bosque hasta los altos picos de los Cárpatos mismos. A derecha e izquierda se levantaban sobre nosotros, con el sol de la tarde cayendo completamente sobre ellos e iluminando todos los colores gloriosos de esta hermosa cordillera, azul oscuro y púrpura en las sombras de los picos, verde y marrón donde se mezclaban pasto y roca, y una perspectiva interminable de roca dentada y picos puntiagudos, hasta que estos mismos se perdían en la distancia, donde se elevaban grandiosamente los picos nevados. Aquí y allá parecía haber grietas poderosas en las montañas, a través de las cuales, cuando el sol comenzaba a hundirse, veíamos de vez en cuando el brillo blanco del agua que cae. Uno de mis compañeros me tocó el brazo mientras dábamos vuelta a la base de una colina y se abría ante nosotros el pico alto cubierto de nieve de una montaña, que parecía, mientras nos movíamos en nuestro camino sinuoso, estar directamente ante nosotros:—"
        },
        {
          "en": "“Look! Isten szek!”—“God’s seat!”—and he crossed himself reverently.",
          "es": "\"¡Mira! ¡Isten szek!\"—\"¡El asiento de Dios!\"—y se santiguó reverentemente."
        },
        {
          "en": "As we wound on our endless way, and the sun sank lower and lower behind us, the shadows of the evening began to creep round us. This was emphasised by the fact that the snowy mountain-top still held the sunset, and seemed to glow out with a delicate cool pink. Here and there we passed Cszeks and Slovaks, all in picturesque attire, but I noticed that goitre was painfully prevalent. By the roadside were many crosses, and as we swept by, my companions all crossed themselves. Here and there was a peasant man or woman kneeling before a shrine, who did not even turn round as we approached, but seemed in the self-surrender of devotion to have neither eyes nor ears for the outer world. There were many things new to me: for instance, hay-ricks in the trees, and here and there very beautiful masses of weeping birch, their white stems shining like silver through the delicate green of the leaves. Now and again we passed a leiter-wagon—the ordinary peasant’s cart—with its long, snake-like vertebra, calculated to suit the inequalities of the road. On this were sure to be seated quite a group of home-coming peasants, the Cszeks with their white, and the Slovaks with their coloured, sheepskins, the latter carrying lance-fashion their long staves, with axe at end. As the evening fell it began to get very cold, and the growing twilight seemed to merge into one dark mistiness the gloom of the trees, oak, beech, and pine, though in the valleys which ran deep between the spurs of the hills, as we ascended through the Pass, the dark firs stood out here and there against the background of late-lying snow. Sometimes, as the road was cut through the pine woods that seemed in the darkness to be closing down upon us, great masses of greyness, which here and there bestrewed the trees, produced a peculiarly weird and solemn effect, which carried on the thoughts and grim fancies engendered earlier in the evening, when the falling sunset threw into strange relief the ghost-like clouds which amongst the Carpathians seem to wind ceaselessly through the valleys. Sometimes the hills were so steep that, despite our driver’s haste, the horses could only go slowly. I wished to get down and walk up them, as we do at home, but the driver would not hear of it. “No, no,” he said; “you must not walk here; the dogs are too fierce”; and then he added, with what he evidently meant for grim pleasantry—for he looked round to catch the approving smile of the rest—“and you may have enough of such matters before you go to sleep.” The only stop he would make was a moment’s pause to light his lamps.",
          "es": "Mientras continuábamos nuestro camino interminable y el sol se hundía más y más tras nosotros, las sombras de la tarde comenzaron a arrastrarse alrededor nuestro. Esto fue enfatizado por el hecho de que la cima nevada aún mantenía la puesta de sol y parecía brillar con un rosa pálido y delicado. Aquí y allá pasamos cerca de Székely y eslovacos, todos con atuendos pintorescos, pero noté que el bocio era dolorosamente prevalente. Al lado de la carretera había muchas cruces y, mientras pasábamos, mis compañeros se santiguaban. Aquí y allá había un campesino hombre o mujer arrodillado ante un santuario, que ni siquiera se daba la vuelta cuando nos acercábamos, sino que parecía en la entrega de sí mismos de la devoción no tener ni ojos ni oídos para el mundo exterior. Había muchas cosas nuevas para mí: por ejemplo, montones de heno en los árboles y aquí y allá masas muy bellas de abedul llorón, sus tallos blancos brillando como plata a través del delicado verde de las hojas. De vez en cuando pasábamos un carro leiter—la carreta campesina ordinaria—con su larga vértebra parecida a una serpiente, calculada para adaptarse a las irregularidades de la carretera. En este siempre había seguro un grupo bastante numeroso de campesinos que regresaban a casa, los Székely con sus vellones blancos y los eslovacos con sus vellones de color, estos últimos llevando al estilo de lanza sus largas varas, con un hacha en el extremo. Cuando cayó la tarde comenzó a hacer mucho frío y el crepúsculo creciente parecía fusionarse en una oscuridad oscura la penumbra de los árboles, roble, haya y pino, aunque en los valles que corrían profundamente entre los espolones de las colinas, mientras ascendíamos a través del Paso, los abetos oscuros se destacaban aquí y allá contra el fondo de la nieve tardía. A veces, cuando la carretera estaba cortada a través de los bosques de pino que parecían en la oscuridad cerrarse sobre nosotros, grandes masas de grisura, que aquí y allá cubrían los árboles, producían un efecto peculiarmente extraño y solemne, que llevaba los pensamientos y las fantasías sombrías engendradas antes en la tarde, cuando la puesta de sol que caía arrojaba en alivio extraño las nubes espectrales que entre los Cárpatos parecen enrollarse incesantemente a través de los valles. A veces las colinas eran tan empinadas que, a pesar de la prisa del conductor, los caballos solo podían ir lentamente. Deseaba bajar y caminar hacia arriba, como hacemos en casa, pero el conductor no quería oír hablar de ello. \"No, no\", dijo; \"no debes caminar aquí; los perros son demasiado fieros\"; y luego añadió, con lo que evidentemente pretendía ser un chiste sombrío—pues miró alrededor para captar la sonrisa aprobadora del resto—\"y puede que tengas bastante de tales asuntos antes de irte a dormir.\" La única parada que haría era una pausa momentánea para encender sus lámparas."
        },
        {
          "en": "When it grew dark there seemed to be some excitement amongst the passengers, and they kept speaking to him, one after the other, as though urging him to further speed. He lashed the horses unmercifully with his long whip, and with wild cries of encouragement urged them on to further exertions. Then through the darkness I could see a sort of patch of grey light ahead of us, as though there were a cleft in the hills. The excitement of the passengers grew greater; the crazy coach rocked on its great leather springs, and swayed like a boat tossed on a stormy sea. I had to hold on. The road grew more level, and we appeared to fly along. Then the mountains seemed to come nearer to us on each side and to frown down upon us; we were entering on the Borgo Pass. One by one several of the passengers offered me gifts, which they pressed upon me with an earnestness which would take no denial; these were certainly of an odd and varied kind, but each was given in simple good faith, with a kindly word, and a blessing, and that strange mixture of fear-meaning movements which I had seen outside the hotel at Bistritz—the sign of the cross and the guard against the evil eye. Then, as we flew along, the driver leaned forward, and on each side the passengers, craning over the edge of the coach, peered eagerly into the darkness. It was evident that something very exciting was either happening or expected, but though I asked each passenger, no one would give me the slightest explanation. This state of excitement kept on for some little time; and at last we saw before us the Pass opening out on the eastern side. There were dark, rolling clouds overhead, and in the air the heavy, oppressive sense of thunder. It seemed as though the mountain range had separated two atmospheres, and that now we had got into the thunderous one. I was now myself looking out for the conveyance which was to take me to the Count. Each moment I expected to see the glare of lamps through the blackness; but all was dark. The only light was the flickering rays of our own lamps, in which the steam from our hard-driven horses rose in a white cloud. We could see now the sandy road lying white before us, but there was on it no sign of a vehicle. The passengers drew back with a sigh of gladness, which seemed to mock my own disappointment. I was already thinking what I had best do, when the driver, looking at his watch, said to the others something which I could hardly hear, it was spoken so quietly and in so low a tone; I thought it was “An hour less than the time.” Then turning to me, he said in German worse than my own:—",
          "es": "Cuando se hizo de noche pareció haber cierta excitación entre los pasajeros y seguían hablándole, uno tras otro, como si lo urgieran a mayor velocidad. Golpeó despiadadamente a los caballos con su largo látigo y con gritos salvajes de aliento los urgió a mayores esfuerzos. Luego a través de la oscuridad pude ver una especie de parche de luz gris ante nosotros, como si hubiera una grieta en las colinas. La excitación de los pasajeros creció; la diligencia loca se balanceó sobre sus grandes muelles de cuero y se bamboleó como un bote sacudido por un mar tempestuoso. Tuve que sostenerme. La carretera se hizo más plana y parecimos volar. Luego las montañas parecieron acercarse a nosotros a cada lado y mirar hacia abajo sobre nosotros; estábamos entrando en el Paso de Borgo. Uno a uno varios pasajeros me ofrecieron regalos, que me presionaban con una seriedad que no aceptaba negación; estos eran ciertamente de un tipo extraño y variado, pero cada uno fue dado en buena fe simple, con una palabra amable y una bendición, y esa extraña mezcla de movimientos de significado de miedo que había visto fuera del hotel en Bistritz—la señal de la cruz y la protección contra el mal de ojo. Luego, mientras volábamos, el conductor se inclinó hacia adelante y a cada lado los pasajeros, inclinándose sobre el borde de la diligencia, miraban ansiosamente hacia la oscuridad. Era evidente que algo muy emocionante estaba sucediendo o se esperaba, pero aunque pregunté a cada pasajero, nadie me dio la menor explicación. Este estado de excitación continuó durante algún tiempo; y finalmente vimos ante nosotros el Paso abrirse en el lado oriental. Había nubes oscuras y rodantes arriba, y en el aire la sensación pesada y opresiva del trueno. Parecía como si la cadena montañosa hubiera separado dos atmósferas y que ahora habíamos entrado en la tronadora. Ahora yo mismo estaba buscando el transporte que debía llevarme al Conde. En cada momento esperaba ver el brillo de lámparas a través de la negrura; pero todo estaba oscuro. La única luz era los rayos parpadeantes de nuestras propias lámparas, en las cuales el vapor de nuestros caballos muy conducidos se elevaba en una nube blanca. Ahora podíamos ver la carretera arenosa tendida blanca ante nosotros, pero no había ningún signo de un vehículo en ella. Los pasajeros se retiraron con un suspiro de alegría, que parecía burlarse de mi propia decepción. Ya estaba pensando qué sería lo mejor hacer cuando el conductor, mirando su reloj, dijo a los otros algo que apenas podía oír, fue hablado tan tranquila y con un tono tan bajo; pensé que era \"Una hora menos que la hora.\" Luego, volviéndose hacia mí, dijo en alemán peor que el mío:—"
        },
        {
          "en": "“There is no carriage here. The Herr is not expected after all. He will now come on to Bukovina, and return to-morrow or the next day; better the next day.” Whilst he was speaking the horses began to neigh and snort and plunge wildly, so that the driver had to hold them up. Then, amongst a chorus of screams from the peasants and a universal crossing of themselves, a calèche, with four horses, drove up behind us, overtook us, and drew up beside the coach. I could see from the flash of our lamps, as the rays fell on them, that the horses were coal-black and splendid animals. They were driven by a tall man, with a long brown beard and a great black hat, which seemed to hide his face from us. I could only see the gleam of a pair of very bright eyes, which seemed red in the lamplight, as he turned to us. He said to the driver:—",
          "es": "\"No hay carruaje aquí. El Herr no se esperaba después de todo. Ahora vendrá a Bukovina y regresará mañana o pasado mañana; mejor pasado mañana.\" Mientras hablaba los caballos comenzaron a relinchar y bufar y saltar salvajemente, de modo que el conductor tuvo que contenerlos. Entonces, entre un coro de gritos de los campesinos y un cruce universal de sí mismos, un calesa con cuatro caballos nos alcanzó, nos adelantó y se detuvo a nuestro lado. Podía ver por el destello de nuestras lámparas, cuando los rayos caían sobre ellos, que los caballos eran negros como el carbón y animales espléndidos. Eran conducidos por un hombre alto con una barba larga marrón y un gran sombrero negro, que parecía ocultarle la cara. Solo podía ver el brillo de un par de ojos muy brillantes, que parecían rojos a la luz de las lámparas, mientras se volvía hacia nosotros. Le dijo al conductor:—"
        },
        {
          "en": "“You are early to-night, my friend.” The man stammered in reply:—",
          "es": "\"Vienes temprano esta noche, mi amigo.\" El hombre tartamudeó en respuesta:—"
        },
        {
          "en": "“The English Herr was in a hurry,” to which the stranger replied:—",
          "es": "\"El Herr inglés tenía prisa\", a lo que el extraño respondió:—"
        }
      ]
    },
    "6": {
      "lines": [
        {
          "en": "“That is why, I suppose, you wished him to go on to Bukovina. You cannot deceive me, my friend; I know too much, and my horses are swift.” As he spoke he smiled, and the lamplight fell on a hard-looking mouth, with very red lips and sharp-looking teeth, as white as ivory. One of my companions whispered to another the line from Burger’s “Lenore”:—",
          "es": "\"Es por eso que, supongo, querías que fuera a Bukovina. No puedes engañarme, mi amigo; sé demasiado y mis caballos son veloces.\" Mientras hablaba sonrió y la luz de la lámpara cayó sobre una boca de aspecto duro, con labios muy rojos y dientes de aspecto afilado, blancos como el marfil. Uno de mis compañeros susurró a otro la línea del \"Lenore\" de Burger:—"
        },
        {
          "en": "“Denn die Todten reiten schnell”—",
          "es": "\"Denn die Todten reiten schnell\"—"
        },
        {
          "en": "(“For the dead travel fast.”)",
          "es": "(\"Pues los muertos viajan rápido.\")"
        },
        {
          "en": "The strange driver evidently heard the words, for he looked up with a gleaming smile. The passenger turned his face away, at the same time putting out his two fingers and crossing himself. “Give me the Herr’s luggage,” said the driver; and with exceeding alacrity my bags were handed out and put in the calèche. Then I descended from the side of the coach, as the calèche was close alongside, the driver helping me with a hand which caught my arm in a grip of steel; his strength must have been prodigious. Without a word he shook his reins, the horses turned, and we swept into the darkness of the Pass. As I looked back I saw the steam from the horses of the coach by the light of the lamps, and projected against it the figures of my late companions crossing themselves. Then the driver cracked his whip and called to his horses, and off they swept on their way to Bukovina. As they sank into the darkness I felt a strange chill, and a lonely feeling came over me; but a cloak was thrown over my shoulders, and a rug across my knees, and the driver said in excellent German:—",
          "es": "El extraño conductor evidentemente oyó las palabras, pues levantó la vista con una sonrisa reluciente. El pasajero apartó la cara, al mismo tiempo extendiendo dos dedos y santiguándose. \"Dame el equipaje del Herr\", dijo el conductor; y con excelente presteza mis bolsas fueron entregadas y puestas en el calesa. Luego descendí del lado de la diligencia, mientras el calesa estaba cerca al lado, el conductor ayudándome con una mano que me agarró el brazo en una embestida de acero; su fuerza debía haber sido prodigiosa. Sin una palabra sacudió las riendas, los caballos giraron y nos adentramos en la oscuridad del Paso. Mientras miraba hacia atrás vi el vapor de los caballos de la diligencia a la luz de las lámparas y proyectado contra él las figuras de mis antiguos compañeros santiguándose. Luego el conductor chasqueó su látigo y llamó a sus caballos y se fueron en su camino a Bukovina. Mientras se hundían en la oscuridad sentí un extraño frío y una sensación solitaria vino sobre mí; pero una capa fue arrojada sobre mis hombros y una manta sobre mis rodillas, y el conductor dijo en excelente alemán:—"
        },
        {
          "en": "“The night is chill, mein Herr, and my master the Count bade me take all care of you. There is a flask of slivovitz (the plum brandy of the country) underneath the seat, if you should require it.” I did not take any, but it was a comfort to know it was there all the same. I felt a little strangely, and not a little frightened. I think had there been any alternative I should have taken it, instead of prosecuting that unknown night journey. The carriage went at a hard pace straight along, then we made a complete turn and went along another straight road. It seemed to me that we were simply going over and over the same ground again; and so I took note of some salient point, and found that this was so. I would have liked to have asked the driver what this all meant, but I really feared to do so, for I thought that, placed as I was, any protest would have had no effect in case there had been an intention to delay. By-and-by, however, as I was curious to know how time was passing, I struck a match, and by its flame looked at my watch; it was within a few minutes of midnight. This gave me a sort of shock, for I suppose the general superstition about midnight was increased by my recent experiences. I waited with a sick feeling of suspense.",
          "es": "\"La noche es fría, mein Herr, y mi amo el Conde me ordenó que tuviera todo cuidado de ti. Hay un frasco de slivovitz (el brandy de ciruela del país) debajo del asiento, si lo necesitas.\" No tomé nada, pero fue un consuelo saber que estaba allí de todas formas. Me sentía un poco extraño y no poco asustado. Creo que de haber habido alguna alternativa la habría tomado, en lugar de proseguir ese viaje nocturno desconocido. El carruaje iba a un ritmo rápido en línea recta y luego dimos una vuelta completa e íbamos por otra carretera recta. Me pareció que simplemente estábamos yendo una y otra vez por el mismo terreno; así que tomé nota de algún punto destacado y descubrí que era así. Me habría gustado preguntar al conductor qué significaba todo esto, pero realmente temía hacerlo, pues pensé que, situado como estaba, cualquier protesta no habría tenido efecto en caso de haber habido la intención de retrasar. Poco a poco, sin embargo, como tenía curiosidad de saber cómo pasaba el tiempo, encendí una cerilla y a su luz miré mi reloj; eran dentro de pocos minutos de medianoche. Esto me dio una especie de susto, pues supongo que la superstición general sobre la medianoche fue aumentada por mis experiencias recientes. Esperé con una sensación enferma de suspense."
        }
      ]
    },
    "7": {
      "lines": [
        {
          "en": "Then a dog began to howl somewhere in a farmhouse far down the road—a long, agonised wailing, as if from fear. The sound was taken up by another dog, and then another and another, till, borne on the wind which now sighed softly through the Pass, a wild howling began, which seemed to come from all over the country, as far as the imagination could grasp it through the gloom of the night. At the first howl the horses began to strain and rear, but the driver spoke to them soothingly, and they quieted down, but shivered and sweated as though after a runaway from sudden fright. Then, far off in the distance, from the mountains on each side of us began a louder and a sharper howling—that of wolves—which affected both the horses and myself in the same way—for I was minded to jump from the calèche and run, whilst they reared again and plunged madly, so that the driver had to use all his great strength to keep them from bolting. In a few minutes, however, my own ears got accustomed to the sound, and the horses so far became quiet that the driver was able to descend and to stand before them. He petted and soothed them, and whispered something in their ears, as I have heard of horse-tamers doing, and with extraordinary effect, for under his caresses they became quite manageable again, though they still trembled. The driver again took his seat, and shaking his reins, started off at a great pace. This time, after going to the far side of the Pass, he suddenly turned down a narrow roadway which ran sharply to the right.",
          "es": "Entonces un perro comenzó a aullar en algún lugar en una granja lejos por la carretera—un aullido largo y angustioso, como si fuera por miedo. El sonido fue tomado por otro perro, y luego por otro y otro, hasta que, llevado por el viento que ahora suspiraba suavemente a través del Paso, un aullido salvaje comenzó, que parecía venir de todas partes del país, tan lejos como la imaginación pudiera comprender a través de la penumbra de la noche. Al primer aullido los caballos comenzaron a tensar y elevarse, pero el conductor les habló tranquilizadoramente y se calmaron, pero temblaron y sudaron como después de una carrera repentina por un susto repentino. Luego, muy lejos en la distancia, desde las montañas a cada lado nuestro comenzó un aullido más fuerte y más agudo—el de los lobos—que afectó tanto a los caballos como a mí de la misma manera—pues estaba predispuesto a saltar del calesa y correr, mientras que ellos se elevaron de nuevo y se sumergieron locamente, de modo que el conductor tuvo que usar toda su gran fuerza para evitar que salieran disparados. Sin embargo, en pocos minutos, mis propios oídos se acostumbraron al sonido y los caballos se calmaron lo suficiente como para que el conductor pudiera descender y pararse frente a ellos. Los acarició y los consoló y susurró algo en sus oídos, como he oído decir que hacen los domadores de caballos, y con un efecto extraordinario, pues bajo sus caricias se volvieron completamente manejables de nuevo, aunque seguían temblando. El conductor volvió a tomar su asiento y, sacudiendo las riendas, partió a gran velocidad. Esta vez, después de llegar al lado lejano del Paso, giró repentinamente por un camino estrecho que corría bruscamente hacia la derecha."
        },
        {
          "en": "Soon we were hemmed in with trees, which in places arched right over the roadway till we passed as through a tunnel; and again great frowning rocks guarded us boldly on either side. Though we were in shelter, we could hear the rising wind, for it moaned and whistled through the rocks, and the branches of the trees crashed together as we swept along. It grew colder and colder still, and fine, powdery snow began to fall, so that soon we and all around us were covered with a white blanket. The keen wind still carried the howling of the dogs, though this grew fainter as we went on our way. The baying of the wolves sounded nearer and nearer, as though they were closing round on us from every side. I grew dreadfully afraid, and the horses shared my fear. The driver, however, was not in the least disturbed; he kept turning his head to left and right, but I could not see anything through the darkness.",
          "es": "Pronto estuvimos rodeados de árboles que en lugares se arqueaban completamente sobre la carretera hasta que pasamos como a través de un túnel; y de nuevo grandes rocas fruncidas nos guardaban audazmente a ambos lados. Aunque estábamos bajo abrigo, podíamos oír el viento creciente, pues gemía y silbaba a través de las rocas y las ramas de los árboles se chocaban entre sí mientras avanzábamos. Se hizo más frío y más frío aún, y comenzó a caer una nieve fina y polvorienta, de modo que pronto nosotros y todo alrededor nuestro fuimos cubiertos con una manta blanca. El viento penetrante seguía llevando el aullido de los perros, aunque esto se hizo más débil mientras continuábamos nuestro camino. El ladrido de los lobos sonaba más cerca y más cerca aún, como si estuvieran cerrándose alrededor nuestro desde todos lados. Me asusté terriblemente y los caballos compartieron mi miedo. El conductor, sin embargo, no estaba en lo más mínimo perturbado; seguía girando la cabeza hacia la izquierda y hacia la derecha, pero no podía ver nada a través de la oscuridad."
        },
        {
          "en": "Suddenly, away on our left, I saw a faint flickering blue flame. The driver saw it at the same moment; he at once checked the horses, and, jumping to the ground, disappeared into the darkness. I did not know what to do, the less as the howling of the wolves grew closer; but while I wondered the driver suddenly appeared again, and without a word took his seat, and we resumed our journey. I think I must have fallen asleep and kept dreaming of the incident, for it seemed to be repeated endlessly, and now looking back, it is like a sort of awful nightmare. Once the flame appeared so near the road, that even in the darkness around us I could watch the driver’s motions. He went rapidly to where the blue flame arose—it must have been very faint, for it did not seem to illumine the place around it at all—and gathering a few stones, formed them into some device. Once there appeared a strange optical effect: when he stood between me and the flame he did not obstruct it, for I could see its ghostly flicker all the same. This startled me, but as the effect was only momentary, I took it that my eyes deceived me straining through the darkness. Then for a time there were no blue flames, and we sped onwards through the gloom, with the howling of the wolves around us, as though they were following in a moving circle.",
          "es": "De repente, lejos a nuestra izquierda, vi una llama azul pálida y parpadeante. El conductor la vio en el mismo momento; inmediatamente frenó los caballos y, saltando al suelo, desapareció en la oscuridad. No sabía qué hacer, menos aún cuando el aullido de los lobos se acercaba; pero mientras me preguntaba el conductor de repente reapareció y sin una palabra tomó su asiento y reanudamos nuestro viaje. Creo que debo haberme quedado dormido y mantuve soñando con el incidente, pues parecía repetirse sin fin, y ahora mirando hacia atrás, es como una especie de pesadilla terrible. Una vez la llama apareció tan cerca de la carretera que incluso en la oscuridad alrededor nuestro podía observar los movimientos del conductor. Fue rápidamente a donde se levantaba la llama azul—debe haber sido muy tenue, pues no parecía iluminar el lugar a su alrededor en absoluto—y recogiendo algunas piedras, las formó en algún dispositivo. Una vez apareció un efecto óptico extraño: cuando se paró entre mí y la llama no la obstruyó, pues podía ver su parpadeo espectral de todos modos. Esto me sorprendió, pero como el efecto fue solo momentáneo, asumí que mis ojos me engañaban por fuerza a través de la oscuridad. Luego por un tiempo no hubo llamas azules y seguimos adelante a través de la penumbra, con el aullido de los lobos alrededor nuestro, como si estuvieran siguiendo en un círculo móvil."
        },
        {
          "en": "At last there came a time when the driver went further afield than he had yet gone, and during his absence, the horses began to tremble worse than ever and to snort and scream with fright. I could not see any cause for it, for the howling of the wolves had ceased altogether; but just then the moon, sailing through the black clouds, appeared behind the jagged crest of a beetling, pine-clad rock, and by its light I saw around us a ring of wolves, with white teeth and lolling red tongues, with long, sinewy limbs and shaggy hair. They were a hundred times more terrible in the grim silence which held them than even when they howled. For myself, I felt a sort of paralysis of fear. It is only when a man feels himself face to face with such horrors that he can understand their true import.",
          "es": "Finalmente llegó un momento en que el conductor se alejó más de lo que jamás había ido y durante su ausencia los caballos comenzaron a temblar peor que nunca y a resoplar y gritar de miedo. No podía ver ninguna causa para ello, pues el aullido de los lobos había cesado por completo; pero justo entonces la luna, navegando a través de las nubes negras, apareció detrás de la cresta dentada de una roca de pino sobresaliente, y por su luz vi alrededor nuestro un anillo de lobos, con dientes blancos y lenguas rojas colgando, con miembros largos y sinuosos y pelaje desgreñado. Eran cien veces más terribles en el silencio sombrío que los sostenía que incluso cuando aullaban. Para mí mismo, sentía una especie de parálisis de miedo. Es solo cuando un hombre se siente frente a tales horrores que puede entender su verdadera importancia."
        },
        {
          "en": "All at once the wolves began to howl as though the moonlight had had some peculiar effect on them. The horses jumped about and reared, and looked helplessly round with eyes that rolled in a way painful to see; but the living ring of terror encompassed them on every side; and they had perforce to remain within it. I called to the coachman to come, for it seemed to me that our only chance was to try to break out through the ring and to aid his approach. I shouted and beat the side of the calèche, hoping by the noise to scare the wolves from that side, so as to give him a chance of reaching the trap. How he came there, I know not, but I heard his voice raised in a tone of imperious command, and looking towards the sound, saw him stand in the roadway. As he swept his long arms, as though brushing aside some impalpable obstacle, the wolves fell back and back further still. Just then a heavy cloud passed across the face of the moon, so that we were again in darkness.",
          "es": "De repente los lobos comenzaron a aullar como si la luz de la luna tuviera algún efecto peculiar en ellos. Los caballos saltaban y se elevaban y miraban desamparados alrededor con ojos que rodaban de una manera dolorosa de ver; pero el anillo viviente de terror los rodeaba por todos lados; y tenían que permanecer dentro de él. Grité al cochero que viniera, pues me parecía que nuestra única oportunidad era intentar romper el anillo y ayudar su enfoque. Grité y golpeé el lado del calesa, esperando que el ruido asustara a los lobos de ese lado, de modo que le diera una oportunidad de llegar a la trampa. Cómo llegó allí, no sé, pero oí su voz levantada en un tono de mando imperioso, y mirando hacia el sonido, lo vi de pie en la carretera. Mientras extendía sus brazos largos, como si apartara algún obstáculo impalpable, los lobos retrocedieron y retrocedieron aún más. Justo entonces una nube pesada pasó a través de la cara de la luna, de modo que estábamos de nuevo en la oscuridad."
        }
      ]
    },
    "8": {
      "lines": [
        {
          "en": "When I could see again the driver was climbing into the calèche, and the wolves had disappeared. This was all so strange and uncanny that a dreadful fear came upon me, and I was afraid to speak or move. The time seemed interminable as we swept on our way, now in almost complete darkness, for the rolling clouds obscured the moon. We kept on ascending, with occasional periods of quick descent, but in the main always ascending. Suddenly, I became conscious of the fact that the driver was in the act of pulling up the horses in the courtyard of a vast ruined castle, from whose tall black windows came no ray of light, and whose broken battlements showed a jagged line against the moonlit sky.",
          "es": "Cuando pude ver de nuevo el conductor estaba subiendo al calesa y los lobos habían desaparecido. Todo esto fue tan extraño y perturbador que un miedo terrible vino sobre mí y temía hablar o moverme. El tiempo parecía interminable mientras continuábamos nuestro camino, ahora en casi completa oscuridad, pues las nubes rodantes ocultaban la luna. Seguimos ascendiendo, con períodos ocasionales de descenso rápido, pero en general siempre ascendiendo. De repente, me di cuenta del hecho de que el conductor estaba en el acto de detener los caballos en el patio de un vasto castillo en ruinas, desde cuyas ventanas negras altas no salía ningún rayo de luz, y cuyas almenas rotas mostraban una línea dentada contra el cielo iluminado por la luna."
        }
      ]
    }
  }
};
