export const chapterContent = {
  "storySlug": "dracula",
  "level": 4,
  "chapter": 2,
  "pages": {
    "1": {
      "lines": [
        {
          "en": "JONATHAN HARKER’S JOURNAL—continued",
          "es": "DIARIO DE JONATHAN HARKER—continuación"
        },
        {
          "en": "5 May.—I must have been asleep, for certainly if I had been fully awake I must have noticed the approach of such a remarkable place. In the gloom the courtyard looked of considerable size, and as several dark ways led from it under great round arches, it perhaps seemed bigger than it really is. I have not yet been able to see it by daylight.",
          "es": "5 de mayo.—Debo haber estado dormido, porque sin duda, si hubiera estado completamente despierto, habría notado la llegada a un lugar tan notable. En la penumbra, el patio parecía bastante grande, y como varios caminos oscuros llevaban desde allí bajo grandes arcos redondos, quizás parecía más grande de lo que realmente era. Aún no he podido verlo a la luz del día."
        },
        {
          "en": "When the calèche stopped, the driver jumped down and held out his hand to assist me to alight. Again I could not but notice his prodigious strength. His hand actually seemed like a steel vice that could have crushed mine if he had chosen. Then he took out my traps, and placed them on the ground beside me as I stood close to a great door, old and studded with large iron nails, and set in a projecting doorway of massive stone. I could see even in the dim light that the stone was massively carved, but that the carving had been much worn by time and weather. As I stood, the driver jumped again into his seat and shook the reins; the horses started forward, and trap and all disappeared down one of the dark openings.",
          "es": "Cuando el carruaje se detuvo, el conductor bajó de un salto y me tendió la mano para ayudarme a bajar. De nuevo no pude dejar de notar su fuerza extraordinaria. Su mano parecía realmente como una prensa de acero que habría podido aplastar la mía si lo hubiera querido. Luego sacó mis maletas y las colocó en el suelo a mi lado mientras yo estaba de pie junto a una puerta enorme, vieja y tachonada con grandes clavos de hierro, colocada en un portal saliente de piedra maciza. Incluso con la poca luz, podía ver que la piedra estaba trabajada masivamente, pero que el trabajo había sido muy gastado por el tiempo y el clima. Mientras estaba allí, el conductor saltó nuevamente a su asiento, sacudió las riendas, los caballos avanzaron y el carruaje desapareció por una de las aberturas oscuras."
        },
        {
          "en": "I stood in silence where I was, for I did not know what to do. Of bell or knocker there was no sign; through these frowning walls and dark window openings it was not likely that my voice could penetrate. The time I waited seemed endless, and I felt doubts and fears crowding upon me. What sort of place had I come to, and among what kind of people? What sort of grim adventure was it on which I had embarked? Was this a customary incident in the life of a solicitor’s clerk sent out to explain the purchase of a London estate to a foreigner? Solicitor’s clerk! Mina would not like that. Solicitor—for just before leaving London I got word that my examination was successful; and I am now a full-blown solicitor! I began to rub my eyes and pinch myself to see if I were awake. It all seemed like a horrible nightmare to me, and I expected that I should suddenly awake, and find myself at home, with the dawn struggling in through the windows, as I had now and again felt in the morning after a day of overwork. But my flesh answered the pinching test, and my eyes were not to be deceived. I was indeed awake and among the Carpathians. All I could do now was to be patient, and to wait the coming of the morning.",
          "es": "Me quedé en silencio donde estaba, pues no sabía qué hacer. No había ninguna campana ni aldaba; a través de estos muros amenazadores y las aberturas de ventanas oscuras, era poco probable que mi voz pudiera penetrar. El tiempo que esperé pareció interminable, y sentí dudas y miedos acumulándose en mí. ¿Qué clase de lugar había encontrado, y entre qué tipo de gente? ¿Qué tipo de aventura siniestra era aquella en la que me había embarcado? ¿Era este un incidente normal en la vida de un empleado de abogado enviado a explicar la compra de una propiedad londinense a un extranjero? ¡Empleado de abogado! A Mina no le gustaría eso. ¡Abogado! Porque justo antes de dejar Londres supe que mi examen había sido exitoso; ¡ahora soy un abogado hecho y derecho! Comencé a frotarme los ojos y a pellizcarme para ver si estaba despierto. Todo parecía una pesadilla horrible, y esperaba despertarme de repente y encontrarme en casa, con el amanecer luchando a través de las ventanas, como había sentido algunas veces por la mañana después de un día de exceso de trabajo. Pero mi carne respondió a la prueba del pellizco, y mis ojos no podían ser engañados. Realmente estaba despierto y entre los Cárpatos. Lo único que podía hacer era ser paciente y esperar la llegada de la mañana."
        },
        {
          "en": "Just as I had come to this conclusion I heard a heavy step approaching behind the great door, and saw through the chinks the gleam of a coming light. Then there was the sound of rattling chains and the clanking of massive bolts drawn back. A key was turned with the loud grating noise of long disuse, and the great door swung back.",
          "es": "Justo cuando había llegado a esta conclusión, escuché pasos pesados aproximándose detrás de la gran puerta y vi a través de las grietas el brillo de una luz que se acercaba. Luego hubo el sonido de cadenas sonando y el ruido de pesados cerrojos siendo descorridos. Una llave fue girada con el fuerte ruido de fricción causado por largo desuso, y la gran puerta se abrió lentamente."
        }
      ]
    },
    "2": {
      "lines": [
        {
          "en": "Within, stood a tall old man, clean shaven save for a long white moustache, and clad in black from head to foot, without a single speck of colour about him anywhere. He held in his hand an antique silver lamp, in which the flame burned without chimney or globe of any kind, throwing long quivering shadows as it flickered in the draught of the open door. The old man motioned me in with his right hand with a courtly gesture, saying in excellent English, but with a strange intonation:—",
          "es": "Dentro estaba un hombre alto y anciano, afeitado excepto por un largo bigote blanco, vestido completamente de negro de pies a cabeza, sin un solo toque de color en ninguna parte. Sostenía en su mano una lámpara de plata antigua, en la cual la llama ardía sin quemador ni globo de ningún tipo, proyectando largas sombras temblantes mientras parpadeaba en la corriente de aire de la puerta abierta. El anciano me hizo señas para entrar con la mano derecha en un gesto cortés, diciendo en excelente inglés, pero con una entonación extraña:—"
        },
        {
          "en": "“Welcome to my house! Enter freely and of your own will!” He made no motion of stepping to meet me, but stood like a statue, as though his gesture of welcome had fixed him into stone. The instant, however, that I had stepped over the threshold, he moved impulsively forward, and holding out his hand grasped mine with a strength which made me wince, an effect which was not lessened by the fact that it seemed as cold as ice—more like the hand of a dead than a living man. Again he said:—",
          "es": "\"¡Bienvenido a mi casa! ¡Entra libremente y de tu propia voluntad!\" No hizo movimiento alguno para venir a mi encuentro, sino que se quedó como una estatua, como si su gesto de bienvenida lo hubiera fijado en piedra. Sin embargo, en el instante en que hube cruzado el umbral, se adelantó impulsivamente, y extendiendo su mano, apretó la mía con una fuerza que me hizo estremecerme, efecto que no fue disminuido por el hecho de que parecía tan fría como el hielo—más como la mano de un muerto que de una persona viva. De nuevo dijo:—"
        },
        {
          "en": "“Welcome to my house. Come freely. Go safely; and leave something of the happiness you bring!” The strength of the handshake was so much akin to that which I had noticed in the driver, whose face I had not seen, that for a moment I doubted if it were not the same person to whom I was speaking; so to make sure, I said interrogatively:—",
          "es": "\"Bienvenido a mi casa. Ven libremente. Vete con seguridad; ¡y llévate algo de la felicidad que traes!\" La fuerza del apretón de manos era tan parecida a la que había notado en el conductor, cuya cara no había visto, que por un momento dudé si no era la misma persona con quien estaba hablando; así que para asegurarme, dije interrogativamente:—"
        },
        {
          "en": "“Count Dracula?” He bowed in a courtly way as he replied:—",
          "es": "\"¿Conde Drácula?\" Él se inclinó de manera cortés mientras respondía:—"
        },
        {
          "en": "“I am Dracula; and I bid you welcome, Mr. Harker, to my house. Come in; the night air is chill, and you must need to eat and rest.” As he was speaking, he put the lamp on a bracket on the wall, and stepping out, took my luggage; he had carried it in before I could forestall him. I protested but he insisted:—",
          "es": "\"Soy Drácula; y te doy la bienvenida, Sr. Harker, a mi casa. Entra; el aire de la noche es frío, y debes necesitar comer y descansar.\" Mientras hablaba, colocó la lámpara en un soporte en la pared, y saliendo, tomó mi equipaje; lo había llevado adentro antes de que pudiera evitarlo. Protesté, pero él insistió:—"
        },
        {
          "en": "“Nay, sir, you are my guest. It is late, and my people are not available. Let me see to your comfort myself.” He insisted on carrying my traps along the passage, and then up a great winding stair, and along another great passage, on whose stone floor our steps rang heavily. At the end of this he threw open a heavy door, and I rejoiced to see within a well-lit room in which a table was spread for supper, and on whose mighty hearth a great fire of logs, freshly replenished, flamed and flared.",
          "es": "\"No, señor, eres mi huésped. Es tarde, y mis sirvientes no están disponibles. Permíteme ocuparme de tu comodidad yo mismo.\" Insistió en llevar mis maletas por el pasillo, y luego subimos una gran escalera circular, y avanzamos por otro gran pasillo, cuyo piso de piedra resonaba fuertemente con nuestros pasos. Al final de este, abrió de par en par una puerta pesada, y me alegré de ver dentro una habitación bien iluminada donde había una mesa preparada para la cena, y cuya chimenea imponente tenía un gran fuego de leños, recientemente alimentado, que ardía y resplandecía."
        }
      ]
    },
    "3": {
      "lines": [
        {
          "en": "The Count halted, putting down my bags, closed the door, and crossing the room, opened another door, which led into a small octagonal room lit by a single lamp, and seemingly without a window of any sort. Passing through this, he opened another door, and motioned me to enter. It was a welcome sight; for here was a great bedroom well lighted and warmed with another log fire,—also added to but lately, for the top logs were fresh—which sent a hollow roar up the wide chimney. The Count himself left my luggage inside and withdrew, saying, before he closed the door:—",
          "es": "El Conde se detuvo, dejando mis bolsas, cerró la puerta, y cruzando la habitación, abrió otra puerta que llevaba a una pequeña habitación octogonal iluminada por una sola lámpara, y aparentemente sin ventana alguna. Pasando a través de ella, abrió otra puerta e hizo señas para que entrara. Era un espectáculo bienvenido; aquí había un dormitorio grande y bien iluminado calentado con otro fuego de leños,—también recientemente alimentado, pues los leños superiores eran frescos—que enviaba un rugido hueco hacia arriba por la chimenea ancha. El Conde mismo dejó mi equipaje dentro y se retiró, diciendo, antes de cerrar la puerta:—"
        },
        {
          "en": "“You will need, after your journey, to refresh yourself by making your toilet. I trust you will find all you wish. When you are ready, come into the other room, where you will find your supper prepared.”",
          "es": "Necesitarás, después de tu viaje, refrescarte arreglándote. Confío en que encontrarás todo lo que desees. Cuando estés listo, ven a la otra habitación, donde encontrarás tu cena preparada."
        },
        {
          "en": "The light and warmth and the Count’s courteous welcome seemed to have dissipated all my doubts and fears. Having then reached my normal state, I discovered that I was half famished with hunger; so making a hasty toilet, I went into the other room.",
          "es": "La luz y el calor y la bienvenida cortés del Conde parecían haber disipado todas mis dudas y miedos. Habiendo recuperado mi estado normal, descubrí que estaba medio muerto de hambre; así que arreglándome rápidamente, entré a la otra habitación."
        },
        {
          "en": "I found supper already laid out. My host, who stood on one side of the great fireplace, leaning against the stonework, made a graceful wave of his hand to the table, and said:—",
          "es": "Encontré la cena ya servida. Mi anfitrión, que estaba de pie a un lado de la gran chimenea, apoyado contra la piedra, hizo un gracioso movimiento de su mano hacia la mesa, y dijo:—"
        },
        {
          "en": "“I pray you, be seated and sup how you please. You will, I trust, excuse me that I do not join you; but I have dined already, and I do not sup.”",
          "es": "Te ruego que te sientes y cenes como desees. Confío en que me disculparás por no unirme a ti; pero ya he cenado, y no ceno."
        },
        {
          "en": "I handed to him the sealed letter which Mr. Hawkins had entrusted to me. He opened it and read it gravely; then, with a charming smile, he handed it to me to read. One passage of it, at least, gave me a thrill of pleasure.",
          "es": ""
        }
      ]
    },
    "4": {
      "lines": [
        {
          "en": "“I must regret that an attack of gout, from which malady I am a constant sufferer, forbids absolutely any travelling on my part for some time to come; but I am happy to say I can send a sufficient substitute, one in whom I have every possible confidence. He is a young man, full of energy and talent in his own way, and of a very faithful disposition. He is discreet and silent, and has grown into manhood in my service. He shall be ready to attend on you when you will during his stay, and shall take your instructions in all matters.”",
          "es": "Le entregué la carta sellada que el Sr. Hawkins me había confiado. La abrió y la leyó con seriedad; luego, con una sonrisa encantadora, me la entregó para que la leyera. Un pasaje de ella, al menos, me dio una emoción de placer."
        },
        {
          "en": "The Count himself came forward and took off the cover of a dish, and I fell to at once on an excellent roast chicken. This, with some cheese and a salad and a bottle of old Tokay, of which I had two glasses, was my supper. During the time I was eating it the Count asked me many questions as to my journey, and I told him by degrees all I had experienced.",
          "es": "Debo lamentar que un ataque de gota, dolencia de la que soy un sufridor constante, me impida absolutamente viajar por un tiempo; pero me alegra decir que puedo enviar un sustituto suficiente, alguien en quien tengo toda la confianza posible. Es un joven lleno de energía y talento a su manera, y de disposición muy leal. Es discreto y silencioso, y se ha convertido en hombre en mi servicio. Estará listo para atenderte cuando lo desees durante su estancia, y recibirá tus instrucciones en todos los asuntos."
        },
        {
          "en": "By this time I had finished my supper, and by my host’s desire had drawn up a chair by the fire and begun to smoke a cigar which he offered me, at the same time excusing himself that he did not smoke. I had now an opportunity of observing him, and found him of a very marked physiognomy.",
          "es": "El Conde mismo se adelantó y levantó la tapa de un plato, y caí de inmediato sobre un excelente pollo asado. Esto, junto con un poco de queso, una ensalada y una botella de Tokay antiguo, del cual bebí dos vasos, fue mi cena. Mientras comía, el Conde me hizo muchas preguntas sobre mi viaje, y le conté gradualmente todo lo que había experimentado."
        },
        {
          "en": "His face was a strong—a very strong—aquiline, with high bridge of the thin nose and peculiarly arched nostrils; with lofty domed forehead, and hair growing scantily round the temples but profusely elsewhere. His eyebrows were very massive, almost meeting over the nose, and with bushy hair that seemed to curl in its own profusion. The mouth, so far as I could see it under the heavy moustache, was fixed and rather cruel-looking, with peculiarly sharp white teeth; these protruded over the lips, whose remarkable ruddiness showed astonishing vitality in a man of his years. For the rest, his ears were pale, and at the tops extremely pointed; the chin was broad and strong, and the cheeks firm though thin. The general effect was one of extraordinary pallor.",
          "es": "Para entonces había terminado mi cena, y por deseo de mi anfitrión, había acercado una silla al fuego y había comenzado a fumar un cigarro que me ofreció, al mismo tiempo que se disculpaba por no fumar. Ahora tenía una oportunidad de observarlo, y lo encontré de una fisonomía muy marcada."
        },
        {
          "en": "Hitherto I had noticed the backs of his hands as they lay on his knees in the firelight, and they had seemed rather white and fine; but seeing them now close to me, I could not but notice that they were rather coarse—broad, with squat fingers. Strange to say, there were hairs in the centre of the palm. The nails were long and fine, and cut to a sharp point. As the Count leaned over me and his hands touched me, I could not repress a shudder. It may have been that his breath was rank, but a horrible feeling of nausea came over me, which, do what I would, I could not conceal. The Count, evidently noticing it, drew back; and with a grim sort of smile, which showed more than he had yet done his protuberant teeth, sat himself down again on his own side of the fireplace. We were both silent for a while; and as I looked towards the window I saw the first dim streak of the coming dawn. There seemed a strange stillness over everything; but as I listened I heard as if from down below in the valley the howling of many wolves. The Count’s eyes gleamed, and he said:—",
          "es": "Su cara era fuerte—muy fuerte—aquilina, con el puente alto de la nariz delgada y ventanas nasales peculiarmente arqueadas; con frente abombada y altiva, y cabello que crecía escasamente alrededor de las sienes pero profusamente en otros lugares. Sus cejas eran muy prominentes, casi uniéndose sobre la nariz, con pelo tupido que parecía rizarse por su propia abundancia. La boca, hasta donde podía verla bajo el bigote pesado, era fija y de aspecto bastante cruel, con dientes blancos peculiarmente afilados; estos sobresalían sobre los labios, cuyo enrojecimiento notable mostraba vitalidad asombrosa en un hombre de sus años. Por lo demás, sus orejas eran pálidas, y en las puntas extremadamente puntiagudas; la barbilla era ancha y fuerte, y las mejillas firmes aunque delgadas. El efecto general era de palidez extraordinaria."
        },
        {
          "en": "“Listen to them—the children of the night. What music they make!” Seeing, I suppose, some expression in my face strange to him, he added:—",
          "es": ""
        },
        {
          "en": "“Ah, sir, you dwellers in the city cannot enter into the feelings of the hunter.” Then he rose and said:—",
          "es": ""
        }
      ]
    },
    "5": {
      "lines": [
        {
          "en": "“But you must be tired. Your bedroom is all ready, and to-morrow you shall sleep as late as you will. I have to be away till the afternoon; so sleep well and dream well!” With a courteous bow, he opened for me himself the door to the octagonal room, and I entered my bedroom....",
          "es": "Hasta entonces había notado el dorso de sus manos mientras descansaban sobre sus rodillas a la luz del fuego, y habían parecido bastante blancas y delicadas; pero viéndolas ahora cerca de mí, no pude dejar de notar que eran bastante toscas—anchas, con dedos cortos y gruesos. Extrañamente, había pelos en el centro de la palma. Las uñas eran largas y finas, y cortadas en punta afilada. Cuando el Conde se inclinó sobre mí y sus manos me tocaron, no pude reprimirme de un escalofrío. Puede ser que su aliento fuera fétido, pero un sentimiento horrible de náusea me sobrecogió, que, por mucho que lo intenté, no pude ocultar. El Conde, evidentemente notándolo, retrocedió; y con una sonrisa siniestra, que mostró más que nunca sus dientes prominentes, se sentó de nuevo en su lado de la chimenea. Ambos guardamos silencio por un rato; y mientras miraba hacia la ventana, vi la primera raya débil del amanecer que se aproximaba. Parecía haber una extraña quietud sobre todo; pero mientras escuchaba, oí como si viniera desde abajo en el valle el aullido de muchos lobos. Los ojos del Conde brillaron, y dijo:—"
        },
        {
          "en": "I am all in a sea of wonders. I doubt; I fear; I think strange things, which I dare not confess to my own soul. God keep me, if only for the sake of those dear to me!",
          "es": "\"Escúchalos—los hijos de la noche. ¡Qué música hacen!\" Viendo, supongo, alguna expresión en mi cara que le parecía extraña, añadió:—"
        },
        {
          "en": "7 May.—It is again early morning, but I have rested and enjoyed the last twenty-four hours. I slept till late in the day, and awoke of my own accord. When I had dressed myself I went into the room where we had supped, and found a cold breakfast laid out, with coffee kept hot by the pot being placed on the hearth. There was a card on the table, on which was written:—",
          "es": "\"Ah, señor, ustedes los habitantes de la ciudad no pueden entrar en los sentimientos del cazador.\" Luego se levantó y dijo:—"
        },
        {
          "en": "“I have to be absent for a while. Do not wait for me.—D.” I set to and enjoyed a hearty meal. When I had done, I looked for a bell, so that I might let the servants know I had finished; but I could not find one. There are certainly odd deficiencies in the house, considering the extraordinary evidences of wealth which are round me. The table service is of gold, and so beautifully wrought that it must be of immense value. The curtains and upholstery of the chairs and sofas and the hangings of my bed are of the costliest and most beautiful fabrics, and must have been of fabulous value when they were made, for they are centuries old, though in excellent order. I saw something like them in Hampton Court, but there they were worn and frayed and moth-eaten. But still in none of the rooms is there a mirror. There is not even a toilet glass on my table, and I had to get the little shaving glass from my bag before I could either shave or brush my hair. I have not yet seen a servant anywhere, or heard a sound near the castle except the howling of wolves. Some time after I had finished my meal—I do not know whether to call it breakfast or dinner, for it was between five and six o’clock when I had it—I looked about for something to read, for I did not like to go about the castle until I had asked the Count’s permission. There was absolutely nothing in the room, book, newspaper, or even writing materials; so I opened another door in the room and found a sort of library. The door opposite mine I tried, but found it locked.",
          "es": "\"Pero debes estar cansado. Tu dormitorio está todo listo, y mañana podrás dormir tanto como quieras. Tengo que ausentarme hasta la tarde; ¡así que duerme bien y sueña bien!\" Con una inclinación cortés, abrió para mí mismo la puerta a la habitación octogonal, y entré en mi dormitorio...."
        },
        {
          "en": "In the library I found, to my great delight, a vast number of English books, whole shelves full of them, and bound volumes of magazines and newspapers. A table in the centre was littered with English magazines and newspapers, though none of them were of very recent date. The books were of the most varied kind—history, geography, politics, political economy, botany, geology, law—all relating to England and English life and customs and manners. There were even such books of reference as the London Directory, the “Red” and “Blue” books, Whitaker’s Almanac, the Army and Navy Lists, and—it somehow gladdened my heart to see it—the Law List.",
          "es": "Estoy completamente sumergido en un mar de maravillas. Dudo; tengo miedo; pienso cosas extrañas, que no me atrevo a confesar ni a mi propia alma. ¡Que Dios me proteja, al menos por el bien de los que me son queridos!"
        }
      ]
    },
    "6": {
      "lines": [
        {
          "en": "Whilst I was looking at the books, the door opened, and the Count entered. He saluted me in a hearty way, and hoped that I had had a good night’s rest. Then he went on:—",
          "es": "7 de mayo.—Es de nuevo temprano por la mañana, pero he descansado y he disfrutado de las últimas veinticuatro horas. Dormí hasta tarde en el día, y me desperté por mí mismo. Cuando me hube vestido, entré en la habitación donde habíamos cenado, y encontré un desayuno frío preparado, con café mantenido caliente por la cafetera colocada en la chimenea. Había una tarjeta en la mesa, en la que estaba escrito:—"
        },
        {
          "en": "“I am glad you found your way in here, for I am sure there is much that will interest you. These companions”—and he laid his hand on some of the books—“have been good friends to me, and for some years past, ever since I had the idea of going to London, have given me many, many hours of pleasure. Through them I have come to know your great England; and to know her is to love her. I long to go through the crowded streets of your mighty London, to be in the midst of the whirl and rush of humanity, to share its life, its change, its death, and all that makes it what it is. But alas! as yet I only know your tongue through books. To you, my friend, I look that I know it to speak.”",
          "es": "\"Tengo que estar ausente por un tiempo. No me esperes.—D.\" Me puse a comer y disfruté de una comida abundante. Cuando terminé, busqué un timbre, para que pudiera avisar a los sirvientes que había terminado; pero no pude encontrar uno. Ciertamente hay deficiencias extrañas en la casa, considerando las evidencias extraordinarias de riqueza que me rodean. El servicio de mesa es de oro, y tan bellamente trabajado que debe ser de valor inmenso. Las cortinas y la tapicería de las sillas y sofás y los colgadores de mi cama son de telas de costo y belleza máximos, y deben haber tenido valor fabuloso cuando se hicieron, pues tienen siglos de antigüedad, aunque en excelente estado. Vi algo parecido en el Palacio de Hampton Court, pero allí estaban desgastadas y deshilachadas y comidas por polillas. Pero aún así en ninguna de las habitaciones hay un espejo. No hay ni siquiera un espejo de baño en mi mesa, y tuve que sacar el pequeño espejo de afeitar de mi bolsa antes de poder afeitarme o cepillarme el pelo. Aún no he visto un sirviente en ningún lugar, ni escuchado sonido alguno cerca del castillo excepto el aullido de lobos. Algún tiempo después de que terminé mi comida—no sé si llamarla desayuno o almuerzo, pues era entre las cinco y las seis cuando la tomé—busqué algo para leer, pues no me gustaba recorrer el castillo hasta que hubiera pedido permiso al Conde. No había absolutamente nada en la habitación, ni libro, ni periódico, ni siquiera materiales de escritura; así que abrí otra puerta en la habitación y encontré una especie de biblioteca. La puerta opuesta a la mía la intenté, pero la encontré cerrada con llave."
        },
        {
          "en": "“But, Count,” I said, “you know and speak English thoroughly!” He bowed gravely.",
          "es": "En la biblioteca encontré, para mi gran deleite, una vasta cantidad de libros en inglés, estanterías completas de ellos, y volúmenes encuadernados de revistas y periódicos. Una mesa en el centro estaba llena de revistas y periódicos en inglés, aunque ninguno de ellos era de fecha muy reciente. Los libros eran de la clase más variada—historia, geografía, política, economía política, botánica, geología, derecho—todos relacionados con Inglaterra y la vida, costumbres y modales ingleses. Incluso había libros de referencia como el Directorio de Londres, los libros \"Rojo\" y \"Azul\", el Almanaque de Whitaker, las Listas del Ejército y la Marina, y—de alguna manera me alegró verlo—la Lista de Abogados."
        },
        {
          "en": "“I thank you, my friend, for your all too-flattering estimate, but yet I fear that I am but a little way on the road I would travel. True, I know the grammar and the words, but yet I know not how to speak them.”",
          "es": "Mientras miraba los libros, la puerta se abrió, y el Conde entró. Me saludó de manera cordial, y esperaba que hubiera descansado bien durante la noche. Luego continuó:—"
        },
        {
          "en": "“Indeed,” I said, “you speak excellently.”",
          "es": "Me alegra que hayas encontrado el camino hacia aquí, pues estoy seguro de que hay mucho que te interesará. Estos compañeros\"—y puso su mano sobre algunos de los libros—\"han sido buenos amigos para mí, y durante algunos años, desde que tuve la idea de ir a Londres, me han dado muchas, muchas horas de placer. A través de ellos he llegado a conocer tu gran Inglaterra; y conocerla es amarla. Deseo recorrer las calles concurridas de tu poderoso Londres, estar en medio del tumulto y la prisa de la humanidad, compartir su vida, su cambio, su muerte, y todo lo que la hace lo que es. Pero ¡ay! por ahora solo conozco tu lengua a través de libros. En ti, mi amigo, espero aprender a hablarla."
        },
        {
          "en": "“Not so,” he answered. “Well, I know that, did I move and speak in your London, none there are who would not know me for a stranger. That is not enough for me. Here I am noble; I am boyar; the common people know me, and I am master. But a stranger in a strange land, he is no one; men know him not—and to know not is to care not for. I am content if I am like the rest, so that no man stops if he see me, or pause in his speaking if he hear my words, ‘Ha, ha! a stranger!’ I have been so long master that I would be master still—or at least that none other should be master of me. You come to me not alone as agent of my friend Peter Hawkins, of Exeter, to tell me all about my new estate in London. You shall, I trust, rest here with me awhile, so that by our talking I may learn the English intonation; and I would that you tell me when I make error, even of the smallest, in my speaking. I am sorry that I had to be away so long to-day; but you will, I know, forgive one who has so many important affairs in hand.”",
          "es": ""
        },
        {
          "en": "Of course I said all I could about being willing, and asked if I might come into that room when I chose. He answered: “Yes, certainly,” and added:—",
          "es": ""
        }
      ]
    },
    "7": {
      "lines": [
        {
          "en": "“You may go anywhere you wish in the castle, except where the doors are locked, where of course you will not wish to go. There is reason that all things are as they are, and did you see with my eyes and know with my knowledge, you would perhaps better understand.” I said I was sure of this, and then he went on:—",
          "es": "\"Pero, Conde,\" dije, \"¡hablas inglés completamente!\" Él se inclinó gravemente."
        },
        {
          "en": "“We are in Transylvania; and Transylvania is not England. Our ways are not your ways, and there shall be to you many strange things. Nay, from what you have told me of your experiences already, you know something of what strange things there may be.”",
          "es": "Te agradezco, mi amigo, por tu estimación demasiado favorecedora, pero aún temo que estoy apenas un poco en el camino que quisiera recorrer. Es verdad, conozco la gramática y las palabras, pero aún no sé cómo hablarlas."
        },
        {
          "en": "This led to much conversation; and as it was evident that he wanted to talk, if only for talking’s sake, I asked him many questions regarding things that had already happened to me or come within my notice. Sometimes he sheered off the subject, or turned the conversation by pretending not to understand; but generally he answered all I asked most frankly. Then as time went on, and I had got somewhat bolder, I asked him of some of the strange things of the preceding night, as, for instance, why the coachman went to the places where he had seen the blue flames. He then explained to me that it was commonly believed that on a certain night of the year—last night, in fact, when all evil spirits are supposed to have unchecked sway—a blue flame is seen over any place where treasure has been concealed. “That treasure has been hidden,” he went on, “in the region through which you came last night, there can be but little doubt; for it was the ground fought over for centuries by the Wallachian, the Saxon, and the Turk. Why, there is hardly a foot of soil in all this region that has not been enriched by the blood of men, patriots or invaders. In old days there were stirring times, when the Austrian and the Hungarian came up in hordes, and the patriots went out to meet them—men and women, the aged and the children too—and waited their coming on the rocks above the passes, that they might sweep destruction on them with their artificial avalanches. When the invader was triumphant he found but little, for whatever there was had been sheltered in the friendly soil.”",
          "es": "De hecho,\" dije, \"hablas excelentemente."
        },
        {
          "en": "“But how,” said I, “can it have remained so long undiscovered, when there is a sure index to it if men will but take the trouble to look?” The Count smiled, and as his lips ran back over his gums, the long, sharp, canine teeth showed out strangely; he answered:—",
          "es": "No es así,\" respondió. \"Bueno, sé que, si me moviera y hablara en tu Londres, no hay nadie allí que no me conocería como extranjero. Eso no es suficiente para mí. Aquí soy noble; soy boyardo; la gente común me conoce, y soy amo. Pero un extranjero en una tierra extraña, no es nadie; los hombres no lo conocen—y no conocer es no importarle. Me contentaré si soy como los demás, de manera que ningún hombre se detenga si me ve, o pause en su habla si escucha mis palabras, '¡Ja, ja! ¡un extranjero!' He sido amo durante tanto tiempo que desearía seguir siendo amo—o al menos que ningún otro sea amo de mí. Vienes a mí no solo como agente de mi amigo Peter Hawkins, de Exeter, para decirme todo sobre mi nueva propiedad en Londres. Confío en que descanses aquí conmigo un tiempo, de manera que con nuestra conversación pueda aprender la entonación inglesa; y desearía que me dijeras cuando cometa un error, aunque sea el más pequeño, en mi habla. Lamento haber tenido que ausentarme tanto tiempo hoy; pero sé que perdonarás a alguien que tiene tantos asuntos importantes en mano."
        },
        {
          "en": "“Because your peasant is at heart a coward and a fool! Those flames only appear on one night; and on that night no man of this land will, if he can help it, stir without his doors. And, dear sir, even if he did he would not know what to do. Why, even the peasant that you tell me of who marked the place of the flame would not know where to look in daylight even for his own work. Even you would not, I dare be sworn, be able to find these places again?”",
          "es": "Por supuesto dije todo lo que pude sobre estar dispuesto, y pregunté si podría entrar en esa habitación cuando quisiera. Respondió: \"Sí, ciertamente,\" y añadió:—"
        },
        {
          "en": "“There you are right,” I said. “I know no more than the dead where even to look for them.” Then we drifted into other matters.",
          "es": "\"Puedes ir a cualquier lugar que desees en el castillo, excepto donde las puertas están cerradas con llave, donde por supuesto no deseará ir. Hay razón para que todas las cosas sean como son, y si vieras con mis ojos y conocieras con mi conocimiento, quizás comprenderías mejor.\" Dije que estaba seguro de esto, y luego continuó:—"
        },
        {
          "en": "",
          "es": "Estamos en Transilvania; y Transilvania no es Inglaterra. Nuestros caminos no son tus caminos, y habrá para ti muchas cosas extrañas. No, por lo que me has contado de tus experiencias ya, sabes algo de lo que cosas extrañas puede haber."
        }
      ]
    },
    "8": {
      "lines": [
        {
          "en": "“Come,” he said at last, “tell me of London and of the house which you have procured for me.” With an apology for my remissness, I went into my own room to get the papers from my bag. Whilst I was placing them in order I heard a rattling of china and silver in the next room, and as I passed through, noticed that the table had been cleared and the lamp lit, for it was by this time deep into the dark. The lamps were also lit in the study or library, and I found the Count lying on the sofa, reading, of all things in the world, an English Bradshaw’s Guide. When I came in he cleared the books and papers from the table; and with him I went into plans and deeds and figures of all sorts. He was interested in everything, and asked me a myriad questions about the place and its surroundings. He clearly had studied beforehand all he could get on the subject of the neighbourhood, for he evidently at the end knew very much more than I did. When I remarked this, he answered:—",
          "es": "Esto llevó a mucha conversación; y como era evidente que deseaba hablar, si solo fuera por hablar, le hice muchas preguntas sobre cosas que ya me habían sucedido o caído bajo mi atención. A veces evitaba el tema, o cambiaba la conversación fingiéndose no entender; pero generalmente respondía a todo lo que preguntaba con mucha franqueza. Luego, a medida que pasaba el tiempo y yo había sido más valiente, le pregunté sobre algunas de las cosas extrañas de la noche anterior, como por ejemplo, por qué el cochero fue a los lugares donde había visto las llamas azules. Entonces me explicó que era comúnmente creído que en una cierta noche del año—la noche pasada, de hecho, cuando se suponía que todos los espíritus malignos tienen poder sin freno—se ve una llama azul sobre cualquier lugar donde se ha escondido un tesoro. \"Ese tesoro ha sido escondido,\" continuó, \"en la región a través de la cual viajaste la noche pasada, no puede haber duda; pues fue el terreno sobre el que lucharon durante siglos los valcos, los sajones y los turcos. ¡Por qué, apenas hay un pie de tierra en toda esta región que no haya sido enriquecido por la sangre de hombres, patriotas o invasores. En los viejos tiempos había tiempos agitados, cuando los austriacos y los húngaros subían en hordas, y los patriotas salían a su encuentro—hombres y mujeres, los ancianos y los niños también—y esperaban su llegada en las rocas sobre los pasos, para que pudieran barrer destrucción sobre ellos con sus aludes artificiales. Cuando el invasor era triunfante, encontraba poco, pues lo que había, había sido protegido en el suelo amigable.\""
        },
        {
          "en": "“Well, but, my friend, is it not needful that I should? When I go there I shall be all alone, and my friend Harker Jonathan—nay, pardon me, I fall into my country’s habit of putting your patronymic first—my friend Jonathan Harker will not be by my side to correct and aid me. He will be in Exeter, miles away, probably working at papers of the law with my other friend, Peter Hawkins. So!”",
          "es": "\"Pero ¿cómo,\" dije, \"¿puede haber permanecido tanto tiempo sin ser descubierto, cuando hay un índice seguro de él si los hombres se tomarán el tiempo de buscar?\" El Conde sonrió, y mientras sus labios se retraían sobre sus encías, los dientes caninos largos y afilados sobresalieron extrañamente; respondió:—"
        },
        {
          "en": "We went thoroughly into the business of the purchase of the estate at Purfleet. When I had told him the facts and got his signature to the necessary papers, and had written a letter with them ready to post to Mr. Hawkins, he began to ask me how I had come across so suitable a place. I read to him the notes which I had made at the time, and which I inscribe here:—",
          "es": "¡Porque tu campesino es en el corazón un cobarde y un tonto! Esas llamas solo aparecen una noche; y en esa noche ningún hombre de esta tierra saldrá, si puede evitarlo, de sus puertas. Y, estimado señor, incluso si lo hiciera, no sabría qué hacer. ¿Por qué, incluso el campesino que me dices que marcó el lugar de la llama no sabría dónde mirar a la luz del día ni siquiera por su propio trabajo? ¿Incluso tú no podrías, me atreveré a jurar, encontrar estos lugares nuevamente?"
        },
        {
          "en": "“At Purfleet, on a by-road, I came across just such a place as seemed to be required, and where was displayed a dilapidated notice that the place was for sale. It is surrounded by a high wall, of ancient structure, built of heavy stones, and has not been repaired for a large number of years. The closed gates are of heavy old oak and iron, all eaten with rust.",
          "es": "\"Tienes razón,\" dije. \"No sé más que los muertos dónde incluso buscar.\" Luego derivamos a otros asuntos."
        },
        {
          "en": "“The estate is called Carfax, no doubt a corruption of the old Quatre Face, as the house is four-sided, agreeing with the cardinal points of the compass. It contains in all some twenty acres, quite surrounded by the solid stone wall above mentioned. There are many trees on it, which make it in places gloomy, and there is a deep, dark-looking pond or small lake, evidently fed by some springs, as the water is clear and flows away in a fair-sized stream. The house is very large and of all periods back, I should say, to mediæval times, for one part is of stone immensely thick, with only a few windows high up and heavily barred with iron. It looks like part of a keep, and is close to an old chapel or church. I could not enter it, as I had not the key of the door leading to it from the house, but I have taken with my kodak views of it from various points. The house has been added to, but in a very straggling way, and I can only guess at the amount of ground it covers, which must be very great. There are but few houses close at hand, one being a very large house only recently added to and formed into a private lunatic asylum. It is not, however, visible from the grounds.”",
          "es": "\"Vamos,\" dijo al fin, \"cuéntame sobre Londres y sobre la casa que has conseguido para mí.\" Con una disculpa por mi descuido, entré en mi propia habitación para sacar los papeles de mi bolsa. Mientras los colocaba en orden escuché un sonido de porcelana y plata en la siguiente habitación, y mientras pasaba, noté que la mesa había sido despejada y la lámpara encendida, pues era ya muy entrada la noche oscura. Las lámparas también estaban encendidas en el estudio o biblioteca, y encontré al Conde recostado en el sofá, leyendo, de todas las cosas del mundo, una Guía de Bradshaw en inglés. Cuando entré, despejó los libros y papeles de la mesa; y con él entré en planos, escrituras y números de toda clase. Estaba interesado en todo, y me hizo innumerables preguntas sobre el lugar y sus alrededores. Claramente había estudiado de antemano todo lo que podía sobre el tema del vecindario, pues evidentemente al final sabía mucho más que yo. Cuando remarqué esto, respondió:—"
        },
        {
          "en": "When I had finished, he said:—",
          "es": "Bueno, pero, mi amigo, ¿no es necesario que lo haga? Cuando vaya allá estaré completamente solo, y mi amigo Harker Jonathan—no, perdóname, caigo en la costumbre de mi país de poner tu patronímico primero—mi amigo Jonathan Harker no estará a mi lado para corregirme y ayudarme. Estará en Exeter, millas de distancia, probablemente trabajando en papeles de ley con mi otro amigo, Peter Hawkins. ¡Así!"
        },
        {
          "en": "“I am glad that it is old and big. I myself am of an old family, and to live in a new house would kill me. A house cannot be made habitable in a day; and, after all, how few days go to make up a century. I rejoice also that there is a chapel of old times. We Transylvanian nobles love not to think that our bones may lie amongst the common dead. I seek not gaiety nor mirth, not the bright voluptuousness of much sunshine and sparkling waters which please the young and gay. I am no longer young; and my heart, through weary years of mourning over the dead, is not attuned to mirth. Moreover, the walls of my castle are broken; the shadows are many, and the wind breathes cold through the broken battlements and casements. I love the shade and the shadow, and would be alone with my thoughts when I may.” Somehow his words and his look did not seem to accord, or else it was that his cast of face made his smile look malignant and saturnine.",
          "es": ""
        }
      ]
    },
    "9": {
      "lines": [
        {
          "en": "Presently, with an excuse, he left me, asking me to put all my papers together. He was some little time away, and I began to look at some of the books around me. One was an atlas, which I found opened naturally at England, as if that map had been much used. On looking at it I found in certain places little rings marked, and on examining these I noticed that one was near London on the east side, manifestly where his new estate was situated; the other two were Exeter, and Whitby on the Yorkshire coast.",
          "es": "Entramos completamente en el negocio de la compra de la propiedad en Purfleet. Cuando le había contado los hechos y obtenido su firma en los papeles necesarios, y había escrito una carta con ellos lista para enviar al Sr. Hawkins, comenzó a preguntarme cómo había llegado a encontrar un lugar tan apropiado. Le leí las notas que había tomado en ese momento, y que aquí inscribo:—"
        },
        {
          "en": "It was the better part of an hour when the Count returned. “Aha!” he said; “still at your books? Good! But you must not work always. Come; I am informed that your supper is ready.” He took my arm, and we went into the next room, where I found an excellent supper ready on the table. The Count again excused himself, as he had dined out on his being away from home. But he sat as on the previous night, and chatted whilst I ate. After supper I smoked, as on the last evening, and the Count stayed with me, chatting and asking questions on every conceivable subject, hour after hour. I felt that it was getting very late indeed, but I did not say anything, for I felt under obligation to meet my host’s wishes in every way. I was not sleepy, as the long sleep yesterday had fortified me; but I could not help experiencing that chill which comes over one at the coming of the dawn, which is like, in its way, the turn of the tide. They say that people who are near death die generally at the change to the dawn or at the turn of the tide; any one who has when tired, and tied as it were to his post, experienced this change in the atmosphere can well believe it. All at once we heard the crow of a cock coming up with preternatural shrillness through the clear morning air; Count Dracula, jumping to his feet, said:—",
          "es": "\"En Purfleet, en una carretera secundaria, encontré un lugar exactamente como parecía ser requerido, y donde se exhibía un aviso deteriorado indicando que la propiedad estaba en venta. Está rodeada por un muro alto, de estructura antigua, construido de piedras pesadas, y no ha sido reparado durante un gran número de años. Los portones cerrados son de roble viejo pesado y hierro, todo comido por el óxido."
        },
        {
          "en": "“Why, there is the morning again! How remiss I am to let you stay up so long. You must make your conversation regarding my dear new country of England less interesting, so that I may not forget how time flies by us,” and, with a courtly bow, he quickly left me.",
          "es": "La propiedad se llama Carfax, sin duda una corrupción de la vieja Quatre Face, ya que la casa tiene cuatro lados, de acuerdo con los puntos cardinales de la brújula. Contiene en total unos veinte acres, completamente rodeados por el muro de piedra maciza mencionado arriba. Hay muchos árboles en ella, lo que la hace en algunos lugares lúgubre, y hay una charca profunda de aspecto oscuro o un pequeño lago, evidentemente alimentado por algunos manantiales, ya que el agua es clara y fluye en un arroyo de tamaño considerable. La casa es muy grande y de todos los períodos que se remontan, diría, a tiempos medievales, pues una parte es de piedra inmensamente gruesa, con solo algunas ventanas muy arriba y fuertemente barradas con hierro. Se parece a parte de un torreón, y está cerca de una antigua capilla o iglesia. No pude entrar en ella, pues no tenía la llave de la puerta que la conectaba con la casa, pero he tomado con mi cámara fotográfica vistas de ella desde varios puntos. La casa ha sido ampliada, pero de una manera muy desaliñada, y solo puedo adivinar la cantidad de terreno que cubre, que debe ser muy grande. Hay solo algunas casas cerca, una siendo una casa muy grande recientemente ampliada y convertida en un asilo privado para enfermos mentales. Sin embargo, no es visible desde los terrenos."
        },
        {
          "en": "I went into my own room and drew the curtains, but there was little to notice; my window opened into the courtyard, all I could see was the warm grey of quickening sky. So I pulled the curtains again, and have written of this day.",
          "es": "Cuando terminé, dijo:—"
        },
        {
          "en": "8 May.—I began to fear as I wrote in this book that I was getting too diffuse; but now I am glad that I went into detail from the first, for there is something so strange about this place and all in it that I cannot but feel uneasy. I wish I were safe out of it, or that I had never come. It may be that this strange night-existence is telling on me; but would that that were all! If there were any one to talk to I could bear it, but there is no one. I have only the Count to speak with, and he!—I fear I am myself the only living soul within the place. Let me be prosaic so far as facts can be; it will help me to bear up, and imagination must not run riot with me. If it does I am lost. Let me say at once how I stand—or seem to.",
          "es": "\"Me alegra que sea vieja y grande. Yo mismo soy de una familia antigua, y vivir en una casa nueva me mataría. Una casa no puede hacerse habitable en un día; y, después de todo, ¿cuántos días se necesitan para hacer un siglo? También me regocijo en que hay una capilla de tiempos antiguos. Nosotros, los nobles de Transilvania, no amamos pensar que nuestros huesos puedan yacer entre los muertos comunes. No busco alegría ni diversión, ni el brillo voluptuoso de mucho sol y aguas que reflejan que gustan a los jóvenes y alegres. Ya no soy joven; y mi corazón, a través de años fatigados de luto por los muertos, no está afinado para la diversión. Además, los muros de mi castillo están rotos; las sombras son muchas, y el viento sopla frío a través de los almenares y ventanas rotos. Amo la sombra y la penumbra, y desearía estar solo con mis pensamientos cuando pueda.\" De alguna manera sus palabras y su mirada no parecían estar de acuerdo, o era que su expresión facial hacía que su sonrisa se viera malévola y saturnina."
        }
      ]
    },
    "10": {
      "lines": [
        {
          "en": "I only slept a few hours when I went to bed, and feeling that I could not sleep any more, got up. I had hung my shaving glass by the window, and was just beginning to shave. Suddenly I felt a hand on my shoulder, and heard the Count’s voice saying to me, “Good-morning.” I started, for it amazed me that I had not seen him, since the reflection of the glass covered the whole room behind me. In starting I had cut myself slightly, but did not notice it at the moment. Having answered the Count’s salutation, I turned to the glass again to see how I had been mistaken. This time there could be no error, for the man was close to me, and I could see him over my shoulder. But there was no reflection of him in the mirror! The whole room behind me was displayed; but there was no sign of a man in it, except myself. This was startling, and, coming on the top of so many strange things, was beginning to increase that vague feeling of uneasiness which I always have when the Count is near; but at the instant I saw that the cut had bled a little, and the blood was trickling over my chin. I laid down the razor, turning as I did so half round to look for some sticking plaster. When the Count saw my face, his eyes blazed with a sort of demoniac fury, and he suddenly made a grab at my throat. I drew away, and his hand touched the string of beads which held the crucifix. It made an instant change in him, for the fury passed so quickly that I could hardly believe that it was ever there.",
          "es": "Pronto, con una disculpa, me dejó, pidiéndome que pusiera todos mis papeles juntos. Estuvo ausente poco tiempo, y comencé a mirar algunos de los libros alrededor de mío. Uno era un atlas, que encontré abierto naturalmente en Inglaterra, como si ese mapa hubiera sido muy usado. Al mirarlo, encontré en ciertos lugares pequeños anillos marcados, y al examinar estos, noté que uno estaba cerca de Londres en el lado este, manifestamente donde su nueva propiedad estaba ubicada; los otros dos eran Exeter y Whitby en la costa de Yorkshire."
        },
        {
          "en": "“Take care,” he said, “take care how you cut yourself. It is more dangerous than you think in this country.” Then seizing the shaving glass, he went on: “And this is the wretched thing that has done the mischief. It is a foul bauble of man’s vanity. Away with it!” and opening the heavy window with one wrench of his terrible hand, he flung out the glass, which was shattered into a thousand pieces on the stones of the courtyard far below. Then he withdrew without a word. It is very annoying, for I do not see how I am to shave, unless in my watch-case or the bottom of the shaving-pot, which is fortunately of metal.",
          "es": "Fue la mejor parte de una hora cuando el Conde regresó. \"¡Aja!\" dijo; \"¿aún con tus libros? ¡Bien! Pero no debes trabajar siempre. Vamos; me informan que tu cena está lista.\" Me tomó del brazo, y entramos a la siguiente habitación, donde encontré una cena excelente lista en la mesa. El Conde de nuevo se disculpó, como lo había hecho cuando estuvo fuera de casa. Pero se sentó como la noche anterior, y charló mientras yo comía. Después de la cena fumé, como la última noche, y el Conde se quedó conmigo, charlando y haciendo preguntas sobre todos los temas concebibles, hora tras hora. Sentí que ya era muy tarde, pero no dije nada, pues sentí que estaba obligado a complacer los deseos de mi anfitrión en todos los sentidos. No tenía sueño, ya que el largo sueño de ayer me había fortalecido; pero no podía evitar experimentar ese frío que viene cuando se aproxima el amanecer, que es, en su forma, como el cambio de marea. Dicen que las personas que están cerca de la muerte generalmente mueren en el cambio al amanecer o en el giro de la marea; cualquiera que ha estado cansado, y atado por así decirlo a su puesto, ha experimentado este cambio en la atmósfera puede estar bien seguro de ello. De repente, escuchamos el cacareo de un gallo ascendiendo con agudeza preternatural a través del aire claro de la mañana; el Conde Drácula, saltando a sus pies, dijo:—"
        },
        {
          "en": "When I went into the dining-room, breakfast was prepared; but I could not find the Count anywhere. So I breakfasted alone. It is strange that as yet I have not seen the Count eat or drink. He must be a very peculiar man! After breakfast I did a little exploring in the castle. I went out on the stairs, and found a room looking towards the South. The view was magnificent, and from where I stood there was every opportunity of seeing it. The castle is on the very edge of a terrible precipice. A stone falling from the window would fall a thousand feet without touching anything! As far as the eye can reach is a sea of green tree tops, with occasionally a deep rift where there is a chasm. Here and there are silver threads where the rivers wind in deep gorges through the forests.",
          "es": "\"¡Por qué, ya es de mañana! ¡Qué negligente soy al dejarte levantado tanto tiempo. Debes hacer tu conversación sobre mi querido nuevo país de Inglaterra menos interesante, para que no olvide cómo el tiempo pasa por nosotros,\" y, con una reverencia cortés, rápidamente me dejó."
        },
        {
          "en": "But I am not in heart to describe beauty, for when I had seen the view I explored further; doors, doors, doors everywhere, and all locked and bolted. In no place save from the windows in the castle walls is there an available exit.",
          "es": "Entré en mi propia habitación y abrí las cortinas, pero había poco que notar; mi ventana se abría al patio, todo lo que podía ver era el gris cálido del cielo que se iluminaba. Así que cerré las cortinas de nuevo, y he escrito sobre este día."
        },
        {
          "en": "The castle is a veritable prison, and I am a prisoner!",
          "es": "8 de mayo.—Comencé a temer mientras escribía en este libro que estaba siendo demasiado prolijo; pero ahora me alegra haber entrado en detalle desde el principio, pues hay algo tan extraño sobre este lugar y todo en él que no puedo dejar de sentirme inquieto. Desearía estar seguro fuera de aquí, o que nunca hubiera venido. Puede ser que esta extraña existencia nocturna me esté afectando; pero ¡desearía que eso fuera todo! Si hubiera alguien con quien hablar, podría soportarlo, pero no hay nadie. Solo tengo al Conde para hablar, ¡y él!—Temo que soy yo mismo la única alma viviente dentro del lugar. Permíteme ser práctico hasta donde los hechos permitan; me ayudará a resistir, y la imaginación no debe descontrolarse. Si lo hace, estoy perdido. Permíteme decir de una vez cómo estoy—o parezco estarlo."
        }
      ]
    },
    "11": {
      "lines": [
        {
          "en": "",
          "es": "Solo dormí pocas horas cuando me acosté, y sintiendo que no podía dormir más, me levanté. Había colgado mi espejo de afeitar en la ventana, y estaba justo comenzando a afeitarme. De repente sentí una mano en mi hombro, y escuché la voz del Conde diciendo, \"Buenos días.\" Me sobresalté, pues me sorprendió que no lo hubiera visto, ya que el reflejo del espejo cubría toda la habitación detrás de mí. Al sobresaltarme, me había cortado ligeramente, pero no lo noté en ese momento. Después de responder al saludo del Conde, giré hacia el espejo nuevamente para ver cómo había cometido un error. Esta vez no podía haber error, pues el hombre estaba cerca de mí, y podía verlo sobre mi hombro. ¡Pero no había reflejo de él en el espejo! Toda la habitación detrás de mí se mostraba; pero no había signo de hombre en ella, excepto yo mismo. Esto fue sorprendente, y, viniendo encima de tantas cosas extrañas, estaba comenzando a aumentar ese sentimiento vago de inquietud que siempre tengo cuando el Conde está cerca; pero en ese instante vi que la herida había sangrado un poco, y la sangre estaba goteando sobre mi barbilla. Dejé caer la navaja, girando mientras lo hacía a medio lado para buscar algo de esparadrapo. Cuando el Conde vio mi cara, sus ojos brillaron con una especie de furia demoníaca, e inmediatamente hizo un movimiento para agarrarme del cuello. Me aparté, y su mano tocó la cuerda de cuentas que sostenía el crucifijo. Hizo un cambio instantáneo en él, pues la furia pasó tan rápidamente que apenas podía creer que alguna vez estuviera allí."
        },
        {
          "en": "",
          "es": "\"Ten cuidado,\" dijo, \"ten cuidado de cómo te cortas. Es más peligroso de lo que piensas en este país.\" Luego, apoderándose del espejo de afeitar, continuó: \"Y esta es la cosa miserable que ha causado el daño. Es un baratija vil de la vanidad del hombre. ¡Fuera con ella!\" y abriendo la ventana pesada con un tirón de su terrible mano, lanzó el espejo, que se hizo añicos en mil pedazos en las piedras del patio muy por debajo. Luego se retiró sin una palabra. Es muy molesto, pues no veo cómo voy a afeitarme, a menos que sea en la funda de mi reloj o en el fondo de la olla de afeitar, que afortunadamente es de metal."
        },
        {
          "en": "",
          "es": "Cuando entré al comedor, el desayuno estaba preparado; pero no podía encontrar al Conde en ninguna parte. Así que desayuné solo. Es extraño que aún no haya visto al Conde comer o beber. ¡Debe ser un hombre muy peculiar! Después del desayuno hice un poco de exploración en el castillo. Subí las escaleras, y encontré una habitación mirando hacia el Sur. La vista era magnífica, y desde donde estaba había toda oportunidad de verla. El castillo está en el mismísimo borde de un precipicio terrible. ¡Una piedra que cayera de la ventana caería mil pies sin tocar nada! Hasta donde el ojo puede alcanzar hay un mar de copas de árboles verdes, con ocasionalmente una grieta profunda donde hay un abismo. Aquí y allá hay hilos de plata donde los ríos serpentean en gargantas profundas a través de los bosques."
        },
        {
          "en": "",
          "es": "Pero no tengo el ánimo para describir belleza, pues cuando hube visto la vista exploré más lejos; puertas, puertas, puertas por todas partes, y todas cerradas y atancadas. En ningún lugar excepto desde las ventanas en los muros del castillo hay una salida disponible."
        },
        {
          "en": "",
          "es": "¡El castillo es una verdadera prisión, y yo soy un prisionero!"
        }
      ]
    }
  }
};
