export const chapterContent = {
  "storySlug": "dracula",
  "level": 4,
  "chapter": 27,
  "pages": {
    "1": {
      "lines": [
        {
          "en": "MINA HARKER’S JOURNAL",
          "es": "DIARIO DE MINA HARKER"
        },
        {
          "en": "1 November.—All day long we have travelled, and at a good speed. The horses seem to know that they are being kindly treated, for they go willingly their full stage at best speed. We have now had so many changes and find the same thing so constantly that we are encouraged to think that the journey will be an easy one. Dr. Van Helsing is laconic; he tells the farmers that he is hurrying to Bistritz, and pays them well to make the exchange of horses. We get hot soup, or coffee, or tea; and off we go. It is a lovely country; full of beauties of all imaginable kinds, and the people are brave, and strong, and simple, and seem full of nice qualities. They are very, very superstitious. In the first house where we stopped, when the woman who served us saw the scar on my forehead, she crossed herself and put out two fingers towards me, to keep off the evil eye. I believe they went to the trouble of putting an extra amount of garlic into our food; and I can’t abide garlic. Ever since then I have taken care not to take off my hat or veil, and so have escaped their suspicions. We are travelling fast, and as we have no driver with us to carry tales, we go ahead of scandal; but I daresay that fear of the evil eye will follow hard behind us all the way. The Professor seems tireless; all day he would not take any rest, though he made me sleep for a long spell. At sunset time he hypnotised me, and he says that I answered as usual “darkness, lapping water and creaking wood”; so our enemy is still on the river. I am afraid to think of Jonathan, but somehow I have now no fear for him, or for myself. I write this whilst we wait in a farmhouse for the horses to be got ready. Dr. Van Helsing is sleeping. Poor dear, he looks very tired and old and grey, but his mouth is set as firmly as a conqueror’s; even in his sleep he is instinct with resolution. When we have well started I must make him rest whilst I drive. I shall tell him that we have days before us, and we must not break down when most of all his strength will be needed.... All is ready; we are off shortly.",
          "es": "1 de noviembre.—Hemos viajado todo el día, y a buena velocidad. Los caballos parecen saber que los tratan bien, pues avanzan voluntariamente a toda velocidad en cada etapa. Hemos hecho tantos cambios y encontrado siempre lo mismo que nos anima a pensar que el viaje será fácil. El Dr. Van Helsing es tacaño en palabras; les dice a los granjeros que se apresura a llegar a Bistritz y les paga bien por cambiar los caballos. Recibimos sopa caliente, café o té; y continuamos. Es un país hermoso, lleno de bellezas de toda clase imaginable, y la gente es valiente, fuerte, sencilla y parece tener buenas cualidades. Son muy, muy supersticiosos. En la primera casa donde paramos, cuando la mujer que nos servía vio la cicatriz en mi frente, se santiguó e hizo dos dedos hacia mí para protegerse del mal de ojo. Creo que se tomaron la molestia de poner ajo extra en nuestra comida; y no puedo soportar el ajo. Desde entonces he tenido cuidado de no quitarme el sombrero o el velo, y así he escapado de sus sospechas. Viajamos rápido, y como no tenemos conductor que cuente historias, vamos delante del escándalo; pero supongo que el miedo al mal de ojo nos seguirá de cerca. El Profesor parece incansable; todo el día se negó a descansar, aunque me hizo dormir largo rato. Al atardecer me hipnotizó, y dice que respondí como siempre: \"oscuridad, agua que corre y madera que cruje\"; así que nuestro enemigo aún está en el río. Me da miedo pensar en Jonathan, pero de alguna forma ya no tengo miedo por él ni por mí. Escribo esto mientras esperamos en una granja a que preparen los caballos. El Dr. Van Helsing está durmiendo. Pobre querido, se ve muy cansado, viejo y gris, pero su boca está tan firme como la de un conquistador; incluso durmiendo está lleno de determinación. Cuando hayamos comenzado bien debo hacer que descanse mientras yo conduzco. Le diré que tenemos días por delante y no debemos derrumbarnos cuando más se necesitará su fuerza.... Todo está listo; nos vamos en breve."
        },
        {
          "en": "2 November, morning.—I was successful, and we took turns driving all night; now the day is on us, bright though cold. There is a strange heaviness in the air—I say heaviness for want of a better word; I mean that it oppresses us both. It is very cold, and only our warm furs keep us comfortable. At dawn Van Helsing hypnotised me; he says I answered “darkness, creaking wood and roaring water,” so the river is changing as they ascend. I do hope that my darling will not run any chance of danger—more than need be; but we are in God’s hands.",
          "es": "2 de noviembre, mañana.—Tuve éxito, y nos turnamos conduciendo toda la noche; ahora ha llegado el día, brillante pero frío. Hay una extraña pesadez en el aire—digo pesadez por falta de palabra mejor; quiero decir que nos oprime a ambos. Hace mucho frío, y solo nuestras pieles cálidas nos mantienen cómodos. Al amanecer Van Helsing me hipnotizó; dice que respondí \"oscuridad, madera que cruje y agua que ruge\", así que el río está cambiando según avanzan. Espero mucho que mi amor no corra más peligro de lo necesario; pero estamos en manos de Dios."
        },
        {
          "en": "2 November, night.—All day long driving. The country gets wilder as we go, and the great spurs of the Carpathians, which at Veresti seemed so far from us and so low on the horizon, now seem to gather round us and tower in front. We both seem in good spirits; I think we make an effort each to cheer the other; in the doing so we cheer ourselves. Dr. Van Helsing says that by morning we shall reach the Borgo Pass. The houses are very few here now, and the Professor says that the last horse we got will have to go on with us, as we may not be able to change. He got two in addition to the two we changed, so that now we have a rude four-in-hand. The dear horses are patient and good, and they give us no trouble. We are not worried with other travellers, and so even I can drive. We shall get to the Pass in daylight; we do not want to arrive before. So we take it easy, and have each a long rest in turn. Oh, what will to-morrow bring to us? We go to seek the place where my poor darling suffered so much. God grant that we may be guided aright, and that He will deign to watch over my husband and those dear to us both, and who are in such deadly peril. As for me, I am not worthy in His sight. Alas! I am unclean to His eyes, and shall be until He may deign to let me stand forth in His sight as one of those who have not incurred His wrath.",
          "es": "2 de noviembre, noche.—Todo el día conduciendo. El país se vuelve más salvaje conforme avanzamos, y los grandes espolones de los Cárpatos, que en Veresti parecían tan lejanos y tan bajos en el horizonte, ahora parecen rodearnos y elevarse frente a nosotros. Ambos parecemos de buen ánimo; creo que cada uno hace un esfuerzo por animar al otro; al hacerlo nos animamos a nosotros mismos. El Dr. Van Helsing dice que por la mañana llegaremos al Paso de Borgo. Las casas son muy pocas aquí ahora, y el Profesor dice que el último caballo que obtuvimos tendrá que seguir con nosotros, pues es posible que no podamos cambiar. Obtuvo dos además de los dos que cambiamos, así que ahora tenemos un tosco tiro de cuatro. Los queridos caballos son pacientes y buenos, y no nos dan problemas. No nos molestan otros viajeros, así que incluso yo puedo conducir. Llegaremos al Paso durante el día; no queremos llegar antes. Así que vamos con calma, y cada uno descansa largo rato por turnos. ¡Oh, qué nos traerá mañana! Vamos a buscar el lugar donde mi pobre amor sufrió tanto. Que Dios nos guíe acertadamente, y que se digne cuidar a mi esposo y a los que nos son queridos a ambos, y que están en tanto peligro mortal. En cuanto a mí, no soy digna ante Su vista. ¡Ay! Soy impura a Sus ojos, y lo seré hasta que Él se digne permitirme estar ante Su vista como una de aquellas que no han incurrido en Su ira."
        },
        {
          "en": "Memorandum by Abraham Van Helsing.",
          "es": "Memorándum de Abraham Van Helsing."
        }
      ]
    },
    "2": {
      "lines": [
        {
          "en": "4 November.—This to my old and true friend John Seward, M. D., of Purfleet, London, in case I may not see him. It may explain. It is morning, and I write by a fire which all the night I have kept alive—Madam Mina aiding me. It is cold, cold; so cold that the grey heavy sky is full of snow, which when it falls will settle for all winter as the ground is hardening to receive it. It seems to have affected Madam Mina; she has been so heavy of head all day that she was not like herself. She sleeps, and sleeps, and sleeps! She who is usual so alert, have done literally nothing all the day; she even have lost her appetite. She make no entry into her little diary, she who write so faithful at every pause. Something whisper to me that all is not well. However, to-night she is more vif. Her long sleep all day have refresh and restore her, for now she is all sweet and bright as ever. At sunset I try to hypnotise her, but alas! with no effect; the power has grown less and less with each day, and to-night it fail me altogether. Well, God’s will be done—whatever it may be, and whithersoever it may lead!",
          "es": "4 de noviembre.—Esto para mi viejo y verdadero amigo John Seward, M. D., de Purfleet, Londres, por si acaso no pueda verlo. Puede que lo explique. Es mañana, y escribo junto a un fuego que he mantenido vivo toda la noche—con la ayuda de la Señora Mina. Hace frío, mucho frío; tan frío que el cielo gris y pesado está lleno de nieve, que cuando caiga se quedará todo el invierno pues el suelo se está endureciendo para recibirla. Parece haber afectado a la Señora Mina; ha estado tan pesada de cabeza todo el día que no parecía ella misma. ¡Duerme, y duerme, y duerme! Ella que es tan alerta, no ha hecho literalmente nada en todo el día; incluso ha perdido el apetito. No hace anotaciones en su pequeño diario, ella que escribe tan fielmente en cada pausa. Algo me susurra que algo no anda bien. Sin embargo, esta noche está más viva. Su largo sueño de todo el día la ha refrescado y restaurado, pues ahora está tan dulce y radiante como siempre. Al atardecer intento hipnotizarla, pero ¡ay! sin efecto; el poder ha disminuido cada día, y esta noche me falla completamente. Bueno, que se haga la voluntad de Dios—sea lo que fuere, y adondequiera que nos lleve."
        },
        {
          "en": "Now to the historical, for as Madam Mina write not in her stenography, I must, in my cumbrous old fashion, that so each day of us may not go unrecorded.",
          "es": "Ahora a lo histórico, pues como la Señora Mina no escribe en su taquigrafía, debo hacerlo yo, a mi torpe manera antigua, para que cada día de nosotros no quede sin registrar."
        },
        {
          "en": "We got to the Borgo Pass just after sunrise yesterday morning. When I saw the signs of the dawn I got ready for the hypnotism. We stopped our carriage, and got down so that there might be no disturbance. I made a couch with furs, and Madam Mina, lying down, yield herself as usual, but more slow and more short time than ever, to the hypnotic sleep. As before, came the answer: “darkness and the swirling of water.” Then she woke, bright and radiant and we go on our way and soon reach the Pass. At this time and place, she become all on fire with zeal; some new guiding power be in her manifested, for she point to a road and say:—",
          "es": "Llegamos al Paso de Borgo justo después del amanecer ayer por la mañana. Cuando vi las señales del alba me preparé para el hipnotismo. Detuvimos el carruaje y bajamos para no haya disturbios. Hice un lecho con pieles, y la Señora Mina, acostada, se entregó como siempre, pero más lentamente y por menos tiempo que nunca, al sueño hipnótico. Como antes, llegó la respuesta: \"oscuridad y el remolino del agua\". Luego despertó, radiante y brillante y continuamos nuestro camino y pronto llegamos al Paso. En este momento y lugar, ella se encendió completamente de celo; algún nuevo poder guía se manifestó en ella, pues señaló un camino y dijo:—"
        },
        {
          "en": "“This is the way.”",
          "es": "Este es el camino."
        },
        {
          "en": "“How know you it?” I ask.",
          "es": "\"¿Cómo lo sabes?\" pregunté."
        }
      ]
    },
    "3": {
      "lines": [
        {
          "en": "“Of course I know it,” she answer, and with a pause, add: “Have not my Jonathan travelled it and wrote of his travel?”",
          "es": "Por supuesto que lo sé,\" respondió, y con una pausa, añadió: \"¿No ha viajado mi Jonathan por él y escribió sobre su viaje?"
        },
        {
          "en": "At first I think somewhat strange, but soon I see that there be only one such by-road. It is used but little, and very different from the coach road from the Bukovina to Bistritz, which is more wide and hard, and more of use.",
          "es": "Al principio pensé que era algo extraño, pero pronto vi que solo había un camino secundario así. Se usa poco, y es muy diferente del camino de carruajes desde Bukovina a Bistritz, que es más ancho y firme, y más usado."
        },
        {
          "en": "So we came down this road; when we meet other ways—not always were we sure that they were roads at all, for they be neglect and light snow have fallen—the horses know and they only. I give rein to them, and they go on so patient. By-and-by we find all the things which Jonathan have note in that wonderful diary of him. Then we go on for long, long hours and hours. At the first, I tell Madam Mina to sleep; she try, and she succeed. She sleep all the time; till at the last, I feel myself to suspicious grow, and attempt to wake her. But she sleep on, and I may not wake her though I try. I do not wish to try too hard lest I harm her; for I know that she have suffer much, and sleep at times be all-in-all to her. I think I drowse myself, for all of sudden I feel guilt, as though I have done something; I find myself bolt up, with the reins in my hand, and the good horses go along jog, jog, just as ever. I look down and find Madam Mina still sleep. It is now not far off sunset time, and over the snow the light of the sun flow in big yellow flood, so that we throw great long shadow on where the mountain rise so steep. For we are going up, and up; and all is oh! so wild and rocky, as though it were the end of the world.",
          "es": "Así bajamos por este camino; cuando encontrábamos otros caminos—no siempre estábamos seguros de que fueran caminos, pues están descuidados y ha caído nieve ligera—los caballos los conocían y solo ellos. Les solté las riendas, y avanzan tan pacientemente. Poco a poco encontramos todas las cosas que Jonathan anotó en ese maravilloso diario de él. Luego continuamos durante largas, largas horas. Al principio, le dije a la Señora Mina que durmiera; lo intentó, y tuvo éxito. Durmió todo el tiempo; hasta que al final, me sentí cada vez más sospechoso, e intenté despertarla. Pero siguió durmiendo, y no pude despertarla aunque lo intenté. No quería intentar demasiado fuerte para no hacerle daño; pues sé que ha sufrido mucho, y el sueño a veces es todo para ella. Creo que yo también dormité, pues de repente me sentí culpable, como si hubiera hecho algo; me encuentro sentándome bruscamente, con las riendas en la mano, y los buenos caballos van avanzando al paso, al paso, como siempre. Miro hacia abajo y encuentro a la Señora Mina aún dormida. Ahora no falta mucho para el atardecer, y sobre la nieve la luz del sol fluye en una gran inundación amarilla, de modo que proyectamos grandes sombras largas donde la montaña se eleva tan empinada. Pues estamos subiendo, y subiendo; y todo es ¡oh! tan salvaje y rocoso, como si fuera el fin del mundo."
        },
        {
          "en": "Then I arouse Madam Mina. This time she wake with not much trouble, and then I try to put her to hypnotic sleep. But she sleep not, being as though I were not. Still I try and try, till all at once I find her and myself in dark; so I look round, and find that the sun have gone down. Madam Mina laugh, and I turn and look at her. She is now quite awake, and look so well as I never saw her since that night at Carfax when we first enter the Count’s house. I am amaze, and not at ease then; but she is so bright and tender and thoughtful for me that I forget all fear. I light a fire, for we have brought supply of wood with us, and she prepare food while I undo the horses and set them, tethered in shelter, to feed. Then when I return to the fire she have my supper ready. I go to help her; but she smile, and tell me that she have eat already—that she was so hungry that she would not wait. I like it not, and I have grave doubts; but I fear to affright her, and so I am silent of it. She help me and I eat alone; and then we wrap in fur and lie beside the fire, and I tell her to sleep while I watch. But presently I forget all of watching; and when I sudden remember that I watch, I find her lying quiet, but awake, and looking at me with so bright eyes. Once, twice more the same occur, and I get much sleep till before morning. When I wake I try to hypnotise her; but alas! though she shut her eyes obedient, she may not sleep. The sun rise up, and up, and up; and then sleep come to her too late, but so heavy that she will not wake. I have to lift her up, and place her sleeping in the carriage when I have harnessed the horses and made all ready. Madam still sleep, and she look in her sleep more healthy and more redder than before. And I like it not. And I am afraid, afraid, afraid!—I am afraid of all things—even to think but I must go on my way. The stake we play for is life and death, or more than these, and we must not flinch.",
          "es": "Entonces despierto a la Señora Mina. Esta vez despierta sin mucha dificultad, e intento ponerla en sueño hipnótico. Pero no duerme, como si yo no estuviera. Aún así intento e intento, hasta que de repente me encuentro a ella y a mí en la oscuridad; así que miro alrededor, y encuentro que el sol se ha puesto. La Señora Mina ríe, y me vuelvo y la miro. Ahora está completamente despierta, y se ve tan bien como nunca la he visto desde aquella noche en Carfax cuando entramos por primera vez en la casa del Conde. Estoy asombrado, y no estoy a gusto entonces; pero ella es tan radiante y tierna y atenta conmigo que olvido todo miedo. Enciendo un fuego, pues hemos traído provisión de leña, y ella prepara comida mientras yo suelto los caballos y los coloco, atados en un abrigo, para que coman. Luego cuando vuelvo al fuego tiene mi cena lista. Voy a ayudarle; pero ella sonríe, y me dice que ya ha comido—que tenía tanta hambre que no quiso esperar. No me gusta, y tengo graves dudas; pero me temo asustarlo, así que guardo silencio. Ella me ayuda e como solo; y luego nos envolvemos en pieles y nos acostamos junto al fuego, y le digo que duerma mientras yo vigilo. Pero presentemente olvido todo de vigilar; y cuando de repente recuerdo que debo vigilar, la encuentro acostada tranquila, pero despierta, y mirándome con ojos tan brillantes. Una vez, dos veces más sucede lo mismo, y duermo bastante hasta antes del amanecer. Cuando despierto intento hipnotizarla; pero ¡ay! aunque cierra los ojos obedientemente, no puede dormir. El sol sube, y sube, y sube; y entonces el sueño también le llega, pero tan profundo que no despertará. Tengo que levantarla, y colocarla durmiendo en el carruaje cuando he enjaezado los caballos y preparado todo. La Señora aún duerme, y se ve en su sueño más saludable y más roja que antes. Y no me gusta. Y tengo miedo, miedo, ¡miedo!—Tengo miedo de todas las cosas—incluso de pensar, pero debo seguir mi camino. Lo que jugamos es la vida y la muerte, o más que eso, y no debemos vacilar."
        },
        {
          "en": "5 November, morning.—Let me be accurate in everything, for though you and I have seen some strange things together, you may at the first think that I, Van Helsing, am mad—that the many horrors and the so long strain on nerves has at the last turn my brain.",
          "es": "5 de noviembre, mañana.—Déjame ser exacto en todo, pues aunque tú y yo hemos visto algunas cosas extrañas juntos, al principio puedes pensar que yo, Van Helsing, estoy loco—que los muchos horrores y la tensión tan larga en los nervios ha girado finalmente mi cerebro."
        }
      ]
    },
    "4": {
      "lines": [
        {
          "en": "All yesterday we travel, ever getting closer to the mountains, and moving into a more and more wild and desert land. There are great, frowning precipices and much falling water, and Nature seem to have held sometime her carnival. Madam Mina still sleep and sleep; and though I did have hunger and appeased it, I could not waken her—even for food. I began to fear that the fatal spell of the place was upon her, tainted as she is with that Vampire baptism. “Well,” said I to myself, “if it be that she sleep all the day, it shall also be that I do not sleep at night.” As we travel on the rough road, for a road of an ancient and imperfect kind there was, I held down my head and slept. Again I waked with a sense of guilt and of time passed, and found Madam Mina still sleeping, and the sun low down. But all was indeed changed; the frowning mountains seemed further away, and we were near the top of a steep-rising hill, on summit of which was such a castle as Jonathan tell of in his diary. At once I exulted and feared; for now, for good or ill, the end was near.",
          "es": "Todo ayer viajamos, acercándonos cada vez más a las montañas, y adentrándose en una tierra cada vez más salvaje y desolada. Hay grandes precipicios amenazadores y mucha agua que cae, y la Naturaleza parece haber tenido alguna vez su carnaval. La Señora Mina sigue durmiendo y durmiendo; y aunque tenía hambre y la saciaba, no podía despertarla—ni siquiera para comer. Comencé a temer que el hechizo fatal del lugar estaba sobre ella, manchada como está con ese bautismo de Vampiro. \"Bueno,\" me dije a mí mismo, \"si es que duerme todo el día, también será que no duerma toda la noche.\" Mientras viajábamos por el camino áspero, pues había un camino de un tipo antiguo e imperfecto, bajé la cabeza y dormí. Nuevamente desperté con un sentido de culpa y de tiempo pasado, y encontré a la Señora Mina aún durmiendo, y el sol bajo. Pero todo ciertamente había cambiado; las montañas amenazadoras parecían más lejanas, y estábamos cerca de la cima de una colina que se elevaba empinadamente, en cuya cumbre había un castillo como el que Jonathan describe en su diario. De inmediato exultaba y temía; pues ahora, para bien o para mal, el fin estaba cerca."
        },
        {
          "en": "I woke Madam Mina, and again tried to hypnotise her; but alas! unavailing till too late. Then, ere the great dark came upon us—for even after down-sun the heavens reflected the gone sun on the snow, and all was for a time in a great twilight—I took out the horses and fed them in what shelter I could. Then I make a fire; and near it I make Madam Mina, now awake and more charming than ever, sit comfortable amid her rugs. I got ready food: but she would not eat, simply saying that she had not hunger. I did not press her, knowing her unavailingness. But I myself eat, for I must needs now be strong for all. Then, with the fear on me of what might be, I drew a ring so big for her comfort, round where Madam Mina sat; and over the ring I passed some of the wafer, and I broke it fine so that all was well guarded. She sat still all the time—so still as one dead; and she grew whiter and ever whiter till the snow was not more pale; and no word she said. But when I drew near, she clung to me, and I could know that the poor soul shook her from head to feet with a tremor that was pain to feel. I said to her presently, when she had grown more quiet:—",
          "es": "Desperté a la Señora Mina, e intenté de nuevo hipnotizarla; pero ¡ay! infructuosamente hasta demasiado tarde. Luego, antes de que cayera la gran oscuridad sobre nosotros—pues incluso después de la puesta del sol los cielos reflejaban el sol desaparecido en la nieve, y todo estaba por un tiempo en un crepúsculo muy grande—saqué los caballos y los alimenté en todo el abrigo que pude. Luego enciendo un fuego; y cerca de él coloco a la Señora Mina, ahora despierta y más encantadora que nunca, sentada cómodamente entre sus mantas. Preparé comida: pero no quiso comer, simplemente diciendo que no tenía hambre. No insistí, conociendo su ineficacia. Pero yo comí, pues ahora debo ser fuerte para todo. Luego, con el miedo de lo que podría ser, tracé un círculo tan grande para su comodidad, alrededor de donde se sentaba la Señora Mina; y sobre el círculo pasé algo de la hostia, y la rompí finamente para que todo estuviera bien protegido. Se quedó completamente quieta todo el tiempo—tan quieta como un muerto; y se puso cada vez más blanca hasta que la nieve no era más pálida; y ninguna palabra dijo. Pero cuando me acerqué, se aferró a mí, y pude ver que la pobre alma temblaba de pies a cabeza con un temblor que era doloroso de sentir. Le dije presentemente, cuando se había calmado más:—"
        },
        {
          "en": "“Will you not come over to the fire?” for I wished to make a test of what she could. She rose obedient, but when she have made a step she stopped, and stood as one stricken.",
          "es": "\"¿No quieres acercarte al fuego?\" pues deseaba hacer una prueba de lo que podía. Se levantó obediente, pero cuando dio un paso se detuvo, y se quedó como si fuera golpeada."
        },
        {
          "en": "“Why not go on?” I asked. She shook her head, and, coming back, sat down in her place. Then, looking at me with open eyes, as of one waked from sleep, she said simply:—",
          "es": "\"¿Por qué no continúas?\" pregunté. Negó con la cabeza, y volviendo, se sentó en su lugar. Luego, mirándome con los ojos abiertos, como quien despierta del sueño, dijo simplemente:—"
        },
        {
          "en": "“I cannot!” and remained silent. I rejoiced, for I knew that what she could not, none of those that we dreaded could. Though there might be danger to her body, yet her soul was safe!",
          "es": "\"¡No puedo!\" y guardó silencio. Me alegré, pues sé que lo que ella no podía hacer, ninguno de aquellos que temíamos podía. Aunque podría haber peligro para su cuerpo, ¡su alma estaba segura!"
        }
      ]
    },
    "5": {
      "lines": [
        {
          "en": "Presently the horses began to scream, and tore at their tethers till I came to them and quieted them. When they did feel my hands on them, they whinnied low as in joy, and licked at my hands and were quiet for a time. Many times through the night did I come to them, till it arrive to the cold hour when all nature is at lowest; and every time my coming was with quiet of them. In the cold hour the fire began to die, and I was about stepping forth to replenish it, for now the snow came in flying sweeps and with it a chill mist. Even in the dark there was a light of some kind, as there ever is over snow; and it seemed as though the snow-flurries and the wreaths of mist took shape as of women with trailing garments. All was in dead, grim silence only that the horses whinnied and cowered, as if in terror of the worst. I began to fear—horrible fears; but then came to me the sense of safety in that ring wherein I stood. I began, too, to think that my imaginings were of the night, and the gloom, and the unrest that I have gone through, and all the terrible anxiety. It was as though my memories of all Jonathan’s horrid experience were befooling me; for the snow flakes and the mist began to wheel and circle round, till I could get as though a shadowy glimpse of those women that would have kissed him. And then the horses cowered lower and lower, and moaned in terror as men do in pain. Even the madness of fright was not to them, so that they could break away. I feared for my dear Madam Mina when these weird figures drew near and circled round. I looked at her, but she sat calm, and smiled at me; when I would have stepped to the fire to replenish it, she caught me and held me back, and whispered, like a voice that one hears in a dream, so low it was:—",
          "es": "Presentemente los caballos comenzaron a gritar, y tiraban de sus ataduras hasta que llegué a ellos y los calmé. Cuando sintieron mis manos sobre ellos, relincharon bajo como en alegría, y lamieron mis manos y estuvieron quietos por un tiempo. Muchas veces durante la noche llegué a ellos, hasta que llegó la hora fría cuando toda la naturaleza está en su punto más bajo; y cada vez mi llegada fue con su calma. En la hora fría el fuego comenzó a apagarse, e iba a salir para reponerlo, pues ahora la nieve caía en ráfagas voladoras y con ella una niebla fría. Incluso en la oscuridad había una luz de algún tipo, como siempre la hay sobre la nieve; y parecía como si los copos de nieve y las volutas de niebla tomaran forma como mujeres con prendas largas. Todo estaba en silencio grim y muerto, excepto que los caballos relinchaban y se encogían, como si tuvieran terror de lo peor. Comencé a temer—miedos horribles; pero luego vino a mí la sensación de seguridad en ese círculo en el que estaba. Comencé también a pensar que mis imaginaciones eran de la noche, la penumbra, y la intranquilidad por la que he pasado, y toda la ansiedad terrible. Era como si mis recuerdos de toda la experiencia horrible de Jonathan me estuvieran engañando; pues los copos de nieve y la niebla comenzaron a girar y circular alrededor, hasta que podía ver como un atisbo sombrío de aquellas mujeres que lo hubieran besado. Y luego los caballos se encogían cada vez más, y gemían de terror como hombres en dolor. Ni siquiera la locura del miedo les permitía escapar. Tenía miedo por mi querida Señora Mina cuando estas figuras extrañas se acercaron y circularon alrededor. Miré hacia ella, pero estaba tranquila, y sonrió hacia mí; cuando hubiera querido ir al fuego para reponerlo, me agarró y me sujetó, y susurró, como una voz que uno escucha en un sueño, tan bajo que:—"
        },
        {
          "en": "“No! No! Do not go without. Here you are safe!” I turned to her, and looking in her eyes, said:—",
          "es": "\"¡No! ¡No! ¡No vayas fuera! ¡Aquí estás seguro!\" Me volví hacia ella, y mirándola a los ojos, dije:—"
        },
        {
          "en": "“But you? It is for you that I fear!” whereat she laughed—a laugh, low and unreal, and said:—",
          "es": "\"¿Pero tú? ¡Es por ti que tengo miedo!\" ante lo cual rió—una risa baja e irreal, y dijo:—"
        },
        {
          "en": "“Fear for me! Why fear for me? None safer in all the world from them than I am,” and as I wondered at the meaning of her words, a puff of wind made the flame leap up, and I see the red scar on her forehead. Then, alas! I knew. Did I not, I would soon have learned, for the wheeling figures of mist and snow came closer, but keeping ever without the Holy circle. Then they began to materialise till—if God have not take away my reason, for I saw it through my eyes—there were before me in actual flesh the same three women that Jonathan saw in the room, when they would have kissed his throat. I knew the swaying round forms, the bright hard eyes, the white teeth, the ruddy colour, the voluptuous lips. They smiled ever at poor dear Madam Mina; and as their laugh came through the silence of the night, they twined their arms and pointed to her, and said in those so sweet tingling tones that Jonathan said were of the intolerable sweetness of the water-glasses:—",
          "es": "\"¿Miedo por mí? ¿Por qué tener miedo por mí? Nadie está más seguro en todo el mundo de ellos que yo,\" y mientras me preguntaba por el significado de sus palabras, una ráfaga de viento hizo que la llama saltara, y vi la cicatriz roja en su frente. Entonces, ¡ay! lo supe. Si no lo hubiera hecho, pronto habría aprendido, pues las figuras circulantes de niebla y nieve se acercaron, pero manteniéndose siempre fuera del círculo sagrado. Luego comenzaron a materializarse hasta que—si Dios no hubiera quitado mi razón, pues lo vi con mis ojos—había ante mí en carne real las mismas tres mujeres que Jonathan vio en la habitación, cuando lo hubieran besado en la garganta. Conocía las formas que se balanceaban, los ojos brillantes y duros, los dientes blancos, el color rubicundo, los labios voluptuosos. Sonreían constantemente a la pobre querida Señora Mina; y mientras su risa atravesaba el silencio de la noche, entrelazaban sus brazos y señalaban hacia ella, y decían en esos tonos tan dulces y vibrantes que Jonathan dijo eran de la dulzura intolerable de las copas de agua:—"
        },
        {
          "en": "“Come, sister. Come to us. Come! Come!” In fear I turned to my poor Madam Mina, and my heart with gladness leapt like flame; for oh! the terror in her sweet eyes, the repulsion, the horror, told a story to my heart that was all of hope. God be thanked she was not, yet, of them. I seized some of the firewood which was by me, and holding out some of the Wafer, advanced on them towards the fire. They drew back before me, and laughed their low horrid laugh. I fed the fire, and feared them not; for I knew that we were safe within our protections. They could not approach, me, whilst so armed, nor Madam Mina whilst she remained within the ring, which she could not leave no more than they could enter. The horses had ceased to moan, and lay still on the ground; the snow fell on them softly, and they grew whiter. I knew that there was for the poor beasts no more of terror.",
          "es": "\"Ven, hermana. Ven con nosotras. ¡Ven! ¡Ven!\" En miedo me volví hacia mi pobre Señora Mina, y mi corazón saltó con alegría como una llama; pues ¡oh! el terror en sus dulces ojos, la repulsión, el horror, contaban una historia a mi corazón que era toda esperanza. Gracias a Dios aún no era una de ellas. Tomé algo de la leña que estaba junto a mí, y sosteniendo algo de la Hostia, avancé hacia ellas hacia el fuego. Se retiraron ante mí, e rieron su risa baja y horrible. Alimenté el fuego, y no les temí; pues sabía que estábamos a salvo dentro de nuestras protecciones. No podían acercarse a mí mientras estuviera así armado, ni a la Señora Mina mientras permaneciera dentro del círculo, que no podía abandonar más de lo que ellas podían entrar. Los caballos habían dejado de gemir, y yacían quietos en el suelo; la nieve caía sobre ellos suavemente, y se volvieron más blancos. Sabía que para los pobres animales no había más terror."
        }
      ]
    },
    "6": {
      "lines": [
        {
          "en": "And so we remained till the red of the dawn to fall through the snow-gloom. I was desolate and afraid, and full of woe and terror; but when that beautiful sun began to climb the horizon life was to me again. At the first coming of the dawn the horrid figures melted in the whirling mist and snow; the wreaths of transparent gloom moved away towards the castle, and were lost.",
          "es": "Y así permanecimos hasta que el rojo del amanecer cayó a través de la penumbra de nieve. Estaba desolado y asustado, y lleno de pena y terror; pero cuando ese hermoso sol comenzó a trepar por el horizonte la vida volvió a mí. Al primer llegar del amanecer las figuras horribles se disolvieron en la niebla y la nieve circulantes; las volutas de penumbra transparente se movieron hacia el castillo, y se perdieron."
        },
        {
          "en": "Instinctively, with the dawn coming, I turned to Madam Mina, intending to hypnotise her; but she lay in a deep and sudden sleep, from which I could not wake her. I tried to hypnotise through her sleep, but she made no response, none at all; and the day broke. I fear yet to stir. I have made my fire and have seen the horses, they are all dead. To-day I have much to do here, and I keep waiting till the sun is up high; for there may be places where I must go, where that sunlight, though snow and mist obscure it, will be to me a safety.",
          "es": "Instintivamente, con la llegada del amanecer, me volví hacia la Señora Mina, con la intención de hipnotizarla; pero yacía en un sueño profundo y repentino, del cual no podía despertarla. Intenté hipnotizarla a través de su sueño, pero no dio respuesta, ninguna en absoluto; y amanció. Aún temo moverme. He encendido mi fuego y he visto los caballos, todos están muertos. Hoy tengo mucho que hacer aquí, y espero hasta que el sol esté alto; pues puede haber lugares donde deba ir, donde esa luz solar, aunque la nieve y la niebla la oscurezcan, será para mí una seguridad."
        },
        {
          "en": "I will strengthen me with breakfast, and then I will to my terrible work. Madam Mina still sleeps; and, God be thanked! she is calm in her sleep....",
          "es": "Me fortaleceré con el desayuno, y luego me iré a mi trabajo terrible. La Señora Mina aún duerme; y ¡gracias a Dios! está tranquila en su sueño...."
        },
        {
          "en": "Jonathan Harker’s Journal.",
          "es": "Diario de Jonathan Harker."
        },
        {
          "en": "4 November, evening.—The accident to the launch has been a terrible thing for us. Only for it we should have overtaken the boat long ago; and by now my dear Mina would have been free. I fear to think of her, off on the wolds near that horrid place. We have got horses, and we follow on the track. I note this whilst Godalming is getting ready. We have our arms. The Szgany must look out if they mean fight. Oh, if only Morris and Seward were with us. We must only hope! If I write no more Good-bye, Mina! God bless and keep you.",
          "es": "4 de noviembre, atardecer.—El accidente del bote ha sido algo terrible para nosotros. Solo por eso habríamos alcanzado el barco hace mucho tiempo; y para ahora mi querida Mina habría sido libre. Me da miedo pensar en ella, lejos en los páramos cerca de ese lugar horrible. Hemos conseguido caballos, y seguimos el rastro. Anoto esto mientras Godalming se prepara. Tenemos nuestras armas. Los Szgany mejor que tengan cuidado si quieren pelear. ¡Oh, si solo Morris y Seward estuvieran con nosotros! ¡Debemos solo esperar! Si no escribo más, ¡adiós, Mina! Que Dios te bendiga y te proteja."
        }
      ]
    },
    "7": {
      "lines": [
        {
          "en": "Dr. Seward’s Diary.",
          "es": "Diario del Dr. Seward."
        },
        {
          "en": "5 November.—With the dawn we saw the body of Szgany before us dashing away from the river with their leiter-wagon. They surrounded it in a cluster, and hurried along as though beset. The snow is falling lightly and there is a strange excitement in the air. It may be our own feelings, but the depression is strange. Far off I hear the howling of wolves; the snow brings them down from the mountains, and there are dangers to all of us, and from all sides. The horses are nearly ready, and we are soon off. We ride to death of some one. God alone knows who, or where, or what, or when, or how it may be....",
          "es": "5 de noviembre.—Con el amanecer vimos a los Szgany delante de nosotros corriendo desde el río con su carro. Los rodeaban en un grupo, y se apresuraban como si estuvieran acosados. La nieve cae ligeramente y hay una extraña emoción en el aire. Puede ser nuestros propios sentimientos, pero la depresión es extraña. A lo lejos escucho los aullidos de los lobos; la nieve los trae de las montañas, y hay peligros para todos nosotros, y de todos los lados. Los caballos están casi listos, y pronto nos vamos. Cabalgamos hacia la muerte de alguien. Solo Dios sabe quién, dónde, qué, cuándo o cómo será...."
        },
        {
          "en": "Dr. Van Helsing’s Memorandum.",
          "es": "Memorándum del Dr. Van Helsing."
        },
        {
          "en": "5 November, afternoon.—I am at least sane. Thank God for that mercy at all events, though the proving it has been dreadful. When I left Madam Mina sleeping within the Holy circle, I took my way to the castle. The blacksmith hammer which I took in the carriage from Veresti was useful; though the doors were all open I broke them off the rusty hinges, lest some ill-intent or ill-chance should close them, so that being entered I might not get out. Jonathan’s bitter experience served me here. By memory of his diary I found my way to the old chapel, for I knew that here my work lay. The air was oppressive; it seemed as if there was some sulphurous fume, which at times made me dizzy. Either there was a roaring in my ears or I heard afar off the howl of wolves. Then I bethought me of my dear Madam Mina, and I was in terrible plight. The dilemma had me between his horns.",
          "es": "5 de noviembre, tarde.—Al menos estoy cuerdo. Gracias a Dios por esa misericordia en todo caso, aunque probarlo ha sido terrible. Cuando dejé a la Señora Mina durmiendo dentro del círculo sagrado, me dirigí al castillo. El martillo de herrero que tomé en el carruaje de Veresti fue útil; aunque todas las puertas estaban abiertas las rompí de las bisagras oxidadas, para que alguna intención o azar malo no las cerrara, así que una vez adentro pudiera salir. La experiencia amarga de Jonathan me sirvió aquí. Por el recuerdo de su diario encontré mi camino a la capilla vieja, pues sabía que allí estaba mi trabajo. El aire era opresivo; parecía como si hubiera algún vapor sulfuroso, que a veces me mareo. O había un rugido en mis oídos o escuchaba a lo lejos el aullido de los lobos. Luego pensé en mi querida Señora Mina, y estaba en terrible apuro. El dilema me tenía entre sus cuernos."
        },
        {
          "en": "Her, I had not dare to take into this place, but left safe from the Vampire in that Holy circle; and yet even there would be the wolf! I resolve me that my work lay here, and that as to the wolves we must submit, if it were God’s will. At any rate it was only death and freedom beyond. So did I choose for her. Had it but been for myself the choice had been easy, the maw of the wolf were better to rest in than the grave of the Vampire! So I make my choice to go on with my work.",
          "es": "A ella, no me atrevía llevarla a este lugar, pero la dejé segura del Vampiro en ese círculo sagrado; y sin embargo incluso allí habría lobos. Me resolví que mi trabajo estaba aquí, y en cuanto a los lobos debemos someternos, si es la voluntad de Dios. En todo caso era solo la muerte y la libertad más allá. Así que elegí por ella. Si hubiera sido por mí la elección hubiera sido fácil, ¡las fauces del lobo eran mejor descanso que la tumba del Vampiro! Así que hago mi elección de continuar con mi trabajo."
        }
      ]
    },
    "8": {
      "lines": [
        {
          "en": "I knew that there were at least three graves to find—graves that are inhabit; so I search, and search, and I find one of them. She lay in her Vampire sleep, so full of life and voluptuous beauty that I shudder as though I have come to do murder. Ah, I doubt not that in old time, when such things were, many a man who set forth to do such a task as mine, found at the last his heart fail him, and then his nerve. So he delay, and delay, and delay, till the mere beauty and the fascination of the wanton Un-Dead have hypnotise him; and he remain on and on, till sunset come, and the Vampire sleep be over. Then the beautiful eyes of the fair woman open and look love, and the voluptuous mouth present to a kiss—and man is weak. And there remain one more victim in the Vampire fold; one more to swell the grim and grisly ranks of the Un-Dead!...",
          "es": "Sabía que había al menos tres tumbas que encontrar—tumbas que están habitadas; así que busco, y busco, y encuentro una de ellas. Yacía en su sueño de Vampiro, tan llena de vida y belleza voluptuosa que me estremezco como si hubiera venido a cometer un asesinato. Ah, no dudo que en tiempos antiguos, cuando tales cosas eran, muchos hombres que se propusieron hacer tal tarea como la mía, encontraron al fin su corazón fallar, y luego sus nervios. Así que demoran, y demoran, y demoran, hasta que la mera belleza y la fascinación de la voluptuosa No-Muerta lo hipnotiza; y permanece y permanece, hasta que llega el atardecer, y el sueño del Vampiro termina. Luego los hermosos ojos de la mujer justa se abren y miran con amor, y la boca voluptuosa se ofrece a un beso—y el hombre es débil. Y hay una víctima más en el redil del Vampiro; ¡una más para aumentar las filas grim y horribles de los No-Muertos!..."
        },
        {
          "en": "There is some fascination, surely, when I am moved by the mere presence of such an one, even lying as she lay in a tomb fretted with age and heavy with the dust of centuries, though there be that horrid odour such as the lairs of the Count have had. Yes, I was moved—I, Van Helsing, with all my purpose and with my motive for hate—I was moved to a yearning for delay which seemed to paralyse my faculties and to clog my very soul. It may have been that the need of natural sleep, and the strange oppression of the air were beginning to overcome me. Certain it was that I was lapsing into sleep, the open-eyed sleep of one who yields to a sweet fascination, when there came through the snow-stilled air a long, low wail, so full of woe and pity that it woke me like the sound of a clarion. For it was the voice of my dear Madam Mina that I heard.",
          "es": "Hay cierta fascinación, seguramente, cuando estoy movido por la mera presencia de tal uno, incluso acostado como yacía en una tumba corroída por la edad y pesada con el polvo de los siglos, aunque hay ese olor horrible como el de las guaridas del Conde. Sí, estaba movido—yo, Van Helsing, con todo mi propósito y con mi motivo de odio—estaba movido a un anhelo de demora que parecía paralizar mis facultades y obstruir mi misma alma. Puede ser que la necesidad del sueño natural, y la extraña opresión del aire comenzaran a vencerme. Cierto era que estaba cayendo en sueño, el sueño de ojos abiertos de quien se entrega a una dulce fascinación, cuando llegó a través del aire silenciado por la nieve un gemido largo y bajo, tan lleno de pena y compasión que me despertó como el sonido de una clarín. Pues era la voz de mi querida Señora Mina que escuché."
        },
        {
          "en": "Then I braced myself again to my horrid task, and found by wrenching away tomb-tops one other of the sisters, the other dark one. I dared not pause to look on her as I had on her sister, lest once more I should begin to be enthrall; but I go on searching until, presently, I find in a high great tomb as if made to one much beloved that other fair sister which, like Jonathan I had seen to gather herself out of the atoms of the mist. She was so fair to look on, so radiantly beautiful, so exquisitely voluptuous, that the very instinct of man in me, which calls some of my sex to love and to protect one of hers, made my head whirl with new emotion. But God be thanked, that soul-wail of my dear Madam Mina had not died out of my ears; and, before the spell could be wrought further upon me, I had nerved myself to my wild work. By this time I had searched all the tombs in the chapel, so far as I could tell; and as there had been only three of these Un-Dead phantoms around us in the night, I took it that there were no more of active Un-Dead existent. There was one great tomb more lordly than all the rest; huge it was, and nobly proportioned. On it was but one word",
          "es": "Luego me armé nuevamente para mi horrible tarea, y encontré arrancando las tapas de las tumbas a otra de las hermanas, la otra oscura. No me atrevía a detenerme para mirar la como lo había hecho en su hermana, para que una vez más no comenzara a ser seducido; pero continúo buscando hasta que, presentemente, encuentro en una tumba alta y grande como si fuera hecha para alguien muy amado esa otra hermana justa que, como Jonathan había visto reunirse de los átomos de la niebla. Era tan justa de mirar, tan radiante y hermosa, tan exquisitamente voluptuosa, que el mismo instinto del hombre en mí, que llama a algunos de mi sexo a amar y proteger a una de los suyos, hizo que mi cabeza diera vueltas con emoción nueva. Pero Dios sea loado, ese gemido del alma de mi querida Señora Mina no se había desvanecido de mis oídos; y antes de que el hechizo pudiera ser obrado más sobre mí, me había armado de valor para mi trabajo salvaje. Para este momento había buscado en todas las tumbas de la capilla, hasta donde podía saber; y como solo había habido tres de estos fantasmas No-Muertos alrededor de nosotros en la noche, tomé que no había más No-Muertos activos existentes. Había una tumba más grande y más señorial que todas las demás; enorme era, y noblemente proporcionada. En ella estaba una sola palabra"
        },
        {
          "en": "DRACULA.",
          "es": "DRÁCULA."
        },
        {
          "en": "This then was the Un-Dead home of the King-Vampire, to whom so many more were due. Its emptiness spoke eloquent to make certain what I knew. Before I began to restore these women to their dead selves through my awful work, I laid in Dracula’s tomb some of the Wafer, and so banished him from it, Un-Dead, for ever.",
          "es": "Este entonces era el hogar No-Muerto del Rey-Vampiro, a quien tantos más debían. Su vacuidad hablaba elocuentemente para hacer cierto lo que sabía. Antes de comenzar a restaurar a estas mujeres a sus muertas a través de mi trabajo horrible, coloqué en la tumba de Drácula algo de la Hostia, y así lo destierre No-Muerto de ella, para siempre."
        }
      ]
    },
    "9": {
      "lines": [
        {
          "en": "Then began my terrible task, and I dreaded it. Had it been but one, it had been easy, comparative. But three! To begin twice more after I had been through a deed of horror; for if it was terrible with the sweet Miss Lucy, what would it not be with these strange ones who had survived through centuries, and who had been strengthened by the passing of the years; who would, if they could, have fought for their foul lives....",
          "es": "Luego comenzó mi tarea terrible, y la temía. Si hubiera sido solo una, hubiera sido fácil, comparativamente. ¡Pero tres! Comenzar dos veces más después de haber pasado por un acto de horror; pues si fue terrible con la dulce Señorita Lucy, ¿qué no sería con estas extrañas que habían sobrevivido a través de siglos, y que habían sido fortalecidas por el paso de los años; que hubieran, si pudieran, peleado por sus vidas asquerosas...."
        },
        {
          "en": "Oh, my friend John, but it was butcher work; had I not been nerved by thoughts of other dead, and of the living over whom hung such a pall of fear, I could not have gone on. I tremble and tremble even yet, though till all was over, God be thanked, my nerve did stand. Had I not seen the repose in the first place, and the gladness that stole over it just ere the final dissolution came, as realisation that the soul had been won, I could not have gone further with my butchery. I could not have endured the horrid screeching as the stake drove home; the plunging of writhing form, and lips of bloody foam. I should have fled in terror and left my work undone. But it is over! And the poor souls, I can pity them now and weep, as I think of them placid each in her full sleep of death for a short moment ere fading. For, friend John, hardly had my knife severed the head of each, before the whole body began to melt away and crumble in to its native dust, as though the death that should have come centuries agone had at last assert himself and say at once and loud “I am here!”",
          "es": "Oh, mi amigo John, pero fue un trabajo de carnicería; si no hubiera sido armado por pensamientos de otros muertos, y de los vivos sobre los que pendía tal pall de miedo, no hubiera podido continuar. Tiemblo y tiemblo incluso ahora, aunque hasta que todo terminó, Dios sea loado, mi nervio se mantuvo. Si no hubiera visto el reposo en el primer lugar, y la alegría que se apoderó de él justo antes de la disolución final, como realización de que el alma había sido ganada, no hubiera podido continuar con mi carnicería. No hubiera podido soportar los aullidos horribles mientras la estaca se hundía; el hundimiento de forma contorsionada, y labios de espuma sangrienta. Hubiera huido en terror y dejado mi trabajo sin terminar. ¡Pero está terminado! Y las pobres almas, ahora puedo compadecerlas y llorar, mientras pienso en ellas placidas cada una en su sueño completo de muerte por un breve momento antes de desvanecerse. Pues, amigo John, apenas mi cuchillo había separado la cabeza de cada una, antes de que el cuerpo completo comenzara a desvanecerse y convertirse en su polvo nativo, como si la muerte que debería haber llegado hace siglos finalmente se afirmara a sí misma y dijera fuerte y claro \"¡Aquí estoy!\""
        },
        {
          "en": "Before I left the castle I so fixed its entrances that never more can the Count enter there Un-Dead.",
          "es": "Antes de que dejara el castillo así aseguré sus entradas para que nunca más el Conde pueda entrar No-Muerto."
        },
        {
          "en": "When I stepped into the circle where Madam Mina slept, she woke from her sleep, and, seeing, me, cried out in pain that I had endured too much.",
          "es": "Cuando entré en el círculo donde dormía la Señora Mina, despertó de su sueño, y viéndome, gritó de dolor que había sufrido demasiado."
        },
        {
          "en": "“Come!” she said, “come away from this awful place! Let us go to meet my husband who is, I know, coming towards us.” She was looking thin and pale and weak; but her eyes were pure and glowed with fervour. I was glad to see her paleness and her illness, for my mind was full of the fresh horror of that ruddy vampire sleep.",
          "es": "\"¡Ven!\" dijo, \"¡ven lejos de este lugar horrible! ¡Déjanos ir a encontrar a mi esposo que, sé, viene hacia nosotros.\" Se veía delgada y pálida y débil; pero sus ojos eran puros y brillaban con fervor. Me alegró ver su palidez y su enfermedad, pues mi mente estaba llena del horror fresco del sueño de vampiro rubicundo."
        }
      ]
    },
    "10": {
      "lines": [
        {
          "en": "And so with trust and hope, and yet full of fear, we go eastward to meet our friends—and him—whom Madam Mina tell me that she know are coming to meet us.",
          "es": "Y así con confianza y esperanza, y sin embargo lleno de miedo, vamos hacia el este a encontrar a nuestros amigos—y a él—a quien la Señora Mina me dice que sabe que vienen a encontrarnos."
        },
        {
          "en": "Mina Harker’s Journal.",
          "es": "Diario de Mina Harker."
        },
        {
          "en": "6 November.—It was late in the afternoon when the Professor and I took our way towards the east whence I knew Jonathan was coming. We did not go fast, though the way was steeply downhill, for we had to take heavy rugs and wraps with us; we dared not face the possibility of being left without warmth in the cold and the snow. We had to take some of our provisions, too, for we were in a perfect desolation, and, so far as we could see through the snowfall, there was not even the sign of habitation. When we had gone about a mile, I was tired with the heavy walking and sat down to rest. Then we looked back and saw where the clear line of Dracula’s castle cut the sky; for we were so deep under the hill whereon it was set that the angle of perspective of the Carpathian mountains was far below it. We saw it in all its grandeur, perched a thousand feet on the summit of a sheer precipice, and with seemingly a great gap between it and the steep of the adjacent mountain on any side. There was something wild and uncanny about the place. We could hear the distant howling of wolves. They were far off, but the sound, even though coming muffled through the deadening snowfall, was full of terror. I knew from the way Dr. Van Helsing was searching about that he was trying to seek some strategic point, where we would be less exposed in case of attack. The rough roadway still led downwards; we could trace it through the drifted snow.",
          "es": "6 de noviembre.—Era tarde en la tarde cuando el Profesor y yo nos dirigimos hacia el este de donde sabía que venía Jonathan. No fuimos rápido, aunque el camino era empinadamente cuesta abajo, pues tuvimos que llevar mantas y envoltorios pesados; no nos atrevimos a enfrentar la posibilidad de quedarnos sin calor en el frío y la nieve. También tuvimos que llevar algunas de nuestras provisiones, pues estábamos en una desolación perfecta, y, hasta donde podíamos ver a través de la caída de nieve, no había ni siquiera la señal de habitación. Cuando habíamos caminado aproximadamente una milla, estaba cansada del caminar pesado y me senté a descansar. Luego miramos hacia atrás y vimos dónde la línea clara del castillo de Drácula cortaba el cielo; pues estábamos tan profundos bajo la colina sobre la que se encontraba que el ángulo de perspectiva de las montañas Cárpatos estaba muy por debajo de ella. La vimos en toda su grandeza, posada a mil pies en la cumbre de un precipicio desnudo, y con aparentemente una gran brecha entre ella y la pendiente empinada de la montaña adyacente de cualquier lado. Había algo salvaje e inquietante sobre el lugar. Podíamos escuchar los aullidos distantes de los lobos. Estaban lejos, pero el sonido, aunque venía apagado a través de la caída de nieve amortiguadora, estaba lleno de terror. Sabía por la forma en que el Dr. Van Helsing estaba buscando que intentaba encontrar algún punto estratégico, donde estaríamos menos expuestos en caso de ataque. El camino áspero aún conducía hacia abajo; podíamos trazarlo a través de la nieve apilada."
        },
        {
          "en": "In a little while the Professor signalled to me, so I got up and joined him. He had found a wonderful spot, a sort of natural hollow in a rock, with an entrance like a doorway between two boulders. He took me by the hand and drew me in: “See!” he said, “here you will be in shelter; and if the wolves do come I can meet them one by one.” He brought in our furs, and made a snug nest for me, and got out some provisions and forced them upon me. But I could not eat; to even try to do so was repulsive to me, and, much as I would have liked to please him, I could not bring myself to the attempt. He looked very sad, but did not reproach me. Taking his field-glasses from the case, he stood on the top of the rock, and began to search the horizon. Suddenly he called out:—",
          "es": "En poco tiempo el Profesor me hizo señales, así que me levanté y me uní a él. Había encontrado un lugar maravilloso, una especie de hueco natural en una roca, con una entrada como una puerta entre dos peñascos. Me tomó de la mano y me jaló adentro: \"¡Mira!\" dijo, \"aquí estarás en abrigo; y si los lobos vienen puedo encontrarlos uno por uno.\" Llevó dentro nuestras pieles, e hizo un nido acogedor para mí, e sacó algunas provisiones y me las obligó a tomar. Pero no podía comer; incluso intentar hacerlo me era repugnante, y, tanto como hubiera querido complacerlo, no pude hacerme intentar. Se veía muy triste, pero no me reprochó. Sacando sus binoculares del estuche, se paró en la cima de la roca, y comenzó a buscar el horizonte. De repente gritó:—"
        },
        {
          "en": "“Look! Madam Mina, look! look!” I sprang up and stood beside him on the rock; he handed me his glasses and pointed. The snow was now falling more heavily, and swirled about fiercely, for a high wind was beginning to blow. However, there were times when there were pauses between the snow flurries and I could see a long way round. From the height where we were it was possible to see a great distance; and far off, beyond the white waste of snow, I could see the river lying like a black ribbon in kinks and curls as it wound its way. Straight in front of us and not far off—in fact, so near that I wondered we had not noticed before—came a group of mounted men hurrying along. In the midst of them was a cart, a long leiter-wagon which swept from side to side, like a dog’s tail wagging, with each stern inequality of the road. Outlined against the snow as they were, I could see from the men’s clothes that they were peasants or gypsies of some kind.",
          "es": "\"¡Mira! Señora Mina, ¡mira! ¡mira!\" Salté y me paré junto a él en la roca; me pasó sus binoculares y señaló. La nieve ahora caía más pesadamente, y se arremolinaba ferozmente, pues estaba comenzando a soplar un viento fuerte. Sin embargo, había momentos cuando había pausas entre las ráfagas de nieve y podía ver una larga distancia. Desde la altura donde estábamos era posible ver una gran distancia; y a lo lejos, más allá de la desolación blanca de nieve, podía ver el río yaciendo como una cinta negra en bucles y ondas mientras se abría camino. Directamente frente a nosotros y no muy lejos—de hecho, tan cerca que me preguntaba no habíamos notado antes—llegó un grupo de hombres a caballo apresurándose. En medio de ellos había un carro, un largo carro-lecho que se balanceaba de lado a lado, como la cola de un perro moviendo, con cada desigualdad áspera del camino. Perfilados contra la nieve como estaban, podía ver por la ropa de los hombres que eran campesinos o gitanos de algún tipo."
        }
      ]
    },
    "11": {
      "lines": [
        {
          "en": "On the cart was a great square chest. My heart leaped as I saw it, for I felt that the end was coming. The evening was now drawing close, and well I knew that at sunset the Thing, which was till then imprisoned there, would take new freedom and could in any of many forms elude all pursuit. In fear I turned to the Professor; to my consternation, however, he was not there. An instant later, I saw him below me. Round the rock he had drawn a circle, such as we had found shelter in last night. When he had completed it he stood beside me again, saying:—",
          "es": "En el carro había un gran cofre cuadrado. Mi corazón saltó al verlo, pues sentía que el fin venía. La tarde ahora se acercaba, y bien sabía que al atardecer la Cosa, que hasta entonces estaba encarcelada allí, tomaría nueva libertad y podría en cualquiera de muchas formas eludir toda persecución. En miedo me volví hacia el Profesor; sin embargo, para mi consternación, no estaba allí. Un instante después, lo vi debajo de mí. Alrededor de la roca había dibujado un círculo, como el abrigo en el que habíamos encontrado refugio la noche anterior. Cuando lo completó se paró junto a mí nuevamente, diciendo:—"
        },
        {
          "en": "“At least you shall be safe here from him!” He took the glasses from me, and at the next lull of the snow swept the whole space below us. “See,” he said, “they come quickly; they are flogging the horses, and galloping as hard as they can.” He paused and went on in a hollow voice:—",
          "es": "\"¡Al menos aquí estarás segura de él!\" Me quitó los binoculares, y en la próxima pausa de la nieve barrió todo el espacio debajo de nosotros. \"Mira,\" dijo, \"vienen rápido; están azotando los caballos, y galopando todo lo que pueden.\" Hizo una pausa y continuó en una voz hueca:—"
        },
        {
          "en": "“They are racing for the sunset. We may be too late. God’s will be done!” Down came another blinding rush of driving snow, and the whole landscape was blotted out. It soon passed, however, and once more his glasses were fixed on the plain. Then came a sudden cry:—",
          "es": "\"Están corriendo hacia el atardecer. Puede ser que lleguemos demasiado tarde. ¡Que se haga la voluntad de Dios!\" Cayó otra ráfaga cegadora de nieve que conducía, y todo el paisaje fue borrado. Sin embargo, pasó pronto, y una vez más sus binoculares estaban fijos en la llanura. Luego vino un grito repentino:—"
        },
        {
          "en": "“Look! Look! Look! See, two horsemen follow fast, coming up from the south. It must be Quincey and John. Take the glass. Look before the snow blots it all out!” I took it and looked. The two men might be Dr. Seward and Mr. Morris. I knew at all events that neither of them was Jonathan. At the same time I knew that Jonathan was not far off; looking around I saw on the north side of the coming party two other men, riding at break-neck speed. One of them I knew was Jonathan, and the other I took, of course, to be Lord Godalming. They, too, were pursuing the party with the cart. When I told the Professor he shouted in glee like a schoolboy, and, after looking intently till a snow fall made sight impossible, he laid his Winchester rifle ready for use against the boulder at the opening of our shelter. “They are all converging,” he said. “When the time comes we shall have gypsies on all sides.” I got out my revolver ready to hand, for whilst we were speaking the howling of wolves came louder and closer. When the snow storm abated a moment we looked again. It was strange to see the snow falling in such heavy flakes close to us, and beyond, the sun shining more and more brightly as it sank down towards the far mountain tops. Sweeping the glass all around us I could see here and there dots moving singly and in twos and threes and larger numbers—the wolves were gathering for their prey.",
          "es": "\"¡Mira! ¡Mira! ¡Mira! ¡Mira, dos jinetes siguen rápido, viniendo desde el sur! Deben ser Quincey y John. Toma el binocular. ¡Mira antes de que la nieve lo borre todo!\" Lo tomé y miré. Los dos hombres podrían ser el Dr. Seward y el Sr. Morris. Sabía en todo caso que ninguno de ellos era Jonathan. Al mismo tiempo sabía que Jonathan no estaba lejos; mirando alrededor vi en el lado norte del grupo que venía otros dos hombres, cabalgando a velocidad atroz. Uno de ellos sabía que era Jonathan, y al otro lo tomé, por supuesto, como Lord Godalming. También estaban persiguiendo al grupo con el carro. Cuando le dije al Profesor gritó de alegría como un escolar, y después de mirar intensamente hasta que una caída de nieve hizo la vista imposible, colocó su rifle Winchester listo para usar contra el peñasco en la abertura de nuestro abrigo. \"Todos convergen,\" dijo. \"Cuando llegue el momento tendremos gitanos de todos los lados.\" Saqué mi revólver listo para usar, pues mientras hablábamos los aullidos de los lobos sonaban más fuerte y más cerca. Cuando la tormenta de nieve se calmó un momento miramos de nuevo. Era extraño ver la nieve cayendo en copos tan pesados cerca de nosotros, y más allá, el sol brillando cada vez más brillantemente mientras se hundía hacia las cimas lejanas de las montañas. Barriendo el binocular alrededor de nosotros podía ver aquí y allá puntos moviéndose solos y en dos y tres y números más grandes—los lobos se estaban reuniendo por su presa."
        },
        {
          "en": "Every instant seemed an age whilst we waited. The wind came now in fierce bursts, and the snow was driven with fury as it swept upon us in circling eddies. At times we could not see an arm’s length before us; but at others, as the hollow-sounding wind swept by us, it seemed to clear the air-space around us so that we could see afar off. We had of late been so accustomed to watch for sunrise and sunset, that we knew with fair accuracy when it would be; and we knew that before long the sun would set. It was hard to believe that by our watches it was less than an hour that we waited in that rocky shelter before the various bodies began to converge close upon us. The wind came now with fiercer and more bitter sweeps, and more steadily from the north. It seemingly had driven the snow clouds from us, for, with only occasional bursts, the snow fell. We could distinguish clearly the individuals of each party, the pursued and the pursuers. Strangely enough those pursued did not seem to realise, or at least to care, that they were pursued; they seemed, however, to hasten with redoubled speed as the sun dropped lower and lower on the mountain tops.",
          "es": "Cada instante parecía una edad mientras esperábamos. El viento llegaba ahora en ráfagas feroces, y la nieve era conducida con furia conforme se barrió sobre nosotros en remolinos circulantes. A veces no podíamos ver una distancia de un brazo delante de nosotros; pero otras, cuando el viento de sonido hueco se barrió alrededor de nosotros, parecía aclarar el espacio de aire alrededor de nosotros para que pudiéramos ver a lo lejos. Últimamente habíamos estado tan acostumbrados a observar el amanecer y el atardecer, que sabíamos con suficiente precisión cuándo sería; y sabíamos que pronto el sol se pondría. Era difícil creer que por nuestros relojes eran menos de una hora que esperábamos en ese abrigo rocoso antes de que varios cuerpos comenzaran a converger cerca de nosotros. El viento llegaba ahora con ráfagas más feroces y más amargas, y más constantemente desde el norte. Aparentemente había llevado las nubes de nieve de nosotros, pues con solo ráfagas ocasionales, la nieve caía. Podíamos distinguir claramente a los individuos de cada grupo, los perseguidos y los perseguidores. Extrañamente los perseguidos no parecían darse cuenta, o al menos les importaba, que estaban siendo perseguidos; parecían, sin embargo, apresurarse con velocidad redoblada conforme el sol caía más y más bajo en las cimas de las montañas."
        }
      ]
    },
    "12": {
      "lines": [
        {
          "en": "Closer and closer they drew. The Professor and I crouched down behind our rock, and held our weapons ready; I could see that he was determined that they should not pass. One and all were quite unaware of our presence.",
          "es": "Más y más cerca vinieron. El Profesor y yo nos agachamos detrás de nuestra roca, y mantuvimos nuestras armas listas; podía ver que estaba determinado que no pasaran. Todos y cada uno eran completamente ajenos a nuestra presencia."
        },
        {
          "en": "All at once two voices shouted out to: “Halt!” One was my Jonathan’s, raised in a high key of passion; the other Mr. Morris’ strong resolute tone of quiet command. The gypsies may not have known the language, but there was no mistaking the tone, in whatever tongue the words were spoken. Instinctively they reined in, and at the instant Lord Godalming and Jonathan dashed up at one side and Dr. Seward and Mr. Morris on the other. The leader of the gypsies, a splendid-looking fellow who sat his horse like a centaur, waved them back, and in a fierce voice gave to his companions some word to proceed. They lashed the horses which sprang forward; but the four men raised their Winchester rifles, and in an unmistakable way commanded them to stop. At the same moment Dr. Van Helsing and I rose behind the rock and pointed our weapons at them. Seeing that they were surrounded the men tightened their reins and drew up. The leader turned to them and gave a word at which every man of the gypsy party drew what weapon he carried, knife or pistol, and held himself in readiness to attack. Issue was joined in an instant.",
          "es": "De repente dos voces gritaron: \"¡Alto!\" Una era la de mi Jonathan, levantada en un tono alto de pasión; la otra el tono fuerte y resuelto de quietud de mando del Sr. Morris. Los gitanos puede que no conocieran el idioma, pero no había forma de equivocarse en el tono, en cualquier lengua que las palabras fueran habladas. Instintivamente frenaron, e en el instante Lord Godalming y Jonathan se lanzaron por un lado y el Dr. Seward y el Sr. Morris por el otro. El líder de los gitanos, un tipo magnífico que se sentaba en su caballo como un centauro, los hizo retroceder, y en una voz feroz dio a sus compañeros alguna palabra para proceder. Azotaron los caballos que saltaron adelante; pero los cuatro hombres levantaron sus rifles Winchester, y de una manera inconfundible les ordenaron detenerse. En el mismo momento el Dr. Van Helsing y yo nos levantamos detrás de la roca y apuntamos nuestras armas hacia ellos. Viendo que estaban rodeados los hombres apretaron sus riendas y se detuvieron. El líder se volvió hacia ellos y dio una palabra por la cual cada hombre del grupo gitano sacó el arma que llevaba, cuchillo o pistola, y se preparó para atacar. El problema comenzó en un instante."
        },
        {
          "en": "The leader, with a quick movement of his rein, threw his horse out in front, and pointing first to the sun—now close down on the hill tops—and then to the castle, said something which I did not understand. For answer, all four men of our party threw themselves from their horses and dashed towards the cart. I should have felt terrible fear at seeing Jonathan in such danger, but that the ardour of battle must have been upon me as well as the rest of them; I felt no fear, but only a wild, surging desire to do something. Seeing the quick movement of our parties, the leader of the gypsies gave a command; his men instantly formed round the cart in a sort of undisciplined endeavour, each one shouldering and pushing the other in his eagerness to carry out the order.",
          "es": "El líder, con un movimiento rápido de su rienda, lanzó su caballo frente, y señalando primero al sol—ahora bajo en las cimas de las colinas—y luego al castillo, dijo algo que no entendí. En respuesta, los cuatro hombres de nuestro grupo se lanzaron de sus caballos y se apresuraron hacia el carro. Debería haber sentido miedo terrible al ver a Jonathan en tal peligro, pero el ardor de la batalla debe haber estado sobre mí también que el resto de ellos; no sentía miedo, sino solo un deseo salvaje y ardiente de hacer algo. Viendo el movimiento rápido de nuestros grupos, el líder de los gitanos dio una orden; sus hombres instantáneamente se formaron alrededor del carro en un esfuerzo indisciplinado, cada uno empujando y presionando al otro en su entusiasmo por cumplir la orden."
        },
        {
          "en": "In the midst of this I could see that Jonathan on one side of the ring of men, and Quincey on the other, were forcing a way to the cart; it was evident that they were bent on finishing their task before the sun should set. Nothing seemed to stop or even to hinder them. Neither the levelled weapons nor the flashing knives of the gypsies in front, nor the howling of the wolves behind, appeared to even attract their attention. Jonathan’s impetuosity, and the manifest singleness of his purpose, seemed to overawe those in front of him; instinctively they cowered, aside and let him pass. In an instant he had jumped upon the cart, and, with a strength which seemed incredible, raised the great box, and flung it over the wheel to the ground. In the meantime, Mr. Morris had had to use force to pass through his side of the ring of Szgany. All the time I had been breathlessly watching Jonathan I had, with the tail of my eye, seen him pressing desperately forward, and had seen the knives of the gypsies flash as he won a way through them, and they cut at him. He had parried with his great bowie knife, and at first I thought that he too had come through in safety; but as he sprang beside Jonathan, who had by now jumped from the cart, I could see that with his left hand he was clutching at his side, and that the blood was spurting through his fingers. He did not delay notwithstanding this, for as Jonathan, with desperate energy, attacked one end of the chest, attempting to prize off the lid with his great Kukri knife, he attacked the other frantically with his bowie. Under the efforts of both men the lid began to yield; the nails drew with a quick screeching sound, and the top of the box was thrown back.",
          "es": "En medio de esto podía ver que Jonathan de un lado del anillo de hombres, y Quincey del otro, estaban forzando un camino hacia el carro; era evidente que estaban decididos a terminar su tarea antes de que el sol se pusiera. Nada parecía detenerlos u obstaculizarlos incluso. Ni las armas levantadas ni los cuchillos centelleantes de los gitanos en frente, ni los aullidos de los lobos detrás, parecían atraer su atención incluso. La impetuosidad de Jonathan, y la singleness manifiesta de su propósito, parecía abrumar a los que estaban enfrente de él; instintivamente se encogían, se apartaban y lo dejaban pasar. En un instante se había saltado en el carro, y con una fuerza que parecía increíble, levantó la gran caja, y la lanzó sobre la rueda al suelo. Mientras tanto, el Sr. Morris había tenido que usar fuerza para pasar a través de su lado del anillo de Szgany. Todo el tiempo que había estado observando ansiosamente a Jonathan, había visto con la cola de mi ojo presionando desesperadamente hacia adelante, y había visto los cuchillos de los gitanos relampaguear mientras abría su camino a través de ellos, y lo cortaban. Había parado con su gran cuchillo bowie, y al principio pensé que él también había pasado con seguridad; pero cuando saltó junto a Jonathan, quien ya había saltado del carro, podía ver que con su mano izquierda se aferraba a su lado, y que la sangre brotaba a través de sus dedos. Sin embargo, no se detuvo, pues cuando Jonathan, con energía desesperada, atacó un extremo del cofre, intentando levantar la tapa con su gran cuchillo Kukri, él atacó el otro frenéticamente con su bowie. Bajo los esfuerzos de ambos hombres la tapa comenzó a ceder; los clavos salieron con un sonido chirriante rápido, y la parte superior de la caja fue lanzada hacia atrás."
        },
        {
          "en": "By this time the gypsies, seeing themselves covered by the Winchesters, and at the mercy of Lord Godalming and Dr. Seward, had given in and made no resistance. The sun was almost down on the mountain tops, and the shadows of the whole group fell long upon the snow. I saw the Count lying within the box upon the earth, some of which the rude falling from the cart had scattered over him. He was deathly pale, just like a waxen image, and the red eyes glared with the horrible vindictive look which I knew too well.",
          "es": "Para este momento los gitanos, viéndose cubiertos por los Winchesters, y a merced de Lord Godalming y del Dr. Seward, habían cedido y no mostraban resistencia. El sol estaba casi en las cimas de las montañas, y las sombras de todo el grupo caían largas sobre la nieve. Vi al Conde yaciendo dentro del cofre sobre la tierra, algo de la cual la caída áspera del carro había esparcido sobre él. Estaba pálido como la muerte, justo como una imagen de cera, y los ojos rojos miraban con la mirada vengativa horrible que ya conocía bien."
        }
      ]
    },
    "13": {
      "lines": [
        {
          "en": "As I looked, the eyes saw the sinking sun, and the look of hate in them turned to triumph.",
          "es": "Mientras miraba, los ojos vieron el sol hundiéndose, y la mirada de odio en ellos se convirtió en triunfo."
        },
        {
          "en": "But, on the instant, came the sweep and flash of Jonathan’s great knife. I shrieked as I saw it shear through the throat; whilst at the same moment Mr. Morris’s bowie knife plunged into the heart.",
          "es": "Pero en el instante, llegó el barrido y destello del gran cuchillo de Jonathan. Grité cuando lo vi cortar a través de la garganta; mientras que en el mismo momento el cuchillo bowie del Sr. Morris se hundió en el corazón."
        },
        {
          "en": "It was like a miracle; but before our very eyes, and almost in the drawing of a breath, the whole body crumbled into dust and passed from our sight.",
          "es": "Fue como un milagro; pero ante nuestros propios ojos, y casi en el dibujo de una respiración, el cuerpo completo se desmoronó en polvo y pasó de nuestra vista."
        },
        {
          "en": "I shall be glad as long as I live that even in that moment of final dissolution, there was in the face a look of peace, such as I never could have imagined might have rested there.",
          "es": "Estaré contenta mientras viva que incluso en ese momento de disolución final, había en la cara una mirada de paz, tal como nunca hubiera podido imaginar que hubiera reposado allí."
        },
        {
          "en": "The Castle of Dracula now stood out against the red sky, and every stone of its broken battlements was articulated against the light of the setting sun.",
          "es": "El Castillo de Drácula ahora se destacaba contra el cielo rojo, y cada piedra de sus almenas rotas estaba articulada contra la luz del sol poniente."
        }
      ]
    },
    "14": {
      "lines": [
        {
          "en": "The gypsies, taking us as in some way the cause of the extraordinary disappearance of the dead man, turned, without a word, and rode away as if for their lives. Those who were unmounted jumped upon the leiter-wagon and shouted to the horsemen not to desert them. The wolves, which had withdrawn to a safe distance, followed in their wake, leaving us alone.",
          "es": "Los gitanos, tomándonos de alguna manera como la causa de la desaparición extraordinaria del hombre muerto, se volvieron sin una palabra, e cabalgaron como si sus vidas dependiera. Aquellos que estaban desmontados saltaron sobre el carro-lecho y gritaron a los jinetes que no los desertaran. Los lobos, que se habían retirado a una distancia segura, los siguieron en su estela, dejándonos solos."
        },
        {
          "en": "Mr. Morris, who had sunk to the ground, leaned on his elbow, holding his hand pressed to his side; the blood still gushed through his fingers. I flew to him, for the Holy circle did not now keep me back; so did the two doctors. Jonathan knelt behind him and the wounded man laid back his head on his shoulder. With a sigh he took, with a feeble effort, my hand in that of his own which was unstained. He must have seen the anguish of my heart in my face, for he smiled at me and said:—",
          "es": "El Sr. Morris, que se había desplomado en el suelo, se apoyó en su codo, sosteniendo su mano presionada contra su lado; la sangre aún brotaba a través de sus dedos. Volé hacia él, pues el círculo sagrado ya no me detenía; también lo hicieron los dos doctores. Jonathan se arrodilló detrás de él y el hombre herido recostó su cabeza en su hombro. Con un suspiro tomó, con un esfuerzo débil, mi mano en la suya que no estaba manchada. Debe haber visto la angustia de mi corazón en mi cara, pues sonrió hacia mí y dijo:—"
        },
        {
          "en": "“I am only too happy to have been of any service! Oh, God!” he cried suddenly, struggling up to a sitting posture and pointing to me, “It was worth for this to die! Look! look!”",
          "es": "¡Estoy más que contento de haber sido de algún servicio! ¡Oh, Dios!\" gritó de repente, luchando por ponerse en postura sentada y apuntando hacia mí, \"¡Valía la pena morir por esto! ¡Mira! ¡mira!"
        },
        {
          "en": "The sun was now right down upon the mountain top, and the red gleams fell upon my face, so that it was bathed in rosy light. With one impulse the men sank on their knees and a deep and earnest “Amen” broke from all as their eyes followed the pointing of his finger. The dying man spoke:—",
          "es": "El sol estaba ahora justo en la cima de la montaña, y los destellos rojos caían sobre mi cara, de modo que estaba bañada en luz rosada. Con un impulso los hombres se arrodillaron y un \"Amén\" profundo y sincero brotó de todos conforme sus ojos seguían el apuntamiento de su dedo. El hombre moribundo habló:—"
        },
        {
          "en": "“Now God be thanked that all has not been in vain! See! the snow is not more stainless than her forehead! The curse has passed away!”",
          "es": "¡Ahora Dios sea loado que todo no ha sido en vano! ¡Mira! ¡la nieve no es más inmaculada que su frente! ¡La maldición ha pasado!"
        },
        {
          "en": "And, to our bitter grief, with a smile and in silence, he died, a gallant gentleman.",
          "es": ""
        }
      ]
    },
    "15": {
      "lines": [
        {
          "en": "NOTE",
          "es": "Y, para nuestro amargo dolor, con una sonrisa y en silencio, murió, un caballero valiente."
        },
        {
          "en": "Seven years ago we all went through the flames; and the happiness of some of us since then is, we think, well worth the pain we endured. It is an added joy to Mina and to me that our boy’s birthday is the same day as that on which Quincey Morris died. His mother holds, I know, the secret belief that some of our brave friend’s spirit has passed into him. His bundle of names links all our little band of men together; but we call him Quincey.",
          "es": "NOTA"
        },
        {
          "en": "In the summer of this year we made a journey to Transylvania, and went over the old ground which was, and is, to us so full of vivid and terrible memories. It was almost impossible to believe that the things which we had seen with our own eyes and heard with our own ears were living truths. Every trace of all that had been was blotted out. The castle stood as before, reared high above a waste of desolation.",
          "es": "Hace siete años pasamos todos por las llamas; y la felicidad de algunos de nosotros desde entonces es, creemos, bien vale el dolor que sufrimos. Es una alegría añadida para Mina y para mí que el cumpleaños de nuestro hijo sea el mismo día en que murió Quincey Morris. Su madre sostiene, sé, la creencia secreta de que algo del espíritu de nuestro valiente amigo ha pasado a él. Su conjunto de nombres une a todo nuestro pequeño grupo de hombres; pero lo llamamos Quincey."
        },
        {
          "en": "When we got home we were talking of the old time—which we could all look back on without despair, for Godalming and Seward are both happily married. I took the papers from the safe where they had been ever since our return so long ago. We were struck with the fact, that in all the mass of material of which the record is composed, there is hardly one authentic document; nothing but a mass of typewriting, except the later note-books of Mina and Seward and myself, and Van Helsing’s memorandum. We could hardly ask any one, even did we wish to, to accept these as proofs of so wild a story. Van Helsing summed it all up as he said, with our boy on his knee:—",
          "es": "En el verano de este año hicimos un viaje a Transilvania, y fuimos sobre el terreno viejo que fue, y es, para nosotros tan lleno de recuerdos vívidos y terribles. Era casi imposible creer que las cosas que habíamos visto con nuestros propios ojos y escuchado con nuestros propios oídos eran verdades vivientes. Cada rastro de todo lo que había sido fue borrado. El castillo se erguía como antes, levantado alto sobre una desolación."
        },
        {
          "en": "“We want no proofs; we ask none to believe us! This boy will some day know what a brave and gallant woman his mother is. Already he knows her sweetness and loving care; later on he will understand how some men so loved her, that they did dare much for her sake.”",
          "es": "Cuando llegamos a casa estábamos hablando de los tiempos antiguos—que todos podíamos mirar hacia atrás sin desesperación, pues Godalming y Seward están ambos felizmente casados. Tomé los papeles de la caja de seguridad donde habían estado desde nuestro regreso hace tanto tiempo. Quedamos sorprendidos por el hecho de que en toda la masa de material del que se compone el registro, hay apenas un documento auténtico; nada sino una masa de mecanografía, excepto los cuadernos de notas posteriores de Mina y Seward y yo, y el memorándum de Van Helsing. Apenas podríamos pedirle a alguien, incluso si quisiéramos, que aceptara estos como pruebas de una historia tan salvaje. Van Helsing lo resumió todo cuando dijo, con nuestro hijo en su rodilla:—"
        },
        {
          "en": "Jonathan Harker.",
          "es": "¡No queremos pruebas; no pedimos que nadie nos crea! Este niño algún día sabrá qué mujer valiente y gallarda es su madre. Ya conoce su dulzura y su cuidado amoroso; después entenderá cómo algunos hombres la amaron tanto, que se atrevieron a hacer mucho por su bien."
        }
      ]
    },
    "16": {
      "lines": [
        {
          "en": "THE END",
          "es": "Jonathan Harker."
        },
        {
          "en": "There’s More to Follow!",
          "es": "FIN"
        },
        {
          "en": "More stories of the sort you like; more, probably, by the author of this one; more than 500 titles all told by writers of world-wide reputation, in the Authors’ Alphabetical List which you will find on the reverse side of the wrapper of this book. Look it over before you lay it aside. There are books here you are sure to want—some, possibly, that you have always wanted.",
          "es": "¡Hay más para seguir!"
        },
        {
          "en": "It is a selected list; every book in it has achieved a certain measure of success.",
          "es": "Más historias del tipo que te gustan; más, probablemente, del autor de esta; más de 500 títulos en total de escritores de reputación mundial, en la Lista Alfabética de Autores que encontrarás en el reverso de la cubierta de este libro. Mírala antes de dejarlo de lado. Hay libros aquí que seguramente querras—algunos, posiblemente, que siempre has querido."
        },
        {
          "en": "The Grosset & Dunlap list is not only the greatest Index of Good Fiction available, it represents in addition a generally accepted Standard of Value. It will pay you to",
          "es": "Es una lista seleccionada; cada libro en ella ha logrado cierta medida de éxito."
        },
        {
          "en": "Look on the Other Side of the Wrapper!",
          "es": ""
        }
      ]
    },
    "17": {
      "lines": [
        {
          "en": "",
          "es": "La lista de Grosset & Dunlap no es solo el Índice más grande de Buena Ficción disponible, sino que representa además un Estándar de Valor generalmente aceptado. Te conviene"
        },
        {
          "en": "",
          "es": "¡Mira el Otro Lado de la Cubierta!"
        }
      ]
    }
  }
};
