export const chapterContent = {
  "storySlug": "dracula",
  "level": 4,
  "chapter": 6,
  "pages": {
    "1": {
      "lines": [
        {
          "en": "MINA MURRAY’S JOURNAL",
          "es": "DIARIO DE MINA MURRAY"
        },
        {
          "en": "24 July. Whitby.—Lucy met me at the station, looking sweeter and lovelier than ever, and we drove up to the house at the Crescent in which they have rooms. This is a lovely place. The little river, the Esk, runs through a deep valley, which broadens out as it comes near the harbour. A great viaduct runs across, with high piers, through which the view seems somehow further away than it really is. The valley is beautifully green, and it is so steep that when you are on the high land on either side you look right across it, unless you are near enough to see down. The houses of the old town—the side away from us—are all red-roofed, and seem piled up one over the other anyhow, like the pictures we see of Nuremberg. Right over the town is the ruin of Whitby Abbey, which was sacked by the Danes, and which is the scene of part of “Marmion,” where the girl was built up in the wall. It is a most noble ruin, of immense size, and full of beautiful and romantic bits; there is a legend that a white lady is seen in one of the windows. Between it and the town there is another church, the parish one, round which is a big graveyard, all full of tombstones. This is to my mind the nicest spot in Whitby, for it lies right over the town, and has a full view of the harbour and all up the bay to where the headland called Kettleness stretches out into the sea. It descends so steeply over the harbour that part of the bank has fallen away, and some of the graves have been destroyed. In one place part of the stonework of the graves stretches out over the sandy pathway far below. There are walks, with seats beside them, through the churchyard; and people go and sit there all day long looking at the beautiful view and enjoying the breeze. I shall come and sit here very often myself and work. Indeed, I am writing now, with my book on my knee, and listening to the talk of three old men who are sitting beside me. They seem to do nothing all day but sit up here and talk.",
          "es": "24 de julio. Whitby.—Lucy me recibió en la estación, luciendo más hermosa y encantadora que nunca, y fuimos en coche hasta la casa en la media luna donde tienen sus habitaciones. Es un lugar precioso. El pequeño río, el Esk, corre por un valle profundo, que se ensancha cuando se acerca al puerto. Un gran viaducto lo cruza, con pilares altos, a través de los cuales la vista parece de alguna manera más lejana de lo que realmente es. El valle es hermosamente verde, y tan empinado que cuando estás en las tierras altas de cualquiera de los lados, miras directamente a través de él, a menos que estés lo suficientemente cerca para ver hacia abajo. Las casas del pueblo antiguo —el lado opuesto a nosotros— tienen todos los techos rojos, y parecen apiladas unas sobre otras sin orden, como en las imágenes que vemos de Nuremberg. Justo encima del pueblo están las ruinas de la Abadía de Whitby, saqueada por los daneses, y que es el escenario de parte de \"Marmion\", donde la chica fue emparedada en la pared. Es una ruina muy noble, de tamaño inmenso, y llena de partes hermosas y románticas; existe una leyenda de que una dama blanca se ve en una de las ventanas. Entre ella y el pueblo hay otra iglesia, la parroquial, alrededor de la cual hay un gran cementerio, completamente lleno de lápidas. Para mí, este es el lugar más bonito de Whitby, porque se encuentra justo encima del pueblo, y tiene una vista completa del puerto y toda la bahía hasta donde el cabo llamado Kettleness se extiende hacia el mar. Desciende tan abruptamente sobre el puerto que parte del terraplén se ha derrumbado, y algunas de las tumbas han sido destruidas. En un lugar, parte de la estructura de piedra de las tumbas se extiende sobre el sendero arenoso muy por debajo. Hay paseos, con bancos junto a ellos, a través del cementerio; y la gente va y se sienta allí todo el día mirando la hermosa vista y disfrutando de la brisa. Vendré aquí a menudo y trabajaré. De hecho, estoy escribiendo ahora, con mi cuaderno en las rodillas, y escuchando la conversación de tres hombres viejos que están sentados junto a mí. Parecen no hacer nada todo el día excepto sentarse aquí y hablar."
        },
        {
          "en": "The harbour lies below me, with, on the far side, one long granite wall stretching out into the sea, with a curve outwards at the end of it, in the middle of which is a lighthouse. A heavy sea-wall runs along outside of it. On the near side, the sea-wall makes an elbow crooked inversely, and its end too has a lighthouse. Between the two piers there is a narrow opening into the harbour, which then suddenly widens.",
          "es": "El puerto se encuentra debajo de mí, con, en el lado opuesto, un largo muro de granito extendiéndose hacia el mar, con una curva hacia afuera al final, en el medio del cual hay un faro. Un pesado muro marino corre a lo largo del exterior. En el lado cercano, el muro marino forma un codo invertido, y su extremo también tiene un faro. Entre los dos muelles hay una estrecha abertura hacia el puerto, que luego se ensancha repentinamente."
        },
        {
          "en": "It is nice at high water; but when the tide is out it shoals away to nothing, and there is merely the stream of the Esk, running between banks of sand, with rocks here and there. Outside the harbour on this side there rises for about half a mile a great reef, the sharp edge of which runs straight out from behind the south lighthouse. At the end of it is a buoy with a bell, which swings in bad weather, and sends in a mournful sound on the wind. They have a legend here that when a ship is lost bells are heard out at sea. I must ask the old man about this; he is coming this way....",
          "es": "Es agradable en pleamar; pero cuando la marea baja, se vuelve poco profunda hasta casi desaparecer, y solo queda la corriente del Esk, corriendo entre orillas de arena, con rocas aquí y allá. Fuera del puerto en este lado se eleva durante aproximadamente media milla un gran arrecife, cuyo borde afilado corre recto desde detrás del faro del sur. Al final hay una boya con una campana, que se balancea en mal tiempo, y envía un sonido melancólico con el viento. Tienen una leyenda aquí de que cuando un barco se pierde se oyen campanas en el mar. Debo preguntarle al hombre viejo sobre esto; viene en esta dirección..."
        },
        {
          "en": "He is a funny old man. He must be awfully old, for his face is all gnarled and twisted like the bark of a tree. He tells me that he is nearly a hundred, and that he was a sailor in the Greenland fishing fleet when Waterloo was fought. He is, I am afraid, a very sceptical person, for when I asked him about the bells at sea and the White Lady at the abbey he said very brusquely:—",
          "es": "Es un hombre viejo divertido. Debe ser terriblemente viejo, porque su cara está toda nudosa y retorcida como la corteza de un árbol. Me dice que tiene casi cien años, y que fue marinero en la flota ballenera de Groenlandia cuando se libró la batalla de Waterloo. Tengo miedo que sea una persona muy escéptica, porque cuando le pregunté sobre las campanas en el mar y la Dama Blanca de la abadía, dijo muy bruscamente:—"
        },
        {
          "en": "“I wouldn’t fash masel’ about them, miss. Them things be all wore out. Mind, I don’t say that they never was, but I do say that they wasn’t in my time. They be all very well for comers and trippers, an’ the like, but not for a nice young lady like you. Them feet-folks from York and Leeds that be always eatin’ cured herrin’s an’ drinkin’ tea an’ lookin’ out to buy cheap jet would creed aught. I wonder masel’ who’d be bothered tellin’ lies to them—even the newspapers, which is full of fool-talk.” I thought he would be a good person to learn interesting things from, so I asked him if he would mind telling me something about the whale-fishing in the old days. He was just settling himself to begin when the clock struck six, whereupon he laboured to get up, and said:—",
          "es": "\"No me preocuparía por esas cosas, señorita. Todas esas cosas están gastadas. Mire, no digo que nunca existieran, pero digo que no existían en mi tiempo. Están muy bien para visitantes y turistas, y personas así, pero no para una joven tan agradable como usted. Esos pies-personas de York y Leeds que siempre están comiendo arenque curado y bebiendo té y buscando comprar ámbar barato creerían cualquier cosa. Me pregunto quién se molestaría en contarles mentiras—incluso los periódicos, que están llenos de tonterías.\" Pensé que sería una buena persona de quien aprender cosas interesantes, así que le pregunté si le importaría contarme algo sobre la pesca de ballenas en los viejos tiempos. Estaba a punto de comenzar cuando el reloj marcó las seis, con lo cual se esforzó por levantarse, y dijo:—"
        },
        {
          "en": "“I must gang ageeanwards home now, miss. My grand-daughter doesn’t like to be kept waitin’ when the tea is ready, for it takes me time to crammle aboon the grees, for there be a many of ’em; an’, miss, I lack belly-timber sairly by the clock.”",
          "es": "Debo irme hacia casa ahora, señorita. A mi nieta no le gusta que la mantengan esperando cuando el té está listo, porque me toma tiempo subir por los escalones, porque hay muchos de ellos; y, señorita, tengo mucha hambre según el reloj."
        }
      ]
    },
    "2": {
      "lines": [
        {
          "en": "He hobbled away, and I could see him hurrying, as well as he could, down the steps. The steps are a great feature on the place. They lead from the town up to the church, there are hundreds of them—I do not know how many—and they wind up in a delicate curve; the slope is so gentle that a horse could easily walk up and down them. I think they must originally have had something to do with the abbey. I shall go home too. Lucy went out visiting with her mother, and as they were only duty calls, I did not go. They will be home by this.",
          "es": "Se fue cojeando, y pude verlo apresurándose, lo mejor que pudo, bajando los escalones. Los escalones son una gran característica del lugar. Conducen desde el pueblo hasta la iglesia, hay cientos de ellos—no sé cuántos—y suben en una curva delicada; la pendiente es tan suave que un caballo podría fácilmente subir y bajar por ellos. Creo que deben haber tenido originalmente algo que ver con la abadía. Yo también me iré a casa. Lucy salió a hacer visitas con su madre, y como eran solo visitas de cortesía, no fui. Deberían estar en casa ya."
        },
        {
          "en": "1 August.—I came up here an hour ago with Lucy, and we had a most interesting talk with my old friend and the two others who always come and join him. He is evidently the Sir Oracle of them, and I should think must have been in his time a most dictatorial person. He will not admit anything, and downfaces everybody. If he can’t out-argue them he bullies them, and then takes their silence for agreement with his views. Lucy was looking sweetly pretty in her white lawn frock; she has got a beautiful colour since she has been here. I noticed that the old men did not lose any time in coming up and sitting near her when we sat down. She is so sweet with old people; I think they all fell in love with her on the spot. Even my old man succumbed and did not contradict her, but gave me double share instead. I got him on the subject of the legends, and he went off at once into a sort of sermon. I must try to remember it and put it down:—",
          "es": "1 de agosto.—Vine aquí hace una hora con Lucy, y tuvimos una conversación muy interesante con mi viejo amigo y los otros dos que siempre vienen y se unen a él. Evidentemente es el Oráculo de ellos, y creo que en su tiempo debe haber sido una persona muy autoritaria. No admite nada, y desaprueba a todos. Si no puede vencer a alguien en una discusión, los intimida, y luego toma su silencio como acuerdo con sus opiniones. Lucy se veía muy hermosa en su vestido blanco de algodón; tiene un color precioso desde que está aquí. Noté que los hombres viejos no perdieron tiempo en acercarse y sentarse cerca de ella cuando nos sentamos. Es tan dulce con la gente mayor; creo que todos se enamoraron de ella inmediatamente. Incluso mi viejo amigo sucumbió y no la contradijo, sino que me dio el doble de lo que me habría dado. Lo dirigí hacia el tema de las leyendas, y enseguida comenzó una especie de sermón. Debo intentar recordarlo y anotarlo:—"
        },
        {
          "en": "“It be all fool-talk, lock, stock, and barrel; that’s what it be, an’ nowt else. These bans an’ wafts an’ boh-ghosts an’ barguests an’ bogles an’ all anent them is only fit to set bairns an’ dizzy women a-belderin’. They be nowt but air-blebs. They, an’ all grims an’ signs an’ warnin’s, be all invented by parsons an’ illsome beuk-bodies an’ railway touters to skeer an’ scunner hafflin’s, an’ to get folks to do somethin’ that they don’t other incline to. It makes me ireful to think o’ them. Why, it’s them that, not content with printin’ lies on paper an’ preachin’ them out of pulpits, does want to be cuttin’ them on the tombstones. Look here all around you in what airt ye will; all them steans, holdin’ up their heads as well as they can out of their pride, is acant—simply tumblin’ down with the weight o’ the lies wrote on them, ‘Here lies the body’ or ‘Sacred to the memory’ wrote on all of them, an’ yet in nigh half of them there bean’t no bodies at all; an’ the memories of them bean’t cared a pinch of snuff about, much less sacred. Lies all of them, nothin’ but lies of one kind or another! My gog, but it’ll be a quare scowderment at the Day of Judgment when they come tumblin’ up in their death-sarks, all jouped together an’ tryin’ to drag their tombsteans with them to prove how good they was; some of them trimmlin’ and ditherin’, with their hands that dozzened an’ slippy from lyin’ in the sea that they can’t even keep their grup o’ them.”",
          "es": "Todo es pura tontería, de principio a fin; eso es lo que es, y nada más. Estos espíritus y apariciones y fantasmas y demonios y traviesos y todo lo relacionado es solo apto para asustar a niños y mujeres tontas. No son más que burbujas de aire. Ellos, y todos los espectros y signos y advertencias, fueron inventados por sacerdotes e ignorantes escribientes y vendedores de ferrocarriles para asustar y desalentar a los jóvenes, y para conseguir que la gente haga cosas a las que no inclinaría de otra manera. Me irrita pensar en ello. Vaya, son ellos los que, no contentos con imprimir mentiras en papel y predicarlas desde los púlpitos, quieren grabarlas en las lápidas. Mira aquí a tu alrededor en cualquier dirección; todas esas piedras, levantando sus cabezas lo mejor que pueden de su orgullo, están llenas de mentiras—simplemente desmoronándose bajo el peso de las mentiras escritas en ellas, 'Aquí yace el cuerpo' o 'Sagrado a la memoria', escritas en todas ellas, y sin embargo en casi la mitad de ellas no hay cuerpos en absoluto; y los recuerdos de ellos no les importan un comino, mucho menos son sagrados. ¡Mentiras todas, nada más que mentiras de un tipo u otro! Caramba, ¡qué espectáculo tan extraño habrá en el Día del Juicio cuando suban tambaleándose en sus mortajas, todos apretados juntos e intentando arrastrar sus lápidas consigo para probar lo buenos que eran; algunos de ellos temblando y titubeando, con sus manos adormecidas y resbaladizas por haber estado en el mar, que ni siquiera pueden mantener su agarre de ellas."
        },
        {
          "en": "I could see from the old fellow’s self-satisfied air and the way in which he looked round for the approval of his cronies that he was “showing off,” so I put in a word to keep him going:—",
          "es": "Pude ver por el aire satisfecho del viejo y la manera en que miró alrededor buscando la aprobación de sus colegas que estaba \"alardear\", así que intercalé una palabra para mantenerlo hablando:—"
        },
        {
          "en": "“Oh, Mr. Swales, you can’t be serious. Surely these tombstones are not all wrong?”",
          "es": "Oh, Sr. Swales, no puede estar hablando en serio. ¿Seguro que no todas las lápidas están equivocadas?"
        },
        {
          "en": "“Yabblins! There may be a poorish few not wrong, savin’ where they make out the people too good; for there be folk that do think a balm-bowl be like the sea, if only it be their own. The whole thing be only lies. Now look you here; you come here a stranger, an’ you see this kirk-garth.” I nodded, for I thought it better to assent, though I did not quite understand his dialect. I knew it had something to do with the church. He went on: “And you consate that all these steans be aboon folk that be happed here, snod an’ snog?” I assented again. “Then that be just where the lie comes in. Why, there be scores of these lay-beds that be toom as old Dun’s ’bacca-box on Friday night.” He nudged one of his companions, and they all laughed. “And my gog! how could they be otherwise? Look at that one, the aftest abaft the bier-bank: read it!” I went over and read:—",
          "es": ""
        },
        {
          "en": "“Edward Spencelagh, master mariner, murdered by pirates off the coast of Andres, April, 1854, æt. 30.” When I came back Mr. Swales went on:—",
          "es": ""
        }
      ]
    },
    "3": {
      "lines": [
        {
          "en": "“Who brought him home, I wonder, to hap him here? Murdered off the coast of Andres! an’ you consated his body lay under! Why, I could name ye a dozen whose bones lie in the Greenland seas above”—he pointed northwards—“or where the currents may have drifted them. There be the steans around ye. Ye can, with your young eyes, read the small-print of the lies from here. This Braithwaite Lowrey—I knew his father, lost in the Lively off Greenland in ’20; or Andrew Woodhouse, drowned in the same seas in 1777; or John Paxton, drowned off Cape Farewell a year later; or old John Rawlings, whose grandfather sailed with me, drowned in the Gulf of Finland in ’50. Do ye think that all these men will have to make a rush to Whitby when the trumpet sounds? I have me antherums aboot it! I tell ye that when they got here they’d be jommlin’ an’ jostlin’ one another that way that it ’ud be like a fight up on the ice in the old days, when we’d be at one another from daylight to dark, an’ tryin’ to tie up our cuts by the light of the aurora borealis.” This was evidently local pleasantry, for the old man cackled over it, and his cronies joined in with gusto.",
          "es": "\"¡Puede ser! Puede haber unos pocos que no estén mal, excepto donde hacen que las personas suenen demasiado buenas; porque hay gente que piensa que un cuenco de agua es como el mar, si es de ellos. Todo el asunto son solo mentiras. Ahora mira aquí; vienes aquí como extranjera, y ves este cementerio de la iglesia.\" Asentí, porque pensé que era mejor estar de acuerdo, aunque no entendía bien su dialecto. Sabía que tenía algo que ver con la iglesia. Continuó: \"¿Y crees que todas estas piedras están sobre gente que está enterrada aquí, segura y limpia?\" Asentí de nuevo. \"Entonces ese es exactamente donde entra la mentira. Vaya, hay docenas de estas tumbas que están tan vacías como la caja de tabaco vieja de Dun el viernes por la noche.\" Empujó a uno de sus compañeros, y todos rieron. \"¡Y caramba! ¿Cómo podrían ser de otra manera? Mira esa, la más lejana detrás del banco del ataúd: ¡léela!\" Fui y leí:—"
        },
        {
          "en": "“But,” I said, “surely you are not quite correct, for you start on the assumption that all the poor people, or their spirits, will have to take their tombstones with them on the Day of Judgment. Do you think that will be really necessary?”",
          "es": "\"Edward Spencelagh, capitán de barco, asesinado por piratas frente a la costa de Andres, abril de 1854, edad 30.\" Cuando regresé, el Sr. Swales continuó:—"
        },
        {
          "en": "“Well, what else be they tombstones for? Answer me that, miss!”",
          "es": "\"¿Quién lo trajo a casa para enterrarlo aquí? ¡Asesinado frente a la costa de Andres! ¿y creías que su cuerpo estaba debajo! Vaya, podría nombrarte una docena cuyos huesos están en los mares de Groenlandia arriba\"—señaló hacia el norte—\"o donde las corrientes podrían haberlos llevado. Están las lápidas alrededor de ti. Puedes, con tus ojos jóvenes, leer la letra pequeña de las mentiras desde aquí. Este Braithwaite Lowrey—conocía a su padre, perdido en el Lively frente a Groenlandia en el 20; o Andrew Woodhouse, ahogado en los mismos mares en 1777; o John Paxton, ahogado frente a Cabo Farewell un año después; o el viejo John Rawlings, cuyo abuelo navegó conmigo, ahogado en el Golfo de Finlandia en el 50. ¿Crees que todos estos hombres tendrán que correr hacia Whitby cuando suene la trompeta? ¡Tengo mis dudas al respecto! Te digo que cuando llegaran aquí estarían empujándose y codazos el uno al otro de tal manera que sería como una pelea en el hielo en los viejos tiempos, cuando nos atacábamos mutuamente desde el amanecer hasta el anochecer, e intentábamos vendarnos las heridas a la luz de la aurora boreal.\" Esto era evidentemente una broma local, porque el viejo rió, y sus colegas se unieron con entusiasmo."
        },
        {
          "en": "“To please their relatives, I suppose.”",
          "es": "Pero\", dije, \"seguramente no estás completamente en lo correcto, porque partes de la suposición de que todos los pobres, o sus espíritus, tendrán que llevar sus lápidas con ellos en el Día del Juicio. ¿Crees que eso será realmente necesario?"
        },
        {
          "en": "“To please their relatives, you suppose!” This he said with intense scorn. “How will it pleasure their relatives to know that lies is wrote over them, and that everybody in the place knows that they be lies?” He pointed to a stone at our feet which had been laid down as a slab, on which the seat was rested, close to the edge of the cliff. “Read the lies on that thruff-stean,” he said. The letters were upside down to me from where I sat, but Lucy was more opposite to them, so she leant over and read:—",
          "es": "Bueno, ¿para qué sirven las lápidas entonces? ¡Respóndeme eso, señorita!"
        },
        {
          "en": "“Sacred to the memory of George Canon, who died, in the hope of a glorious resurrection, on July, 29, 1873, falling from the rocks at Kettleness. This tomb was erected by his sorrowing mother to her dearly beloved son. ‘He was the only son of his mother, and she was a widow.’ Really, Mr. Swales, I don’t see anything very funny in that!” She spoke her comment very gravely and somewhat severely.",
          "es": ""
        }
      ]
    },
    "4": {
      "lines": [
        {
          "en": "“Ye don’t see aught funny! Ha! ha! But that’s because ye don’t gawm the sorrowin’ mother was a hell-cat that hated him because he was acrewk’d—a regular lamiter he was—an’ he hated her so that he committed suicide in order that she mightn’t get an insurance she put on his life. He blew nigh the top of his head off with an old musket that they had for scarin’ the crows with. ’Twarn’t for crows then, for it brought the clegs and the dowps to him. That’s the way he fell off the rocks. And, as to hopes of a glorious resurrection, I’ve often heard him say masel’ that he hoped he’d go to hell, for his mother was so pious that she’d be sure to go to heaven, an’ he didn’t want to addle where she was. Now isn’t that stean at any rate”—he hammered it with his stick as he spoke—“a pack of lies? and won’t it make Gabriel keckle when Geordie comes pantin’ up the grees with the tombstean balanced on his hump, and asks it to be took as evidence!”",
          "es": "Para complacer a sus parientes, supongo."
        },
        {
          "en": "I did not know what to say, but Lucy turned the conversation as she said, rising up:—",
          "es": "\"¡Para complacer a sus parientes, supones!\" Dijo esto con intenso desprecio. \"¿Cómo complacerá a sus parientes saber que hay mentiras escritas sobre ellos, y que todos en el lugar saben que son mentiras?\" Señaló una piedra a nuestros pies que había sido colocada como una losa, sobre la cual se apoyaba el asiento, cerca del borde del acantilado. \"Lee las mentiras en esa piedra de banco\", dijo. Las letras estaban al revés para mí desde donde estaba sentada, pero Lucy estaba más cerca de ellas, así que se inclinó y leyó:—"
        },
        {
          "en": "“Oh, why did you tell us of this? It is my favourite seat, and I cannot leave it; and now I find I must go on sitting over the grave of a suicide.”",
          "es": "\"Sagrado a la memoria de George Canon, quien murió, con la esperanza de una resurrección gloriosa, el 29 de julio de 1873, cayendo de las rocas en Kettleness. Esta tumba fue erigida por su afligida madre a su muy querido hijo. 'Era el único hijo de su madre, y ella era viuda.' Realmente, Sr. Swales, ¡no veo nada muy gracioso en eso!\" Habló su comentario muy seriamente y algo severamente."
        },
        {
          "en": "“That won’t harm ye, my pretty; an’ it may make poor Geordie gladsome to have so trim a lass sittin’ on his lap. That won’t hurt ye. Why, I’ve sat here off an’ on for nigh twenty years past, an’ it hasn’t done me no harm. Don’t ye fash about them as lies under ye, or that doesn’ lie there either! It’ll be time for ye to be getting scart when ye see the tombsteans all run away with, and the place as bare as a stubble-field. There’s the clock, an’ I must gang. My service to ye, ladies!” And off he hobbled.",
          "es": "¡No ves nada gracioso! ¡Ja! ¡Ja! Pero eso es porque no entiendes que la afligida madre era una bruja furiosa que lo odiaba porque era deforme—era un completo tullido—y él la odiaba tanto que se suicidó para que ella no obtuviera el seguro que contrató sobre su vida. Se voló casi la parte superior de la cabeza con un viejo mosquete que tenían para asustar cuervos. No era para cuervos entonces, porque trajo las moscas y los insectos a él. Así es como cayó de las rocas. Y, en cuanto a las esperanzas de una resurrección gloriosa, lo he oído decir muchas veces que esperaba ir al infierno, porque su madre era tan piadosa que seguramente iría al cielo, y él no quería estar donde ella estaba. Ahora, ¿no es esa piedra en cualquier caso\"—la golpeó con su bastón mientras hablaba—\"un montón de mentiras? ¿y no hará reír a Gabriel cuando Geordie suba jadeando los escalones con la lápida equilibrada en su joroba, y pida que sea considerada como evidencia!"
        },
        {
          "en": "Lucy and I sat awhile, and it was all so beautiful before us that we took hands as we sat; and she told me all over again about Arthur and their coming marriage. That made me just a little heart-sick, for I haven’t heard from Jonathan for a whole month.",
          "es": "No sabía qué decir, pero Lucy cambió la conversación cuando se levantó y dijo:—"
        },
        {
          "en": "",
          "es": "¡Oh, por qué nos contaste esto? Este es mi asiento favorito, y no puedo abandonarlo; y ahora descubro que debo seguir sentada sobre la tumba de un suicida."
        }
      ]
    },
    "5": {
      "lines": [
        {
          "en": "The same day. I came up here alone, for I am very sad. There was no letter for me. I hope there cannot be anything the matter with Jonathan. The clock has just struck nine. I see the lights scattered all over the town, sometimes in rows where the streets are, and sometimes singly; they run right up the Esk and die away in the curve of the valley. To my left the view is cut off by a black line of roof of the old house next the abbey. The sheep and lambs are bleating in the fields away behind me, and there is a clatter of a donkey’s hoofs up the paved road below. The band on the pier is playing a harsh waltz in good time, and further along the quay there is a Salvation Army meeting in a back street. Neither of the bands hears the other, but up here I hear and see them both. I wonder where Jonathan is and if he is thinking of me! I wish he were here.",
          "es": "\"Eso no te hará daño, mi bonita; y puede alegrar al pobre Geordie tener a una chica tan elegante sentada en su regazo. Eso no te hará daño. Vaya, he estado sentado aquí de vez en cuando durante casi veinte años, y no me ha hecho daño. ¡No te preocupes por quienes están debajo de ti, o los que no están debajo tampoco! Será hora de que te asustes cuando veas todas las lápidas desaparecidas, y el lugar tan vacío como un campo de rastrojos. Está el reloj, y debo irme. ¡Mi respeto a ustedes, señoras!\" Y se fue cojeando."
        },
        {
          "en": "Dr. Seward’s Diary.",
          "es": "Lucy y yo nos quedamos un rato, y era todo tan hermoso ante nosotros que nos cogimos de las manos mientras estábamos sentadas; y ella me contó todo de nuevo sobre Arthur y su próximo matrimonio. Eso me hizo sentir un poco destrozada, porque no he sabido de Jonathan durante un mes entero."
        },
        {
          "en": "5 June.—The case of Renfield grows more interesting the more I get to understand the man. He has certain qualities very largely developed; selfishness, secrecy, and purpose. I wish I could get at what is the object of the latter. He seems to have some settled scheme of his own, but what it is I do not yet know. His redeeming quality is a love of animals, though, indeed, he has such curious turns in it that I sometimes imagine he is only abnormally cruel. His pets are of odd sorts. Just now his hobby is catching flies. He has at present such a quantity that I have had myself to expostulate. To my astonishment, he did not break out into a fury, as I expected, but took the matter in simple seriousness. He thought for a moment, and then said: “May I have three days? I shall clear them away.” Of course, I said that would do. I must watch him.",
          "es": "El mismo día. Vine aquí sola, porque estoy muy triste. No había carta para mí. Espero que no haya nada malo con Jonathan. El reloj acaba de dar las nueve. Veo las luces esparcidas por todo el pueblo, a veces en hileras donde están las calles, y a veces individuales; corren hacia arriba por el Esk y desaparecen en la curva del valle. A mi izquierda, la vista está cortada por una línea negra del techo de la casa vieja junto a la abadía. Las ovejas y corderos están balando en los campos detrás de mí, y hay un repiqueteo de cascos de burro subiendo la carretera pavimentada abajo. La banda en el muelle toca un vals áspero al compás, y más adelante en el muelle hay una reunión del Ejército de Salvación en una calle trasera. Ninguna de las bandas oye a la otra, pero desde aquí oigo y veo a ambas. ¡Me pregunto dónde está Jonathan y si está pensando en mí! Desearía que estuviera aquí."
        },
        {
          "en": "18 June.—He has turned his mind now to spiders, and has got several very big fellows in a box. He keeps feeding them with his flies, and the number of the latter is becoming sensibly diminished, although he has used half his food in attracting more flies from outside to his room.",
          "es": "Diario del Dr. Seward."
        },
        {
          "en": "1 July.—His spiders are now becoming as great a nuisance as his flies, and to-day I told him that he must get rid of them. He looked very sad at this, so I said that he must clear out some of them, at all events. He cheerfully acquiesced in this, and I gave him the same time as before for reduction. He disgusted me much while with him, for when a horrid blow-fly, bloated with some carrion food, buzzed into the room, he caught it, held it exultantly for a few moments between his finger and thumb, and, before I knew what he was going to do, put it in his mouth and ate it. I scolded him for it, but he argued quietly that it was very good and very wholesome; that it was life, strong life, and gave life to him. This gave me an idea, or the rudiment of one. I must watch how he gets rid of his spiders. He has evidently some deep problem in his mind, for he keeps a little note-book in which he is always jotting down something. Whole pages of it are filled with masses of figures, generally single numbers added up in batches, and then the totals added in batches again, as though he were “focussing” some account, as the auditors put it.",
          "es": "5 de junio.—El caso de Renfield se vuelve más interesante cuanto más llego a entender al hombre. Tiene ciertas cualidades muy desarrolladas; egoísmo, secreto, y propósito. Desearía poder averiguar cuál es el objeto de este último. Parece tener algún plan establecido, pero aún no sé cuál es. Su cualidad que lo redime es un amor por los animales, aunque, en verdad, tiene unos giros tan curiosos en esto que a veces imagino que es solo anormalmente cruel. Sus mascotas son de tipos extraños. Ahora mismo su pasatiempo es atrapar moscas. Tiene actualmente tantas que he tenido que protestar yo mismo. Para mi sorpresa, no estalló en una furia, como esperaba, sino que tomó el asunto con seriedad. Pensó por un momento, y luego dijo: \"¿Puedo tener tres días? Las limpiaré.\" Por supuesto, dije que está bien. Debo observarlo."
        }
      ]
    },
    "6": {
      "lines": [
        {
          "en": "8 July.—There is a method in his madness, and the rudimentary idea in my mind is growing. It will be a whole idea soon, and then, oh, unconscious cerebration! you will have to give the wall to your conscious brother. I kept away from my friend for a few days, so that I might notice if there were any change. Things remain as they were except that he has parted with some of his pets and got a new one. He has managed to get a sparrow, and has already partially tamed it. His means of taming is simple, for already the spiders have diminished. Those that do remain, however, are well fed, for he still brings in the flies by tempting them with his food.",
          "es": "18 de junio.—Ahora ha dirigido su mente a las arañas, y tiene varios especímenes muy grandes en una caja. Las alimenta con sus moscas, y el número de estas está disminuyendo notablemente, aunque ha usado la mitad de su comida atrayendo más moscas de afuera a su habitación."
        },
        {
          "en": "19 July.—We are progressing. My friend has now a whole colony of sparrows, and his flies and spiders are almost obliterated. When I came in he ran to me and said he wanted to ask me a great favour—a very, very great favour; and as he spoke he fawned on me like a dog. I asked him what it was, and he said, with a sort of rapture in his voice and bearing:—",
          "es": "1 de julio.—Sus arañas ahora se están volviendo tan molestas como sus moscas, y hoy le dije que debe deshacerse de ellas. Se veía muy triste por esto, así que dije que debe eliminar algunas de ellas, en todo caso. Estuvo de acuerdo alegremente con esto, y le di el mismo tiempo que antes para la reducción. Me disgusto mucho mientras estaba con él, porque cuando una mosca horrible, hinchada de alguna carroña, zumbó en la habitación, la atrapó, la sostuvo con exultación durante unos momentos entre sus dedos, y, antes de que me diera cuenta de qué iba a hacer, se la metió en la boca y se la comió. Lo regañé por ello, pero él argumentó tranquilamente que era muy bueno y muy saludable; que era vida, vida fuerte, y le daba vida a él. Esto me dio una idea, o el comienzo de una. Debo observar cómo se deshace de sus arañas. Evidentemente tiene algún problema profundo en su mente, porque lleva un pequeño cuaderno en el que siempre está anotando algo. Páginas enteras están llenas de masas de números, generalmente números individuales sumados en lotes, y luego los totales sumados nuevamente en lotes, como si estuviera \"enfocando\" alguna cuenta, como dicen los auditores."
        },
        {
          "en": "“A kitten, a nice little, sleek playful kitten, that I can play with, and teach, and feed—and feed—and feed!” I was not unprepared for this request, for I had noticed how his pets went on increasing in size and vivacity, but I did not care that his pretty family of tame sparrows should be wiped out in the same manner as the flies and the spiders; so I said I would see about it, and asked him if he would not rather have a cat than a kitten. His eagerness betrayed him as he answered:—",
          "es": "8 de julio.—Hay un método en su locura, y la idea rudimentaria en mi mente está creciendo. Será una idea completa pronto, y entonces, ¡oh, pensamiento inconsciente! tendrás que ceder ante tu hermano consciente. Me alejé de mi amigo durante unos días, para que pudiera notar si había algún cambio. Las cosas permanecen como estaban excepto que se ha deshecho de algunas de sus mascotas y ha conseguido una nueva. Ha logrado conseguir un gorrión, y ya lo ha domesticado parcialmente. Su método de domesticación es simple, porque las arañas ya han disminuido. Las que quedan, sin embargo, están bien alimentadas, porque sigue trayendo moscas tentándolas con su comida."
        },
        {
          "en": "“Oh, yes, I would like a cat! I only asked for a kitten lest you should refuse me a cat. No one would refuse me a kitten, would they?” I shook my head, and said that at present I feared it would not be possible, but that I would see about it. His face fell, and I could see a warning of danger in it, for there was a sudden fierce, sidelong look which meant killing. The man is an undeveloped homicidal maniac. I shall test him with his present craving and see how it will work out; then I shall know more.",
          "es": "19 de julio.—Estamos progresando. Mi amigo ahora tiene toda una colonia de gorriones, y sus moscas y arañas casi han desaparecido. Cuando entré, corrió hacia mí y dijo que quería pedirme un gran favor—un favor muy, muy grande; y mientras hablaba se comportaba como un perro adulador. Le pregunté cuál era, y dijo, con una especie de éxtasis en su voz y porte:—"
        },
        {
          "en": "10 p. m.—I have visited him again and found him sitting in a corner brooding. When I came in he threw himself on his knees before me and implored me to let him have a cat; that his salvation depended upon it. I was firm, however, and told him that he could not have it, whereupon he went without a word, and sat down, gnawing his fingers, in the corner where I had found him. I shall see him in the morning early.",
          "es": "\"Un gatito, un gatito bonito, suave y juguetón, con el que pueda jugar, enseñar, y alimentar—y alimentar—y alimentar!\" No estaba desprevenido para esta solicitud, porque había notado cómo sus mascotas seguían aumentando de tamaño y vivacidad, pero no quería que su bonita familia de gorriones domesticados fuera eliminada de la misma manera que las moscas y las arañas; así que dije que vería qué se podía hacer, y le pregunté si no preferiría un gato a un gatito. Su entusiasmo lo traicionó cuando respondió:—"
        },
        {
          "en": "",
          "es": "\"¡Oh, sí, me gustaría un gato! Solo pedí un gatito por si me negaras un gato. ¿Quién me negaría un gatito, verdad?\" Negué con la cabeza, y dije que en este momento temía que no fuera posible, pero que vería qué se podía hacer. Su cara se ensombreció, y pude ver un aviso de peligro en ella, porque había una mirada repentina y feroz, de soslayo que significaba matar. El hombre es un maníaco homicida sin desarrollar. Lo probaré con su actual deseo y veré cómo se desarrolla; entonces sabré más."
        }
      ]
    },
    "7": {
      "lines": [
        {
          "en": "20 July.—Visited Renfield very early, before the attendant went his rounds. Found him up and humming a tune. He was spreading out his sugar, which he had saved, in the window, and was manifestly beginning his fly-catching again; and beginning it cheerfully and with a good grace. I looked around for his birds, and not seeing them, asked him where they were. He replied, without turning round, that they had all flown away. There were a few feathers about the room and on his pillow a drop of blood. I said nothing, but went and told the keeper to report to me if there were anything odd about him during the day.",
          "es": "10 p.m.—Lo he visitado de nuevo y lo he encontrado sentado en una esquina meditando. Cuando entré, se arrodilló ante mí e me implored que le permitiera tener un gato; que su salvación dependía de ello. Fui firme, sin embargo, y le dije que no podía tener uno, con lo cual se fue sin una palabra, y se sentó, royéndose los dedos, en la esquina donde lo había encontrado. Lo voy a ver temprano por la mañana."
        },
        {
          "en": "11 a. m.—The attendant has just been to me to say that Renfield has been very sick and has disgorged a whole lot of feathers. “My belief is, doctor,” he said, “that he has eaten his birds, and that he just took and ate them raw!”",
          "es": "20 de julio.—Visité a Renfield muy temprano, antes de que el asistente hiciera su ronda. Lo encontré levantado y tarareando una melodía. Estaba extendiendo su azúcar, que había ahorrado, en la ventana, y estaba claramente comenzando de nuevo a atrapar moscas; y comenzándolo alegremente y con buena disposición. Miré alrededor buscando sus pájaros, y al no verlos, le pregunté dónde estaban. Respondió, sin darse la vuelta, que todos se habían volado. Había algunas plumas en la habitación y en su almohada una gota de sangre. No dije nada, pero fui y le dije al cuidador que me informara si había algo extraño sobre él durante el día."
        },
        {
          "en": "11 p. m.—I gave Renfield a strong opiate to-night, enough to make even him sleep, and took away his pocket-book to look at it. The thought that has been buzzing about my brain lately is complete, and the theory proved. My homicidal maniac is of a peculiar kind. I shall have to invent a new classification for him, and call him a zoöphagous (life-eating) maniac; what he desires is to absorb as many lives as he can, and he has laid himself out to achieve it in a cumulative way. He gave many flies to one spider and many spiders to one bird, and then wanted a cat to eat the many birds. What would have been his later steps? It would almost be worth while to complete the experiment. It might be done if there were only a sufficient cause. Men sneered at vivisection, and yet look at its results to-day! Why not advance science in its most difficult and vital aspect—the knowledge of the brain? Had I even the secret of one such mind—did I hold the key to the fancy of even one lunatic—I might advance my own branch of science to a pitch compared with which Burdon-Sanderson’s physiology or Ferrier’s brain-knowledge would be as nothing. If only there were a sufficient cause! I must not think too much of this, or I may be tempted; a good cause might turn the scale with me, for may not I too be of an exceptional brain, congenitally?",
          "es": "11 a.m.—El asistente acaba de venir a decirme que Renfield ha estado muy enfermo y ha vomitado un montón de plumas. \"Mi creencia es, doctor\", dijo, \"que se ha comido sus pájaros, ¡y simplemente los tomó y se los comió crudos!\""
        },
        {
          "en": "How well the man reasoned; lunatics always do within their own scope. I wonder at how many lives he values a man, or if at only one. He has closed the account most accurately, and to-day begun a new record. How many of us begin a new record with each day of our lives?",
          "es": "11 p.m.—Le di a Renfield un opiáceo fuerte esta noche, suficiente para hacerlo dormir incluso a él, y le quité su cuaderno de bolsillo para mirarlo. El pensamiento que ha estado zumbando en mi cerebro últimamente está completo, y la teoría está probada. Mi maníaco homicida es de un tipo peculiar. Tendré que inventar una nueva clasificación para él, y llamarlo un maníaco zoófago (que come vida); lo que desea es absorber tantas vidas como pueda, y se ha propuesto lograrlo de manera acumulativa. Dio muchas moscas a una araña y muchas arañas a un pájaro, y luego quería un gato para comerse los muchos pájaros. ¿Cuáles habrían sido sus pasos posteriores? Casi valdría la pena completar el experimento. Podría hacerse si hubiera una causa suficientemente buena. Los hombres se burlaban de la vivisección, ¡pero miren sus resultados hoy! ¿Por qué no avanzar la ciencia en su aspecto más difícil y vital—el conocimiento del cerebro? Si tuviera incluso el secreto de una mente como esa—si tuviera la clave del capricho de incluso un loco—podría llevar mi propia rama de la ciencia a una altura comparada con la cual la fisiología de Burdon-Sanderson o el conocimiento del cerebro de Ferrier serían como nada. ¡Si solo hubiera una causa suficientemente buena! No debo pensar demasiado en esto, o podría estar tentado; una buena causa podría inclinar la balanza conmigo, porque ¿acaso yo también podría tener un cerebro excepcional, congénitamente?"
        },
        {
          "en": "To me it seems only yesterday that my whole life ended with my new hope, and that truly I began a new record. So it will be until the Great Recorder sums me up and closes my ledger account with a balance to profit or loss. Oh, Lucy, Lucy, I cannot be angry with you, nor can I be angry with my friend whose happiness is yours; but I must only wait on hopeless and work. Work! work!",
          "es": "Qué bien razonaba el hombre; los locos siempre lo hacen dentro de su propio alcance. Me pregunto en cuántas vidas valúa él a un hombre, o si solo en una. Ha cerrado la cuenta muy exactamente, y hoy ha comenzado un nuevo registro. ¿Cuántos de nosotros comenzamos un nuevo registro con cada día de nuestras vidas?"
        }
      ]
    },
    "8": {
      "lines": [
        {
          "en": "If I only could have as strong a cause as my poor mad friend there—a good, unselfish cause to make me work—that would be indeed happiness.",
          "es": "Para mí parece que fue solo ayer que toda mi vida terminó con mi nueva esperanza, y que verdaderamente comencé un nuevo registro. Así será hasta que el Gran Registrador me sume y cierre mi cuenta de ledger con un balance de ganancia o pérdida. Oh, Lucy, Lucy, no puedo estar enojado contigo, ni puedo estar enojado con mi amigo cuya felicidad es la tuya; pero solo debo esperar sin esperanza y trabajar. ¡Trabajar! ¡trabajar!"
        },
        {
          "en": "Mina Murray’s Journal.",
          "es": "Si solo pudiera tener una causa tan fuerte como la de mi pobre amigo loco—una causa buena y desinteresada para hacerme trabajar—eso sería verdaderamente felicidad."
        },
        {
          "en": "26 July.—I am anxious, and it soothes me to express myself here; it is like whispering to one’s self and listening at the same time. And there is also something about the shorthand symbols that makes it different from writing. I am unhappy about Lucy and about Jonathan. I had not heard from Jonathan for some time, and was very concerned; but yesterday dear Mr. Hawkins, who is always so kind, sent me a letter from him. I had written asking him if he had heard, and he said the enclosed had just been received. It is only a line dated from Castle Dracula, and says that he is just starting for home. That is not like Jonathan; I do not understand it, and it makes me uneasy. Then, too, Lucy, although she is so well, has lately taken to her old habit of walking in her sleep. Her mother has spoken to me about it, and we have decided that I am to lock the door of our room every night. Mrs. Westenra has got an idea that sleep-walkers always go out on roofs of houses and along the edges of cliffs and then get suddenly wakened and fall over with a despairing cry that echoes all over the place. Poor dear, she is naturally anxious about Lucy, and she tells me that her husband, Lucy’s father, had the same habit; that he would get up in the night and dress himself and go out, if he were not stopped. Lucy is to be married in the autumn, and she is already planning out her dresses and how her house is to be arranged. I sympathise with her, for I do the same, only Jonathan and I will start in life in a very simple way, and shall have to try to make both ends meet. Mr. Holmwood—he is the Hon. Arthur Holmwood, only son of Lord Godalming—is coming up here very shortly—as soon as he can leave town, for his father is not very well, and I think dear Lucy is counting the moments till he comes. She wants to take him up to the seat on the churchyard cliff and show him the beauty of Whitby. I daresay it is the waiting which disturbs her; she will be all right when he arrives.",
          "es": "Diario de Mina Murray."
        },
        {
          "en": "27 July.—No news from Jonathan. I am getting quite uneasy about him, though why I should I do not know; but I do wish that he would write, if it were only a single line. Lucy walks more than ever, and each night I am awakened by her moving about the room. Fortunately, the weather is so hot that she cannot get cold; but still the anxiety and the perpetually being wakened is beginning to tell on me, and I am getting nervous and wakeful myself. Thank God, Lucy’s health keeps up. Mr. Holmwood has been suddenly called to Ring to see his father, who has been taken seriously ill. Lucy frets at the postponement of seeing him, but it does not touch her looks; she is a trifle stouter, and her cheeks are a lovely rose-pink. She has lost that anæmic look which she had. I pray it will all last.",
          "es": "26 de julio.—Estoy ansiosa, y me consuela expresarme aquí; es como susurrarme a mí misma y escucharme al mismo tiempo. Y también hay algo sobre los símbolos de taquigrafía que lo hace diferente de escribir. No estoy feliz respecto a Lucy y respecto a Jonathan. No había sabido de Jonathan durante algún tiempo, y estaba muy preocupada; pero ayer el querido Sr. Hawkins, que es siempre tan amable, me envió una carta de él. Había escrito preguntándole si había sabido algo, y dijo que la carta adjunta acaba de ser recibida. Es solo una línea fechada en el Castillo Drácula, y dice que acaba de comenzar su regreso a casa. Eso no es como Jonathan; no lo entiendo, y me hace sentir incómoda. Además, Lucy, aunque está tan bien, últimamente ha vuelto a su viejo hábito de caminar dormida. Su madre ha hablado conmigo sobre ello, y hemos decidido que debo cerrar la puerta de nuestra habitación todas las noches. La Sra. Westenra tiene la idea de que los sonámbulos siempre salen a los tejados de las casas y por los bordes de los acantilados y luego se despiertan de repente y caen con un grito de desesperación que resuena por todo el lugar. La pobre querida, naturalmente está ansiosa respecto a Lucy, y me dice que su marido, el padre de Lucy, tenía el mismo hábito; que se levantaría por la noche y se vestiría y saldría, si no lo detenían. Lucy se va a casar en el otoño, y ya está planeando sus vestidos y cómo ha de disponerse su casa. Simpatizo con ella, porque hago lo mismo, solo que Jonathan y yo comenzaremos la vida de una manera muy simple, y tendremos que intentar que los gastos no superen los ingresos. El Sr. Holmwood—es el Honorable Arthur Holmwood, único hijo del Conde de Godalming—vendrá aquí muy pronto—tan pronto como pueda dejar la ciudad, porque su padre no está muy bien, y creo que la querida Lucy está contando los momentos hasta que llegue. Quiere llevarlo al asiento en el acantilado del cementerio y mostrarle la belleza de Whitby. Supongo que es la espera la que la perturba; estará bien cuando llegue."
        },
        {
          "en": "3 August.—Another week gone, and no news from Jonathan, not even to Mr. Hawkins, from whom I have heard. Oh, I do hope he is not ill. He surely would have written. I look at that last letter of his, but somehow it does not satisfy me. It does not read like him, and yet it is his writing. There is no mistake of that. Lucy has not walked much in her sleep the last week, but there is an odd concentration about her which I do not understand; even in her sleep she seems to be watching me. She tries the door, and finding it locked, goes about the room searching for the key.",
          "es": "27 de julio.—Sin noticias de Jonathan. Estoy bastante ansiosa respecto a él, aunque no sé por qué; pero desearía que escribiera, aunque fuera solo una línea. Lucy camina más que nunca, y cada noche me despierto por sus movimientos en la habitación. Afortunadamente, el clima es tan caluroso que no puede enfriarse; pero aún así, la ansiedad y el estar constantemente despierta está comenzando a afectarme, y estoy nerviosa e insomne yo misma. Gracias a Dios, la salud de Lucy se mantiene. El Sr. Holmwood ha sido llamado de repente a Ring para ver a su padre, quien ha caído gravemente enfermo. Lucy se lamenta por el aplazamiento de verlo, pero no afecta su apariencia; está un poco más robusta, y sus mejillas tienen un hermoso rosa. Ha perdido ese aspecto pálido que tenía. Rezo para que todo continúe así."
        }
      ]
    },
    "9": {
      "lines": [
        {
          "en": "6 August.—Another three days, and no news. This suspense is getting dreadful. If I only knew where to write to or where to go to, I should feel easier; but no one has heard a word of Jonathan since that last letter. I must only pray to God for patience. Lucy is more excitable than ever, but is otherwise well. Last night was very threatening, and the fishermen say that we are in for a storm. I must try to watch it and learn the weather signs. To-day is a grey day, and the sun as I write is hidden in thick clouds, high over Kettleness. Everything is grey—except the green grass, which seems like emerald amongst it; grey earthy rock; grey clouds, tinged with the sunburst at the far edge, hang over the grey sea, into which the sand-points stretch like grey fingers. The sea is tumbling in over the shallows and the sandy flats with a roar, muffled in the sea-mists drifting inland. The horizon is lost in a grey mist. All is vastness; the clouds are piled up like giant rocks, and there is a “brool” over the sea that sounds like some presage of doom. Dark figures are on the beach here and there, sometimes half shrouded in the mist, and seem “men like trees walking.” The fishing-boats are racing for home, and rise and dip in the ground swell as they sweep into the harbour, bending to the scuppers. Here comes old Mr. Swales. He is making straight for me, and I can see, by the way he lifts his hat, that he wants to talk....",
          "es": "3 de agosto.—Otra semana se ha ido, y sin noticias de Jonathan, ni siquiera del Sr. Hawkins, de quien he sabido. Oh, espero que no esté enfermo. Seguramente habría escrito. Miro esa última carta suya, pero de alguna manera no me satisface. No suena como él, y sin embargo es su escritura. No hay error en eso. Lucy no ha caminado mucho dormida esta última semana, pero hay una concentración extraña respecto a ella que no entiendo; incluso en su sueño parece estar vigilándome. Prueba la puerta, y encontrándola cerrada, busca por la habitación la llave."
        },
        {
          "en": "I have been quite touched by the change in the poor old man. When he sat down beside me, he said in a very gentle way:—",
          "es": "6 de agosto.—Otros tres días, y sin noticias. Esta incertidumbre se está volviendo terrible. Si solo supiera dónde escribir o adónde ir, me sentiría mejor; pero nadie ha sabido nada de Jonathan desde esa última carta. Solo debo rezar a Dios por paciencia. Lucy está más excitable que nunca, pero por lo demás está bien. La noche pasada fue muy amenazante, y los pescadores dicen que nos espera una tormenta. Debo intentar observarla y aprender los signos del clima. Hoy es un día gris, y el sol mientras escribo está oculto en nubes espesas, altas sobre Kettleness. Todo es gris—excepto el pasto verde, que parece una esmeralda entre él; roca gris y terrosa; nubes grises, teñidas con el estallido de sol en el borde lejano, se ciernen sobre el mar gris, en el cual los puntos de arena se extienden como dedos grises. El mar está tumultuando sobre los bajíos y los bajíos arenosos con un rugido, amortiguado en las brumas marinas que se desplazan hacia tierra. El horizonte se pierde en una bruma gris. Todo es vastedad; las nubes están apiladas como rocas gigantes, y hay un gemido sobre el mar que suena como un presagio de perdición. Hay figuras oscuras en la playa aquí y allá, a veces medio envueltas en la bruma, y parecen \"hombres como árboles caminando\". Los botes de pesca están corriendo hacia casa, y suben y bajan en el mar de fondo mientras entran en el puerto, inclinándose hasta los escupidores. Aquí viene el viejo Sr. Swales. Se dirige directamente hacia mí, y puedo ver, por la manera en que se quita el sombrero, que quiere hablar..."
        },
        {
          "en": "“I want to say something to you, miss.” I could see he was not at ease, so I took his poor old wrinkled hand in mine and asked him to speak fully; so he said, leaving his hand in mine:—",
          "es": "He estado muy conmovida por el cambio en el pobre hombre viejo. Cuando se sentó a mi lado, dijo de una manera muy suave:—"
        },
        {
          "en": "“I’m afraid, my deary, that I must have shocked you by all the wicked things I’ve been sayin’ about the dead, and such like, for weeks past; but I didn’t mean them, and I want ye to remember that when I’m gone. We aud folks that be daffled, and with one foot abaft the krok-hooal, don’t altogether like to think of it, and we don’t want to feel scart of it; an’ that’s why I’ve took to makin’ light of it, so that I’d cheer up my own heart a bit. But, Lord love ye, miss, I ain’t afraid of dyin’, not a bit; only I don’t want to die if I can help it. My time must be nigh at hand now, for I be aud, and a hundred years is too much for any man to expect; and I’m so nigh it that the Aud Man is already whettin’ his scythe. Ye see, I can’t get out o’ the habit of caffin’ about it all at once; the chafts will wag as they be used to. Some day soon the Angel of Death will sound his trumpet for me. But don’t ye dooal an’ greet, my deary!”—for he saw that I was crying—“if he should come this very night I’d not refuse to answer his call. For life be, after all, only a waitin’ for somethin’ else than what we’re doin’; and death be all that we can rightly depend on. But I’m content, for it’s comin’ to me, my deary, and comin’ quick. It may be comin’ while we be lookin’ and wonderin’. Maybe it’s in that wind out over the sea that’s bringin’ with it loss and wreck, and sore distress, and sad hearts. Look! look!” he cried suddenly. “There’s something in that wind and in the hoast beyont that sounds, and looks, and tastes, and smells like death. It’s in the air; I feel it comin’. Lord, make me answer cheerful when my call comes!” He held up his arms devoutly, and raised his hat. His mouth moved as though he were praying. After a few minutes’ silence, he got up, shook hands with me, and blessed me, and said good-bye, and hobbled off. It all touched me, and upset me very much.",
          "es": "\"Quiero decirle algo, señorita.\" Pude ver que no estaba a gusto, así que tomé su pobre mano arrugada en la mía y le pedí que hablara completamente; así que dijo, dejando su mano en la mía:—"
        },
        {
          "en": "I was glad when the coastguard came along, with his spy-glass under his arm. He stopped to talk with me, as he always does, but all the time kept looking at a strange ship.",
          "es": "\"Tengo miedo, mi querida, de que debo haberla chocado con todas las cosas malvadas que he estado diciendo sobre los muertos, y cosas así, durante semanas; pero no las pensaba, y quiero que recuerde eso cuando me haya ido. Nosotros los viejos que estamos confundidos, y con un pie al otro lado de la puerta, no queremos del todo pensar en ello, y no queremos sentirnos asustados de ello; y por eso he tomado a burlarse de ello, para alegrar mi propio corazón un poco. Pero, por amor del cielo, señorita, no tengo miedo de morir, ni un poco; solo no quiero morir si puedo evitarlo. Mi tiempo debe estar cerca ahora, porque estoy viejo, y cien años es demasiado para que cualquier hombre espere; y estoy tan cerca que el Viejo Segador ya está afilando su guadaña. Ves, no puedo dejarme de bromear sobre ello todo a la vez; la lengua hablará como está acostumbrada. Algún día pronto el Ángel de la Muerte tocará su trompeta para mí. Pero no llores ni grites, mi querida\"—porque vio que estaba llorando—\"si viniera precisamente esta noche no me negaría a responder su llamada. Porque la vida es, después de todo, solo una espera de algo más de lo que estamos haciendo; y la muerte es todo en lo que podemos confiar verdaderamente. Pero estoy contento, porque viene hacia mí, mi querida, y viene rápido. Puede venir mientras estemos mirando y preguntándonos. Quizá esté en ese viento sobre el mar que trae consigo pérdida y naufragio, y angustia grave, y corazones tristes. ¡Mira! ¡mira!\" gritó de repente. \"Hay algo en ese viento y en el gemido más allá que suena, se ve, se siente, y huele a muerte. Está en el aire; lo siento venir. ¡Señor, hazme responder alegremente cuando venga mi llamada!\" Levantó los brazos devotamente, y se quitó el sombrero. Su boca se movía como si estuviera rezando. Después de unos minutos de silencio, se levantó, me estrechó la mano, me bendijo, y se despidió, y se fue cojeando. Todo ello me conmovió mucho y me perturbó."
        }
      ]
    },
    "10": {
      "lines": [
        {
          "en": "“I can’t make her out,” he said; “she’s a Russian, by the look of her; but she’s knocking about in the queerest way. She doesn’t know her mind a bit; she seems to see the storm coming, but can’t decide whether to run up north in the open, or to put in here. Look there again! She is steered mighty strangely, for she doesn’t mind the hand on the wheel; changes about with every puff of wind. We’ll hear more of her before this time to-morrow.”",
          "es": "Me alegró cuando llegó el guardacostas, con su catalejo bajo el brazo. Se detuvo para hablar conmigo, como siempre lo hace, pero todo el tiempo estuvo mirando un barco extraño."
        },
        {
          "en": "",
          "es": "No puedo identificarlo\", dijo; \"parece ser un ruso, por su aspecto; pero está merodeando de la manera más extraña. No se decide en absoluto; parece que ve la tormenta acercándose, pero no puede decidirse entre correr hacia el norte en el mar abierto, o entrar aquí. ¡Mira allá de nuevo! Está siendo dirigido de manera muy extraña, porque no obedece la mano del timón; cambia con cada ráfaga de viento. Nos enteraremos de más sobre él antes de estas fechas mañana."
        }
      ]
    }
  }
};
