export const chapterContent = {
  "storySlug": "the-adventures-of-tom-sawyer",
  "level": 5,
  "chapter": 21,
  "pages": {
    "1": {
      "lines": [
        {
          "en": "Vacation was approaching. The schoolmaster, always severe, grew severer and more exacting than ever, for he wanted the school to make a good showing on “Examination” day. His rod and his ferule were seldom idle now—at least among the smaller pupils. Only the biggest boys, and young ladies of eighteen and twenty, escaped lashing. Mr. Dobbins’ lashings were very vigorous ones, too; for although he carried, under his wig, a perfectly bald and shiny head, he had only reached middle age, and there was no sign of feebleness in his muscle. As the great day approached, all the tyranny that was in him came to the surface; he seemed to take a vindictive pleasure in punishing the least shortcomings. The consequence was, that the smaller boys spent their days in terror and suffering and their nights in plotting revenge. They threw away no opportunity to do the master a mischief. But he kept ahead all the time. The retribution that followed every vengeful success was so sweeping and majestic that the boys always retired from the field badly worsted. At last they conspired together and hit upon a plan that promised a dazzling victory. They swore in the signpainter’s boy, told him the scheme, and asked his help. He had his own reasons for being delighted, for the master boarded in his father’s family and had given the boy ample cause to hate him. The master’s wife would go on a visit to the country in a few days, and there would be nothing to interfere with the plan; the master always prepared himself for great occasions by getting pretty well fuddled, and the signpainter’s boy said that when the dominie had reached the proper condition on Examination Evening he would “manage the thing” while he napped in his chair; then he would have him awakened at the right time and hurried away to school.",
          "es": "Las vacaciones se acercaban. El maestro, siempre severo, se volvió más severo y exigente que nunca, pues deseaba que la escuela luciera impecable el día del \"Examen\". Su vara y su palmeta apenas descansaban ahora, al menos entre los alumnos más pequeños. Solo los chicos más grandes y las jóvenes de dieciocho y veinte años escapaban de los castigos. Los castigos del señor Dobbins eran muy vigorosos, además; aunque llevaba bajo su peluca una cabeza perfectamente calva y reluciente, apenas había alcanzado la mediana edad, y no había ningún signo de debilidad en su musculatura. Conforme se acercaba el gran día, toda la tiranía que llevaba dentro salió a la superficie; parecía experimentar un placer vengativo al castigar las faltas más insignificantes. La consecuencia fue que los chicos más pequeños pasaban los días aterrados y sufriendo, y las noches tramando venganza. No dejaban pasar ninguna oportunidad de perjudicar al maestro. Pero él siempre estaba un paso adelante. La represalia que seguía a cada venganza exitosa era tan arrolladora y majestuosa que los chicos siempre se retiraban del campo completamente derrotados. Finalmente conspiraron juntos y concibieron un plan que prometía una victoria deslumbrante. Juramentaron al hijo del pintor de señales, le explicaron el esquema y pidieron su ayuda. Él tenía sus propias razones para estar encantado, pues el maestro se hospedaba en casa de su padre y le había dado amplio motivo para odiarlo. La esposa del maestro viajaría al campo en unos pocos días, y nada interferiría con el plan; el maestro siempre se preparaba para las grandes ocasiones emborrachándose bastante, y el hijo del pintor de señales dijo que cuando el dominie hubiera alcanzado el estado apropiado la noche del Examen, él \"manejaría el asunto\" mientras dormitaba en su silla; entonces lo despertaría en el momento oportuno y lo apresuraría hacia la escuela."
        },
        {
          "en": "In the fulness of time the interesting occasion arrived. At eight in the evening the schoolhouse was brilliantly lighted, and adorned with wreaths and festoons of foliage and flowers. The master sat throned in his great chair upon a raised platform, with his blackboard behind him. He was looking tolerably mellow. Three rows of benches on each side and six rows in front of him were occupied by the dignitaries of the town and by the parents of the pupils. To his left, back of the rows of citizens, was a spacious temporary platform upon which were seated the scholars who were to take part in the exercises of the evening; rows of small boys, washed and dressed to an intolerable state of discomfort; rows of gawky big boys; snowbanks of girls and young ladies clad in lawn and muslin and conspicuously conscious of their bare arms, their grandmothers’ ancient trinkets, their bits of pink and blue ribbon and the flowers in their hair. All the rest of the house was filled with non-participating scholars.",
          "es": "Con el paso del tiempo llegó la ocasión tan esperada. A las ocho de la noche la escuela estaba brillantemente iluminada y adornada con guirnaldas y festones de follaje y flores. El maestro estaba sentado en su gran silla sobre una plataforma elevada, con su pizarra detrás de él. Se veía bastante animado. Tres filas de bancos a cada lado y seis filas frente a él estaban ocupadas por los personajes notables del pueblo y por los padres de los alumnos. A su izquierda, detrás de las filas de ciudadanos, había una amplia plataforma temporal donde estaban sentados los estudiantes que participarían en los ejercicios de la noche; filas de niños pequeños, lavados y vestidos con una incomodidad intolerable; filas de muchachos grandes y desgarbados; masas blancas de chicas y jóvenes vestidas con muselina y tela de algodón, conspicuamente conscientes de sus brazos desnudos, los trinquetes antiguos de sus abuelas, sus listones rosa y azul y las flores en su cabello. El resto de la casa estaba lleno de estudiantes que no participaban."
        },
        {
          "en": "The exercises began. A very little boy stood up and sheepishly recited, “You’d scarce expect one of my age to speak in public on the stage,” etc.—accompanying himself with the painfully exact and spasmodic gestures which a machine might have used—supposing the machine to be a trifle out of order. But he got through safely, though cruelly scared, and got a fine round of applause when he made his manufactured bow and retired.",
          "es": "Los ejercicios comenzaron. Un niño muy pequeño se puso de pie y recitó tímidamente: \"Apenas esperarías que uno de mi edad hable en público en el escenario\", etc., acompañándose con gestos dolorosamente exactos y espasmódicos que una máquina podría haber utilizado, suponiendo que la máquina estuviera un poco averiada. Pero logró terminarlo sin problemas, aunque asustado cruamente, y recibió una ronda magnífica de aplausos cuando hizo su reverencia fabricada y se retiró."
        },
        {
          "en": "A little shamefaced girl lisped, “Mary had a little lamb,” etc., performed a compassion-inspiring curtsy, got her meed of applause, and sat down flushed and happy.",
          "es": "Una niña avergonzada pronunció con ceceo: \"María tenía un cordero pequeño\", etc., realizó una reverencia inspiradora de compasión, obtuvo su merecido aplauso y se sentó sonrojada y feliz."
        },
        {
          "en": "Tom Sawyer stepped forward with conceited confidence and soared into the unquenchable and indestructible “Give me liberty or give me death” speech, with fine fury and frantic gesticulation, and broke down in the middle of it. A ghastly stage-fright seized him, his legs quaked under him and he was like to choke. True, he had the manifest sympathy of the house but he had the house’s silence, too, which was even worse than its sympathy. The master frowned, and this completed the disaster. Tom struggled awhile and then retired, utterly defeated. There was a weak attempt at applause, but it died early.",
          "es": "Tom Sawyer avanzó con confianza arrogante y se lanzó al discurso inextinguible e indestructible de \"Dame la libertad o dame la muerte\", con furor fino y gesticulation frenética, y se derrumbó en medio de él. Un miedo escénico horrible lo apresó, sus piernas temblaban bajo él y casi se ahoga. Es verdad que tenía la simpatía manifiesta de la audiencia, pero también tenía el silencio de la audiencia, que era aún peor que su simpatía. El maestro frunció el ceño, y esto completó el desastre. Tom forcejó un rato y luego se retiró, completamente derrotado. Hubo un intento débil de aplausos, pero murió temprano."
        },
        {
          "en": "“The Boy Stood on the Burning Deck” followed; also “The Assyrian Came Down,” and other declamatory gems. Then there were reading exercises, and a spelling fight. The meagre Latin class recited with honor. The prime feature of the evening was in order, now—original “compositions” by the young ladies. Each in her turn stepped forward to the edge of the platform, cleared her throat, held up her manuscript (tied with dainty ribbon), and proceeded to read, with labored attention to “expression” and punctuation. The themes were the same that had been illuminated upon similar occasions by their mothers before them, their grandmothers, and doubtless all their ancestors in the female line clear back to the Crusades. “Friendship” was one; “Memories of Other Days”; “Religion in History”; “Dream Land”; “The Advantages of Culture”; “Forms of Political Government Compared and Contrasted”; “Melancholy”; “Filial Love”; “Heart Longings,” etc., etc.",
          "es": "\"El Chico Estaba en la Cubierta Ardiente\" siguió; también \"El Asirio Descendió\", y otras joyas de declamación. Luego hubo ejercicios de lectura y una competencia de deletreo. La clase de latín exigua recitó con honor. La característica principal de la noche estaba lista ahora, las \"composiciones\" originales de las jóvenes. Cada una a su turno avanzó hacia el borde de la plataforma, se aclaró la garganta, levantó su manuscrito (atado con un listón delicado) y procedió a leer, con atención laboriosa a la \"expresión\" y la puntuación. Los temas eran los mismos que habían sido iluminados en ocasiones similares por sus madres antes que ellas, sus abuelas, y sin duda todos sus ancestros en la línea femenina hasta las Cruzadas. \"La Amistad\" era uno; \"Memorias de Otros Días\"; \"La Religión en la Historia\"; \"La Tierra de los Sueños\"; \"Las Ventajas de la Cultura\"; \"Formas de Gobierno Político Comparadas y Contrastadas\"; \"Melancolía\"; \"Amor Filial\"; \"Anhelos del Corazón\", etc., etc."
        },
        {
          "en": "A prevalent feature in these compositions was a nursed and petted melancholy; another was a wasteful and opulent gush of “fine language”; another was a tendency to lug in by the ears particularly prized words and phrases until they were worn entirely out; and a peculiarity that conspicuously marked and marred them was the inveterate and intolerable sermon that wagged its crippled tail at the end of each and every one of them. No matter what the subject might be, a brainracking effort was made to squirm it into some aspect or other that the moral and religious mind could contemplate with edification. The glaring insincerity of these sermons was not sufficient to compass the banishment of the fashion from the schools, and it is not sufficient today; it never will be sufficient while the world stands, perhaps. There is no school in all our land where the young ladies do not feel obliged to close their compositions with a sermon; and you will find that the sermon of the most frivolous and the least religious girl in the school is always the longest and the most relentlessly pious. But enough of this. Homely truth is unpalatable.",
          "es": "Una característica prevalente en estas composiciones era una melancolía cultivada y mimada; otra era un derroche opulento de \"lenguaje refinado\"; otra era una tendencia a traer por las orejas palabras y frases particularmente valoradas hasta que se desgastaban completamente; y una peculiaridad que las marcaba y echaba a perder conspicuamente era el sermón inveterado e intolerable que movía su cola lisiada al final de cada una de ellas. No importaba cuál fuera el tema, se hacía un esfuerzo que rompía el cerebro para retorcerlo en algún aspecto que la mente moral y religiosa pudiera contemplar con edificación. La desvergüenza flagrante de estos sermones no fue suficiente para lograr el destierro de la moda de las escuelas, y no es suficiente hoy; nunca será suficiente mientras el mundo exista, quizás. No hay escuela en toda nuestra tierra donde las jóvenes no se sientan obligadas a cerrar sus composiciones con un sermón; y encontrará que el sermón de la chica más frívola y menos religiosa de la escuela es siempre el más largo y el más despiadadamente piadoso. Pero basta de esto. La verdad sencilla es desagradable."
        },
        {
          "en": "Let us return to the “Examination.” The first composition that was read was one entitled “Is this, then, Life?” Perhaps the reader can endure an extract from it:",
          "es": "Volvamos al \"Examen\". La primera composición que se leyó fue una titulada \"¿Es esto, entonces, la Vida?\". Quizás el lector pueda soportar un fragmento de ella:"
        }
      ]
    },
    "2": {
      "lines": [
        {
          "en": "“In the common walks of life, with what delightful emotions does the youthful mind look forward to some anticipated scene of festivity! Imagination is busy sketching rose-tinted pictures of joy. In fancy, the voluptuous votary of fashion sees herself amid the festive throng, ‘the observed of all observers.’ Her graceful form, arrayed in snowy robes, is whirling through the mazes of the joyous dance; her eye is brightest, her step is lightest in the gay assembly.",
          "es": "\"En los caminos comunes de la vida, ¡con qué emociones deliciosas la mente juvenil espera ansiosamente alguna escena anticipada de festividad! La imaginación está ocupada esbozando cuadros teñidos de rosa de alegría. En la fantasía, la votaria voluptuosa de la moda se ve a sí misma entre la multitud festiva, 'la observada de todos los observadores'. Su forma grácil, ataviada con ropas níveas, gira a través de los laberintos de la danza gozosa; su ojo es el más brillante, su paso es el más ligero en la asamblea alegre."
        },
        {
          "en": "“In such delicious fancies time quickly glides by, and the welcome hour arrives for her entrance into the Elysian world, of which she has had such bright dreams. How fairy-like does everything appear to her enchanted vision! Each new scene is more charming than the last. But after a while she finds that beneath this goodly exterior, all is vanity, the flattery which once charmed her soul, now grates harshly upon her ear; the ballroom has lost its charms; and with wasted health and imbittered heart, she turns away with the conviction that earthly pleasures cannot satisfy the longings of the soul!”",
          "es": "\"En tales fantasías deliciosas el tiempo pasa rápidamente, y llega la hora anhelada para su entrada en el mundo Eliseo, del cual ha tenido tales sueños radiantes. ¡Cuán feérico parece todo a su visión encantada! Cada nueva escena es más encantadora que la anterior. Pero después de un tiempo descubre que bajo este exterior digno, todo es vanidad, el halago que una vez encantaba su alma, ahora le raspa cruelmente el oído; el salón de baile ha perdido sus encantos; y con la salud desperdiciada y el corazón amargado, se aparta con la convicción de que los placeres terrenales no pueden satisfacer los anhelos del alma\".”"
        },
        {
          "en": "And so forth and so on. There was a buzz of gratification from time to time during the reading, accompanied by whispered ejaculations of “How sweet!” “How eloquent!” “So true!” etc., and after the thing had closed with a peculiarly afflicting sermon the applause was enthusiastic.",
          "es": "Y así sucesivamente. Hubo un zumbido de satisfacción de vez en cuando durante la lectura, acompañado de exclamaciones susurradas de \"¡Qué dulce!\" \"¡Qué elocuente!\" \"¡Tan cierto!\" etc., y después de que la cosa hubiera terminado con un sermón particularmente angustioso, los aplausos fueron entusiastas."
        },
        {
          "en": "Then arose a slim, melancholy girl, whose face had the “interesting” paleness that comes of pills and indigestion, and read a “poem.” Two stanzas of it will do:",
          "es": "Entonces se levantó una chica delgada y melancólica, cuya cara tenía la palidez \"interesante\" que proviene de las píldoras y la indigestión, y leyó un \"poema\". Dos estrofas de él bastarán:"
        },
        {
          "en": "“A MISSOURI MAIDEN’S FAREWELL TO ALABAMA",
          "es": "\"LA DESPEDIDA DE UNA DONCELLA DE MISURI A ALABAMA"
        },
        {
          "en": "“Alabama, goodbye! I love thee well! But yet for a while do I leave thee now! Sad, yes, sad thoughts of thee my heart doth swell, And burning recollections throng my brow! For I have wandered through thy flowery woods; Have roamed and read near Tallapoosa’s stream; Have listened to Tallassee’s warring floods, And wooed on Coosa’s side Aurora’s beam.",
          "es": "\"Alabama, ¡adiós! ¡Te amo bien! Pero por un tiempo te dejo ahora! Tristes, sí, tristes pensamientos de ti mi corazón se hincha, ¡Y ardientes recuerdos abarrotan mi frente! Pues he vagado a través de tus bosques floridos; He viajado y leído cerca del arroyo Tallapoosa; He escuchado los torrentes guerreros de Tallassee, Y cortejado en la orilla de Coosa el rayo de Aurora."
        },
        {
          "en": "“Yet shame I not to bear an o’erfull heart, Nor blush to turn behind my tearful eyes; ’Tis from no stranger land I now must part, ’Tis to no strangers left I yield these sighs. Welcome and home were mine within this State, Whose vales I leave—whose spires fade fast from me And cold must be mine eyes, and heart, and tête, When, dear Alabama! they turn cold on thee!”",
          "es": "\"Y no me avergüenza llevar un corazón desbordante, Ni me ruborizo al dar vuelta mis ojos llenos de lágrimas; No es de tierra extraña que ahora debo partir, No es a extraños dejados que cedo estos suspiros. Bienvenida y hogar fueron míos dentro de este Estado, Cuyos valles dejo, cuyas agujas se desvanecen rápido de mí, Y fría debe ser mi vista, y corazón, y tête, Cuando, ¡querida Alabama! se vuelvan fríos hacia ti\".”"
        },
        {
          "en": "There were very few there who knew what “tête” meant, but the poem was very satisfactory, nevertheless.",
          "es": "Había muy pocas personas allí que supieran qué significaba \"tête\", pero el poema fue muy satisfactorio, de todas formas."
        }
      ]
    },
    "3": {
      "lines": [
        {
          "en": "Next appeared a dark-complexioned, black-eyed, black-haired young lady, who paused an impressive moment, assumed a tragic expression, and began to read in a measured, solemn tone:",
          "es": "Luego apareció una joven de complexión oscura, ojos negros y cabello negro, quien hizo una pausa impresionante, asumió una expresión trágica y comenzó a leer en un tono medido y solemne:"
        },
        {
          "en": "A VISION",
          "es": "UNA VISIÓN"
        },
        {
          "en": "Dark and tempestuous was night. Around the throne on high not a single star quivered; but the deep intonations of the heavy thunder constantly vibrated upon the ear; whilst the terrific lightning revelled in angry mood through the cloudy chambers of heaven, seeming to scorn the power exerted over its terror by the illustrious Franklin! Even the boisterous winds unanimously came forth from their mystic homes, and blustered about as if to enhance by their aid the wildness of the scene.",
          "es": "Oscura y tempestuosa era la noche. Alrededor del trono en lo alto ni una sola estrella temblaba; pero las entonaciones profundas del trueno pesado vibraban constantemente en el oído; mientras que el rayo aterrador se regocijaba en estado airado a través de las cámaras nubosas del cielo, pareciendo desdeñar el poder ejercido sobre su terror por el ilustre Franklin. Incluso los vientos borrascosos unánimemente salieron de sus hogares místicos, y sopló alrededor como si para mejorar por su ayuda la salvajedad de la escena."
        },
        {
          "en": "At such a time, so dark, so dreary, for human sympathy my very spirit sighed; but instead thereof,",
          "es": "En tal momento, tan oscuro, tan desolado, por simpatía humana mi mismo espíritu suspiraba; pero en su lugar,"
        },
        {
          "en": "‘My dearest friend, my counsellor, my comforter and guide— My joy in grief, my second bliss in joy,’ came to my side.",
          "es": "\"Mi queridísimo amigo, mi consejero, mi consolador y guía, Mi alegría en el duelo, mi segunda dicha en la alegría\", vino a mi lado."
        },
        {
          "en": "She moved like one of those bright beings pictured in the sunny walks of fancy’s Eden by the romantic and young, a queen of beauty unadorned save by her own transcendent loveliness. So soft was her step, it failed to make even a sound, and but for the magical thrill imparted by her genial touch, as other unobtrusive beauties, she would have glided away unperceived—unsought. A strange sadness rested upon her features, like icy tears upon the robe of December, as she pointed to the contending elements without, and bade me contemplate the two beings presented.",
          "es": "Se movía como uno de esos seres radiantes pintados en los paseos soleados del Edén de la fantasía por los románticos y jóvenes, una reina de belleza sin adorno excepto por su propia hermosura trascendente. Tan suave era su paso que no producía ni un sonido, y de no ser por el escalofrío mágico impartido por su toque genial, como otras bellezas discretas, se habría deslizado imperceptible, sin ser buscada. Una extraña tristeza reposaba sobre sus facciones, como lágrimas heladas sobre la túnica de diciembre, mientras señalaba los elementos contendientes afuera y me instaba a contemplar a los dos seres presentados."
        },
        {
          "en": "This nightmare occupied some ten pages of manuscript and wound up with a sermon so destructive of all hope to non-Presbyterians that it took the first prize. This composition was considered to be the very finest effort of the evening. The mayor of the village, in delivering the prize to the author of it, made a warm speech in which he said that it was by far the most “eloquent” thing he had ever listened to, and that Daniel Webster himself might well be proud of it.",
          "es": "Esta pesadilla ocupaba alrededor de diez páginas de manuscrito y terminaba con un sermón tan destructivo para toda esperanza para los no presbiterianos que ganó el primer premio. Esta composición fue considerada el esfuerzo más fino de la noche. El alcalde del pueblo, al entregar el premio al autor, pronunció un discurso cálido en el cual dijo que era con mucho lo más \"elocuente\" que jamás había escuchado, y que el propio Daniel Webster bien podría estar orgulloso de ello."
        },
        {
          "en": "It may be remarked, in passing, that the number of compositions in which the word “beauteous” was over-fondled, and human experience referred to as “life’s page,” was up to the usual average.",
          "es": "Puede observarse, de paso, que el número de composiciones en las cuales la palabra \"hermoso\" fue excesivamente acariciada, y la experiencia humana se refirió como \"la página de la vida\", fue hasta el promedio acostumbrado."
        }
      ]
    },
    "4": {
      "lines": [
        {
          "en": "Now the master, mellow almost to the verge of geniality, put his chair aside, turned his back to the audience, and began to draw a map of America on the blackboard, to exercise the geography class upon. But he made a sad business of it with his unsteady hand, and a smothered titter rippled over the house. He knew what the matter was, and set himself to right it. He sponged out lines and remade them; but he only distorted them more than ever, and the tittering was more pronounced. He threw his entire attention upon his work, now, as if determined not to be put down by the mirth. He felt that all eyes were fastened upon him; he imagined he was succeeding, and yet the tittering continued; it even manifestly increased. And well it might. There was a garret above, pierced with a scuttle over his head; and down through this scuttle came a cat, suspended around the haunches by a string; she had a rag tied about her head and jaws to keep her from mewing; as she slowly descended she curved upward and clawed at the string, she swung downward and clawed at the intangible air. The tittering rose higher and higher—the cat was within six inches of the absorbed teacher’s head—down, down, a little lower, and she grabbed his wig with her desperate claws, clung to it, and was snatched up into the garret in an instant with her trophy still in her possession! And how the light did blaze abroad from the master’s bald pate—for the signpainter’s boy had gilded it!",
          "es": "Ahora el maestro, animado casi hasta el borde de la genialidad, apartó su silla, dio la vuelta a la audiencia y comenzó a dibujar un mapa de América en la pizarra, para ejercitar a la clase de geografía. Pero hizo un pésimo trabajo con su mano inestable, y una risa sofocada ondulé sobre la casa. Él sabía qué era lo que pasaba y se propuso arreglarlo. Borró líneas y las rehizo; pero solo las distorsionó más que antes, y la risa fue más pronunciada. Concentró toda su atención en su trabajo ahora, como si estuviera decidido a no ser vencido por la diversión. Sentía que todos los ojos estaban fijos en él; se imaginaba que tenía éxito, y sin embargo la risa continuaba; incluso aumentaba manifiestamente. Y bien podría hacerlo. Había una buhardilla arriba, atravesada por una claraboya sobre su cabeza; y a través de esta claraboya bajaba un gato, suspendido por los cuartos traseros con una cuerda; tenía un trapo atado alrededor de la cabeza y las mandíbulas para evitar que maullara; mientras descendía lentamente se curvaba hacia arriba y arañaba la cuerda, se balanceaba hacia abajo y arañaba el aire intangible. La risa subió más y más, el gato estaba a seis pulgadas de la cabeza del maestro absorto, abajo, abajo, un poco más bajo, ¡y agarró su peluca con sus garras desesperadas, se aferró a ella, y fue arrebatado hacia la buhardilla en un instante con su trofeo aún en su posesión! ¡Y cómo brillaba la luz desde la coronilla calva del maestro, pues el hijo del pintor de señales la había dorado!"
        },
        {
          "en": "That broke up the meeting. The boys were avenged. Vacation had come.",
          "es": "Eso terminó la reunión. Los chicos fueron vengados. Las vacaciones habían llegado."
        },
        {
          "en": "[*] NOTE:—The pretended “compositions” quoted in this chapter are taken without alteration from a volume entitled “Prose and Poetry, by a Western Lady”—but they are exactly and precisely after the schoolgirl pattern, and hence are much happier than any mere imitations could be.",
          "es": "[*] NOTA: Las \"composiciones\" supuestamente citadas en este capítulo se toman sin alteración de un volumen titulado \"Prosa y Poesía, por una Dama Occidental\", pero son exacta y precisamente conforme al patrón de composición escolar, y por lo tanto son mucho más felices que cualquier mera imitación podría serlo."
        }
      ]
    }
  }
};
