export const chapterContent = {
  "storySlug": "the-adventures-of-tom-sawyer",
  "level": 5,
  "chapter": 3,
  "pages": {
    "1": {
      "lines": [
        {
          "en": "Tom presented himself before Aunt Polly, who was sitting by an open window in a pleasant rearward apartment, which was bedroom, breakfast-room, dining-room, and library, combined. The balmy summer air, the restful quiet, the odor of the flowers, and the drowsing murmur of the bees had had their effect, and she was nodding over her knitting—for she had no company but the cat, and it was asleep in her lap. Her spectacles were propped up on her gray head for safety. She had thought that of course Tom had deserted long ago, and she wondered at seeing him place himself in her power again in this intrepid way. He said: “Mayn’t I go and play now, aunt?”",
          "es": "Tom se presentó ante la tía Polly, quien estaba sentada junto a una ventana abierta en un agradable aposento trasero que funcionaba como dormitorio, comedor, sala de desayunos y biblioteca al mismo tiempo. El aire veraniego perfumado, la quietud reconfortante, el aroma de las flores y el murmullo adormecedor de las abejas habían ejercido su efecto, y ella cabeceba sobre su tejido—pues no tenía más compañía que el gato, quien dormía en su regazo. Sus lentes estaban colocados sobre su cabeza gris por seguridad. Había pensado que, por supuesto, Tom se había marchado hace mucho tiempo, y le sorprendía verlo colocarse nuevamente en su poder de manera tan audaz. Él dijo: \"¿Puedo irme a jugar ahora, tía?\""
        },
        {
          "en": "“What, a’ready? How much have you done?”",
          "es": "\"¿Cómo, ¿ya? ¿Cuánto has hecho?\""
        },
        {
          "en": "“It’s all done, aunt.”",
          "es": "\"Ya está todo hecho, tía.\""
        },
        {
          "en": "“Tom, don’t lie to me—I can’t bear it.”",
          "es": "\"Tom, no me mientas—no puedo soportarlo.\""
        },
        {
          "en": "“I ain’t, aunt; it is all done.”",
          "es": "\"No estoy mintiendo, tía; está todo hecho.\""
        },
        {
          "en": "Aunt Polly placed small trust in such evidence. She went out to see for herself; and she would have been content to find twenty per cent. of Tom’s statement true. When she found the entire fence white-washed, and not only whitewashed but elaborately coated and recoated, and even a streak added to the ground, her astonishment was almost unspeakable. She said:",
          "es": "La tía Polly depositaba poca confianza en tales evidencias. Salió a verificar por sí misma; y habría estado conforme con encontrar un veinte por ciento de lo que Tom afirmaba siendo verdad. Cuando descubrió la cerca completamente encalada, y no solo encalada sino elaboradamente cubierta y recubierta, e incluso un trazo añadido al suelo, su asombro fue casi indecible. Ella dijo:"
        },
        {
          "en": "“Well, I never! There’s no getting round it, you can work when you’re a mind to, Tom.” And then she diluted the compliment by adding, “But it’s powerful seldom you’re a mind to, I’m bound to say. Well, go ’long and play; but mind you get back some time in a week, or I’ll tan you.”",
          "es": "\"¡Bueno, nunca! No hay forma de negarlo, puedes trabajar cuando te lo propones, Tom.\" Y luego diluyó el cumplido añadiendo: \"Pero es extraordinariamente raro que te lo propongas, debo decir. Bueno, vete a jugar; pero procura volver en algún momento dentro de una semana, o te daré una paliza.\""
        },
        {
          "en": "She was so overcome by the splendor of his achievement that she took him into the closet and selected a choice apple and delivered it to him, along with an improving lecture upon the added value and flavor a treat took to itself when it came without sin through virtuous effort. And while she closed with a happy Scriptural flourish, he “hooked” a doughnut.",
          "es": "Estaba tan abrumada por la magnitud de su logro que lo llevó al armario y seleccionó una manzana exquisita y se la entregó, junto con una conferencia edificante sobre el valor añadido y el sabor que un obsequio adquiría cuando llegaba sin pecado a través del esfuerzo virtuoso. Y mientras ella cerraba con un floreo bíblico dichoso, él \"se apropió\" de una rosquilla."
        }
      ]
    },
    "2": {
      "lines": [
        {
          "en": "Then he skipped out, and saw Sid just starting up the outside stairway that led to the back rooms on the second floor. Clods were handy and the air was full of them in a twinkling. They raged around Sid like a hail-storm; and before Aunt Polly could collect her surprised faculties and sally to the rescue, six or seven clods had taken personal effect, and Tom was over the fence and gone. There was a gate, but as a general thing he was too crowded for time to make use of it. His soul was at peace, now that he had settled with Sid for calling attention to his black thread and getting him into trouble.",
          "es": "Luego salió corriendo y vio a Sid justo iniciando el ascenso por la escalera exterior que conducía a las habitaciones traseras del segundo piso. Terrones de tierra estaban a mano y el aire se llenó de ellos en un instante. Volaban alrededor de Sid como una granizada; y antes de que la tía Polly pudiera recuperar sus facultades sorprendidas y acudir al rescate, seis o siete terrones habían tenido efecto personal, y Tom estaba sobre la cerca y había desaparecido. Había una puerta, pero generalmente estaba demasiado apremiado de tiempo para hacer uso de ella. Su alma estaba en paz, ahora que había saldado cuentas con Sid por llamar la atención sobre su hilo negro y meterlo en problemas."
        },
        {
          "en": "Tom skirted the block, and came round into a muddy alley that led by the back of his aunt’s cow-stable. He presently got safely beyond the reach of capture and punishment, and hastened toward the public square of the village, where two “military” companies of boys had met for conflict, according to previous appointment. Tom was General of one of these armies, Joe Harper (a bosom friend) General of the other. These two great commanders did not condescend to fight in person—that being better suited to the still smaller fry—but sat together on an eminence and conducted the field operations by orders delivered through aides-de-camp. Tom’s army won a great victory, after a long and hard-fought battle. Then the dead were counted, prisoners exchanged, the terms of the next disagreement agreed upon, and the day for the necessary battle appointed; after which the armies fell into line and marched away, and Tom turned homeward alone.",
          "es": "Tom rodeó la manzana y entró en un callejón fangoso que llevaba por detrás del establo de vacas de su tía. Pronto se encontró más allá del alcance de la captura y el castigo, y se apresuró hacia la plaza pública del pueblo, donde dos compañías \"militares\" de chicos se habían reunido para el conflicto, según una cita previa. Tom era general de uno de estos ejércitos, Joe Harper (un amigo íntimo) general del otro. Estos dos grandes comandantes no se dignaban luchar en persona—lo cual era más apropiado para la gente aún más pequeña—sino que se sentaban juntos en una elevación y dirigían las operaciones del campo de batalla mediante órdenes entregadas a través de ayudantes de campo. El ejército de Tom ganó una gran victoria, tras una batalla larga y feroz. Luego se contaron los muertos, se intercambiaron prisioneros, se acordaron los términos del próximo desacuerdo y se fijó el día para la batalla necesaria; después de lo cual los ejércitos se alinearon y marcharon, y Tom se dirigió a casa solo."
        },
        {
          "en": "As he was passing by the house where Jeff Thatcher lived, he saw a new girl in the garden—a lovely little blue-eyed creature with yellow hair plaited into two long-tails, white summer frock and embroidered pantalettes. The fresh-crowned hero fell without firing a shot. A certain Amy Lawrence vanished out of his heart and left not even a memory of herself behind. He had thought he loved her to distraction; he had regarded his passion as adoration; and behold it was only a poor little evanescent partiality. He had been months winning her; she had confessed hardly a week ago; he had been the happiest and the proudest boy in the world only seven short days, and here in one instant of time she had gone out of his heart like a casual stranger whose visit is done.",
          "es": "Mientras pasaba por la casa donde vivía Jeff Thatcher, vio una nueva chica en el jardín—una criatura encantadora de ojos azules con cabello amarillo trenzado en dos largas coletas, vestido de verano blanco y pantaletas bordadas. El héroe recién coronado cayó sin disparar un tiro. Una tal Amy Lawrence desapareció de su corazón sin dejar ni siquiera un recuerdo de sí misma. Había creído que la amaba con distracción; había considerado su pasión como adoración; y he aquí que era solo una pobre y efímera inclinación. Había pasado meses ganándola; ella había confesado apenas hace una semana; había sido el chico más feliz y más orgulloso del mundo solo hace siete días, y aquí en un instante ella había desaparecido de su corazón como una extraña casual cuya visita ha terminado."
        },
        {
          "en": "He worshipped this new angel with furtive eye, till he saw that she had discovered him; then he pretended he did not know she was present, and began to “show off” in all sorts of absurd boyish ways, in order to win her admiration. He kept up this grotesque foolishness for some time; but by-and-by, while he was in the midst of some dangerous gymnastic performances, he glanced aside and saw that the little girl was wending her way toward the house. Tom came up to the fence and leaned on it, grieving, and hoping she would tarry yet awhile longer. She halted a moment on the steps and then moved toward the door. Tom heaved a great sigh as she put her foot on the threshold. But his face lit up, right away, for she tossed a pansy over the fence a moment before she disappeared.",
          "es": "La adoraba, ese nuevo ángel, con mirada furtiva, hasta que vio que ella lo había descubierto; entonces fingió que no sabía que ella estaba presente, y comenzó a \"presumir\" de todas las formas absurdas posibles de un chico, para ganar su admiración. Mantuvo esta tontería grotesca durante algún tiempo; pero después, mientras estaba en medio de algunas acrobacias gimnásticas peligrosas, miró a un lado y vio que la pequeña chica se dirigía hacia la casa. Tom se acercó a la cerca y se apoyó en ella, afligido, esperando que se quedara un poco más. Ella se detuvo un momento en los escalones y luego se dirigió hacia la puerta. Tom exhaló un gran suspiro cuando ella puso el pie en el umbral. Pero su rostro se iluminó de inmediato, porque ella lanzó una margarita sobre la cerca un momento antes de desaparecer."
        },
        {
          "en": "The boy ran around and stopped within a foot or two of the flower, and then shaded his eyes with his hand and began to look down street as if he had discovered something of interest going on in that direction. Presently he picked up a straw and began trying to balance it on his nose, with his head tilted far back; and as he moved from side to side, in his efforts, he edged nearer and nearer toward the pansy; finally his bare foot rested upon it, his pliant toes closed upon it, and he hopped away with the treasure and disappeared round the corner. But only for a minute—only while he could button the flower inside his jacket, next his heart—or next his stomach, possibly, for he was not much posted in anatomy, and not hypercritical, anyway.",
          "es": "El chico corrió alrededor y se detuvo a uno o dos pies de la flor, y luego se cubrió los ojos con la mano y comenzó a mirar calle abajo como si hubiera descubierto algo de interés en esa dirección. Presentemente recogió una brizna de paja y comenzó a intentar equilibrarla sobre su nariz, con la cabeza inclinada bastante hacia atrás; y mientras se movía de un lado a otro en sus esfuerzos, se acercaba cada vez más hacia la margarita; finalmente su pie descalzo descansó sobre ella, sus dedos flexibles se cerraron sobre ella, y saltó con el tesoro y desapareció alrededor de la esquina. Pero solo por un minuto—solo mientras podía abrochar la flor dentro de su chaqueta, junto a su corazón—o junto a su estómago, posiblemente, pues no estaba muy versado en anatomía, y no era hipercrítico de todas formas."
        },
        {
          "en": "He returned, now, and hung about the fence till nightfall, “showing off,” as before; but the girl never exhibited herself again, though Tom comforted himself a little with the hope that she had been near some window, meantime, and been aware of his attentions. Finally he strode home reluctantly, with his poor head full of visions.",
          "es": "Regresó ahora y merodeó junto a la cerca hasta el anochecer, \"presumiendo\", como antes; pero la chica nunca volvió a exhibirse, aunque Tom se consolaba a sí mismo un poco con la esperanza de que hubiera estado cerca de alguna ventana, mientras tanto, y hubiese sido consciente de sus atenciones. Finalmente se dirigió a casa con reluctancia, con su pobre cabeza llena de visiones."
        },
        {
          "en": "All through supper his spirits were so high that his aunt wondered “what had got into the child.” He took a good scolding about clodding Sid, and did not seem to mind it in the least. He tried to steal sugar under his aunt’s very nose, and got his knuckles rapped for it. He said:",
          "es": "Durante toda la cena sus ánimos eran tan elevados que su tía se preguntaba \"qué le habría pasado al niño.\" Recibió una buena reprimenda por lanzar terrones a Sid, y no pareció importarle en lo más mínimo. Intentó robar azúcar ante las narices mismas de su tía, y se ganó un golpe en los nudillos. Él dijo:"
        },
        {
          "en": "“Aunt, you don’t whack Sid when he takes it.”",
          "es": "\"Tía, no le pegas a Sid cuando él la coge.\""
        }
      ]
    },
    "3": {
      "lines": [
        {
          "en": "“Well, Sid don’t torment a body the way you do. You’d be always into that sugar if I warn’t watching you.”",
          "es": "\"Bueno, Sid no me atormenta de la manera que lo haces tú. Siempre estarías metido en ese azúcar si no estuviera vigilándote.\""
        },
        {
          "en": "Presently she stepped into the kitchen, and Sid, happy in his immunity, reached for the sugar-bowl—a sort of glorying over Tom which was wellnigh unbearable. But Sid’s fingers slipped and the bowl dropped and broke. Tom was in ecstasies. In such ecstasies that he even controlled his tongue and was silent. He said to himself that he would not speak a word, even when his aunt came in, but would sit perfectly still till she asked who did the mischief; and then he would tell, and there would be nothing so good in the world as to see that pet model “catch it.” He was so brimful of exultation that he could hardly hold himself when the old lady came back and stood above the wreck discharging lightnings of wrath from over her spectacles. He said to himself, “Now it’s coming!” And the next instant he was sprawling on the floor! The potent palm was uplifted to strike again when Tom cried out:",
          "es": "Presentemente ella entró en la cocina, y Sid, feliz en su inmunidad, extendió la mano hacia el azucarero—una especie de jactancia sobre Tom que era casi insoportable. Pero los dedos de Sid resbalaron y el azucarero se cayó y se rompió. Tom estaba en éxtasis. En tal éxtasis que incluso controló su lengua y guardó silencio. Se dijo a sí mismo que no diría una palabra, incluso cuando su tía entrara, sino que se quedaría perfectamente quieto hasta que ella preguntara quién había causado el daño; y entonces lo diría, y no habría nada tan bueno en el mundo como ver a ese modelo favorito \"recibir su merecido.\" Estaba tan rebosante de exultación que apenas podía contenerse cuando la anciana regresó y se quedó de pie sobre los restos descargando rayos de ira sobre sus lentes. Se dijo a sí mismo: \"¡Ahora viene!\" ¡Y al instante siguiente estaba tendido en el piso! La potente palma se levantaba para golpear de nuevo cuando Tom gritó:"
        },
        {
          "en": "“Hold on, now, what ’er you belting me for?—Sid broke it!”",
          "es": "\"¡Espera, ahora, ¿por qué me estás pegando?—¡Sid lo rompió!\""
        },
        {
          "en": "Aunt Polly paused, perplexed, and Tom looked for healing pity. But when she got her tongue again, she only said:",
          "es": "La tía Polly se detuvo, perpleja, y Tom buscó compasión sanadora. Pero cuando recuperó el habla, solo dijo:"
        },
        {
          "en": "“Umf! Well, you didn’t get a lick amiss, I reckon. You been into some other audacious mischief when I wasn’t around, like enough.”",
          "es": "\"¡Umf! Bueno, supongo que el golpe no te vino del todo mal. Probablemente hayas estado metido en alguna otra travesura audaz cuando no estaba alrededor.\""
        },
        {
          "en": "Then her conscience reproached her, and she yearned to say something kind and loving; but she judged that this would be construed into a confession that she had been in the wrong, and discipline forbade that. So she kept silence, and went about her affairs with a troubled heart. Tom sulked in a corner and exalted his woes. He knew that in her heart his aunt was on her knees to him, and he was morosely gratified by the consciousness of it. He would hang out no signals, he would take notice of none. He knew that a yearning glance fell upon him, now and then, through a film of tears, but he refused recognition of it. He pictured himself lying sick unto death and his aunt bending over him beseeching one little forgiving word, but he would turn his face to the wall, and die with that word unsaid. Ah, how would she feel then? And he pictured himself brought home from the river, dead, with his curls all wet, and his sore heart at rest. How she would throw herself upon him, and how her tears would fall like rain, and her lips pray God to give her back her boy and she would never, never abuse him any more! But he would lie there cold and white and make no sign—a poor little sufferer, whose griefs were at an end. He so worked upon his feelings with the pathos of these dreams, that he had to keep swallowing, he was so like to choke; and his eyes swam in a blur of water, which overflowed when he winked, and ran down and trickled from the end of his nose. And such a luxury to him was this petting of his sorrows, that he could not bear to have any worldly cheeriness or any grating delight intrude upon it; it was too sacred for such contact; and so, presently, when his cousin Mary danced in, all alive with the joy of seeing home again after an age-long visit of one week to the country, he got up and moved in clouds and darkness out at one door as she brought song and sunshine in at the other.",
          "es": "Luego su conciencia le reprochó, y anheló decir algo amable y cariñoso; pero juzgó que esto sería interpretado como una confesión de que ella había estado equivocada, y la disciplina se lo prohibía. Así que guardó silencio y continuó con sus asuntos con el corazón perturbado. Tom se enfurruñó en una esquina y exaltó sus desdichas. Sabía que en el fondo de su corazón su tía estaba de rodillas ante él, y estaba moralmente gratificado por la conciencia de ello. No levantaría ninguna señal, no haría caso de ninguna. Sabía que una mirada anhelante caía sobre él, de vez en cuando, a través de una velo de lágrimas, pero rechazaba reconocerlo. Se imaginaba a sí mismo enfermo de muerte y a su tía inclinándose sobre él suplicando una pequeña palabra de perdón, pero él giraría la cara hacia la pared y moriría sin pronunciar esa palabra. Ah, ¿cómo se sentiría ella entonces? Y se imaginaba a sí mismo traído de vuelta del río, muerto, con sus rizos completamente mojados, y su corazón adolorido en paz. ¡Cómo se lanzaría sobre él, y cómo sus lágrimas caerían como lluvia, y sus labios rogarían a Dios que le devolviera su hijo y ella nunca, nunca lo maltratría de nuevo! Pero él estaría allí frío y blanco sin dar señal alguna—un pobre sufridorcito, cuyas angustias habrían terminado. Trabajó tanto sus sentimientos con la patética calidad de estos sueños, que tuvo que seguir tragando, tan cerca estaba de ahogarse; y sus ojos nadaban en una bruma de agua, que se desbordaba cuando parpadeaba, y corría hacia abajo y goteaba desde la punta de su nariz. Y tal lujo era para él este ensimismarse en sus penas, que no podía soportar que ninguna alegría mundana o ningún deleite estridente se intrusara en ello; era demasiado sagrado para tal contacto; y así, presentemente, cuando su prima Mary entró bailando, toda vivacidad por la alegría de ver el hogar de nuevo después de una visita que parecía una eternidad de una semana al campo, él se levantó y se marchó entre nubes y oscuridad por una puerta mientras ella traía canción y luz solar por la otra."
        },
        {
          "en": "He wandered far from the accustomed haunts of boys, and sought desolate places that were in harmony with his spirit. A log raft in the river invited him, and he seated himself on its outer edge and contemplated the dreary vastness of the stream, wishing, the while, that he could only be drowned, all at once and unconsciously, without undergoing the uncomfortable routine devised by nature. Then he thought of his flower. He got it out, rumpled and wilted, and it mightily increased his dismal felicity. He wondered if she would pity him if she knew? Would she cry, and wish that she had a right to put her arms around his neck and comfort him? Or would she turn coldly away like all the hollow world? This picture brought such an agony of pleasurable suffering that he worked it over and over again in his mind and set it up in new and varied lights, till he wore it threadbare. At last he rose up sighing and departed in the darkness.",
          "es": "Deambuló lejos de los lugares acostumbrados de los chicos y buscó lugares desolados que estaban en armonía con su espíritu. Una balsa de troncos en el río lo invitó, y se sentó en su borde exterior y contempló la vastedad lúgubre de la corriente, deseando, mientras tanto, poder ser ahogado, de una sola vez e inconscientemente, sin someterse a la rutina incómoda ideada por la naturaleza. Luego pensó en su flor. La sacó, arrugada y marchita, e incrementó enormemente su felicidad lúgubre. Se preguntó si ella lo compadecería si lo supiera. ¿Lloraría, y desearía tener derecho a poner sus brazos alrededor de su cuello y consolarlo? ¿O se apartaría con frialdad como todo el mundo hueco? Esta imagen le causó tal agonía de sufrimiento placentero que la trabajó una y otra vez en su mente y la presentó bajo luces nuevas y variadas, hasta que la desgastó. Al fin se levantó suspirando y partió en la oscuridad."
        },
        {
          "en": "About half-past nine or ten o’clock he came along the deserted street to where the Adored Unknown lived; he paused a moment; no sound fell upon his listening ear; a candle was casting a dull glow upon the curtain of a second-story window. Was the sacred presence there? He climbed the fence, threaded his stealthy way through the plants, till he stood under that window; he looked up at it long, and with emotion; then he laid him down on the ground under it, disposing himself upon his back, with his hands clasped upon his breast and holding his poor wilted flower. And thus he would die—out in the cold world, with no shelter over his homeless head, no friendly hand to wipe the death-damps from his brow, no loving face to bend pityingly over him when the great agony came. And thus she would see him when she looked out upon the glad morning, and oh! would she drop one little tear upon his poor, lifeless form, would she heave one little sigh to see a bright young life so rudely blighted, so untimely cut down?",
          "es": "Alrededor de las nueve y media o las diez se acercó por la calle desierta hasta donde vivía la Diosa Desconocida; se detuvo un momento; ningún sonido llegó a su oído atento; una vela proyectaba un brillo opaco sobre la cortina de una ventana del segundo piso. ¿Estaba la presencia sagrada allí? Escaló la cerca, se abrió paso sigilosamente entre las plantas, hasta que se quedó de pie bajo esa ventana; la miró durante mucho tiempo, con emoción; luego se acostó boca arriba en el suelo bajo ella, con las manos cruzadas sobre el pecho sujetando su pobre flor marchita. Y así moriría—en el mundo frío, sin abrigo sobre su cabeza sin hogar, sin mano amiga que secara el rocío mortal de su frente, sin rostro amoroso que se inclinara compasivamente sobre él cuando llegara la gran agonía. Y así lo vería ella cuando mirara hacia la mañana radiante, ¡y ay! ¿Dejaría caer una pequeña lágrima sobre su forma pobre e inerte, exhalaría un pequeño suspiro al ver una vida joven tan brillante tan brutalmente marchitada, tan prematuramente cortada?"
        }
      ]
    },
    "4": {
      "lines": [
        {
          "en": "The window went up, a maid-servant’s discordant voice profaned the holy calm, and a deluge of water drenched the prone martyr’s remains!",
          "es": "La ventana se abrió, la voz discordante de una criada profanó la calma sagrada, ¡y una lluvia de agua empapó los restos del mártir postrado!"
        },
        {
          "en": "The strangling hero sprang up with a relieving snort. There was a whiz as of a missile in the air, mingled with the murmur of a curse, a sound as of shivering glass followed, and a small, vague form went over the fence and shot away in the gloom.",
          "es": "¡El héroe sofocante saltó con un resoplido aliviador. Hubo un silbido como de un proyectil en el aire, mezclado con el murmullo de una maldición, un sonido como de vidrio rompiéndose siguió, y una forma pequeña y vaga pasó por encima de la cerca y se alejó disparada en la penumbra."
        },
        {
          "en": "Not long after, as Tom, all undressed for bed, was surveying his drenched garments by the light of a tallow dip, Sid woke up; but if he had any dim idea of making any “references to allusions,” he thought better of it and held his peace, for there was danger in Tom’s eye.",
          "es": "No mucho después, mientras Tom, completamente desvestido para la cama, estaba examinando sus prendas empapadas a la luz de una vela de sebo, Sid se despertó; pero si tenía alguna idea vaga de hacer algunas \"referencias a alusiones,\" pensó mejor y guardó silencio, pues había peligro en los ojos de Tom."
        },
        {
          "en": "Tom turned in without the added vexation of prayers, and Sid made mental note of the omission.",
          "es": "Tom se acostó sin la vexación adicional de las oraciones, y Sid tomó nota mental de la omisión."
        }
      ]
    }
  }
};
